### ISSUE TITLE
GC3 r204: [Multiplayer] Players can make planets go out of sync just by sleeping on beds

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1074]
In Galacticraft, the planets and moons are supposed to be in sync (e.g. 1 Moon day = 8 Overworld days, 1 Mars day = 1 Overworld day) but this can be disrupted just by going to bed.

Ref.: http://forum.micdoodle8.com/index.php?threads/telescopes-and-astronomy.2261/page-4#post-34799

EDIT:
For the servers with "astronomical disruption", I suggest that the next builds should check if the dimensions are in sync (by admin request or periodically), if not the mod would re-sync the dimensions taking the Overworld time as reference time.

**Comment by radfast** [comment]
Now that Cryogenic Chambers is working properly, I have looked some more at this.

It is **not possible** to have sleeping make the time update correctly to "next morning" on the planet where the player currently is, without doing one of these two things.  Either:

(A) force change the time on all worlds in sync - which could be not a day/night change, for example it could make the sun position on the Moon advance 1/8 day - and this would be **extremely weird** on a multiplayer server, for example a player on Mars sleeps because he's the only player on that planet, and a player on the Moon sees the sun "jump" position in the sky

or:

(B) have time of day go out of sync between the different worlds - the issue reported here

I think (B) is the way to go.  There is no astronomical rule which says "if it's noon on Earth, it must be noon on Mars".  Normally there should be an offset between the time on each planet, depending on date, also because Mars day is ~25 hours.

In Minecraft, time is a bit artificial - we have fixed length days and nights regardless of season, and the sleeping mechanic can cause the night to be skipped.

I think it's OK therefore if there is not sync lock between time of day on - for example - Mars and Overworld.  In the game, it will depend on who slept on which world.  In real life, it depends on the date.  Either way, there is variation so I think in game terms this is better than sync.
