### ISSUE TITLE
Steve's carts 2 Ore extractor

### ISSUE THREAD

**Issue by taz1004** [micdoodle8/Galacticraft#1101]
Steve's carts 2 currently is my main mining tool and it has a module to extract entire vains of ores.  It works on all other mods ores except world gen from Galacticraft.  Perahps a minor issue but would love to have it fixed.

**Comment by radfast** [comment]
All of Galacticraft's ores are correctly registered as "ore" in the OreDictionary.

The reason Steve's Carts' "Ore Extractor" module is not mining the Galacticraft blocks is because - in coding terms - Steve's Carts is ignoring the __metadata__, it is looking only at the block.  Galacticraft blocks will only be detected correctly as ores if the module checks the metadata as well.

This can only be fixed in Steve's Carts, and it's a simple thing to fix if they are willing to do it.

I'm sure ours is not the only mod affected - there must be other mods whose ores depend on metadata values - but I don't know right now which other mods are also affected.

If Steve's Carts are not willing to fix this compatibility issue then players will have to wait until Minecraft 1.8, when the block metadata system will be changed in the vanilla game and so all of this will change.
