### ISSUE TITLE
Energy Beam Loss

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1113]
I filled an energy cluster with one battery's worth of energy. 15k gJ.
I used energy beams to transfer to another, empty cluster. Got 13.8k gJ.
Same test with aluminum wires 100% transfer.
-Also-
Did same test, but beamed to a full cluster. Energy was lost as it was requested despite the destination being full.

**Comment by dj3520** [comment]
I'm still having this problem and I'm straying away from using the beams at all. it's nice to have all that transferring speed but not with the loss. It's as if the beams themselves require power.
As explained before, once the destination is full (the transfer should stop) the source continues to be drained. Tested cluster to cluster and cluster to MFSU.

**Comment by radfast** [comment]
Thanks for the update, sorry it's taking so long to deal with this issue.

**Comment by dj3520** [comment]
Problem exists from Cluster to MFSU but not Cluster to Cluster.

**Comment by radfast** [comment]
OK thanks, I'll test that.  
One of the "known issues" is:
> GC energy Beam Receivers cannot pull power out of other mods machines

But it sounds like you have seen that issue the other way around, putting energy into the MFSU?
Please can you also check that an aluminium wire puts energy into the MFSU correctly?

**Comment by dj3520** [comment]
There seems to be some issues with energy in my testing.
All tests done on surface of mars in creative mode. Multiplayer server.
IndustrialCraft conversion value is 6.6 in config. (exact value)
Conversion loss factor is 100 percent in config.
All tests done with newly spawned devices not integrated in any other system.

2.5m gJ converts to 378787.87 repeating EU via divide by 6.6
Cluster shows 378,787 EU storage (no round up?)

MFSU stores 40 million EU

Full MFSU -> Cluster via 2x Heavy Alum Wire
MFSU = 39621120EU Cluster = 378787
40mEU - 39621120EU = 378880EU drained from MFSU.
Result is 93 EU loss

Full Cluster -> MFSU via 2x Heavy Alum Wire.
Cluster drained to 0. MFSU = 378787 EU.
Result is 0 EU loss.

Recharged Cluster via Infinite Battery at this point. Removed once charged 100%

Batbox stores 40,000 EU
Full Cluster -> Batbox via 2x Heavy Alum Wire.
Batbox = 40k EU Cluster = 338457 EU
378787EU - 338457EU = 40330EU drained from Cluster.
Result is 330 EU loss.

At this point attempted to drain Cluster via Lapotron Crystal. Item was accepted but no transfer of energy was done. (intentional?)
Drained Cluster to Energy Crystal. Drained Energy Crystal to dead MFSU. 
MFSU = 338457EU. Cluster prior to drain = 338457EU as above.
Result is 0 EU loss.

Full Batbox -> Cluster via 2x Heavy Alum Wire.
Batbox = 10EU (outputs 32EU/t, so cannot be full drained.) Cluster = 40064EU
Result is 74 EU gain.

Willing to do more testing to resolve problems, but only energy involved mods are Buildcraft, Big Reactors, Galaticraft and IndustrialCraft.
Also willing to run custom builds on server/client to aid in solving problems.

**Comment by radfast** [comment]
EU losses: I don't see that as a problem, the amounts are tiny (0.02%).  It will be due to rounding, but hard to know whether that's in Galacticraft's code or IC2 - it's notable that Cluster->MFSU has no EU loss.

What tier is a Lapotron Crystal? If an Energy Crystal charges but a Lapotron Crystal does not charge, it's probably because Lapotron Crystal is Tier 3 or Tier 4 which would be too high for a Cluster, only a high tier IC2 energy box will charge it.

The 74 EU __gain__ I am more concerned about, as we don't want to be producing infinite energy.

**Comment by dj3520** [comment]
The Lapotron Crystal is tier 4 and the Energy Crystal is tier 3. The issue here is that the Cluster accepts the Lapotron Crystal even though it can't/won't charge it.

My guess as to the gain is it has something to do with the fact the batbox couldn't fully drain itself (had 10EU left) but since this is less than the 330EU that was lost once I'll agree in retrospect it's tiny. But there might be more to this, and in reality we're not loosing or gaining anything.

Let's take this into consideration. Let's say a Cluster has 2034EU of free storage left. The MFSU sees this and outputs energy. However, the MFSU outputs 2048EU/t when it sees a request for energy. It could be that the cluster accepts 2034EU and rejects the rest due to being full. This puts 14EU in limbo. I wouldn't be too surprized if taking some of the energy out of the cluster would result in that 14EU arriving once the space is avalible.

As for the beams, I think the problem is the destination MFSU never says "I'm full" so the drain continues. Maybe the beam and recievers could stop spinning when there's no transfer as a way to see if I'm right. Cluster to Cluster the beams will stop and so will the drain, but if the beams don't stop with the MFSU, then it's a bigger problem.

**Comment by radfast** [comment]
> The Lapotron Crystal is tier 4 and the Energy Crystal is tier 3. The issue here is that the Cluster accepts the Lapotron Crystal even though it can't/won't charge it.

I checked the code.  That is exactly as intended.  Galacticraft Tier 1 machines (Energy Storage Module) can charge IC2 Tier 1 or Tier 2 energy items.  Galacticraft Tier 2 machines (Energy Storage Cluster) can charge IC2 Tier 1, Tier 2 or Tier 3.  I think it's normal for an IC2 item to be accepted in a machine even if the tier won't charge it - even if that's not normal, it's not something I plan on changing in GC as it's too minor.

> My guess as to the gain is it has something to do with the fact the batbox couldn't fully drain itself (had 10EU left) but since this is less than the 330EU that was lost once I'll agree in retrospect it's tiny. But there might be more to this, and in reality we're not loosing or gaining anything.

A gain should not be possible in Galacticraft.  This looks like an IC2 issue, as 40,064 is exactly 313 x 128.  My guess is the Batbox outputs packets of 128 EU/t.  It looks like the Batbox has output one more 128EU packet than it should have.   Maybe it's because of that final 10 EU.  But most likely it is because the Batbox was "overfilled" with more than 40,000 EU when you started.  All IC2 machines work that way.  So if the Batbox has 40,000 capacity and you feed it 128 EU/t, 313 ticks makes 40,000 EU with remainder 64 EU left over.  The remaining 64 EU is held in an "overfill" buffer and will be added to the machine's energy store when IC2 is next able to do that.

> Let's take this into consideration. Let's say a Cluster has 2034EU of free storage left. The MFSU sees this and outputs energy. However, the MFSU outputs 2048EU/t when it sees a request for energy. It could be that the cluster accepts 2034EU and rejects the rest due to being full. This puts 14EU in limbo. I wouldn't be too surprized if taking some of the energy out of the cluster would result in that 14EU arriving once the space is avalible.

Correct, that is exactly what happens (see above), thanks for reminding me of that.  378,880 is exactly 185 x 2048.  So it's not surprising that is the amount which drains from the MFSU, it seems to be exactly correct.

>  As for the beams, I think the problem is the destination MFSU never says "I'm full" so the drain continues. Maybe the beam and recievers could stop spinning when there's no transfer as a way to see if I'm right. Cluster to Cluster the beams will stop and so will the drain, but if the beams don't stop with the MFSU, then it's a bigger problem.

The beams - the original issue you posted - is something I plan to look at.

**Comment by dj3520** [comment]
>even if that's not normal, it's not something I plan on changing in GC as it's too minor.

I'm going to say that this isn't normal since I can't place a lapotron crystal in anything but an MFSU on IC2's side. The difference in behavior is what made me write about this.
>My guess is the Batbox outputs packets of 128 EU/t.

If memory serves me right the batbox is 32EU/t
>But most likely it is because the Batbox was "overfilled" with more than 40,000 EU when you started.

There is a full batbox via creative that is posted to hold 40k EU via tooltip. The reasoning behind this is wrenching the batbox will have it keep a percent of it's stored energy. So in theory, the batbox has exactly 40k EU/t since I never filled it via external source.
>The remaining 64 EU is held in an "overfill" buffer and will be added to the machine's energy store when IC2 is next able to do that.

That technically means despite the weirdness on the surface, things are working properly. I'm a bit curious as to what GC would "do" if I transferred IC2 to IC2 via GC wire, as well as GC to GC with IC2 wire.
>The beams - the original issue you posted - is something I plan to look at.

Don't worry I wasn't doubting you. Just providing requested information.
>Maybe the beam and recievers could stop spinning when there's no transfer as a way to see if I'm right.

Consider this half-suggestion, half-debug tool.

**Comment by radfast** [comment]
Nice suggestion, thank you.

As you're using a 40,000 EU creative batbox there is a problem here though, that means there is an energy gain.  I'm interested in what happens in these four situations:
* Batbox -> GC energy storage through IC2 cable
* Batbox -> GC energy storage through alu wire
* Batbox -> MFSU through IC2 cable
* Batbox -> MFSU through alu wire

That should give more clues as to where any gain is arising.  Even though the gain is small, it is worth looking at this, as if something that _should_ be impossible is happening it does mean there may be a bug in the code somewhere which could have other bad effects also.  If you have time to test those four configurations, would be great, otherwise I will test next time I have IC2 loaded up on my test platform.

**Comment by dj3520** [comment]
I'll take advantage of IC2 and GC wire not connecting anymore like it did in GC2 in order to make a compact setup. Energy travels forward, up, then back. All Batboxes are 40k via creative.
![image](https://cloud.githubusercontent.com/assets/8284194/6182404/18a3d4e2-b311-11e4-80c7-6e59627ddf0b.png)
Had to cheat the cluster readings with a text card. IC2 Nuclear Control's energy kit turns into a card but reads 0, so I just manually read the values. Not an issue since it's not made to interface with GC.

I believe the gain was from me using the same batbox twice by accident since it didn't happen this time around. The only problem is that using Alu wires for IC2 to IC2 creates a loss.

**Comment by radfast** [comment]
Nice setup, and thanks for comprehensive test.  I am glad we do not have an unwanted energy gain.  

The loss of 2 must be a rounding issue because the energy is converted and converted back, anyhow it's so small I'm not going to worry about it.

**Comment by dj3520** [comment]
I'm getting quite skilled at building. The main reason the loss concerns me
is that I'm attempting to make a somewhat infinite loop for energy. I've
had some success in small scale, but any loss becomes substantial since the
system energizes itself. A single solar panel at noon is a big help, so
that should tell you what kind of balancing act I'm trying to accomplish.
Wireless energy makes things easier to keep small and simple.

**Comment by dj3520** [comment]
Retest with GC 400 and IC2 782 (can test with newer but might not be as easy to see energy drains) and BC 7.1.9 (can upgrade but has other issues)
Seems to only effect GC -> non GC transfers, such as these two:

![image](https://cloud.githubusercontent.com/assets/8284194/11004164/ad13f158-8484-11e5-8a8b-19bf6e851fad.png)
Top is a BC laser (shouldn't draw power at idle) and bottom a full MFSU.
Both ESC's are drawing in the same amount of power as they'd output. This shouldn't happen as this causes a loss of energy as the transfer doesn't stop.

Good news is that GC to GC seems perfectly OK.

**Comment by radfast** [comment]
This is fixed in build 410.  The energy stops being taken by the beam, if the beam receiver cannot use it.  (Note: a "small" amount of energy, around 10,000 EU / 30,000 gJ, is stored in the beam itself even when the beam is not transmitting.  If in future the Beam Receiver is able to use energy again, that energy will become available for it to use.  But if the Beam Transmitter -> Beam Receiver blocks are broken without ever using that energy, then the energy will be lost.)
