### ISSUE TITLE
New crash

### ISSUE THREAD

**Issue by Dokman** [micdoodle8/Galacticraft#1175]
java.lang.IllegalArgumentException: bound must be positive
    at java.util.Random.nextInt(Unknown Source)
    at net.minecraft.src.mcreator_crossIce.generateSurface(mcreator_crossIce.java:133)
    at net.minecraft.src.BuildingMod.generate(BuildingMod.java:263)
    at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:130)
    at micdoodle8.mods.galacticraft.core.util.WorldUtil.otherModGenerate(WorldUtil.java:922)
    at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:394)
    at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1168)
    at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:249)
    at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:169)
    at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:137)
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:469)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
    at java.lang.Thread.run(Unknown Source)

**Comment by trismegistis** [comment]
Can you help me with my crash.. lol it's not yours but I can't tell what it is..

net.minecraft.util.ReportedException: Exception getting block type in world
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.checkBlock(EventHandlerGC.java:511) ~[EventHandlerGC.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:445) ~[EventHandlerGC.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359) ~[EventHandlerGC.class:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler_591_EventHandlerGC_populate_Post.invoke(.dynamic) ~[?:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448) [aqz.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) [ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) [apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345) [ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147437_c(World.java:365) [ahb.class:?]
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:147) [BaseCropWorldgen.class:?]
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:46) [BaseCropWorldgen.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) [apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) [ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) [ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_72938_d(World.java:414) [ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_72825_h(World.java:1742) [ahb.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateOyster(WorldGenHandler.java:76) [WorldGenHandler.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateSurface(WorldGenHandler.java:38) [WorldGenHandler.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generate(WorldGenHandler.java:27) [WorldGenHandler.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) [GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) [ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) [apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) [ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) [ms.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) [MinecraftServer.class:?]
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130) [bsx.class:?]
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) [bsx.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#313]  Caused by: java.lang.IllegalArgumentException: bound must be positive
[B#313]  	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_60]
[B#313]  	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111) ~[ChestGenHooks.class:?]
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.generateChestContent(WeightedRandomChestContent.java:93) ~[qx.class:?]
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38) ~[qx.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.basement(StructureJourneymanTower.java:1164) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.build(StructureJourneymanTower.java:1110) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.func_76484_a(StructureJourneymanTower.java:47) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.PlaceTraps.generate(PlaceTraps.java:177) ~[PlaceTraps.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
[B#313]  	... 42 more
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: Index: 2 Listeners:
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 0: NORMAL
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 1: ASM: noppes.npcs.ServerEventsHandler@4a0b47cf populateChunk(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 2: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@d481a39 populate(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 3: ASM: buildcraft.core.SpringPopulate@53498056 populate(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 4: ASM: com.rwtema.extrautils.EventHandlerServer@55b7062d decoratePiEasterEgg(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 5: ASM: powercrystals.netherores.net.ClientProxy@35dc2708 evt(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR] [FML]: 6: ASM: forestry.core.WorldGenerator@6db6ee9b populateChunk(Lnet/minecraftforge/event/terraingen/PopulateChunkEvent$Post;)V
[B#313]  [06:44:32] [Server thread/ERROR]: Encountered an unexpected exception
[B#313]  net.minecraft.util.ReportedException: Exception getting block type in world
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:147) ~[BaseCropWorldgen.class:?]
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:46) ~[BaseCropWorldgen.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040) ~[apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_72938_d(World.java:414) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_72825_h(World.java:1742) ~[ahb.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateOyster(WorldGenHandler.java:76) ~[WorldGenHandler.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateSurface(WorldGenHandler.java:38) ~[WorldGenHandler.class:?]
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generate(WorldGenHandler.java:27) ~[WorldGenHandler.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055) ~[apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265) ~[MinecraftServer.class:?]
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130) ~[bsx.class:?]
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153) ~[bsx.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#313]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[B#313]  Caused by: java.lang.IllegalArgumentException: bound must be positive
[B#313]  	at java.util.Random.nextInt(Unknown Source) ~[?:1.8.0_60]
[B#313]  	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111) ~[ChestGenHooks.class:?]
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.generateChestContent(WeightedRandomChestContent.java:93) ~[qx.class:?]
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38) ~[qx.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.basement(StructureJourneymanTower.java:1164) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.build(StructureJourneymanTower.java:1110) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.func_76484_a(StructureJourneymanTower.java:47) ~[StructureJourneymanTower.class:?]
[B#313]  	at com.draco18s.artifacts.worldgen.PlaceTraps.generate(PlaceTraps.java:177) ~[PlaceTraps.class:?]
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.checkBlock(EventHandlerGC.java:511) ~[EventHandlerGC.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:445) ~[EventHandlerGC.class:?]
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359) ~[EventHandlerGC.class:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler_591_EventHandlerGC_populate_Post.invoke(.dynamic) ~[?:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[B#313]  	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448) ~[aqz.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
[B#313]  	... 27 more
[B#313]  [06:44:33] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Ryan\AppData\Roaming\.technic\modpacks\the-technium-of-trismegistis\crash-reports\crash-2015-09-05_06.44.32-server.txt
[B#313]  [06:44:33] [Server thread/INFO] [FML]: Applying holder lookups
[B#313]  [06:44:33] [Server thread/INFO] [FML]: Holder lookups applied
[B#313]  [06:44:33] [Server thread/INFO] [Compact Machines]: Unregistering dimension 36 on client side
[B#313]  [06:44:33] [pool-10-thread-1/INFO] [EnderIO]: ServerChannelRegister: Dimensional Transceiver data saved to C:\Users\Ryan\AppData\Roaming\.technic\modpacks\the-technium-of-trismegistis\saves\Quest Creation Only\enderio\dimensionalTransceiver.json
[B#313]  [06:44:33] [Server thread/INFO] [InvisiZonesManager]: Clearing zones on: CLIENT
[B#313]  [06:44:33] [Server thread/INFO] [ProjectE]: Completed server-stop actions.
[B#313]  [06:44:33] [Server thread/INFO] [mcjty.varia.Logging]: RFTools: server is stopping. Shutting down gracefully
[B#313]  [06:44:33] [Server thread/INFO] [mcjty.varia.Logging]: Cleaning up RFTools dimensions
[B#313]  [06:44:34] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
[B#313]  [06:44:34] [Server thread/INFO] [FML]: The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.
[B#313]  [06:44:34] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:-1]: ---- Minecraft Crash Report ----
[B#313]  // Why is it breaking :(
[B#313]  
[B#313]  Time: 9/5/15 6:44 AM
[B#313]  Description: Exception getting block type in world
[B#313]  
[B#313]  java.lang.IllegalArgumentException: bound must be positive
[B#313]  	at java.util.Random.nextInt(Unknown Source)
[B#313]  	at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111)
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.generateChestContent(WeightedRandomChestContent.java:93)
[B#313]  	at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38)
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.basement(StructureJourneymanTower.java:1164)
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.build(StructureJourneymanTower.java:1110)
[B#313]  	at com.draco18s.artifacts.worldgen.StructureJourneymanTower.func_76484_a(StructureJourneymanTower.java:47)
[B#313]  	at com.draco18s.artifacts.worldgen.PlaceTraps.generate(PlaceTraps.java:177)
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419)
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345)
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.checkBlock(EventHandlerGC.java:511)
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.generateOil(EventHandlerGC.java:445)
[B#313]  	at micdoodle8.mods.galacticraft.core.event.EventHandlerGC.populate(EventHandlerGC.java:359)
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler_591_EventHandlerGC_populate_Post.invoke(.dynamic)
[B#313]  	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[B#313]  	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
[B#313]  	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:448)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419)
[B#313]  	at net.minecraft.world.World.func_147439_a(World.java:345)
[B#313]  	at net.minecraft.world.World.func_147437_c(World.java:365)
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:147)
[B#313]  	at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:46)
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
[B#313]  	at net.minecraft.world.World.func_72964_e(World.java:419)
[B#313]  	at net.minecraft.world.World.func_72938_d(World.java:414)
[B#313]  	at net.minecraft.world.World.func_72825_h(World.java:1742)
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateOyster(WorldGenHandler.java:76)
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generateSurface(WorldGenHandler.java:38)
[B#313]  	at mariculture.core.handlers.WorldGenHandler.generate(WorldGenHandler.java:27)
[B#313]  	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
[B#313]  	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1055)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
[B#313]  	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
[B#313]  	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:265)
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:130)
[B#313]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:153)
[B#313]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
[B#313]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
