### ISSUE TITLE
Moon Village rare water visual bug when generating a new chunk

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1208]
![2557-11-04_21 54 43](https://cloud.githubusercontent.com/assets/6128413/4912420/99634d32-649d-11e4-957a-73740b1b4a72.png)

Seed : 1989408553
Coordinate X Y Z : Please see on the minimap.

**Comment by radfast** [comment]
I think this has been fixed by the recent changes in Galacticraft 3.0.9.297, which will have made Moon worldgen happen in a more predictable way - most importantly, that version stops there being any "block updates" during the worldgen process.  Previously there were a lot of block updates.  As you know, it is block updates which cause a water source block (placed by worldgen) to start flowing.

It's not possible to check this 100% as the recent changes have also had a consequence of changing the order of rand.get####() calls, so the RNG will make different moon terrain now for the same World Seed.  Meaning: if I fly to those co-ordinates on the World Seed you specified, now there is no village there.

But like I say, I think this is fixed.  If you ever see the problem again, please do re-open.
