### ISSUE TITLE
Extra NASA Workbench drops in Creative mode

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1212]
Today found bench dupe.
 
Steps: 
1) Place NASA Workbench
2) Place NASA Workbench here: http://2.firepic.org/2/images/2014-11/06/hdsue9npcyzi.png

Result: +1 Workbench at right-click

**Comment by micdoodle8** [comment]
I'm going to close this, since it's a minor issue that only affects creative mode. It's also likely not fixable, because I have no access to the player instance that breaks that block, therefore cannot check if the player is in creative. Also note, the same thing happens with cacti in vanilla; breaking the base when two or more cacti blocks are stacked will drop the top blocks even in creative.
