### ISSUE TITLE
GC foods not using vanilla food routines, breaks compatibility

### ISSUE THREAD

**Issue by Syndaryl** [micdoodle8/Galacticraft#1215]
GC foods, such as the dehydrated apples and carrots, are not using the vanilla food functions to adjust hunger, satiation, and so forth. 
This is breaking compatability with frex. AppleCore, which reports on the food value of food, and gives diminishing returns if you don't eat a variety of food.
An example generic ItemFood that uses the vanilla routines is here:
https://github.com/squeek502/AppleCore/blob/master/java/squeek/applecore/example/ItemMetadataFood.java
This allows mods such as AppleCore to correctly intercept food behaviour and modify it as appropriate.

I can't find where in the code the food items are being handled, or I'd try to pull and patch this myself. If someone can point me to the object, I'll do the work.

**Comment by Grim-Ascensions** [comment]
Bumping this up in hopes that someone is still working on a fix. I lack the skills to do it myself, but I'm very interested in seeing it get corrected.

**Comment by Syndaryl** [comment]
I'm actually still here, although shortly after I posted the above I had a major illness that has pulled me entirely away from development work and the computer in general. I'm still not quite back on track.

For either myself, If I get back to work here soon, or for someone else if they pick it up first:
The simple fixes for the compatibility problems can't be used here because you've got food items as metadata items combined with non-food items. I think the ideal solution would be to refactor the ItemBasic into ItemBasic, and ItemBasicFood (which would be a metadata object that inherits properly from the MC food object).

**Comment by radfast** [comment]
In theory I'm certainly happy to refactor, I don't like ItemBasic containing food methods any more than you do :)

But refactoring can be a big problem in existing worlds - players would lose the food items (or they would convert into something different).  It would need some kind of auto-conversion code.

Over the next week or so I'll look at whether we can do this refactoring.  I'll post any update here.

Sorry to hear about your illness, glad that you're recovering: sometimes it's healthy to take a break from the computer for a time anyhow.

**Comment by Syndaryl** [comment]
A sort of messy possibility, which I haven't fully explored, would be to make ItemBasic actually extend the minecraft ItemFood, instead of generic Item, and then in the eating methods check if it's NOT actually a food item.

**Comment by radfast** [comment]
I've looked at this and I can see no way to do auto-conversion - bearing in mind that in existing worlds, food items can be in any type of storage, including chests, or other mods storage (include Applied Energistics), as well as the player inventory.

We cannot extend ItemFood, otherwise there would be the eating animation and sound when a player is holding a non-food GC item (including ingots etc.) - even if it give 0 saturation.

We can implement the same classes as vanilla ItemFood, like onEaten() etc, if that's any help to you?  But it would need Galacticraft-specific code in the other mods to use this.

Apart from that, I do not see any solution, sorry - but we can look again in 1.8 when I think items have to be coded differently (by name not metadata) anyhow.
