### ISSUE TITLE
Spam Wikipedia GC

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1326]
Good afternoon. 
After updating, in chat was very often write about the help and Wikipedia.
Can I make a configuration to disable help?

**Comment by radfast** [comment]
I need more info on this one, exact steps to reproduce it.
(I'm not seeing any problem in my testing.)

**Comment by EzerArch** [comment]
Those messages keep appearing every time you reload the game.

1. Save and Quit to Title
2. Load the world again
3. Press E and click on Galacticraft tab, or place a rocket
4. Message appears.

**Comment by radfast** [comment]
Currently, once per world load like that is intended, I wouldn't call that "spam".  (If it's more than once per world load that would be a bug which I would want to do something about, that's what I'm trying to understand here - any comment guys?)

If that's getting annoying I can look at turning down the frequency.  The key thing is for the help message to be shown to new players more than once because they're probably concentrating on other things or other mods in the first few minutes of the game - Galacticraft is really a late-game mod.

**Comment by EzerArch** [comment]
> Currently, once per world load like that is intended,

Sometimes not, the same message has shown up twice. Probably it was due to a death.

![2015-01-05_20 32 46](https://cloud.githubusercontent.com/assets/6743303/5621184/29490da4-951a-11e4-923f-51486587bd55.png)

**Comment by radfast** [comment]
oops, it shouldn't reset when you die, that's my bad

I'll also take a look at eliminating this for old players, with a count for how many times the player has seen the message.  I don't want to add yet another config.
