### ISSUE TITLE
Unable to access galacticraft dimensions

### ISSUE THREAD

**Issue by Hatventures** [micdoodle8/Galacticraft#1338]
Hi,
I'm having a weird issue, and since there's no crash nor exceptions in the console, i'll have to explain what's going on. I'll try to be to the point.

- Multiple servers using the same configuration, players couldnt access said dimensions
- Decided to update, and testing on a dev server with exactly the same configurations
- Worked as intended, moon, mars, everything
- Updated all the production servers
- Cant access the dimensions
  * With a rocket
  * With the dimensiontp command

Since there's no output about anything, i'm wondering if you have any idea on what could be causing it

Cheers

**Comment by Hatventures** [comment]
I'm sorry, i kinda forgot about this ticket (holidays and all).

This issue is very much unsolved, as galacticraft is currently incompatible with bungeecord (dimensions infos packets arent being sent to the client on login).

While I, from a user stand point, could imagine that a fix could be made (detects bungeecord and/or option, with said option enabled sync dimension IDs only after the player is logged in via normal packets and always spawn player in a regular dimension if player is in an "unknown" dimension), i also understand that this not may be something you want.

I'll close the ticket now.

**Comment by radfast** [comment]
@Hatventures no worries.  There is already a BungeeCord issue open, that's #1164, so this issue can sensibly be closed.  I don't know if that BungeeCord issue will ever be resolved - I had hopes that the BungeeCord team or dualspiral would find a solution.  It seems fairly clear to me that the "fault", if there's a fault at all here, is BungeeCord's, as we are sending permitted Forge custom packets (and I can't believe we are the only mod to do that) and BungeeCord has taken a deliberate decision not to support those - so in effect BungeeCord does not provide full support for Forge mods.  For the reasons explained there, Galacticraft has to send dimension info to the client during the connection stage because the client's first action after connection is to place the player in a dimension.  I will think some time about whether, as you suggest, we can do that differently if Bungee is detected.  Dropping a player back to Overworld spawn if the dimension is "unknown" seems problematic, as it would most likely be a player on a Space Station and the player would then need to take another rocket to get back there.

**Comment by Hatventures** [comment]
@radfast Yes, i thought that would cause multiple gameplay issues. I was merely thinking of a "workable" solution :).
In any case, thank you for taking the time to reply. And i hope that one day, somehow, we manage to find a solution!

Until then, happy coding.
