### ISSUE TITLE
Spacegear not rendering with Optifine (Standard and Ultra)

### ISSUE THREAD

**Issue by PsychoLynx** [micdoodle8/Galacticraft#1350]
Installed build #250 of GalactiCraft 1.7.10 and ran the game with only that and with each of the three different versions of Optifine (1.7.10 Light A4, 1.7.10 Standard B4 and 1.7.10 Ultra B4) - the spacegear (helmet, tanks etc.) was only rendered when I used Optifine Light A4 and GC. 

Thanks!

**Comment by PsychoLynx** [comment]
Wow, how did I miss your post! Thanks a lot, I will try it right away :)

**Comment by radfast** [comment]
That's odd, I missed the post also - normally I would be notified.
Maybe I was partying on 31 December 2014 :)

**Comment by radfast** [comment]
I incorporated Adama007's change to SmartRender in the next version so you guys can update to the latest Galacticraft.  (Anyhow it's better coding, because our rendering code is really using SmartRender and not SmartMoving, it would have bugged out if SmartMoving was installed without SmartRender...)

I guess the SmartRender guys found a way to fix the Optifine issue, so I will try to figure out what that is now.  Leaving this open until I have done that ...

**Comment by micdoodle8** [comment]
Fixed as of f126b90452f9a02d7a6ce031c91cd48949b55c4e

Other Optifine issues remain, but I'll close this issue since gear rendering should now work fine.
