### ISSUE TITLE
Galacticraft and Big Reactors in Space

### ISSUE THREAD

**Issue by MachiavelliSeraphim** [micdoodle8/Galacticraft#1367]
Ive got a strange problem and cant seem to find a cause.

In Minecraft and Mystcraft Dimensions this Turbine works as expected and as my math shows it should.
![overworld](https://cloud.githubusercontent.com/assets/10451525/5664861/9103bf1c-9721-11e4-843e-6b5ea5a73ca1.png)

In the space station dimension, I get really strange things happening.
![space station](https://cloud.githubusercontent.com/assets/10451525/5664886/cbd8f38c-9721-11e4-8551-9eb964a5e0b2.png)

Its almost if something in galacticraft is adjusting the drag coefficient for the turbine.  But even if I over drive them with steam, I do not get the full output at higher RPM.
![over-driven](https://cloud.githubusercontent.com/assets/10451525/5664912/0cceb732-9722-11e4-882f-76d2cb803438.png)

Got any Ideas?
Im stumped if Galacticraft isnt changing values for Big Reactors.
They work in all other dimensions as expected.
I have not built one on the moon, mars, or the asteroid belt yet either.

If you would like me to, please let me know.
Running FORGE 1277 with these Mods.
![mod list](https://cloud.githubusercontent.com/assets/10451525/5664939/592ef48e-9722-11e4-9f7e-c1e7edb3488a.png)

**Comment by radfast** [comment]
Galacticraft is not changing anything specifically to do with Big Reactors.

I'm not a Big Reactors expert, but from my general experience with other Minecraft mods (for example Atomic Science), I think most likely, an issue of this kind is connected with:
* some difference in the way the reactor is build
* a difference in alignment, e.g. one reactor is East West, the other is North South
* maybe a difference in height is relevant: there are mods with generators which work at different efficiencies at different y heights
* different positioning in the chunk, maybe something works differently if it is near a chunk boundary (especially if you are using a chunk loader which only loads the chunk it is in)
* differences in the number of solid blocks nearby, maybe a Big Reactors reactor counts yp the number of stone blocks within a 30 block radius and uses them as neutron dampeners or something - in a space station there would not be stone or other solid blocks unless you put them there

Galacticraft does of course change the gravity and the oxygen in space dimensions, but that should only have an effect on living entities.  Not reactors.  (A current open issue is that vehicles, e.g. Moon Buggy, in the Space Station dimension still have gravity.)

One other possibility is it is connected with the dimension loading and unloading.  Do you have a chunk loader at that location?

I'd be interested in what happens if you build a reactor in the Asteroids dimension.  That is very similar to the Space Station dimension in terms of how Galacticraft works (space station, oxygen, etc).

**Comment by MachiavelliSeraphim** [comment]
I will try building the same turbine in other locations and see what happens.

I know i have 8 turbines all behaving the same in space and 3 in other locations working fine.  

Its strange.

Yes the area is chunk loaded and it covers all the areas the turbines occupy.

The turbines are all exact clones of each other, only difference is in where the output ports are.

I just find it strange that only turbines in the space station dimension act wierd so far....

Ill let you know what I find.

Date: Thu, 8 Jan 2015 10:26:33 -0800

**Comment by MachiavelliSeraphim** [comment]
Everything works as expected in the Asteroids Dimension.
This is quite odd isnt it?

  
    
    
  
  
 		 	   		  =

**Comment by MachiavelliSeraphim** [comment]
After some more messing around, I think its the BR issue where turbines can misbehave when built across chunk boundaries.  Ive let  erogenousbeef know what I've found out and told him i think its a repeat of the previously discovered issue.

Unless I find out more, I'm going to leave this as is and rack it up to the chunk boundary problem.

Thanks for the time.
Keep up the phenomenal work.

**Comment by radfast** [comment]
OK, thanks for coming back, I will close this issue now.
