### ISSUE TITLE
Fuel Loader Doesnt accept Buildcraft Fluid pipes

### ISSUE THREAD

**Issue by Cracks777** [micdoodle8/Galacticraft#1409]
the fuel loader will accept buildcraft power pipes but it wont fill with fuel from pipes?
Is this Intended or a bug.

**Comment by radfast** [comment]
It does accept Buildcraft Fluid pipes.

Just to be sure, I just tested it in the latest Galacticraft.  A Golden Fluid Pipe connects properly and fills the Fuel Loader with fuel.  Everything is good.

If it's still not working for you, please post:
* screenshots of the setup which is not working
* which exact Buildcraft and Galacticraft versions
* fml-client-latest.log

If it's actually working, please can I ask you to take more care before posting new issue reports about things which are, in fact, not broken, at least not broken for anyone else.  (See also #1397)

It is also possible that you, and you alone, have a buggy installation - maybe because of another mod, a bad download, a strange Forge version, or something wrong with your Java or your Minecraft client...  We can't trouble-shoot those things - they are not Galacticraft bugs - but it might be a good idea to test the exact same in-game setup on a friend's computer where everything is working.
