### ISSUE TITLE
[Add-on] Frequency Module message with breathable planet

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1411]
![untitled](https://cloud.githubusercontent.com/assets/6128413/5899444/bddac2cc-a58d-11e4-9e25-1fa866a827fc.png)

Why message is asked Frequency Module? I set getSoundVolReductionAmount to 0.0F

**Comment by radfast** [comment]
You should set getSoundVolReductionAmount to __1.0F__  if you do not want to change the sound.  

Because the sound volume reduction is a divisor, 0.0F will make the sounds very loud (volume x 100, because the code sets a minimum value for getSoundVolReductionAmount of 0.01F).

I added code so there will be no frequency module warning if getSoundVolReductionAmount is 1.0F or less

**Comment by SteveKunG** [comment]
OK. Thank you very much. :)
