### ISSUE TITLE
Feature request: Galacticraft Blocks (Copper Block, Tin Block, & Aluminum Block) included in "oreDictionary"

### ISSUE THREAD

**Issue by thormbush42** [micdoodle8/Galacticraft#1421]
When trying to convert Galacticraft's blocks (Copper Block, Tin Block, & Aluminum Block) to other mods' versions of those blocks, nothing is shown and the blocks appear to not be configured with oreDictionary (correctly or at all).

Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.8.257
OreDictionary Converter version: 1.6.0

**Comment by radfast** [comment]
That's intended.  How are you trying to convert the blocks?

**Comment by thormbush42** [comment]
Using the "Ore Conversion Table" from the "OreDictionary Converter" mod which uses oreDictionary to convert the blocks

**Comment by thormbush42** [comment]
For example, I want to convert the "Copper Block" from GC to the "Copper Block" from IC2

**Comment by radfast** [comment]
I guess just break it into ingots, convert the ingots, and make your IC2 block.

I'll look at how easy it is to add our blocks to the OreDictionary without breaking the current crafting rules which are smart, right now I'm not sure if that's going to be possible.

**Comment by thormbush42** [comment]
That's the thing, as a result of having several mods that have this same crafting recipe, and having the "OreDictionaryConverter" mod allowing other mods' similar items craft the same blocks, I am only able to craft the Galacticraft copper blocks using copper ingots. So, progression in other mods is halted as a result of not being able to convert GC's copper block.

**Comment by radfast** [comment]
That should not be happening in the recent versions of Galacticraft.  For example, Mekanism ingots will make the Mekanism copper block.

Which version of GC are you using?

**Comment by thormbush42** [comment]
Oh, well now it's giving IC2 copper block with GC copper ingots
![2015-01-31_23 31 50](https://cloud.githubusercontent.com/assets/10698365/5990287/84c4ab48-a9a1-11e4-8a93-00415304cc69.png)
![2015-01-31_23 32 02](https://cloud.githubusercontent.com/assets/10698365/5990286/84c41ff2-a9a1-11e4-82c6-732b4b6c769b.png)

**Comment by thormbush42** [comment]
But this is easily solved by converting the blocks into other mods' blocks - like what I'm requesting GC have enabled with it's ore storage blocks

**Comment by radfast** [comment]
I understand what you are asking for, but it seems to me that it's only going to help players who have the "OreDictionary Converter" mod.

IC2 should not be allowing their block to be crafted from Galacticraft ingots, that's the real problem here.  Have you reported this as an issue over at IC2?  Please point them to this if they want some ideas as to how to do it: https://github.com/micdoodle8/Galacticraft/commit/c28c292d1315a0154ad6fa567fc71fb909537fe6

**Comment by thormbush42** [comment]
I just tried this without the OreDictionaryConverter mod, and this was still the case.

**Comment by thormbush42** [comment]
This also happens with Mekanism and Thermal Expansion copper ores - IC2's block crafting seems to allow other mod items to craft IC2 stuffs even if it means overriding other mod crafting recipes.

**Comment by thormbush42** [comment]
I have now reported this issue to the IC2 mantis bug tracker and have referred to the link you have provided. Thanks for the help.

**Comment by thormbush42** [comment]
If anyone's interested, the past 2 hours of Googling has resulted in me finding a mod that fixes the crafting recipe conflict issue where ingots from one mod craft blocks from another. it's called "NoMoreRecipeConflicts" (download here - http://www.8minecraft.org/no-more-recipe-conflicts-mod/)

**Comment by Adaptivity** [comment]
@thormbush42 NEVER use links like you provided. Replace your link with official one: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287599-gotolink-updates-natureoverhaul-2015-01-28

**Comment by radfast** [comment]
I'm going to mark this as closed because
- it's really a suggestion, there is no bug or issue in Galacticraft currently
- the suggestion is to workaround a bug caused by another mod, here IC2, overriding all recipes: really IC2 need to fix that
- even if we implement the suggestion (which I might do if it does not break something else) it will only be useful for players who have installed that specific other mod, the OreDictionaryConverter, or something equivalent from another mod

I have noted the suggestion, thank you for raising it.
