### ISSUE TITLE
[1.6.4] Not working on modded server

### ISSUE THREAD

**Issue by Joeakuaku** [micdoodle8/Galacticraft#1430]
I run a small modded server with about 50 different mods installed, not counting child mods. This one won't work.

On clients, for example when you switch to the second inventory tab, it says "Galacticraft player instance null server-side. This is a bug.".

On the server, it says "Could not find player base server instance for player x"

This is really getting annoying since this seems like an awesome mod that me and my friends wanted to play. I should also say that I'm running Forge 965 for Minecraft 1.6.4, Galacticraft 1.6.4-2.0.14.1084. Did I miss anything?

**Comment by radfast** [comment]
You should use the latest Galacticraft for 1.6.4, that's 2.0.14.1098 (the one in red on the downloads page).  It has a few bugfixes over 1084 and is the most stable version.

Galacticraft works fine for everyone else in 1.6.4 AFAIK.  It's included in most of the biggest 1.6.4 modpacks and has been that way for a long time.  You're using the correct Forge version.  So ... I'm not too sure what might be going wrong in your install, but seems like it must be one of the other mods conflicting.

If you want to spend some time trying to fix this, it would help me if you can identify which exact other mod is conflicting.  Make a new server folder for these tests (copy across whatever server files you need) with a new world: these tests will definitely destroy an existing world.
* first off, see if you can run a server with only Forge 965 + Galacticraft installed
* then start copying other mods into the /mods folder in batches until things stop working, and figure out which mod is conflicting
* then to confirm, see what happens if you run the server with only Galacticraft and that other mod

Once you've narrowed it down like this, give us details and also paste up your ```fml-server-latest.log``` somewhere and provide the link.

Or: you could take the leap and switch your server to 1.7.10.

**Comment by radfast** [comment]
Also post up your complete fml-server log please.

**Comment by radfast** [comment]
Closing due to lack of needed information, also this is a 1.6.4 issue which is most likely not a problem in 1.7.10 (due to the option of using the PlayerAPI in 1.7.10).

To be clear: we do want people also to enjoy playing our mod in 1.6.4 and I am very happy to look into this issue some more, but to do that I will need specific information about which other mod is conflicting with Galacticraft (from logs + testing).  Give me that information, and I will re-open this issue.
