### ISSUE TITLE
Crash in achievements GUI

### ISSUE THREAD

**Issue by XBlackLeopardX** [micdoodle8/Galacticraft#1431]
Why I try to look through my achievements GUI I get this crash
I am currently using the lastest version of every mod and also forge
http://pastebin.com/YVtu4A0U

**Comment by Robijnvogel** [comment]
Are you certain that your browsing through achievements was the issue here?
The crash seems to be caused by Galacticraft trying to determine if a Draconic Evolution Tolkiencraft "pig mob soul" should be set on fire or not. Maybe this mod uses some unconventional layout objects on its achievements page that conflict with Galacticraft. This is likely, especially as the "pig mob soul" seems to be located at world coordinates (0,0,0). If this is the case, maybe there is an option to turn these "fancy achievements" off in the Draconic Evolution Tolkiencraft config file(s).

i suggest you try to do the latter and report if the problem persists or not.

**Comment by Robijnvogel** [comment]
![image](https://cloud.githubusercontent.com/assets/7999099/6092478/40114a2a-aee1-11e4-885e-05392c4a51af.png)

I tested it and it is exactly as I thought! The achievement I have so gracefully encircled in paint, is the culprit. It shows an alternating mob that is spinning, for which, somewhere deep in the code, it probably uses an entity. Galacticraft does not know if it should set fire to this entity or not. Maybe because its resident Dimension is not specified or because the official location of the "pig mob soul" is exactly between two blocks and it is not capable of determining the light level there.

There does not seem to be a config option to turn off this one achievement render. I checked.

The mod creator of Draconic Evolution probably should not have used this method, but then again, this might lead to the code of Galacticraft becoming more waterproof. Who knows?

What you should do now:
Report this problem to Draconic Evolution. They should at the very least add a config option to turn off the animation on the achievement.
Until this problem is resolved you should:
1. not browse your achievements,
2. temporarily remove Galacticraft from the pack (but I can not guarantee that other mods do not also conflict with this particular achievement animation)
3. or temporarily remove Draconic Evolution from the pack

**Comment by XBlackLeopardX** [comment]
okay will do thanks

**Comment by radfast** [comment]
Galacticraft has code to prevent mobs from burning in space.  The code (obviously) tests which dimension the mob is in.  The code is not expecting to find a burning mob which has no dimension.  Draconic Evolution's Achievements screen draws a burning mob which is not in any dimension (because it's being drawn on a graphic on an Achievements screen).  I guess Draconic Evolution must be the only mod to do that, otherwise we would have seen this bug before...

Galacticraft code is fixed next build to cope with this.

@XBlackLeopardX  you should be Ok from Galacticraft version 3.0.8.262, you can keep all your mods.

---

@Robijnvogel the way you write makes it seem as if you are knowledgeable but your explanations are not correct, which results in you giving players incorrect advice.

**Comment by XBlackLeopardX** [comment]
@radfast Okay, and I did notice that in the snapshot for the next release of Draconic Evolution they have fixed the issue I tested the snapshot with version 261 of Galacticraft and it was fixed on their end in the snapshot

**Comment by Robijnvogel** [comment]
@radfast

Could you please tell me what is incorrect about my explanations and/or advice? By knowing my flaws, I can better myself.

**Comment by radfast** [comment]
@Robijnvogel I appreciate that you are trying to help, but you wrote a lot including speculations about various possible causes of this error, when in fact the cause is (in this case) clear from the stacktrace.  Reading from the mid to the top it was the Achievements screen -> rendering an entity -> a standard Entity.shouldRenderOnFire() check -> a Galacticraft hook into our WorldUtil which extinguishes the fire in space.

I don't think there was any coding error in Draconic Evolution.  It could give us problems (extra work) if a compatibility issue is reported on another mod's issue list when, in this case, it was an easily-fixed Galacticraft bug.  In my opinion it's bad for us reputationally if other mod authors think we at Galacticraft are happy to say "it's a coding error in the other mod" when in fact the bug is in our code.  To be clear, I'm very happy to say that when it __is__ an error in the other mod (or when I think it is in the other mod), but I'm not at all happy to say that when the fault is in Galacticraft.

Also, any "null pointer exception" is easy to fix in coding terms, as soon as the stacktrace is posted.  We can always add a null check, it takes a couple of minutes or less.  Usually a null pointer exception is - as here - simply a case of the programmer originally assuming that a null was not possible at that place in the code.  Sometimes an exceptional situation like Draconic Evolution's achievement screen comes along, and that's OK, we just fix the issue.
