### ISSUE TITLE
Capes.txt -> Update

### ISSUE THREAD

**Issue by NeturonicAngelz** [micdoodle8/Galacticraft#1446]
Hello, there doesn't seem to be support for UUID's whatsoever for 1.7.10+ versions, which is why I am posting this here. I've changed my username from X_angelz_X -> Angelz and would love an update on the contributors list to actually show my correct MC username. (Please disable the cape as well)

Thanks, and sorry if this is a bit awkward place to be posting it.

**Comment by EzerArch** [comment]
Relevant: http://forum.micdoodle8.com/index.php?threads/name-changes-donation-capes.4905/

**Comment by radfast** [comment]
That's fine to post here, it will need coding changes to support UUIDs and the open issue reminds me that that is needed.

Update on the contributors list seems more tricky, I'm sure micdoodle8 can do that manually for you but right now I don't see any way to automate it that isn't absurdly complicated, and I guess there won't be more than around 1 name change a month.

**Comment by radfast** [comment]
Your cape now updated to not shown (anyhow it would not show because of your name change).  If you want the cape in-game again under your new name Angelz please just ask anytime.

Updating the Donators list on the website will take a little longer, sorry.

I'm going to leave this issue open to remind me to change all capes to UUID.

**Comment by NeturonicAngelz** [comment]
Thanks! Yeah I'm not really wanting the cape shown since I have a Minecon cape. Just wanting to be sure its known and such that my username has been changed. ;)
