### ISSUE TITLE
Weird error on server

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#1454]
Does this error has anything to do witht Galacticraft?
http://paste.ubuntu.com/10180411/

**Comment by Cracks777** [comment]
ive never seen any of that from galacticraft. and i use several of the mods you have in there.

**Comment by radfast** [comment]
The error is caused by 2 things in combination:

1.  You do not have matching GalacticraftCore and MicdoodleCore versions and the startup code is trying to tell you that.

2.  To tell you that, the startup code wants to draw a simple message box on the server's screen with options to download the latest version or ignore the error.  It appears that your server is running on a PC which does not have display drivers (or maybe Java libraries) even to draw a message box on screen - is this a server box with no screen which you are accessing remotely?

Anyhow I have updated Galacticraft in version 3.0.8.266 to hopefully not crash in situation 2, it will just write the error to the console if it can't find a display.

__You can fix situation 1 easily enough by just making sure your versions of all three Galacticraft files match.__

(If that still keeps on produces a version mismatch error in console when you launch then please let us know - I think that may still be possible in Linux - and in that case I can give you a workaround.)
