### ISSUE TITLE
2 Rocket on 1 platform

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1459]
![Image](http://firepic.org/images/2015-02/18/hvqdtg5496nc.png)
![Image](http://firepic.org/images/2015-02/18/m05rle4801a4.png)

After landing, rocket which was in passive mode - breaks
![Image](http://firepic.org/images/2015-02/18/q085cpb2ogj7.png)

I think you need to make check on a rocket standing at given coordinates in the controller start

**Comment by radfast** [comment]
I don't see 2 rockets breaking in your screenshots, there is only 1?

Anyhow, it's by design that if a rocket ("Rocket B") lands on a pad which already has 1 rocket on it ("Rocket A"), then Rocket A will break.

You're suggesting that a launch controller should not allow Rocket B to fly if there is another rocket already on the destination pad.  But that doesn't cover all situations.  Maybe Rocket A is placed n the destination pad after Rocket B already launched.  Maybe Rocket A will start flying before Rocket B arrives.

One other possibility would be if the destination launchpad is full then Rocket B should hover in-flight above the destination until it uses up all its fuel, but then it will have to land (or crash).

The real answer here is that players should not be so dumb as to have a system where there can be a possibility of another rocket on the destination pad - or if players do have that possibility, they need something to pick up any rocket which drops.  (Hopper?)
