### ISSUE TITLE
All downloads incomplete

### ISSUE THREAD

**Issue by ElMenduko** [micdoodle8/Galacticraft#1467]
I haven't played modded minecraft in a while now, so I downloaded Recommended 1.7.10 galacticraft files (all 3 of them) and came up with this:

First, I got a message saying incomplete download (Mod file Galacticraft-Planets-1.7-3.0.8.257.jar is an incomplete download and will likely cause errors, please re-download it!). I decided to try both options so I ignored and:

java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP

Minecraft crashed when trying to create/load a world. So tried the other option, and googled.

Found out that redownloading had solved the problem for a lot of people so that's what I did. It crashed again.

Redownloaded the latest 1.7.10 version, crashed again. Redownloaded both in other computer, crashed again!

I think the issue might be with the download, and not with the mod files (cos none of them work, and someone should've noticed). Gonna paste my crash report anyways:

Crash report: http://pastebin.com/PRf3yESd

From what I understand, it has trouble with the player GUI because of "ClassNotFound"; and I think that confirms the download is incomplete. But they all are!

**Comment by radfast** [comment]
This is not a bug in the mod.  The mod already told you, you have an incomplete download.

You need to fix the download and then everything will be OK.

The site is working 100% fine just now, I tested it and got a complete download.  I'm aware that very rarely people can get incomplete downloads but I've never figured out the cause.  I guess you know how to download stuff otherwise you wouldn't have the smarts to come onto Github and post a crash report, so we can assume this is not user error.  The only thing you can do in that case is be patient, wait a few hours, then try again; maybe also clear caches on your browser and try using a different browser like Firefox or Chrome.

**Comment by radfast** [comment]
By the way, the __Latest__ version is the recommended one.  The one which is called stable is not recommended, it has known bugs, it's only there to keep happy the kind of people who think that an older version is more stable ...

http://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide  tells you the latest is recommended :)

**Comment by radfast** [comment]
Did you get this working, in the end, @ElMenduko?

Another player on MinecraftForum has reported a similar-sounding problem, using MultiMC (which we do not explicitly support).
