### ISSUE TITLE
Feature request: Biome registration

### ISSUE THREAD

**Issue by kdb424** [micdoodle8/Galacticraft#1484]
Would you consider adding biome registration to your API or mod. I know that there are other ways that you can check, but I'm working on a mod that hooks in, and it's simple enough to do. If you would like me to make the changes and push up, I could, but I'd need it in the API to really leverage it. Thank you for your consideration.

net.minecraftforge.common.BiomeDictionary

**Comment by radfast** [comment]
Is this connected with this: https://github.com/MinecraftForge/MinecraftForge/issues/1704

I'd like more info on what your mod proposes to do and how you will fix that issue.

It's also not clear what you are asking us to make available in the API.  Please be more specific.

I'm closing this as it's not a current issue with Galacticraft, but you can continue the discussion of course - we will see, and respond to, your posts here.

**Comment by kdb424** [comment]
Forestry has hooks for generating things by BiomeDictionary. Unless I failed to search through your code correctly, I couldn't find what your moon biome was registered as. I'm trying to generate something on the surface by biome ID if that would be possible. I could work around it, but I'm trying to keep within both API's for updating purposes.

**Comment by radfast** [comment]
The purpose of the BiomeDictionary is so that mods creating new biome types (let's say, new types of icy/snowy biomes) can be populated with the right type of mobs, flowers etc by other mobs.  So all Biomes can be registered as various types.

Unfortunately, a lot of mods in my experience don't use it - which leads to a poor gameplay experience, for example, in a modpack __Attack of the B Team__ because it includes Biomes O'Plenty so around 90% of the biomes are non-vanilla biomes, but some items essential to the game only spawn in vanilla biomes.

None of that is relevant for Galacticraft.  First up, none of our biomes is on the Overworld, so the problem I described can't happen.  Second, we don't want other mods spawning items in our biomes normally, certainly not trees and flowers and mobs, because our biomes are on other planets.  Third, our biomes don't fit into any of the "types" in BiomeDictionary.

I am still not understanding what you are needing to generate in moon biomes, maybe a screenshot would help.  But you also need to be aware that by default (it's configurable) Galacticraft will disable __all__ other mods worldgens in space biomes, that's to stop us seeing IC2 Rubber Trees and Tinker's Construct slime islands and Natura clouds on the Moon.

**Comment by kdb424** [comment]
I'm working on a mod that adds additional Bee Hives in game that tries to place them on the surface of other planets. I'm integrated with Forestry, but now I understand why none of my generation code was working. Thank you for clearing that up. If I did want to spawn something by force on the surface, keeping in mind they are about as common as villages and only 1 block, what would be your recommended way of achieving this in terms of something that would bypass your block on generation for this small change?

**Comment by radfast** [comment]
You should register a handler for ```micdoodle8.mods.galacticraft.api.event.wgen.GCCoreEventPopulate```

Search our code on this Github for references to ```GCCoreEventPopulate``` and you should see some examples of it in use.

**Comment by kdb424** [comment]
Thank you so much for your suggestion. I'll report back if I have any problems, but consider this problem solved. Your help and guidance is great as always.

**Comment by radfast** [comment]
This is probably the closest to what you want - spawning Slimeling eggs on Mars.

https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/planets/mars/EventHandlerMars.java#L130-153

**Comment by radfast** [comment]
hmm looking at that EggGenerator code (which I have never looked at in detail before), it's not perfect because it takes a simple approach of trying to spawn an egg anywhere between y=0 and y=128, and simply testing whether that is a surface, meaning solid block with an air block above it.  That's going to result in eggs spawning sometimes in underground caverns and dungeons.

**Comment by kdb424** [comment]
Got it generating on mars. Thank you for the help. Now I just have to sort out my code's problems and get an on the surface generation, and I'll be good. Consider this closed, and thank you for going over the top to help me.

**Comment by kdb424** [comment]
Sorry to bring this back up, but I got Moon and Mars generation working absolutely flawlessly. When trying to use the same code on asteroids, it's not working at all. It's not even trying unfortunately. Checked that it is calling the class, but I think there is a change in onPlanetDecorated as it's not working the same. If you need a reference of my code, it's here.
https://github.com/kdb424/SpaceBees/blob/master/src/main/java/spacebees/world/feature/HiveGenAsteroids.java

**Comment by radfast** [comment]
There's no planet...

We are also not (currently) generating other mods ores in the asteroids, though that is something I need to look at.

We may one day implement the dwarf planet Ceres in the Asteroids dimension but there are other priorities just now.

**Comment by kdb424** [comment]
Would you recommend that I look for another way of hooking into world get just for that dimension, or would you say it's just better to wait until you implement it? I'm just trying to avoid as much conflict as I can. Sorry for asking so much. I haven't programmed i java for a while, and haven't worked on minecraft mods since 1.2 with modloader, and things have changed a lot.

**Comment by radfast** [comment]
For Asteroids, wait, and consider skipping it completely (unless / until there is Ceres).  Because Asteroids are not planets we generally do not expect any other mod - even SpaceBees - to be doing worldgen there.

**Comment by kdb424** [comment]
Alright. I don't expect you to change your project for mine what so ever. Just wanted to make sure that it wasn't my code that was causing my issues. All cleared up. If you guys ever want help with anything, I'm always up for helping out. Thank you again for all of your help!

**Comment by radfast** [comment]
You're very welcome.
