### ISSUE TITLE
Can't change dimensions.

### ISSUE THREAD

**Issue by demethan** [micdoodle8/Galacticraft#1497]
Hi, 
Love your mod, 

I can't go to other planets. I tried with a rockets and the /dimensiontp .
I always fall back to overworld

thanks 

Ver. 1.7-3.0.8.271 (Core , Planets)

**Comment by radfast** [comment]
Are you playing single player or on a server?
Either way, please provide full log (```fml-client-latest.log``` or ```fml-server-latest.log```).

**Comment by demethan** [comment]
I downgraded to 257 and it seems fine when I remove Mariculture. 

Sorry  for wasting your time.

**Comment by radfast** [comment]
Wait!  It's not a waste of time.  If Mariculture is blocking the dimension changes, that's something we need to know.

(Also there should not be any difference between 257 and the latest, dimension-wise.  257 is not now recommended, it has a few known issues.)

**Comment by radfast** [comment]
You're not using JourneyMap?

**Comment by demethan** [comment]
Yes we are using Journeymap, 
Our pack is http://www.atlauncher.com/pack/DelusionsofAdequacy

here is the info I have so far. 

It is not Mariculture directly. It is a combination of Mariculture and Gregtech5 (I know GT5 is dead)

Gregtech5 bypass the worldgen blacklist from Mariculture. That makes the world generation of the dimensions crash. 

you can look at this thread for more info. https://github.com/joshiejack/Mariculture/issues/256#event-248273559

The workaround that Joshiejack suggested fixes the problem completely. 

Thank you.

**Comment by radfast** [comment]
OK  I don't really understand what's written in that other thread, or why worldgen would be affecting your ability to use /dimensiontp.  Rockets, and /dimensiontp, take the player to the Planet Selection Screen before any other dimension is even chosen.

Anyhow, what I'm getting from this is that it's not a Galacticraft issue, so that's fine.

Please see what is written here under 'GregTech' and 'JourneyMap':
http://wiki.micdoodle8.com/wiki/Compatibility
If you can suggest anything to add there, please tell me what you think it should say.  We want to help other players who might have a problem, but we do not want to falsely state incompatibility when things are actually OK for most people.

**Comment by demethan** [comment]
Sorry if I wasn't clear. I was jumping between multiple things.

There is a problem for generating dimensions, when Mariculture and Gregtech is installed in a pack. 
So generating planets was one of the symptoms of the above problem. 
the workaround is posted in my earlier post.

/dimmensiontp worked fine and the planet map works fine.

Hope this clarifies things and helps other players.
