### ISSUE TITLE
Evolved creeper causing client crash (impossible variable conversion)

### ISSUE THREAD

**Issue by jjplay175** [micdoodle8/Galacticraft#1511]
For some reason galacticraft mobs can spawn on the overworld in a small bundle like 2-3 of them in a specific location, if an evolvedcreeper spawns the client crashes, I assume it is the creeper but it started doing it on rare occasions and I have to delete the chunk it spawned in using mcedit, Clients only crash if the chunk is loaded on their side

Full log http://pastebin.com/kebQs0CR

**Comment by radfast** [comment]
The usual reason for this is because you have different mods or different versions on client and server.  It's not Galacticraft causing this.  It's because one of your other mods, is making a mob on the server which does not exist on the client (or the way around) so the mob ID numbers have gone out of sync.

You need to carefully check the modlist between your server and your clients and make sure the clients have __exactly__ matching versions of every mod.

If all the mods exactly match and you still have the problem, then check the configs: especially other mods' configs to do with things like whether one of their mobs are enabled or disabled.

**Comment by radfast** [comment]
__You should also update your Galacticraft.__
