### ISSUE TITLE
Extra utilities not getting along with galacticraft core

### ISSUE THREAD

**Issue by CrusherTechnologies** [micdoodle8/Galacticraft#1518]
Well the title pretty much says my problem
http://pastebin.com/crzXtdKK

Seems like a problem between Extra utils and galactricraft core's player entity
So when ever I use a block with a gui or item it crashes the client.

**Comment by radfast** [comment]
The title, and the suggestion of any "problem" with Galacticraft here, is wrong.

This is 100% an Extra utils problem, looks like a bug in their mod, or maybe a problem between their mod and vanilla Minecraft (or could be Forge or a version issue).

The fact that you see this line in your crash report:
>        at micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP.func_70071_h_(GCEntityClientPlayerMP.java:55)

is basically irrelevant.  You will see that line any time any mod has a crash relating to the player in Minecraft, because whenever Galacticraft is installed, all players in the game are changed from the vanilla type to GCEntityClientPlayerMP.  It's not a Galacticraft issue any more than it's an issue with vanilla EntityClientPlayerMP.

I repeat, this is NOT a Galacticraft problem.   At all.  Our mod is fully compatible with all other major mods including Extra Utilities and we act swiftly to fix genuine incompatibilities or crashes.
