### ISSUE TITLE
Circuit Fabricator crash

### ISSUE THREAD

**Issue by XFactHD** [micdoodle8/Galacticraft#1531]
When I place a circuit fabricator on one side of a tesseract that is receiving power, the game crashes with an exception in the MJ-API.

**Comment by radfast** [comment]
It's because you have mixed other mods with 2 different versions of Buildcraft API in your modpack.
http://wiki.micdoodle8.com/wiki/Compatibility#Buildcraft_API_-_outdated_versions_in_other_mods
You can __workaround__ this by updating Galacticraft.
You can __fix this properly__ by finding which other mods have out-dated Buildcraft API and updating them.
