### ISSUE TITLE
Unable to return to Overworld with non-vanilla Worldgeneration in Multiplayer

### ISSUE THREAD

**Issue by Voidi** [micdoodle8/Galacticraft#1550]
May similar to #370
I use the latest Galacticraft versions and [Alternate Terrain Generation](www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291067-atg-alternate-terrain-generation).
When trying to return from the moon, i am unable to select the overworld (launch button is red).
This only occurs in multiplayer, singleplayer works fine.

**Comment by radfast** [comment]
Please carefully check the configs on your server.   Especially this one in Galacticraft core.conf:
>     B:"Disable rockets from returning to Overworld"=false

Maybe delete the Galacticraft configs on your server and let the mod make you a fresh set which is good?

If there's still an issue after you fixed the configs, we'll need you to test your same game world without the Alternate Terrain Generation mod installed : make a ___backup of your game world before testing__ (copy the World folder on your server) because changing mods in an existing map can result in block or item loss.

Closing for now, because my guess is it is your configs which are the problem.  If it proves to be some other problem we can re-open.

**Comment by Voidi** [comment]
Solved.
As changed this config, i thought this would delete the used rockets.
