### ISSUE TITLE
ForgeMultipart support for Galacticraft decoration blocks

### ISSUE THREAD

**Issue by halvors** [micdoodle8/Galacticraft#1552]
ForgeMultipart support for Galacticraft decoration blocks. This would allow nicer wiring on space stations etc.

**Comment by dj3520** [comment]
Suggestions belong in the forum

**Comment by radfast** [comment]
@halvors  Thank you for the suggestion, we will implement this.  I'll post here again when it's done, could be a few days.

**Comment by radfast** [comment]
That was easier than I thought.  Try the latest build (3.0.11.315), this has Forge Microblock versions of:
* Tin Decoration block (2 types, one with a pattern one without)
* Aluminum, Copper, Tin + Meteoric Iron blocks
* Moon Turf, Moon Dirt, Moon Rock
* Moon Dungeon Brick

We can look at adding a few Mars and Asteroids blocks as well once I make sure there are no new issues caused by what is done so far.

**Comment by dj3520** [comment]
@radfast What about support for routing wires/pipes through blocks that are hollow? I realize there's sealable blocks and walkways, but not that look like <insert a specific block here>

**Comment by halvors** [comment]
@dj3520 +1

**Comment by radfast** [comment]
Unfortunately guys that's at least an order of magnitude different in terms of suggestion - it would basically mean re-writing all of the Galacticraft wire and pipe code.  That's not something I am willing to do.  For a start, I do not believe the pipe and wire models are currently the correct sizes to fit exactly into the space in 'hollow' blocks.

If you want wires and pipes that fit with Forge Microblocks, get them from a mod which specializes in wires and pipes - for example _Mekanism_.

For the future, we can maybe look at adding a way to texture sealable blocks - that has been suggested on the forum.

**Comment by dj3520** [comment]
>I do not believe the pipe and wire models are currently the correct sizes to fit exactly into the space in 'hollow' blocks.

Project Red's framed wires are much bigger and fit nicely.The red alloy framed wire is second from the left.
![image](https://cloud.githubusercontent.com/assets/8284194/7032985/b637d7e6-dd44-11e4-8412-f7311b13b60f.png)
Textured sealable blocks reminds me of facades.
>@dj3520 Excellent idea :D

Originally I thought this was what you were trying to suggest.

**Comment by halvors** [comment]
I don't think the size will be a problem, this is one od the things that Galacticraft is missing out on. Cables and pipes should really support ForgeMultipart :D

**Comment by radfast** [comment]
The picture shows the size problem.  The Galacticraft wires are smaller than the hollow area, resulting in air around meaning that it will (a) look bad and (b) not make a seal.

**Comment by dj3520** [comment]
If I actually used microblocks (above is just demonstration) The wires would run horizontal/vertical through the walls so that they wouldn't be seen. Your point A can be overturned via functionality. Secondly, I'd use the sealable block as a sort of wall outlet. Now point B is overturned so long as the hollow portion runs parallel with the wall and never faces outside.
