### ISSUE TITLE
Large items in hand rendering improperly.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1558]
![image](https://cloud.githubusercontent.com/assets/8284194/7057444/c7f1810a-de23-11e4-967e-7fba09b1f529.png)

**Comment by EzerArch** [comment]
Needs more info: Galacticraft version and log with a list of mods, probably another mod is affecting player/model rendering.

This is what I get with Galacitcraft 315.
![2015-04-08_21 01 00](https://cloud.githubusercontent.com/assets/6743303/7057977/632409fa-de32-11e4-8b7d-17d655f256eb.png)

**Comment by dj3520** [comment]
Well that looks better, but it is going through your head.
My bad where are my manners? Client side mods list (CMP enviroment):
AFSU-1.2.1a-Mustard
ATG-1.7.10-0.12.0
BigReactors-0.4.1A2
buildcraft-6.4.8
CodeChickenCore-1.7.10-1.0.4.35-universal
CoFHCore-[1.7.10]3.0.0B9-40
ComputerCraft1.73
CoroUtil-1.1
Galacticraft-Planets-1.7-3.0.11.315
GalacticraftCore-1.7-3.0.11.315
IC2NuclearControl-2.1.2a
iChunUtil-4.1.3
industrialcraft-2-2.2.711-experimental
ironchest-1.7.10-6.0.62.742-universal
MicdoodleCore-1.7-3.0.11.315
MmmMmmMmmMmm-1.6
NotEnoughItems-1.7.10-1.0.4.90-universal
NotEnoughKeys-1.7.10-1.0.0b29
openccsensors-1.7.2
OptiFine_1.7.10_HD_U_B5
PiP-4.0.0
ProjectRed-1.7.10-4.5.15.75-Base
ProjectRed-1.7.10-4.5.15.75-Compat
ProjectRed-1.7.10-4.5.15.75-Integration
ProjectRed-1.7.10-4.5.15.75-Lighting
Railcraft_1.7.10-9.5.0.0
Sync-4.0.0
Weather-2.3.6
[1.7.10]DamageIndicatorsMod-3.2.3

**Comment by Nick-77ab2** [comment]
update all of your cofh mods and your big reactors
your running at least 3 months behind on the COFH mods the most recent stable version is RC7-211 for COFH Core, i advice you to update from a beta build to a stable build

**Comment by Nick-77ab2** [comment]
also ichunutil also Coroutil to latest and weather mod to 2.3.7
from the website: Updated CoroUtil to remove console spam and visual glitches 
maybe the visual glitches means with other mods?

**Comment by dj3520** [comment]
Currently Cauldron is stuck on forge version 1236, so if any mod relies on a higher forge version I can't update to it. Couldn't find Coroutil 1.1.2 but updated to 1.1.1 and weather 2.3.7
Tried again and noticed something concerning:
![image](https://cloud.githubusercontent.com/assets/8284194/7082005/5f86f88c-df1a-11e4-82f4-63c839c0ac2d.png)
Astrominer, all rockets, cryo chamber, and buggy are doing this...

**Comment by Cracks777** [comment]
Cauldron is on version 1307 and 1343

**Comment by dj3520** [comment]
Could you give me a link?

**Comment by Cracks777** [comment]
http://tcpr.ca/cauldron

**Comment by radfast** [comment]
The issue is not happening in Galacticraft alone, so it is an interaction with another mod.

I don't know half the mods in your modlist @dj3520 but you have enough experience to know what to do here ... try pulling some of the mods out of your list, make a test world in single player, start the game and see if the issue happens.

This is nothing to do with a server or Cauldron, it is something on the player side.  It will be connected with some other mod which changes the visuals of the player.  I would start by looking at DamageIndicators and PIP.

Another thing to try: you may find that installing PlayerAPI and RenderPlayerAPI fixes the issue "all by itself".  (Or in extreme cases, those two plus the SmartMoving renderer.)

If this is happening, I imagine you will also have other issues connected with limb positioning - so in Galacticraft:
* a player holding a large item should hold it above his head
* there's also a special way of holding a Flag
* a player in a rocket has his arms by his side
* a player using a parachute has his arms in the air
* a player on the Moon should "bound" slowly, not move the limbs at the normal Minecraft speed

**Comment by Nick-77ab2** [comment]
http://coros.us/mods/coroutil?dl
download for 1.1.2

**Comment by Nick-77ab2** [comment]
and dont use cauldron, use a regular forge server with nogui in the start/launch.bat so it doesn't show the gui if you dont want it

**Comment by Nick-77ab2** [comment]
it makes for a good server, and it is flexible sinc eit is forge itself, except for getting "plugins" but there are mods for that

**Comment by Cracks777** [comment]
cauldron as far as i can tell its more performance friendly, it runs much better than forge alone since it has spigot which optimizes code, i have a cauldron server with almost 150 mods and like 20 bukkit plugins and it runs 20 tps all across the board, no lag with 10 ppl online and we have at least 20+ chunk loaders and over 30 dimensions. regular forge lags so bad its unplayable with more than 3 ppl.

**Comment by Nick-77ab2** [comment]
not for me

**Comment by Nick-77ab2** [comment]
3 people is easy with forge for me

**Comment by radfast** [comment]
hmm, I am seeing this on one of my test platforms actually.  It could be Optifine B5.

**Comment by radfast** [comment]
Confirmed, it's Optifine.  This should be fixable by installing SmartRender as explained on the wiki:
http://wiki.micdoodle8.com/wiki/Compatibility#Optifine

**Comment by dj3520** [comment]
Thanks radfast, looks like I didn't have to do much but report the problem.
Nick and Cracks, not exactly the place to discuss this, but realistically this all comes down to your environment. How much ram you give java, how many cores you have and how fast they are, mods and their settings, etc. However cauldron does have spigot so that might tip the scale. Also I run a few plugins that I either can't find for forge or simply don't work as well.

**Comment by radfast** [comment]
Crosslinking: This is an aspect of #1350.
