### ISSUE TITLE
Overworld sky rendering issue

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1565]
![2558-04-10_20 59 26](https://cloud.githubusercontent.com/assets/6128413/7100880/e21782d0-e064-11e4-8c75-ba9f70ec67c3.png)

**Comment by radfast** [comment]
That's not good.

I'm also seeing a sky rendering issue in all dimensions when the NEI HUD is active, do you get that too?

**Comment by EzerArch** [comment]
> I'm also seeing a sky rendering issue in all dimensions when the NEI HUD is active, do you get that too?

I disabled NEI hud (not removed the mod itself), I'm still getting that.

![2015-04-11_16 42 19](https://cloud.githubusercontent.com/assets/6743303/7102973/074496b0-e06a-11e4-9806-e5354fa8f617.png)

Off-topic but NEI related: when I disable NEI and click on Galacticraft Player Tab, I get this:

![2015-04-11_16 42 14](https://cloud.githubusercontent.com/assets/6743303/7102980/5d229726-e06a-11e4-8642-5c8d28018d32.png)

**Comment by radfast** [comment]
The tabs + inventory issue is also noted in comments on #1505.  There's not much we can do about it, I think - it's an NEI issue, not re-drawing the whole screen.

**Comment by radfast** [comment]
I cannot reproduce the Overworld sky rendering issue in either 1.7.2 or 1.7.10.

Is it connected with this, do you think?
https://github.com/micdoodle8/Galacticraft/commit/64587ae0d40003fb8487ba67d46070c9b5fd1fc9

Build 3.0.10.298 was the last version before that...  
ci.micdoodle8.com/job/Galacticraft-1.7/298/

**Comment by radfast** [comment]
Please try latest build 3.0.11.318

**Comment by radfast** [comment]
Tabs + inventory issue is also fixed, I think.  (Maybe not fixed if you have CustomNPCs or ExtraTiC installed as well as Galacticraft.)

**Comment by EzerArch** [comment]
> Please try latest build 3.0.11.318

![2015-04-15_22 16 24](https://cloud.githubusercontent.com/assets/6743303/7172387/62aa7eec-e3bd-11e4-8ac1-d71e889f5bf6.png)

**Comment by radfast** [comment]
@SteveKunG , @EzerArch  - are you using Optifine?  Which exact version of Optifine?  Seems like it could be connected with that.

**Comment by EzerArch** [comment]
> are you using Optifine?

No. I'm using MCPatcher with resource packs.

**Comment by SteveKunG** [comment]
I'm testing on Eclipse. No Optifine.

**Comment by radfast** [comment]
ok thanks guys, this is a weird one - I have seen it once on my test platforms but not other times, I will keep looking at it.  It's probably a 1 line fix, just a question of finding it ...

**Comment by radfast** [comment]
Is this still happening?  I have not seen this issue in any of my recent testing.  Micdoodle8 made several fixes to Sky Providers in https://github.com/micdoodle8/Galacticraft/commit/982dff5d12d73c72a023212acefcf359dc512f35#diff-8776767ca6c95148437a2950be99fbcd and https://github.com/micdoodle8/Galacticraft/commit/d2a60d781b6e93248d8793d087e114eb8b39cd00#diff-8776767ca6c95148437a2950be99fbcd.

**Comment by EzerArch** [comment]
Testing with:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
Galacticraft-Planets-1.7-3.0.12.424.jar
GalacticraftCore-1.7-3.0.12.424.jar
MicdoodleCore-1.7-3.0.12.424.jar
SmartMoving-1.7.10-15.6.jar
SmartRender-1.7.10-2.1.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.0.jar 

**Results**

(editing)

**Comment by radfast** [comment]
I think a good proportion of players have Optifine, and riding a rocket into space is the main feature of the mod, so I want to fix this.

Thank you so much for identifying that this is Optifine-related :)

**Comment by SteveKunG** [comment]
![2559-01-20_01 03 04](https://cloud.githubusercontent.com/assets/6128413/12443243/34ef75ea-bf89-11e5-88e8-80a0ee647a3d.png)

Star still rendering behind the moon. Using eclipse development for testing + without Optifine.

**Comment by EzerArch** [comment]
Thinking of the other dimensions: does this bug affect only Overworld?

I remember I had a hard time trying to make textures for other celestial bodies in ther other dimensions' skies. It's either the whole texture is translucent or the alpha channel simply doesn't work rendering the texture completely opaque.

**Comment by radfast** [comment]
This issue was not caused by Optifine.

It was caused by one of the many different "sky color adjustments" in vanilla Minecraft still operating.  These are tough issues to reproduce + troubleshoot because they are different according to the time of day and the weather, maybe also the biome.

So in vanilla you have:
- time of day/night (the sky is brighter / bluer at midday than at dawn/dusk when it is a more grey color, obviously black at night)
- sunrise + sunset effects
- cloudiness and rain effects
- thunderstorm effects
- also (I think ... not 100% sure) humidity / haze effects

It's fairly complex and it's a part of the vanilla code which is not well explained in Forge, just a bunch of numbered variable names like var21.

Anyhow, next build makes some improvement.  It's not yet where I want it to be, and it doesn't yet have some of the cool features which @SpacedViking has proposed, but those will come ...

**Comment by radfast** [comment]
This has also fixed the issue where a player reaching the top of the atmosphere in a rocket, briefly sees rain / snow / other atmospheric effects, for 0.5 seconds before the game transitions to the Celestial Catalog screen.

**Comment by radfast** [comment]
Build 434 now up.

**Comment by SteveKunG** [comment]
![2559-01-31_13 33 53](https://cloud.githubusercontent.com/assets/6128413/12700687/77610db4-c81f-11e5-9054-558481a6ea5a.png)
![2559-01-31_13 33 55](https://cloud.githubusercontent.com/assets/6128413/12700688/7798798e-c81f-11e5-85f2-573c09be7ffe.png)

100% Fixed :)

**Comment by EzerArch** [comment]
@radfast, and as to the "can't render orbital planet sprite in OF" part?

![2016-01-31_15 06 18](https://cloud.githubusercontent.com/assets/6743303/12703632/0ffe9c80-c82f-11e5-8592-1a6f2a5a769a.png)

Sometimes I think it is an unfinished feature once only the overworld has this feature.

**Comment by radfast** [comment]
I don't understand what I'm looking at.  The display on the left looks messed up, the rocket is wrong.  In the main display the rocket is gold, should be black.  And there is a strange red dot.

I don't see any of those types of issues in my testing.

**Comment by XFactHD** [comment]
The red dot is a marker from the map mod.

**Comment by EzerArch** [comment]
Ouch, sorry for not telling you I was using other mods along with in windowed mode. And those GalaxySpace rockets are huge!

The problems I'd like to point out, now being more precise:
1. The overworld orbital sprite is not rendered behind the rocket. Optifine only. My guess is optifine can't render an entity so far away.
2. The sky has a light-blue haze all the way up if you launch during daytime. Optifine only.
3. ~~The moon texture are rendered full opaque. Both. That means, if your texture has a non-square moon, stars won't be rendered within the texture. Probably because the game uses black (RGBA 0,0,0,255) as background. Interesting, the sun also uses back and it works quite fine.~~ *(Please don't bother about this one for now. Let me isolate this item better and rewrite it.)*

**About 1 and 2**

Comparison between a launch sequence without optifine (1st launch) and with optifine (2nd launch) :

[GIF](https://cloud.githubusercontent.com/assets/6743303/12708323/755271fa-c885-11e5-8f68-ca86c17ee473.gif)

As you can see in the 2nd launch, the overworld orbital sprite is not rendered behind the rocket all the way up. Now with more detail, slower, capturing the whole screen:

[GIF](https://cloud.githubusercontent.com/assets/6743303/12708425/736b1d8c-c886-11e5-9bbd-2df063aab549.gif)

This shows the overworld orbital sprite is rendered only within a very short Y-range, between Y=222 and Y=260. To reproduce that: launch a rocket on creative, go up until the selection screen, select Overworld, using the fly mode go up and down to see the glitch.

**About 2**:

[test2](https://cloud.githubusercontent.com/assets/6743303/12707875/a24fc8f6-c880-11e5-8498-110b45b5e372.gif)

With Optifine:

[test](https://cloud.githubusercontent.com/assets/6743303/12707877/a25281d6-c880-11e5-96e7-5f8043cf8fb1.gif)

**About 3** (rewrite for later)

![2016-02-01_01 23 01](https://cloud.githubusercontent.com/assets/6743303/12708332/9442ac56-c885-11e5-9fb3-55f8e74e8215.png)

(I am posting to avoid losing anything)

**Comment by radfast** [comment]
Bother, Optifine again.

> Wouldn't it be better if above a certain height (Y=256), Galacticraft kicks out Optifine sky rendering and uses its own textures and rendering procedure? 

Galacticraft does that, above y=200 it takes total control of the sky.  Optifine must be messing with that in some way.

Micdoodle8 made a creative decision way back to use a very yellow texture for the sun in space (Overworld launch sequence and on the Moon and Asteroids) - it matches the texture in the Celestial Catalog screen.  I changed that for Overworld Orbit.  I will think about changing it for launch sequence and for the Moon.  Really for the launch sequence I want its yellowness to fade to white as the sky fades from blue to black.  (By the way I'm quite pleased with how that's looking now, except there is an ugly transition as the rocket rises through y=200.)

> That means, if your texture has a non-square moon, stars won't be rendered within the texture. Probably because the game uses black (RGBA 0,0,0,255) as background.

On other dimensions including Orbit, Galacticraft draws the stars, then draws a black box over them, then draws moon / sun on top of that black box.

In the launch sequence I couldn't get that to work (not sure why) so now it simply does not draw any stars in a small square around the location where the sun and the moon should be.   It's not an exact mask, it's intended that the star-free area should be slightly larger.

Maybe one day I will take an astronomy type approach - or open up the GC skyboxes for an astronomy plug-in - but for now it uses a fairly simple approach, stars are random squares of white drawn in the sky.  In build .437 I am assigning different brightness levels to the stars and having the least bright "fade in" as you rise higher in the atmosphere.

**Comment by EzerArch** [comment]
> Bother, Optifine again.

LOL. If you want, let me investigate a little further about this sky box issue before any action, then I will write a more comprehensive report.

I remember that back in early 2015 (with the astrominer debut) this issue didn't happen with MCPatcher (a more advanced version of Optifine): https://youtu.be/3eSIg6WtfZ4?t=3m10s. I think of testing those old builds to confirm if the sky box wasn't broken with Optifine as well.
