### ISSUE TITLE
IC2 compatibility issue with enclosed blocks

### ISSUE THREAD

**Issue by ollieread** [micdoodle8/Galacticraft#1584]
We've encountered an error with the enclosed blocks when dealing with IC2 wiring.
The particular error is recursive and continues on, and on and on.

http://pastebin.com/pMFM3aeD

We originally though this was an IC2 issue but I traced it through both codebases to fine the cause of the issue. I believe that the issue is caused because the IC2 network manager users WorldData, and since the TE for the enclosed block creates a new instance of the IC2 wiring TE, and invokes a method which calls said WorldData, without calling setWorldObj() on the new instance of the IC2 TE wire.

I hope that makes sense and helps, if need be I can make a PR for this.

**Comment by radfast** [comment]
Hey.  Thanks for looking in.

I'm afraid this is a known issue (see #1420).  I just haven't had time to look at the IC2 code and see how the reflection code for the enclosed block should work.  I'd be extremely grateful for a PR which fixes this.

If you can fix it in 1.7.10 that would be great and help 95% of players and modpacks, so I am sure it would be much appreciated.

But a "full" solution would involve also 1.7.2 which may be different, as the IC2 API certainly changed between 1.7.2 and 1.7.10 and I imagine the core code also changed ...  this is one of the reasons for my slowness.  (Galacticraft is a dual-build for both 1.7.2 and 1.7.10 and it adjusts all its IC2 compatible code appropriately.)

**Comment by ollieread** [comment]
Ahh right. Well, for the build that I tested it against, `TileEntity.setWorldObj()` should most definitely fix the issue, though there may be a chance that it'd fix 1.7.2.

I will take a look and see if I can get a PR that works for both.

**Comment by ollieread** [comment]
@radfast Do you an ASM transformer? I can't run my modified code in my dev environment because it's calling private core methods.

**Comment by radfast** [comment]
http://wiki.micdoodle8.com/wiki/GC3_API#Full_Galacticraft_Sources

**Comment by ollieread** [comment]
Excellent, thank you @radfast

**Comment by radfast** [comment]
I'd prefer not to change the build.gradle in any way, it took us a whole week to get it right.  Bear in mind it's integrated with scripts on the Jenkins server and on the Downloads page.

But if there's an easier way for other coders to set up the sources in an IDE, let me know and I'll update the wiki.

**Comment by radfast** [comment]
OK it's the weekend and I'm able to spend some time coding now :)   I can fix this if you don't have time to make a PR.

I did wonder whether we need enclosed Enclosed IC2 cables so much at all, given the new Construction Foam / Foamed Cable feature in IC2 for 1.7.10.  But given that Enclosed IC2 cables are in Galacticraft already and it won't need much to have them properly working, I guess we should - players like these blocks for their consistent look with other Galacticraft blocks.  (Also a future Galacticraft feature may be to allow a wider range of colouring and texturing for all Enclosed blocks.)

I took a look at ic2.core.block.wiring.BlockCable as I think BlockEnclosed should be emulating that.  I'd really appreciate some guidance on a few points:

1.  Should we be fully emulating this - I mean what does IC2.platform.isSimulating do?

```> public void onNeighborBlockChange(World world, int x, int y, int z, Block neighbor)
  {
    super.onNeighborBlockChange(world, x, y, z, neighbor);

    if (IC2.platform.isSimulating()) {
      TileEntityCable te = (TileEntityCable)getOwnTe(world, x, y, z);
      if (te == null) return;

      te.onNeighborBlockChange();
    }
  }```

2.  I assume we do not emulate the "isFoamed" functionality, see comments above.

3.  Should we implement any of these: getCableColor(), reColourBlock() or colorBlock()?  I'm hoping we can get away without doing that, because it's enclosed.

4.  I looked at ic2.core.block.BlockMultiID.createTileEntity() and I see that is using reflection, and a simple constructor to create a new TileEntity but I don't see a call to te.setWorldObj() - so where can I find that in IC2 code for a regular IC2 cable block?

**Comment by radfast** [comment]
Hmmm.  Is the issue in fact because the Galacticraft enclosed block does not copy the IC2 block's getOwnTE() method?

I mean, looking at BlockMultiID.getOwnTE(), I am seeing this in the return path where a tile is not already set in the world:
>       te = createTileEntity(world, meta);
        world.setTileEntity(x, y, z, te);

I am wondering whether the root of the issue here is the bizarro thing in Minecraft / Forge 1.7.10 where a TileEntity can be created and validated before it has its world object set?

So I guess there's a question here: did the IC2 team come up with getOwnTE() as a workaround for that issue in Minecraft / Forge?

**Comment by radfast** [comment]
Hoping that will do it :)

I think in the end it was because we were calling TileEntity.onNeighborBlockChange() too early, ie. before the Tile Entity has had its world, x, y and z set.  The IC2 BlockCable does not now call .onNeighborBlockChange() when the block is placed.  Maybe it did in a former life, as we wouldn't have invented that...

**Comment by radfast** [comment]
Seems to have fixed it, no crashes and electricity is being transferred correctly.

One small problem still, the Enclosed HV Cable when placed in the world shows up as a Enclosed Gold Cable.

**Comment by radfast** [comment]
hmm there's more to do here, the recipes need fixing.

Are the names of the corresponding IC2 items still:
* tinCableItem
* insulatedCopperCableItem
* insulatedGoldCableItem
* insulatedIronCableItem   (that's for HV - I think we really want the double-insulated one here)
* glassFiberCableItem

**Comment by ollieread** [comment]
Ahh excellent, that change you made was exactly what I had, though I was having trouble testing as the IC2 jar just didn't want to run, and kept referencing missing things within itself (for some reason).

From what I can tell, the cables are handled by a single block and thus a single item, though for some strange reason, the internal code gets the name of the block through an enum.
