### ISSUE TITLE
No Saturn/Uranus ring in a display screen

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1585]
![2558-04-17_10 27 40](https://cloud.githubusercontent.com/assets/6128413/7199993/10f94904-e523-11e4-8b0f-29c7415b3640.png)

**Comment by EzerArch** [comment]
"Intended behavior"? I don't know if this label reflects well this issue. I'm not sure if someone would *intentionally* depict Saturn without rings unless for difficulty.

I think this is rather an "Incomplete feature" or "Hard/Postponed feature" than something intended.

**Comment by radfast** [comment]
"Postponed feature" then :)

It's not something I plan to change in 1.7.10 because the ring graphics for the main Galacticraft Map / Planet Selection Screen didn't look so good on the Display Screen, where the lines are finer, so it would need some new type of ring graphics to be created.

The Display Screen is overall a bit of a placeholder, there is plenty more which can be done with Display Screens in future (and I made an API so that other people can add new screens).  Eventually I would like it to have more of a 3D render of the solar system, instead of an orthogonal projection.

But for now there are many other priorities, including:
* the space stations transport system and all the other things being currently discussed on EzerArch's forum thread
* finishing the Asteroids with a boss / dungeon and Treasure Chest
* starting on next planets
