### ISSUE TITLE
Render issues with mask,gear and tanks

### ISSUE THREAD

**Issue by Aerithone** [micdoodle8/Galacticraft#1604]
Here is an issue with rendering oxygen mask,oxygen gear and any tanks.They are just missing models on the player.
I'm using GC v.1.7-3.0.11.320 with optifine HD_U_B6,player api and player render api.
What should I do to fix it?

**Comment by EzerArch** [comment]
Sure you wanted to close this? If I have Player API and Player Render API, the oxygen gears cannot be rendered.

**Comment by radfast** [comment]
http://wiki.micdoodle8.com/wiki/Compatibility#Optifine

It's Optifine B6.  If you need to use that, then for now you can fix the rendering problem by installing SmartRender, link given on the wiki.  Micdoodle8 and I are both aware of this issue and looking for a more permanent solution, it's not straightforward because Opftifine is not open source and the changes it makes to rendering are complex.

**Comment by radfast** [comment]
Duplicate of #1350.
