### ISSUE TITLE
Canisters in TE's fluid transposers and forestry's bottlers

### ISSUE THREAD

**Issue by nigraforce** [micdoodle8/Galacticraft#1606]
Oil canister, liquid nitrogen canister and all other GC canisters dont get drained in TE's fluid transposers.
Empty canisters don't get filled correctly when put in forestry's bottler - you get a full canister of whatever liquid, but there is some leftover in the bottler's inner tank.
Some time ago, there was almost the same issue on this tracker. However, then redfast said that this is probably thermal expansion's problem. However, my guess is that theese problems arise because of canister's reliance on its damage value, while other fluid containers(TE's tanks, pressurepipes canisters) either use NBT tags to measure the amount of liquid in them, or store a fixed amount of liquid(vanilla buckets, forestry's capsules, mariculture's bottles) in them.
Galacticraft version: GalacticraftCore-1.7-3.0.11.320, Galacticraft-Planets-1.7-3.0.11.320
Forestry version: forestry_1.7.10-3.5.4.13
Thermal Expansion version: ThermalExpansion-[1.7.10]4.0.1-182
Forge version: 10.13.3.1388

**Comment by radfast** [comment]
Please just report the issue, guesses are not helpful.

I still think both problems are __likely__ to be in the other mods, because the way canisters work in coding terms is fairly standard and canisters empty and fill correctly in, for example, IC2 bottling plant, Buildcraft tanks and Railcraft tanks.

When I have time I will do some more testing in those versions of Forestry and Thermal Expansion to see where this gets to, in particular I'm concerned about the duping possibilities using Forestry's bottler: even if it's minor, we don't duping of any fluids otherwise a smart player can just make a loop.

**Comment by radfast** [comment]
Ok I now see this is the same issue as #1618 

Although you reported the issue first, if you don't mind I'm going to close this one and keep #1618 open, because KingLemming (who wrote the Forge fluid code) has been kind enough to participate in the #1618 discussion.
