### ISSUE TITLE
Chicken not falling in Asteroids dimension

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#1614]
![2558-04-26_22 10 03](https://cloud.githubusercontent.com/assets/6128413/7344037/74f353ce-ecf2-11e4-858e-60bd100611e6.png)

**Comment by EzerArch** [comment]
This bug is old. It happens when the gravity pull is low enough for the vertical speed to be rounded down to zero. It always happened in the space station dims.

**Comment by radfast** [comment]
I'm thinking this might be fixable by giving air-borne chickens some extra gravity.

Though I might instead decide to make them move upwards if the gravity is low enough...  will have to see how that looks.

I believe that IRL, chickens and other birds totally freak out in micro gravity, because they flap their wings as they normally would and it makes them go whizzing upwards.  Basically they don't have any way to move in the downwards direction, because the wing flap is kind of upwards only.

It's similar to some of the difficulties with the jetpacks from other mods.

**Comment by dj3520** [comment]
If we look at the technical aspects, on the moon, asteroids and space station dimensions there's no atmosphere. Without that air below their wings, they'd fall like any normal mob, even taking fall damage. I think that would confuse any long time vanilla player to the point of laughter.

However in a sealed space or on mars this isn't the case. Perhaps in low gravity situations they flap if they're moving downwards as fast as they would on the Overworld, but just flapping once makes their fall completely stop, or float upwards for a small amount of time before dropping again. This repeats in an amusing loop until they reach a block.

As for infinite up chickens, this would be eliminated unless you have an infinite upwards sealed area. Still, I'd find it funny as all get out if they just took off like a balloon out of a child's hand. Really though this "chicken elevator" could have some sort of use in survival, granted it only works in two places.
