### ISSUE TITLE
Astro Miner base GUI not recognizing miner exists

### ISSUE THREAD

**Issue by tkdberger** [micdoodle8/Galacticraft#1671]
The GUI looks a bit like this:
![2015-05-25_19 10 15](https://cloud.githubusercontent.com/assets/8628974/7803011/80cf0fc2-0312-11e5-884d-99208898a53a.png)
Yet when I try to add a miner, it says there is one already set to it. And if you wait, one will show up. Eventually.

**Comment by radfast** [comment]
The existing miner is probably in a chunk which is only sometimes loaded.  Is this on a server or single player?  Try using the Recall button to call it home next time you see it show up.

I don't see this as an issue in the mod which needs fixing, unless you are telling me the miner is in the next chunk or something?

**Comment by tkdberger** [comment]
SSP, and you're right.The recall button is clearly grayed out and unclickable, as you can see.

**Comment by radfast** [comment]
Do you mean, you can see the Astro Miner (like it's right next to where you are standing, or not far away) and even so, the Recall button is grayed out and unclickable?

I __think__ what is happening here is your view distance is quite small (so that the chunk loading radius is small) and the Astro Miner moved so far away from its dock that it moved into an unloaded chunk and stopped.  You should be able to fix this in these 2 ways.

(1)  The player can go in the same direction the Astro Miner went - either go find it in its tunnels, or at least move closer to where it must be so that the chunk it is in now loads - and follow it for a while until it moves closer to its base.  If this is a pain, I guess you will need to do some base building or farming or something on that side of your base, or maybe break the Astro Miner and its dock and place them down in a different spot.

(2)  Increase your view distance, which should increase your chunk loading radius as well.  80 or 96 blocks should mostly be OK for the Astro Miner, or the Minecraft default of 128 blocks (8 chunks) should be totally fine.

**Comment by radfast** [comment]
I am looking at whether we need to do more about this - like either keep the Astro Miner closer to its base, or find a way to temporarily load the 1 chunk where it is at (if its base is chunk loaded).

__So please do give feedback on what works for you.__

**Comment by tkdberger** [comment]
Yeah. The miner flies out of my tiny render distance, unloads and there you go.

On 5/30/15, Galacticraft developer <notifications@github.com> wrote:
> Do you mean, you can see the Astro Miner (like it's right next to where you
> are standing, or not far away) and even so, the Recall button is grayed out
> and unclickable?
>
> I __think__ what is happening here is your view distance is quite small (so
> that the chunk loading radius is small) and the Astro Miner moved so far
> away from its dock that it moved into an unloaded chunk and stopped.  You
> should be able to fix this in these 2 ways.
>
> (1)  The player can go in the same direction the Astro Miner went - either
> go find it in its tunnels, or at least move closer to where it must be so
> that the chunk it is in now loads - and follow it for a while until it moves
> closer to its base.  If this is a pain, I guess you will need to do some
> base building or farming or something on that side of your base, or maybe
> break the Astro Miner and its dock and place them down in a different spot.
>
> (2)  Increase your view distance, which should increase your chunk loading
> radius as well.  80 or 96 blocks should mostly be OK for the Astro Miner, or
> the Minecraft default of 128 blocks (8 chunks) should be totally fine.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/micdoodle8/Galacticraft/issues/1671#issuecomment-107103298


-- 
 Sincerely,
Caleb

**Comment by radfast** [comment]
hmm, I guess we need better support for players with a Tiny render distance, even though this is basically intended behaviour.  (I mean a vanilla minecart, or any similar moving entity from any other mod - for example a Tunnel Bore from _Railcraft_ - would have the exact same problem.)

For now, please try to set up your Astro Miner dock so that it is on one side of your base pointing _towards_ your base but underneath or something - so that the area where the Astro Miner actually mines will be close to your base.  Most of the time the Astro Miner will be looking to mine from around 30-60 blocks in front of its dock in the direction the dock is facing - also some distance below of course.

**Comment by tkdberger** [comment]
So I noticed. At least in the Overworld...

On 5/30/15, Galacticraft developer <notifications@github.com> wrote:
> hmm, I guess we need better support for players with a Tiny render distance,
> even though this is basically intended behaviour.  (I mean a vanilla
> minecart, or any similar moving entity from any other mod - for example a
> Tunnel Bore from _Railcraft_ - would have the exact same problem.)
>
> For now, please try to set up your Astro Miner dock so that it is on one
> side of your base pointing _towards_ your base but underneath or something -
> so that the area where the Astro Miner actually mines will be close to your
> base.  Most of the time the Astro Miner will be looking to mine from around
> 30-60 blocks in front of its dock in the direction the dock is facing - also
> some distance below of course.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/micdoodle8/Galacticraft/issues/1671#issuecomment-107103478


-- 
 Sincerely,
Caleb

**Comment by radfast** [comment]
:o  fair point, in the Asteroids dimension the Astro Miner can easily move 100+ blocks away from its dock - almost immediately in fact

**Comment by baxandrei** [comment]
I have same problem on my server

**Comment by radfast** [comment]
@baxandrei  please give much more detail than that...

For a start, which Galacticraft version + build?  There's been a lot of work on Astro Miners since May 2015...

**Comment by baxandrei** [comment]
I use 1.7-3.0.12.502
the problem is when astro miner exit from loaded chunks, and then i can`t get it back, i suggest to add a chunk loader to astro miner to prevent it from losing it on space!

**Comment by radfast** [comment]
Chunk loader for Astro Miner is included in Galacticraft 4 for Minecraft 1.8.9+.

We won't be including this in 1.7.10.  Everybody should eventually move to 1.8.9+

**Comment by baxandrei** [comment]
Thanks, i will remember this for future, but now i can`t update because i have a modpack with a lot of mods stuck on 1.7.10.
