### ISSUE TITLE
(Urgent)Player Entity Issue

### ISSUE THREAD

**Issue by Omuck3** [micdoodle8/Galacticraft#1675]
Hi.  I just tried to add galacticraft to my server(without oil and ore generation, because there have been bugs in the past and we have other mods).  However, I keep getting this crash: http://pastebin.com/j9NwTEiW

Please tell me how I can fix it!

**Comment by XFactHD** [comment]
Try to reinstall Galacticraft and see if it solves the issue.

**Comment by Omuck3** [comment]
The issue is over, but then I got some client crashes.  Anything I can do to fix this:  http://pastebin.com/MEQwj9Fn

**Comment by XFactHD** [comment]
It looks like Gregtech is trying to use the EntityPlayerMP (the vanilla player entity) which is overridden by Galacticraft's GCPlayerMP. Try to install the PlayerAPI, it may fix the issue.

**Comment by Omuck3** [comment]
I did... :(
I just took galacticraft out of the client and server and am going to go back to the pre-galacticraft world backup.  Thanks for helping..

**Comment by XFactHD** [comment]
I got another idea. There is a crossover/add-on mod for Galacticraft and Gregtech. It's called GalacticGreg. Maybe this solves the problem.

**Comment by Omuck3** [comment]
I'll look for a 1.7 version..

**Comment by Omuck3** [comment]
Now I get this: http://pastebin.com/feWE9nam

**Comment by Omuck3** [comment]
IT WORKS! THANK YOU!

**Comment by radfast** [comment]
> without oil and ore generation, because there have been bugs in the past and we have other mods

Please "put up or shut up" as they say.  There are currently no bugs in Galacticraft relating to oil or ore generation, and that has been the position for some months now.  "Bugs" in the past with other mods were in fact caused by a bug in another mod, CoFHCore, not a bug in Galacticraft, but to avoid problems for our players we have implemented a workaround for it in Galacticraft so that the issue will not happen now.

The crash reported in the first post was likely an incomplete download of Galacticraft, as a search would most likely have told you.

The "client crashes" reported in the third post are Gregtech crashes, not a Galacticraft issue at all.  This type of situation is well documented, for example here http://wiki.micdoodle8.com/index.php?title=Common_Problems#Crash_involving_GCEntityClientPlayerMP and also on the [notes for contributors](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) which you would have been directed to when creating this issue.

(@XFactHD _you are also well advised to read that material as the response you gave in the fourth post was incorrect, although your response in the second post was correct and appreciated._)

I can see no other issue being reported here, if there is a remaining issue please say clearly what it is.

It appears that the fundamental problem here is an _incorrect_ belief by @Omuck3 that Galacticraft is buggy or likely to be incompatible with other mods.  I'm not sure where that belief comes from.  The fact is that Galacticraft is stable and compatible, these days more than most other large mods.  Also, any crashiness or compatibility issue which is shown to us is very quickly fixed, apart from the rare or minor issues which are currently open issues, or [3 compatibility issues stated on our wiki as unfixable](http://wiki.micdoodle8.com/wiki/Compatibility#Non-fixable_issues).
