### ISSUE TITLE
Minecraft Crashing on Tier 3 Rocket Launch

### ISSUE THREAD

**Issue by NecroNile** [micdoodle8/Galacticraft#1698]
Hello, I've been playing my world now for about a week with no problems. I successfully launched to the Moon and to Mars with no problem. Now I'm trying to launch to the Asteroid Belt and every time I jump into my rocket and hit SPACE the game crashes. I used to be playing with the .333 recommended version but I updated to the .341 version for all three parts to the mod hoping that would fix the issue but to no avail. The problem is indefinitely recreate able. The crash report is also labeled crash-2015-06-06 20.24.24-**server** which is different from other crashes that I have seen that have **client** at the end of them. To me that's odd because this is a solely single player game, no servers involved. Here is the full crash report: 

http://pastebin.com/ZxiTuhmy

If you need any more information just let me know. 
Thanks

**Comment by radfast** [comment]
The error is happening because the dimension ID for Asteroids (-30) not loading the Asteroids world like it should.

Please post your ```configs\galacticraft\asteroids.cfg```

Do you know if you have any other mod which creates a new dimension and has maybe chosen dimension ID -30?  Especially smaller / newer / lesser known mods?  The "big" mods like ThermalFoundation we check with Galacticraft a lot, but you have others I don't know, for example AnotherOneBitesTheDust, also check AetherII.

Please also post a screenshot of your world folder for this world - showing all the folder names like DIM-28, DIM-29 etc.

You might be able to fix this by changing the dimension ID in ```Asteroids.conf```.

**Comment by NecroNile** [comment]
Here's my asteroids.conf, pastebin to avoid making a really long post.

http://pastebin.com/xU3mCB2G

The only mods I can think of that I have that come with new dimensions are Twilight Forest and AetherII. Another One Bites The Dust is a Tinker's Construct add-on that improves its compatibility with mods. Aether is using 3 and 4 as dimension ID and Twilight Forest is using ID 7. 

Here's a picture of my world folder: 
http://i162.photobucket.com/albums/t271/undeadorcjerk/world%20save%20folder_zpsp4juu5od.png

I'm going to try changing the dimension ID for asteroids and I'll get back to you on the results.

**Comment by radfast** [comment]
I'm confused too, but something you have in your mods is definitely making more dimensions thank you think - you have -100 and -112 there as well.

If you can figure out which one it is, that can maybe help other players - we can cover it in the Compatibility notes on the wiki.

**Comment by radfast** [comment]
You have quite a few mods I don't know.  JurassiCraft?  It's also possible even some of the well-known mods have added dimensions since I last checked.
