### ISSUE TITLE
GC & BC energy connecting when shouldn't

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1702]
Beam receivers connect to pipe inputs (wood and emerald) but not others which is OK. Energy drained from source but no transfer done.
![image](https://cloud.githubusercontent.com/assets/8284194/8071250/068530fa-0ed6-11e5-8072-fa35736c7c6a.png)
Aluminum wire connects. No energy transfer done. Lower priority since there's no energy loss.
![image](https://cloud.githubusercontent.com/assets/8284194/8071280/66499bf2-0ed6-11e5-8b42-c69ac31798d0.png)

**Comment by kremsy** [comment]
Another issue we noticed there, don't know if it is a Buildcraft or Galacticraft bug:

We found out that (with opis) that on the connection, the first buildcraft pipe block causes huge amount of laggs.

**Comment by dj3520** [comment]
Retest with 400. Persists. Using BC 7.1.9 (Can test with newer but has other problems.)

@kremsy
>We found out that (with opis) that on the connection, the first buildcraft pipe block causes huge amount of laggs.

This is actually why it's intended this doesn't happen. GC wires are not supposed to connect to any other mod's wires for lag issues.

**Comment by dj3520** [comment]
Update with BC 7.1.14 and GC 404. Title changed to accommodate more problems.

GC connecting to BC extraction pipes and providing them energy when BC does not do this itself
![image](https://cloud.githubusercontent.com/assets/8284194/11544680/1f1c6ca8-9911-11e5-8be8-f8542870a514.png)
Unless a power adapter is placed on the extraction pipe.
![image](https://cloud.githubusercontent.com/assets/8284194/11544714/54af69a6-9911-11e5-933f-fe8ce513d4e7.png)
This acts like it works when connected to a power load of any kind, but does not transfer energy when the engines run. This is OK but might signal something unexpected in code.
![image](https://cloud.githubusercontent.com/assets/8284194/11544792/d1d11d4e-9911-11e5-987f-57634aa4dffd.png)
My favorite exploit which allows me to charge buildcraft items at IC2 rates. I'm actually using this in survival.
![image](https://cloud.githubusercontent.com/assets/8284194/11544901/63dfe4d6-9912-11e5-9cc9-f32862dc7741.png)

I also tried moving energy wirelessly with beam receivers. BC and GC still connect with receivers but without energy transfer. Decided to wirelessly GC to GC and then use the above exploit. However the beam receiver you don't see in this picture does a disappearing act once the beam connects.
![image](https://cloud.githubusercontent.com/assets/8284194/11545077/4b461d04-9913-11e5-89ba-d1b720e48836.png)

Perhaps @asiekierka could help out with this...

**Comment by asiekierka** [comment]
1. BC has an explicit check for kinesis pipes connecting to non-kinesis pipes, but I want other RF producers to power them and I can't block pipes from other mods automatically.

2. Redstone engines don't produce RF anymore.

**Comment by dj3520** [comment]
@asiekierka 
>I want other RF producers to power them

Galacticraft uses it's own energy system and converts it to RF on the fly. This means every wire-to-pipe connection causes more and more strain on the server. It would be GC's job to block this, we'd just need a method of doing so.

> I can't block pipes from other mods automatically

Galacticraft is supposed to do this. The goal is connecting to any RF, gJ, or EU machines, but not their wiring. I've noticed the power adapter seems to change extraction pipes into receiving piped energy. Gc doesn't see this and connects regardless. Perhaps there's some condition GC can check against there so it doesn't connect when it shouldn't. There should also be one for kinesis pipes as well, making it so GC doesn't appear as an RF transfer to BC in that instance. That way a connection isn't made.

**Comment by radfast** [comment]
Recap:

**Issue A**: Beam Receivers are not tranferring energy into BC input pipes, even thought the Beam Receivers are draining their beam source.

**Issue B**: BC Kinesis Pipes - the mid-pipe colors, not wood or emerald - "look" as though they are connecting to GC Aluminium Wire.  The GC Aluminium Wire does not accept the connection and does not transfer any energy.

This is a solely BC issue.  The GC Aluminium Wire is behaving correctly:- it is not intended for GC wiring to connect to the *wires*/*power conduits* from other mods.  This is for two reasons: it looks wrong, and it can produce lag and other problems because any mod's wiring is at the same time a power receiver and a power output.  These problems are potentially worse if a player builds wire networks using wires from two mods which connect at multiple points (imagine a long run of two mods' wires side by side).

It would need @AsieKirka to fix this in BC, but see his comment number (1) above.  I suggest that with a minor amount of effort it could be fixed in BC by using code similar to [the code GC has used](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#L80-L89).  This code looks for known wiring types from other mods, and specifically blocks Aluminium Wire from connecting to them - unfortunately the code will need updating from time to time as other mods add new types of wiring.  This approach is necessary because RF has chosen not to provide a way in the API to distinguish between energy sources/sinks and wires - compare IEnergyConductor in IC2 which gives a useful way to do this.  [In December 2014](https://github.com/micdoodle8/Galacticraft/issues/791) I have explained to @Skyboy the good sense of including this in the RF API but he didn't see it as a high priority.

**Issue C**: GC Aluminium Wire is connecting to BC Extraction Pipes (even when they do not have a Power Adaptor fitted)

**Issue D**: "on the connection, the first buildcraft pipe block causes huge amount of laggs".  *I don't understand this, please can @kremsy or someone else provide a screenshot of the type of connection causing the lag problem.  What type of pipe block?*

**Issue E**: GC Aluminium wiring is not connecting to the output of a redstone engine.  I intend that it should connect and should transfer power: GC Aluminium Wire is intended to be a universal conductor.

**Issue F**: An "exploit" where GC Aluminium Wire is used to connect an IC2 power source to a BC kinesis pipe.  This should be fixable by fixing issue B above for all colors of BC pipe.  It will still be possible to connect IC2 power to BC systems via a GC Energy Storage Module.

**Issue G**: Disappearing Beam Receiver when connected to Aluminium Wire.

**Comment by dj3520** [comment]
Issue E conflicts with point 2 of the previous post. No energy to transfer.
The Redstone engine would otherwise be a cheap source of power. Also
doesn't connect to BC's own energy pipes.

**Comment by radfast** [comment]
What does a Redstone Engine do now, then?  What does it output?

**Comment by asiekierka** [comment]
It outputs 1 RF every 16? ticks, but only to tiles implementing
IRedstoneEnergyReceiver.

If you implement it on a cable I will not be pleased.

2016-01-06 20:51 GMT+01:00 Galacticraft developer <notifications@github.com>
:

**Comment by radfast** [comment]
Thanks for that.  OK I will not implement cable connections to it.  Therefore Issue E is a non-issue and does not need to be fixed.

**Comment by dj3520** [comment]
I was typing an explanation when suddenly answers. It's really only supposed to power extraction pipes and pumps. Even when it did connect (think it was 1.6.4) it wasn't practical despite not needing any form of fuel other than a redstone signal

**Comment by radfast** [comment]
OK, 17330f0 should now fix Issue C, Issue D and Issue F in next build of Galacticraft.  Aluminium Wire will refuse to connect to any type of BC pipe at all.  (Please check that this also successfully blocks connection to the Extraction Pipe as that seems to be a BC add-on, not core BC code.)

We have agreed Issue E does not need fixing - @dj3520 please can you confirm that Aluminium Wire is correctly connecting to the other types of BC engines, and not connecting to the Redstone Engine.

Issue B is for @asiekierka to fix if he wants to, by using code similar to mine [here](https://github.com/micdoodle8/Galacticraft/blob/17330f0ce266c4b2ca420c9a83fc3cb4952de9d4/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#L99-L113 and https://github.com/micdoodle8/Galacticraft/blob/17330f0ce266c4b2ca420c9a83fc3cb4952de9d4/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#L302-L307).  Alternatively it is possible to check for Galacticraft wiring without using Java reflection, if using the GC API - all wiring is an instance of **micdoodle8.mods.galacticraft.api.transmission.tile.IConnector**.

Issue A and Issue G are Beam Receiver issues which I still need to deal with.

**Comment by dj3520** [comment]
![image](https://cloud.githubusercontent.com/assets/8284194/12156739/e03d9c82-b49a-11e5-9f5e-735a9e2ef4eb.png)

Light shows energy flow. All but redstone show connected visually and are connected electrically. Also tested railcraft steam engines. do not show visually but do connect electrically as shown (last 3)

Mod versions are GC 1.7-3.0.12.406, BC 7.1.14 (with compat 7.1.3) and RC 1.7.10-9.8.0.0

**Comment by radfast** [comment]
Thank you, nice build, very helpful indeed.  So we have:

**Issue H**: GC Aluminium Wire does not connect visually to Railcraft Steam Engines.

**Comment by radfast** [comment]
Update: Issue A is a duplicate of #1113.  I am working on fixing it, but it's a tough one.  Any further discussion of Issue A will be there, because this thread is already complicated enough.

Issue G (disappearing Beam Receiver) is a duplicate of #1720, and again it's better to deal with it there.

**Comment by radfast** [comment]
Issue H fixed in latest commit, this will be in the next build.

The issue was because the Railcraft [engine](https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/beta/TileEngine.java) does not implement **IEnergyProvider** in the RF API.  I think it probably should: it provides energy.  Anyhow, I have now made GC work around that.

All issues A-H are now fixed or duplicated on other threads, so I can close this.

**Comment by dj3520** [comment]
### OH NOES!!
Updated from 435 to 441 to have #2043 fixed. However there's a much larger problem for me.
![image](https://cloud.githubusercontent.com/assets/8284194/12938810/6b535aae-cf86-11e5-8160-034840536cc7.png)

Aluminum wire does not connect to IC2 storage block outputs. All other IC2 connections seem the same as from 431, including power generators.

Aluminum wire _does_ connect to BC extraction pipes, and even kinesis pipes!
![image](https://cloud.githubusercontent.com/assets/8284194/12938948/11819138-cf88-11e5-9e3e-08fcba9c8ef7.png)

**Meaning issues B, C, and F are back!**

Please note that the only mod updated was Galacticraft. I'm going to guess this happened in 436 or 437 but I cannot test that right now at the moment.

**Comment by dj3520** [comment]
Confirmed everything is the same on 437, so the problem can be narrowed down to only changes done between 435 and 437.

**Comment by radfast** [comment]
Thanks for reporting.  You are right, this was caused in 436.

All or most of these issues should be fixed in [new build 443](http://ci.micdoodle8.com/job/Galacticraft-1.7/443/)

Please let me know if you are still seeing any of issues B, C and F in 443.
If so, please tell me BC and IC2 version numbers so I can test exactly the same.

**Comment by dj3520** [comment]
What's incredible about your speed is that I'm still watching the dev build on the console. Btw it worked.

**Comment by radfast** [comment]
ok great stuff, I think we can close this then.

Please post if anything more emerges.

**Comment by dj3520** [comment]
I was afraid you'd take my "it worked" towards my test. I meant the 
build was successful. Sorry my client doesn't quite load that quickly. I 
am still downloading actually. Will test super soon though.

**Comment by radfast** [comment]
OK :)   It works in my testing, but it could be affected by the presence of other mods (RF mods) in your modpack.

**Comment by dj3520** [comment]
![image](https://cloud.githubusercontent.com/assets/8284194/13200600/3af4e2c4-d81e-11e5-84f7-19530dfc5ab5.png)
Only using the following mods:
Buildcraft 7.1.14 with BC Compat 7.1.3
CodeChickenCore 1.7.10 1.0.7.47 universal
GC 443
IC2exp 2.2.811 universal
NEI 1.0.5.120 universal with Integration 1.1.1
optifine D1
PlayerAPI & RenderPlayerAPI 1.4
Walia 1.5.10 with Harvestability 1.1.6
MCHeli 0.10.8 (No energy system, harder to remove for testing)

**Comment by dj3520** [comment]
Oh and fresh world

**Comment by dj3520** [comment]
As far as anything that would need to be changed on Buildcraft's side, from what I can gather asie is attempting to "pass the torch" of BC's developer and maintainer, while the 1.8(.9) port is being handled by AlexIIL (github name but purposely not mentioned.) Something interesting he's currently somewhat secretly working on is updates to the refinery to make it less of a set-and-forget thing which somehow includes gasses (which might be stored from the top of the tank downwards.) "Discussion" would be [here](https://github.com/AlexIIL/Buildcraft_1.8_Issues/issues/122) anything 1.7.10 will only be updated for serious bugfixes, so 7.1.14 might be the end of 1.7.10 builds. Again, disclaimer: This is only assumptions from what I see.

**Comment by radfast** [comment]
IC2 issue is fixed in build 444 coming later today.

The Buildcraft pipe rendering issue cannot be fixed on our side, as already explained above.  It's a purely visual issue, no energy will in fact be transferred because the Galacticraft Aluminium Wires will refuse to accept it.

**Comment by dj3520** [comment]
I understand that Buildcraft can't be fixed because it's attempting to connect on it's side. However it _was_ transferring power. Will test 444.
>(in fact it was connected)

I figured it was something irritating like that

**Comment by dj3520** [comment]
![image](https://cloud.githubusercontent.com/assets/8284194/13209882/777ecbc2-d8f7-11e5-8b9b-573460beab9a.png)
Huzzah! Fixed in 444 with more than just my minimal testing set loaded. @radfast is the best
