### ISSUE TITLE
Desh Ingot Item ID issue

### ISSUE THREAD

**Issue by itanshi** [micdoodle8/Galacticraft#1704]
This is an NEI dump of my inventory. I highlighted it. Might be a metadata thing.

![galac](https://cloud.githubusercontent.com/assets/373669/8097612/17b1f38e-0faa-11e5-9851-8044ec035432.png)

**Comment by radfast** [comment]
This looks like an Excel spreadsheet.

I'm not seeing what the problem is here - is something in the game not working?

**Comment by itanshi** [comment]
It appears that the NEI dump provided and odd name for the ingot, I used this name in a changed recipe and it works. so eh not sure what to think of it.

**Comment by dj3520** [comment]
The problem is a desh ingot is a "item.null", not a "item.deshIngot."

I was actually having a problem telling another mod to use a desh ingot in a crafting recipe (specifically MCHeli) and complained that the item did not exist. Other people might run into issues as well since the name appears as "null" when it's actually a desh ingot. Plus "/give player GalacticraftMars:item.null" seems confusing.

**Comment by radfast** [comment]
This is the correct internal name for the item and intended behaviour.  You just need to use the correct metadata if you need to use the /give command manually.

No more discussion.
