### ISSUE TITLE
Question: is GC compatible with RedstoneFlux?

### ISSUE THREAD

**Issue by AgentK9** [micdoodle8/Galacticraft#1707]

**Comment by radfast** [comment]
I have a few questions for you in return:

Q1.  Did you read the 'Guidelines for Contributors' before posting that?

Q2.  Did you test Galacticraft with an RF mod?  If so, how did you get on?

Q3.  Did you read the Galacticraft wiki at all for example http://wiki.micdoodle8.com/wiki/Whats_New

Q4.  It's actually a strange question to ask - why do you think Galacticraft might __not__ be compatible?

**Comment by AgentK9** [comment]
How, though? the BC pipes don't connect up, and everything is in joules

**Comment by dj3520** [comment]
Once again, [the wiki](http://wiki.micdoodle8.com/wiki/Galacticraft) should provide the information I'm about to share. If it doesn't please say so.
To change Galacticraft to provide energy levels in RF, type "/gcenergyunits RF"
Buildcraft kinesis pipes should connect to machines with square indicators with a green or red dot. If you're trying to pull energy out of a machine (say an energy module) you'll need to connect a wood or emerald kinesis pipe to the red (output) side.
If you're using an old version of Buildcraft, or another mod that has an older version of RF, Galacticraft disables it's RF functionality in order to avoid a crash.

**Comment by radfast** [comment]
@dj3520  I have deleted the post you made as it was mostly incorrect, and would confuse people.

@AgentK9 for more help you need to give screenshots or information about what exactly is not connecting for you.  You can switch displayed energy units in Galacticraft machines using the /gcenergyunits command.  This is well documented on Galacticraft wiki.

For BC pipes, it is possible you have a broken Buildcraft setup due to mixing in older and newer versions of other mods.  Maybe try connecting EnderIO or Thermal Expansion energy conduits, see if those work.  If those work but Buildcraft pipes do not work then the problem is with your modpack.
