### ISSUE TITLE
Could not get provider type for dimension -30, does not exist

### ISSUE THREAD

**Issue by AlexPlus117** [micdoodle8/Galacticraft#1716]
Everytime I execute the command /dimensiontp, the game says "Could not get provider type for dimension -30, does not exist". I also tried to modify the dimension ID of asteroids, which is -30, but it doesn't work the same. If I change it to -94 the game says "Could not get provider type for dimension -94, does not exist" and so on. I have GalactiCraft 3.0.12.344 and its addons GalaxySpace 2.0 and More Planets 1.2.8.

**Comment by radfast** [comment]
This works correctly in a fresh download of Galacticraft 344.

Please:
* state whether you are on a server or in SSP
* post your ```asteroids.conf``` config file - give us server and client copies if you are on a server
* try without those add-ons - and maybe try with only one of them

If there is an issue caused by an add-on, you will need to raise that with the add-on author - not here on Galacticraft's own issues list.  The add-on author can then get in touch with me if anything needs changing in Galacticraft itself (or he can just make a Pull Request).

**Comment by SteveKunG** [comment]
I think dimension ids is conflict.
