### ISSUE TITLE
IBreathableArmor not working as intended.

### ISSUE THREAD

**Issue by Yuri6037** [micdoodle8/Galacticraft#1719]
Hello all,

So I created a MInecraftForge 1.7.10 mod using latest Galacticraft, but I can't get the IBreathableArmor to work correctly.

Basicaly I'm trying to create an armor that adds every resources you need to be able to live in space (energy system managed by my mod) !
Like when you're in creative mod, you can breath on every planets without needing to wear anything. Well I want that feature but for survival Gamemode with a condition that player wears my cheated armor (extremely complicated to craft : hello diamond block) and has activated the presurization feature of the armor.
But well when I return true for function canBreathe, well it's not changing anything. I made a hacky system that fulls oxygen tanks each game ticks. This solves oxygen problem, however I still have the WARNING Invalid setup message, and I need to health the player because the mod kills me...

Is there any way I can enable unlimited resources for the time my armor works ?

**Comment by radfast** [comment]
This is not a good issue for the Github.  Although we of course support add-on authors and our API - and will make any additions to the API which people reasonably ask for, and fix anything which looks broken - I can't help you with your own code.

The issues you describe are not possible for me to check as ```IBreathableArmor``` is not actually used by any of Galacticraft's own items and I'm not going to write a test add-on to test this.  Please go over Galacticraft [source code](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/OxygenUtil.java#L283) and see how it works for yourself, and if you think something is wrong please give me exact pointers to the broken code, or make a PR.  One thing to check: __you are making a full set of your modded armor, right?__  Because if one piece is missing, that would be an invalid oxygen setup.

**Comment by Yuri6037** [comment]
So you prefer people to use hacking ways to make armor working with your mod !? Well done...

If that's indeed the case, well you need to know I found a way using direct acces to your client side player (GCEntityClientPlayerMP) and setting the variable oxygenSetupValid to true each ticks, then my client stopped to return the Warning message. The problem is linked to you function checkGears in GCPlayerHandler. You should create an api to break the function (eg : forge event that you can set oxygen value, thermal level, is player able to hear sound).

If you want I can make that and send as pull request but you'll need to wait, by the way I have exams currently...
