### ISSUE TITLE
Short Range Telepad ticking when updating from 341 to 344

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#1736]
I updated from 341 to 344, and tried to load my world. I'm getting Ticking block entity.

https://gist.github.com/EzerArch/cf3053212a2530bb3461

Creating a new world and placing down a Short Range Telepad, and reloading the world, will not crash the game.

**Comment by radfast** [comment]
Hey.  Thanks for reporting.  It seems to be connected with the dimension ID somehow having changed since this Short Range Telepad first had its frequency set.  I don't really see how that is possible.  The next build should prevent the crash and also include a log line giving the dimension ID and x, y, z of the erroring target - like this:
> Bad TileEntity in Telepad Handler: address(f) dim -30 x y z

Please could you keep an eye open for that and post up the details if you see it.
