### ISSUE TITLE
BloodArsenal crash, they say it's probably Galacticraft.

### ISSUE THREAD

**Issue by tethlah** [micdoodle8/Galacticraft#1751]
Post I originally posted on Arc's GitHub:

"When placing a Compact Master Ritual Stone from Blood Arsenal beneath a Master Ritual Stone from Blood magic and right clicking on the Compact Master Stone with a Transparent Orb from Blood Arsenal it will crash the entire client. After that, You can't get back onto the server unless you have the server admin wipe your playerdata from from the server."

Here is the one from the guy who discovered it: http://pastebin.com/20iqRvAj
Here is the one from my patch tester that verified it: http://pastebin.com/uj5dChdK

And here is the one that the guy who discovered it got when he tried to reconnect: http://pastebin.com/1NMifFb5

Arc says the issue resides in Galacticraft.  Anyway you guys can take a look at this and see if that's the case?

**Comment by radfast** [comment]
I have looked at the crash reports you posted, all three are the same.  These crash reports do __not__ seem to show any Galacticraft issue.  That should be fairly obvious to anyone who knows Java and how to read a stacktrace.  This is also well documented, both on the Galacticraft wiki '[Common Problems page](http://wiki.micdoodle8.com/wiki/Common_Problems#Crash_involving_GCEntityClientPlayerMP)' and on our Notes for Contributors which you were asked to read before posting this issue.

I am therefore surprised that another mod developer says this is a Galacticraft issue.

If Arc would like to speak to me directly about this, he is welcome to of course.

**Comment by tethlah** [comment]
I'll be honest with you, I'm entirely ignorant in this because I don't know how to read these things, that's why I'm posting here looking for help.  So you can get angry with me, that's fine, I'll just uninstall all mods involved.  But we love galacticraft more than bloodarsenal, and if it's not something that can be fixed I'd rather just get rid of that instead.

People don't come here because we are experts, we come here because we are not.  And yes, I read through all sorts of stuff on various pages, I missed that one.  It's not a lack of due diligence, it's just simply me missing it.

I am learning though, I hope that sooner or later I will learn to read these logs and stacktraces and rather than coming asking mod developers to waste their time interpreting it for me, I'll be able to triage and fix things on my own, or pinpoint the problem and legitimately bring bugs to help with productivity rather than asking for advice.

And to explain how I got here, I went to this page:  https://github.com/micdoodle8
And from there I clicked "Issues", I didn't see anything clearly asking me to read anything anywhere directing me to the page you posted.  Thank you for your prompt response anyway.

**Comment by radfast** [comment]
I'm not angry at you!   My comments were aimed at the other (add-on) developer for wrongly saying it is a Galacticraft issue.  That is surprising and has led to me having to spent time to explain to him, I also posted on the Blood Arsenal Github.

To read a Minecraft crash report, start at the top.
*  _Normally_ the first line is the mod which is crashing - so report the crash to that mod.  Give the mod author the whole crash report, although in most cases only the first line is needed.  Everything below that is simply a trace of how it got there, which is normally not relevant but it tells for example whether it happened when a player placed a block, or when a player took damage from a mob, or during a normal tick update.
* _Sometimes_ the crash report has an extra section headed "Caused by ..." and in that case the problem is in the first line of the _last_ "Caused By" section.
*  _Occasionally_ what is at the top is some vanilla Minecraft code, in which case you need to look down the crash report until you find a line of modded code.

You have mentioned uninstalling Galacticraft being a possibility to resolve this issue (even though you don't want to).  Let me try this again: this is __not__ a Galacticraft issue.  What I mean by that is that __the exact same crash will happen here even if you uninstall Galacticraft__.  Try that and you will see.  (Backup your world first!  Or create a new test world just for this.)

The issue is flagged as invalid because of the guidelines, when you clicked on the 'New Issue' button the page with the form for entering the issue said at the top:
> Please review the [guidelines for contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) to this repository.

**Comment by tethlah** [comment]
Ah my bad.  Yeah I searched all over trying to find it before I clicked the button. Once the form popped up I just copied and pasted over what I had on his github.

That's actually really helpful.  I'm starting to learn Java and taking some udemy tutorials and stuff, aside from making modpacks I want to start making my own mods.  Thanks for the input, it's definately going to be helpful in the future!

But yeah, currently this issue is on the Development server only.  I planned on sending the new release of our pack today for July 4th.  Blood Magic and Arsenal are mods we are adding, so we were not having this issue until they were added.  And actually, we had tested and modified the configs of nearly everything, this was a last minute catch before submitting the files to FTB.

**Comment by radfast** [comment]
For your modpack, please do check regularly for future Galacticraft updates, you should expect to update it every 1 - 2 months if you want your players to have the latest fixes and new content.  Unlike some other mods (_CoFH, ahem_) the Galacticraft updates are always backwards compatible so that updating Galacticraft will not break your modpack.

You can track major changes easily [here](http://wiki.micdoodle8.com/wiki/Whats_New)

**Comment by tethlah** [comment]
Yeah, once a month I actually go through and check for build updates for all mods.  Then I go through and check what the change logs say.  Usually though, when a version update goes through I wait until the next minor revision I put out before I update that mod.

Of course I'm insanely organized as you can see here:  https://docs.google.com/spreadsheets/d/1m5mDo_tSXxX9W4cgxi4DRGGKyPKfx1uOxRCNNyTf9f4
