### ISSUE TITLE
Automation of Circuit Fabricator with AE2 interface not possible

### ISSUE THREAD

**Issue by twothe** [micdoodle8/Galacticraft#1768]
It is not possible to automate the Circuit Fabricator with an AE2 interface alone. Against the description the incoming silicone is not distributed evenly, but put in the top slot (see image).

It is necessary to re-request the crafting, only on the 2nd try will the silicone be distributed.

![galaerror](https://cloud.githubusercontent.com/assets/1131621/8509799/cbec6450-22bb-11e5-9b15-ce556055a52e.jpg)

**Comment by twothe** [comment]
The same is true for the Electric Compressor I just noticed. Items are not distributed until the crafting is requested again.

**Comment by n00b7** [comment]
use one gc silicon and one ae2 silicon in the recipie

**Comment by twothe** [comment]
Automatically crafting two different ore dictionary items in one machine is not possible either. ;)

An easier workaround is to pre-fill the machine with one of the two items (1 silicon, 1 coal, 1 iron...) in which case the items get distributed as they should (most of the time). This however makes it impossible to use different recipes in the same machine, because the one extra item is basically locking the recipe.

**Comment by radfast** [comment]
These machines distribute the items correctly with a Hopper or an item pipe or other item inputs.  I think this is most likely an AE2 issue.

_Note: distribution of the items correctly may not be possible with complex recipes in an Electric Compressor, because no item input knows the recipe layout.  [Wiki article all about this](http://wiki.micdoodle8.com/wiki/Electric_Compressor#Automation)_

**Comment by twothe** [comment]
Hoppers drop items one at a time, while AE2 pushes the entire stack at once.

**Comment by bballboy2002** [comment]
I don't know why, but with the electric compressor I got compressed ingots working by making the pattern create 1 at a time but I have to ALWAYS craft an odd number of items at a time or else there will be one ingot in the wrong place. Interface > hopper > compressor > import bus works just fine with any amount.
With the heavy-duty plates however, you need to pre-fill it with 64 of the ingredients. You will likely never need that many ingredients worth of heavy-duty plates anyways so not worth.
Circuit fabricator: doesn't work directly with the interface because of the silicon thing at the top of this issue. The interface > hopper system I mentioned before works fine, however. As for the silicon from different mods, its not that using silicon from mod A in the same crafting as silicon from mod B breaks it, its that GC silicon is not oredicted despite the circuit fabricator accepting any oredicted silicon. So if you use two oredicted silicon from two different mods that are not GC it should work fine.

**Comment by dj3520** [comment]
What I did for logistics pipes to function with the electric compressor (should also work with AE):

One temporary inventory has a single item drawn out if a hopper on top of the compressor is empty. This works because the electric compressor will accept two ingots and place them where they should go. Should the hopper try to push a different kind of ingot the compressor will block it until it's done crafting. Additionally the ingots in the temporary inventory should stack, meaning that for the most part the same kind of ingot will be pulled until that ingot has been depleted (or you've requested a lot of plates and the ingots make more than 1 stack)

Note this won't work for anything but making compressed plates from ingots, so heavy duty plates and such are not accommodated for in this build.

**Comment by radfast** [comment]
I can probably fix some of this, I will re-open this to remind me.

**Comment by radfast** [comment]
OK, I've looked at this again.

###Circuit Fabricator

Now added Silicon to the oredict, so that tricks using GC Silicon + a type of Silicon from another mod can work

> The interface > hopper system I mentioned before works fine, however. 

Good, then there's a solution even if people don't have another mod with Silicon. :)

###Electric Ingot Compressor

* Next build of GC will automate Hopper + Compressor better so that it can build automatically most items - including **Heavy Duty Plates** - from Hopper inputs, so long as it starts from an empty crafting grid.

* I think this will mean that AE -> Hopper -> Compressor recipes should now work in all situations

* This will also fix the issue where you were randomly seeing 1 ingot left over when using a Hopper to craft basic compressed metals from ingots.  The randomness is now removed.

* These changes will be for the **Electric** Ingot Compressor only.  I think it's OK that, as a Tier 2 machine, that will work in a smarter way than the basic Ingot Compressor.

* We cannot make the **direct** connection of the AE interface work better.  The problem there is on their side, not ours.  When directly connected, their AE interface "takes control" of our machine and decides to put the whole stack into one slot, without asking our machine if that's OK.  The only question AE asks is "can this full stack go into this slot or not?"  and if our machine answered "no" to that question, then nothing would craft.  The best solution would be for AE to understand that there can be machine recipes which need 2x stacks of something to be offered.  If AE came with 2 stacks of ingredients and presented stack1, then stack2, then everything would work great.

* I am not willing to change these GC machines so that they can craft if there is a big stack of items in one slot only - that would be changing our game rules and it could create new issues (for example it could affect other people's builds who built for the current system).  More generally, it would take mod development time when there are other priorities.

**Comment by dj3520** [comment]
A thought on the compressor and AE2. Perhaps we accept only 1 item when there is none in the crafting grid. From that one item I think it can be determined what the intended crafting recipe is. Then we simply accept as many of that item that makes sense (so for ingot compression that's 2 stacks, heavy duty plates it's two stacks per type of plate needed, etc) I _believe_ this will solve the issue of dumping everything in like a chest.

**Comment by radfast** [comment]
> we accept only 1 item when there is none in the crafting grid

LIke I said, that is not possible.  AE does not give us the choice to accept only 1 item. AE checks if GC can accept all the items, yes or no.  If GC says "no" then no crafting will happen.  If GC says "yes" then AE takes over and forces the whole stack into 1 single machine slot even though that is not what players want.

As you and others have already pointed out, this problem is easily solved in-game either by:
*  using a Hopper
*  using 2 different types of whatever it is (silicon / ingot / etc)
*  using another automation mod like Logistics Pipes

----

When new GC version 477 becomes available, try it and you will see the hopper solution now works perfectly.

**Comment by dj3520** [comment]
@radfast I'm not sure if my idea is coming across.

The electric compressor, when empty, accepts 1 stack of items (or possibly just 1 item at all.) AE2 will see this and send only 1 stack of items (or just 1 item.) Then depending on what that item is we increase the size and apply a filter, saying that we'll only accept the appropriate amount of items for a crafting recipe. AE2 should see the size change and attempt to place more items inside according to size and filter restrictions. Using this method there might be a moment where it looks like things aren't working and there's just one stack of an item in the compressor until AE2 notices the inventory size change. This behavior should also benefit the hopper method but possibly in such a minor manner it's not noticeable.

**Comment by radfast** [comment]
Things do not work in that way in coding terms.  AE2 does not ask how many items other machines can accept.  AE2 asks whether a type of item can go in a slot or not, that's the only question it asks.  If the item can go in the slot, then AE2 places the whole stack in the slot, without looking to see whether there is any other slot it can also go in.  When AE2 has placed the whole stack in a slot, it thinks its job is finished.  What you said about it "seeing the size change" is not a real thing.

**Comment by dj3520** [comment]
Hmm that is a bit troublesome. Thanks for explaining though.

**Comment by radfast** [comment]
With version 477 I hope it will work **perfectly** with hoppers used between AE2 and the GC machine.

Without hoppers, I guess it may actually work if you just request AE2 to craft a single item and then make a second request, so you request the crafting of an item **twice.**  I think then AE2 will place the ingredients in half of the required spots the first time, and the other half of the required spots the second time.  This should be less error-prone than before 477 as I have removed the randomness, as long as the Electric Compressor is able to figure out that what it is receiving is part of a known recipe.
