### ISSUE TITLE
Cauldron Server freeze with GC and Multiverse

### ISSUE THREAD

**Issue by FloxRoxX** [micdoodle8/Galacticraft#1777]
Hi all,
we have a strange beahaviour on our Server since a while now. It does not happen everytime but when it happenes it will freeze the whole server.

I tried to rebuild the process how it will hang up:
We have Multiverse(plugin) and Galacticraft(mod) on our server running. If a player goes from his space station to the moon, waits a bit and then uses /spawn or a build up stargate from SG Craft for example, then the server will freeze.

This is what i have as last log entry:
http://pastebin.com/DQ6e7Wcr

The "Could not pass event PlayerTeleportEvent to Multiverse-Core v2.4-b527" seems to be fired everytime a player teleports from a non registered multiverse world to another world. This seems not to be the problem because its something on the multiverse handler. It just happens with the Teleport from the moon back to the main world for example.

We use GalacticraftCore-1.7-3.0.11.333; Galacticraft-Planets-1.7-3.0.11.333 and MicdoodleCore-1.7-3.0.11.333
We use cauldron-1.7.10-2.1403.1.54-server

**Comment by radfast** [comment]
The bug is in Multiverse at this line:
> MultiverseCore.listeners.MVPlayerListener.playerTeleport line 198

Probably this problem can be cured in practice by setting the Moon and other Galacticraft planets as static dimensions in Galacticraft's **core.conf**.  This is covered on the Wiki [here](http://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Making_dimensions_available_to_other_mods_using_core.conf) and also [here](http://wiki.micdoodle8.com/wiki/Compatibility#Multiverse).
