### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#1784]
Get this crash when i entering a new Game.
https://gist.github.com/Dream-Master/e8f812842582ef917737#file-gistfile1-txt

**Comment by micdoodle8** [comment]
That's a GregTech error, it's just passing through the Galacticraft player, which will happens with almost every crash report no matter what the cause is.

Gregtech error:
https://gist.github.com/Dream-Master/e8f812842582ef917737#file-gistfile1-txt-L11

Normal "passing through" of the Galacticraft player's update method...
https://gist.github.com/Dream-Master/e8f812842582ef917737#file-gistfile1-txt-L19
