### ISSUE TITLE
Galaxy backpack was gone!

### ISSUE THREAD

**Issue by RedArrowss** [micdoodle8/Galacticraft#1811]
Unable to open the backpack placed an oxygen bottle. Minecraft press E to open the bag, did not see the open oxygen cylinder backpack icon. MOD is installed.

**Comment by dj3520** [comment]
Galacticraft doesn't have an "oxygen cylinder backpack" per say, but the tanks do go on your back.
You place them in an inventory slot on a second tab of a survival inventory. Should look like this: 
![image](https://cloud.githubusercontent.com/assets/8284194/9047358/73b3d448-39ff-11e5-82be-2b75c42b029b.png)
*image from wiki*

If you cannot see the tanks on your back it's due to Optifine. Details and fix are here: http://wiki.micdoodle8.com/wiki/Compatibility#Optifine
