### ISSUE TITLE
Galacticraft & Ic2 crashes / 1.7.10

### ISSUE THREAD

**Issue by Dameoneon** [micdoodle8/Galacticraft#1821]
I have scoured the interwebs for a fix that I cannot seem to find. It is in a 1.7.10 launcher, but all the solutions are for 1.6.4 and havent worked with this particular crash. I have redownloaded each file numerous times and deleted the double copies. 

http://pastebin.com/gDuY17yG

**Comment by Arytas** [comment]
Hi,
i think thuis error appears on server start up???
some of your mods arent on version 1.7.10 (also Galacticraft, u re using v1.7.3, maybe update it)
and it looks, that the problem is the mod "MineFactoryReloaded" 
GC and IC2 werent the problem
so maybe try it to start your server without and/or MineFactoryReloaded update all the old mods if it is possible

**Comment by Arytas** [comment]
sand maybe you´ve some mods installed that require other mods to be installed (and these are missing)
look in the fml log (not the crash log) this should say which mod is missing

**Comment by dj3520** [comment]
Minefactory is looking for Thermal Expansion for a recipe. This is not
related to either Galaticraft nor IC2, which work together in my testing.

**Comment by Dameoneon** [comment]
Hm.. Thank you.. I thought it was Galacticraft at first because I
downloaded that first with no problem, then started to add mods, and once
it hit Industrial it crashed.. Thanks otherwise mates.
