### ISSUE TITLE
World leaks spiral out of control after trips to moon

### ISSUE THREAD

**Issue by jackmott** [micdoodle8/Galacticraft#1844]
I am running a server with a FTB Infinite modpack with galacticraft added.

Minecraft 1.7.10
FTB Infinite 1.7, latest version
Galacticraft 1.7-3.0.12.357
Environment - Creeperhost (linux? I don't know)

When someone goes to the moon, I start seeing world leaks in the logs repeating frequently, and then an hour two later the server will hang, without crashing. Upon server restart, all is well. Relevant area of server log is here:

(pastebin would not accept due to size, please accept this link to my personal website instead)
http://www.aeroweenie.com/mottcraft/fml-server-latest-worldleaks.log

**Comment by micdoodle8** [comment]
Odd.. I don't usually see complaints about world leaks any more. It's possible that another mod is keeping other worlds loaded but I can't point any fingers because it's hard to track what is holding the references. What type of dimension is "MottWorld"?

**Comment by radfast** [comment]
Sorry for the delayed response.  This must be another mod conflicting, because this does not happen with only Galacticraft (or with other modpacks I have tested).

Is it possible to try this modpack without JourneyMap?

**Comment by radfast** [comment]
**Note: world leaks are not what people think they are**  A world "leak" means that any mod is holding a reference to a world somewhere inside its code, even though all players have left the world so it is unloaded.  If the "Moon" leaks, it means a mod - probably another mod - was holding a reference to the Moon for some reason, maybe because one of its mobs or worldgen features is there.  It does not mean a bug in Galacticraft.  It is usually a bug in another mod.

Maybe use a third party tool to identify what code is running when the server freezes?

I am closing this now due to no answer from the OP in 3 months to the questions from micdoodle8 and me.

You are welcome to re-open this if you have answers to the questions, or if there is some other evidence that it is a Galacticraft issue.
