### ISSUE TITLE
Broken/outdated localization files

### ISSUE THREAD

**Issue by martinm236** [micdoodle8/Galacticraft#1868]

**Comment by hunator** [comment]
I would say, that some of the loc. files are not up to date.

@micdoodle8 : Should I try to update that via pull request? Or do you have a script to delete deprecated strings and to add non-translated ones, as before? If so I'll wait with pull request.

Anyway, I can add some of these translations into current loc. files.

**Comment by micdoodle8** [comment]
radfast Had the scripts to do that, I've asked him to update the language file using those scripts. I'll see if he still has them and go from there.

**Comment by hunator** [comment]
@micdoodle8 and @radfast : It seems to be fixed for now. However the length of that file is still longer that en_US one. For the future, it should be checked over all of the localization files (length differs among them). I've also corrected some typos I made before in pull request #1875 .

@martinm236 Thank you for pointing down this issue. I suggest to close the issue or change the title to smth like: "Broken/outdated localization files" and keep it as reminder that that issue is broader than only Czech localization file.

**Comment by radfast** [comment]
Thanks @martinm236 @hunator @micdoodle8 

I'll run all the language files through the script which matches it to the en_US, next update.

Generally speaking it is OK if a language file has extra lines - either comments or historic translations from older versions of Galacticraft: that should not cause any issues.  Therefore the script does not delete lines: it only adds lines which exist in the en_US but which are missing in (for example) the cz_CZ.

**Comment by radfast** [comment]
@martinm236  please see: https://github.com/micdoodle8/Galacticraft/commit/5fe0dc404dcbd04ac372ada7e8984f81c98f1f12
