### ISSUE TITLE
Remove global entity registration

### ISSUE THREAD

**Issue by Adaptivity** [micdoodle8/Galacticraft#1896]
Looking at the code, there are two places [here](https://github.com/micdoodle8/Galacticraft/blob/ceb718af52f90e228dc914ce834a682e5d085d09/src/main/java/micdoodle8/mods/galacticraft/core/util/GCCoreUtil.java#L61) and [here](https://github.com/micdoodle8/Galacticraft/blob/d4aed34e45f0ff217a60bd58fbacbe66773abac2/src/main/java/micdoodle8/mods/galacticraft/planets/mars/MarsModule.java#L230) where you are using global entity registration. Please, don't do this. Use mod entity registration instead. This will solve *potential* entity id conflicts.
[Here the Forge issue](https://github.com/MinecraftForge/MinecraftForge/issues/1880) where LexManos states that modders shouldn't use global entity ids.

**Comment by Adaptivity** [comment]
Thanks!

**Comment by radfast** [comment]
Removing global entity ID registration messes up entity spawning eggs, and also entity colors (e.g. as used by the Safari Net).  See discussion here: https://github.com/MinecraftForge/MinecraftForge/issues/1703

https://github.com/micdoodle8/Galacticraft/commit/c4095d3f74bcb4be53c1d823122f472cdc35a267 basically recreates the effects of using a global entity ID, manually.  Note specifically:
>  EntityList.IDtoClassMapping.put(nextEggID, var0);

(but ClasstoIDMapping seems to be missing.)

I'm extremely :/ about this.

Wondering whether the put to IDtoClassMapping is needed there?

**Comment by Adaptivity** [comment]
https://github.com/GirafiStudios/Atum/commit/a325f7f7e485d43553d041f693b524c84e5419f8 Atum uses IDtoClassMapping class too. So I guess it should be there somewhere? If you want to set color for spawn eggs you should do something like "setSpawnEgg(0xC2C2C2, 0x040F85)". Again, check Atum code.

P.S Glad you back to Galacticraft development after a long break :+1:

**Comment by radfast** [comment]
OK I've found a neat solution.  For non-global entities, the entity list ID does not have to be in the range 0-255, as there is no actual entity with this number.  The entity list ID is used in EntityList.IDtoClassMapping, EntityList.ClasstoIDMapping - the main uses of this are connected with Spawn Eggs and the 'Mobs' section of the Statistics page (killed by / killed you).

Now implementing this.  This will also mean the Statistics page will now show GC mobs again :)

**Comment by radfast** [comment]
I'm not going to check Atum code, I have my solution.  But thanks for the welcome back :)

**Comment by Adaptivity** [comment]
Glad you found the solution :)

**Comment by radfast** [comment]
OK I did look at Atum code.  I think he will have egg ID clash issues if another mod is using Global Entity IDs (naughty naughty) and registers its entities after Atum's mod has taken an ID number for one of his eggs...  Example: his eggs will have IDs 121, 122, 123 etc.  But those IDs are not taken by any global entity.  If another mod now registers a global entity with ID 121, there will be an egg problem...

---

Anyhow, I'm glad global entity IDs have been removed from Galacticraft, I always felt bad about that.  And it produced rare "there's a Creeper Boss on the overworld" problems when player clients used different modlists / configs from servers ... due to a global entity ID mismatch between server and client, the server thought it was a sheep but the client thought it was a Creeper Boss.

**Comment by Adaptivity** [comment]
"If another mod now registers a global entity..." just don't think about this. If a mod registers a *global* entity then players should report this to mod developer to remove this. Global entities shouldn't be used by mods at all. If they do, it's a mod problem.

**Comment by radfast** [comment]
@Adaptivity that is the theoretical answer, but mod authors also need to think about real situations.

Real players mix and match different versions of different mods.  Often, people use the "stable" version of one mod from 6 months ago, but update some other mod.  Therefore, every mod author has to assume that his mod could be installed alongside a version of another mod dating from anywhere in the range (approximately) -12 months to +6 months against his own mod.

So if any other mod past, present or future is using global entities - and some are, actually it's easy to spot as any which has spawn eggs with the same item ID# as vanilla spawn eggs is probably either using global entities, or using Atum's solution - then this problem can arise.

For similar reasons I spend a lot of effort making Galacticraft compatible with the legacy power systems in older versions of other mods (for example, Buildcraft 6) as well as current versions of those mods.  It is because some players might install Galacticraft alongside an old version of the other mod.  I guess we could instead insist that Galacticraft must only be used with version 7.1.x or later of the other mod, but that can then make a bad mess for anyone trying to create a set of mods or a modpack, what if mod C requires version 7.1.x of mod B but mod D requires BC 7.0.x of mod B?  [If you've ever tried installing multiple CoFH mods you'll understand what I mean here :) ]

**Comment by radfast** [comment]
And thank you to L-Clouds.  Issue #2030 has covered exactly the type of problem which I had in mind, showing why we needed to do this.
