### ISSUE TITLE
[Bug] New System Space Station 2 [Build >367] 

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1918]
Ok, you've fixed the bug in map view mode
But, in the mode of flight between the planets was a bug.

![1](http://6.firepic.org/6/images/2015-10/28/rq4kxjcvg5wb.png)
![2](http://6.firepic.org/6/images/2015-10/28/qo8hw3a4xit7.png)
![3](http://6.firepic.org/6/images/2015-10/28/xuyk72mohfy5.png)
![4](http://6.firepic.org/6/images/2015-10/28/isbdqugiqxcy.png)

**Comment by micdoodle8** [comment]
What's the issue? I don't know what I'm looking at.

**Comment by dj3520** [comment]
Text overlap?

**Comment by BlesseNtumble** [comment]
Tablet the space station appears on the planet that can not fly.

**Comment by SpacedViking** [comment]
I think he's trying to say the status window for space station creation is cramped due to the localized string being long enough to cause a third word wrap. Hence the window should resize to accommodate for this extra space.

Personally I consider there should be an extra row for text as a good margin for localization in the first place. With some time a small redesign will be worked out.

**Comment by BlesseNtumble** [comment]
No. It is not what I mean.

Windows making the Station should not be planets that can not fly.

**Comment by dj3520** [comment]
My turn again: You've marked a planet as being able to have a space
station, however the button for its creation is still red and/or going to
the storage station button is red.

**Comment by SteveKunG** [comment]
Same as me. Unreachable planet can created a Space Station. (If a new space station has registered.)

**Comment by micdoodle8** [comment]
You can no longer create space stations on an unreachable planet. Also, I've offset the lower part of the GUI if the "can create" message is more than two lines long.
