### ISSUE TITLE
Rare Glitch w/ Rockets

### ISSUE THREAD

**Issue by Youjust** [micdoodle8/Galacticraft#1928]
Every once in a blue moon, playing GC, I'll send a rocket up to space, and it'll go all the way up to 1200 y but then stay there indefinitely. The Y coord won't go up or down, and I have to reload my client to fix the issue. Haven't had any problems yet using build 401, but I've only flown once since the update :P

**Comment by dj3520** [comment]
Can you test this in creative?

**Comment by radfast** [comment]
I think this type of problem has been fixed in build 420.

If it happens again, please re-open this.

(It's **nothing connected** with creative mode, @dj3520 - don't know why you would think that.)

What will be helpful info if this happens again is:
* which exact GC version?
* SSP or playing on a client + server?   if client + server, is the server on your LAN or is it remote?
* which type of rocket, and was a player riding it?
* was it an automatic launch using a Launch Controller, or launched using the Space bar?
* finally, please enable Debug mode in ```.minecraft/config/Galacticraft/core.conf``` and then when the problem happens again, post an extract from the log from around the time when it happened

**Comment by dj3520** [comment]
Wasn't referring to this happening only in creative, but instead asking for more testing.
>I've only flown once since the update
