### ISSUE TITLE
Add support ElectricItem/Armor/Weapon

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#1932]
I create electric armor is my addon, and encountered a problem that I can not charge it in power modules.
I search for files and found the following:
```
         this.tileEntity = batteryBox;
         // Top slot for battery output
         this.addSlotToContainer (new SlotSpecific (batteryBox, 0, 33, 24, ItemElectricBase.class));
         // Bottom slot for batter input
         this.addSlotToContainer (new SlotSpecific (batteryBox, 1, 33, 48, ItemElectricBase.class));
         int var3;
```
As I understand, the slots can be inserted only objects that extends class ItemElectricBase, but armor extend ItemArmor and implement IItemElectric.

Is there any way to solve this problem and allow addons to create things more globally?
And of course to add the ability recharge the armor and other items in modules of other modifications.

**Comment by radfast** [comment]
The commit resolves this - for the containers SlotSpecific didn't need to be ItemElectricBase, it can be IItemElectric in all the GC machines.

This resolves the issue.

@BlesseNtumble if you want your addon electric armor to be chargeable **by other mods** for example IC2 then you will need to extend ItemElectricBase.  That contains all the methods which other mods need to use.  I can't include those in the GC API, it's not appropriate.  And if you copy all that code in your addon (i.e. you make blesseNtumble.addon.ItemElectricBase like the GC class) it won't work probably - that's because the custom annotations only work in GC's code.

**Comment by radfast** [comment]
Note that automated item systems - for example Applied Energistics or BC pipes - will probably not be able to insert or extract the electric armor into these GC machine charging slots automatically.  That would need a re-write of the isValidForSlot code in all the tiles.  I will maybe do that some time but not today.
