### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by BlueCardinal** [micdoodle8/Galacticraft#1938]
I am on a macbook pro version 10.9.5. I have downloaded galacticraft planets, core, and micdoodle jar files and moved them to the mod file. I also installed forge craft to load the mods. When i load it up everything seems fine until I opened my creative inventory. A lot of textures are missing, presenting themselves as white boxes. This same problem happened when I tried botania. Is there a problem with my forge, or do I need something to load the mods, or what? Please help thanks

**Comment by radfast** [comment]
I have seen this issue on a Macbook as well.  I do not know the reason, it may be a Forge issue.  It is not a Galacticraft issue - Macbooks seem to do this with any large mods.  I'm sure there must be plenty of discussion of it on Minecraft forums somewhere, but this is not the place: it's not an issue caused by Galacticraft.
