### ISSUE TITLE
 Clicking Buildcraft tank with fuel does not fill canister

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1952]
Decided to make some rocket boosters today. Saw they required a filled fuel canister. Crafted an empty one and clicked on the Buildcraft tank that my refinery and gas liquefier output into, with plenty of fuel. Canister stayed empty. Sad face. Turned off fluid extraction on gas liquefier and waited for the canisters to fill that way. Worked, but still sad face.

**Comment by micdoodle8** [comment]
Hmmm. Well first of all, I need to look at the recipes again because I don't think the rocket boosters should require full fuel tanks - that doesn't make much sense. I'll have to see if the main issue here is something I can fix, since I'm moving away from canisters and towards the bucket system for compatibility's sake.

**Comment by dj3520** [comment]
Well if it's about removing the fuel canister (kinda a bummer to see it go) then the recipe for the spin thruster will also need changed. NEI isn't reporting any other uses for it.

**Comment by radfast** [comment]
I prefer the original title!

**Comment by dj3520** [comment]
BC 7.1.14 and GC 3.0.12.406
[Full list of mods, plugins and versions on my survival server](http://git.dj3520.net:8000/minecraft/modlist.btm)

**Comment by radfast** [comment]
The canisters should now fill from Buildcraft tanks (and other mods' tanks).  Please can someone test this.

Canisters are still fully operational in Galacticraft.  They are working properly since cd813d7, if any further issues emergy I would prefer to fix the issues, than remove canisters.  Oil buckets can be used to collect oil, in place of the (deprecated) Oil Extractor + canister system, but both work.  The Refinery can take either buckets or canisters.  The Fuel Loader can also take either buckets or canisters.  The Wiki will need updating to reflect the current situation.

The Rocket Booster recipe uses full fuel canisters because in my mind the Rocket Booster is similar to the Solid Rocket Boosters (SRBs) on the Space Shuttle, and those were pre-fueled.
