### ISSUE TITLE
[Minor] Railcraft metals chest.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1959]
Small issue since Galacticraft adds a few ingots that can be considered "metals."
Railcraft metals chests are special chests that automatically compress ingots/nuggets into blocks/ingots  respectively, but only of the metal kind (iron. gold, etc, not redstone, diamond, etc)
Below is the result of a single stack of every GC ingot placed in this chest. Copper and Tin get changed into Railcraft's equivalent, which is actually convenient. Aluminium, Meteoric Iron, and Titanium stay in ingot form. Not sure if desh is a metal or not.
![image](https://cloud.githubusercontent.com/assets/8284194/11545499/9ebbe6b0-9915-11e5-974e-20605f290fd1.png)

**Comment by micdoodle8** [comment]
It appears that this is something that needs a hook on the Railcraft side of things. Here's a link to the code that is evaluating the inventory:

https://github.com/CovertJaguar/Railcraft/blob/master/src/main/java/mods/railcraft/common/blocks/machine/beta/TileChestMetals.java#L42

You can see it's only looking at the metals hard-coded in the Metals class, so there's no way to add more. The only reason why copper and tin are working is because the ore dictionary allows them to.

**Comment by dj3520** [comment]
Ah ok. Didn't know how the metals chest looked up items. Oh well.
