### ISSUE TITLE
MFR machines on the space station bug/feature?

### ISSUE THREAD

**Issue by zachtingle** [micdoodle8/Galacticraft#1961]
I'm running a multiplayer server on the tekkit main pack (Galacticraft 2.0.12 & MFR 2.7.8). I've had a couple of complaints about blocks disappearing when placed on the space station. I went in a tested it and the only blocks that cause problems are the full-sized machine blocks (grinder, rancher, planter, etc.) from MineFactory Reloaded. 

Is this a glitch or is it intentional?

**Comment by micdoodle8** [comment]
Nothing comes to mind that would cause this, since the dimensions I've added are very standard in terms of underlying complexity. Unless others are having the issue (and please leave a comment if you are), this is probably a world save or block ID issue.

**Comment by radfast** [comment]
@zachtingle if it's still a problem, please post a screenshot of the setup which you tested with this issue - like where were the machine blocks, exactly?

Are any other mods around which could be causing this?  Any Galacticraft wiring or machinery nearby?  If an oxygen sealer was operational, were these MFR blocks inside or outside the sealed space?

Just because the issue is seen on a space station, does not mean Galacticraft caused it - otherwise people could say every issue seen on the Overworld is caused by vanilla....

Also which exact Galacticraft version?  I don't know which GC2 version the Tekkit Lite guys are using.  Galacticraft 2.0.12 [final versions](http://ci.micdoodle8.com/job/Galacticraft/1096/) have been pretty much stable for more than 1 year now...

**Comment by radfast** [comment]
Closing as this is Galacticraft 2, the issue is over 1 year old, and no response from the OP to the requests for information.  Seems unlikely that GC was the cause.
