### ISSUE TITLE
[Request] GC r323 - NEI handler "recipes" option/button

### ISSUE THREAD

**Issue by TheTrueForce** [micdoodle8/Galacticraft#1965]
Hi,
In most NEI handlers out there(MC furnace, TE Pulverizer, etc), you can hover over the progress bar for a machine, and you'll get a "Recipes" tooltip. If you click, you get a list of all recipes that that machine(or crafting handler) provides.
Galacticraft's Ingot Compressor does not follow this behavior. Could it please be made to do so?

**Comment by dj3520** [comment]
Try again with GC404

**Comment by TheTrueForce** [comment]
OK, I borked up. I'm using GC 333, not 323.
I tried with GC 404 and it's not there. I do see that you've used the usual space for a progress percentage in the actual machine, but as far as I can tell, the NEI handler is the same.

**Comment by dj3520** [comment]
Confirmed issue with 404

**Comment by radfast** [comment]
The NEI request comes under the category of "Suggestions" and is not welcome on this Issues list, please use the forum for suggestions.

Galacticraft does not provide any way to change the machines' specific recipes, apart from the settings described here which affect how Compressors work: http://wiki.micdoodle8.com/wiki/Game_Balance  (did you read that already?)

If you are making a public modpack and you can explain to me what you want to change the recipes to and why the change will be of benefit to players, we can maybe look at adding a config to do exactly what you need.

**Comment by TheTrueForce** [comment]
I did read the wiki page you've referenced, and it didn't seem to be quite what I wanted to do. I did have the idea that I could write a mod to add an alternative compressor, and then disable the GC one. I will pursue this route, since I do not intend to release the pack. I wasn't happy with the yield of the heavy-duty plate recipe in particular, but I have since come up with other uses for a compressor that are not related to GC.
As for the NEI request, I didn't want to have to make yet another forum account for something I'll probably only use once. In future, I will bear in mind that suggestions/feature requests are not welcome on this Github. If I have any more, I'll take 'em to the forum instead.

**Comment by radfast** [comment]
Thank you, there are 2 good reasons for taking suggestions to the forum.  1. This issues list is for current problems, and our ultimate goal is to get it down to zero issues - we receive a lot of suggestions and it would make the issues list too long if they were all here.   2.  There are plenty of active players on the forum and posting suggestions there gives a chance for feedback from other people on whether it is a good idea / bad idea or additional comments, and gives us a way to judge how much 'player demand' there is for a request.

If you want to **add** recipes to the Compressor and you have your own mod (it can be a micro-sized mod to do this), that can easily be done by calling:
    CompressorRecipes.addShapelessRecipe
as [here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/recipe/RecipeManagerGC.java#L517-522).  You would need to use Java reflection to access that Class and Method, because they are not in the API, but that should be easy enough.

Changing or disabling the existing GC recipes is not possible.

How did you want to change the yield of the heavy-duty plate recipe?

**Comment by TheTrueForce** [comment]
I didn't know about that class. I'd assumed that the adding routine would be in something like an IMC handler, rather than raw code.
I assume you don't want people removing recipes so that they don't break them for users, who will then likely come here, cluttering the issues list and generally being a pain.
I think I wanted the recipe to yield 3 H-D plates, rather than 1 or 2. I don't remember it well anymore. But knowing that I can add recipes is useful. That means that I don't *have* to finish the Compressor in my mod, and I can get on with adding/moving recipes.
