### ISSUE TITLE
[Minor] Using anchors on dynamic loading dimenstions is impossible after server restart.

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#1986]
Situation: I've made a space station and placed an anchor on the station itself. Since it would be next to impossible to make any newly created space stations stay statically loaded by default, I've kept them as dynamic. Anchors work perfect until server restarts. Since the dimension doesn't exist it's impossible to keep it loaded. In the config it states that space stations will load when the player they belong to joins the server, however this isn't the case in my testing and actually happens when said player reaches orbit. The only way to get back to my space station is either to launch a rocket, /dimensiontp, or forcing the chunks to load, which wouldn't be possible for the majority of players wanting to play both survival and legitimately. To solve this problem for the time being I always log out while on my station since logging in forces it to load, which works OK. I haven't tested it but I'd imagine that launch controllers are also subject to this as well even if launchControllerChunkLoad=true

* On server start, all dimensions set to dynamic loading should be loaded immediately. This lets other mods search for their "always on" anchors when the server starts and keep those chunks loaded accordingly.
* Config optiion "LoadOnLogin" should actually load chunks when a player joins. This lets any anchors that work like Railcraft's passive anchor (only functions when its owner is online) to work. It also works as a failsafe in case any "always on" anchors are missed during server start.

**Comment by radfast** [comment]
This behaviour is by design.

Please read [this Wiki page](http://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins#Guide_to_Galacticraft_dimensions_and_commands
) if you haven't already (I expect you have!)

> On server start, all dimensions set to dynamic loading should be loaded immediately. 

Loaded immediately = static loading.  I don't understand why you have a problem with static loading.  You can set all space stations where you want to use an anchor to load statically.  The server owner can set this either in the core.conf or while the server is running using the **/gckeeploaded** command.  On large public servers (with multiple admin staff with command privileges) any admin can use the **/gckeeploaded** command.

---

I have not tested the Launch Controllers recently in non-loaded dimensions, thanks for raising that query, it's certainly one of the things I will be checking when I get to the Launch Controller issues.

**Comment by radfast** [comment]
Just so I'm clear: every space station created has a fixed dimension number (it receives the same dimension ID when the server restarts) so it should be easy enough to do this.

If you're saying it's hard to figure out the dimension ID of each space station, that's a different issue.  I keep meaning to add a command to let server owners list all the space stations ...

**Comment by dj3520** [comment]
>Please read this Wiki page if you haven't already (I expect you have!)

Yep

> I don't understand why you have a problem with static loading.

I have an issue with this with space stations. There isn't an automated way to have them statically load. Even if there was I wouldn't want this. 

>You can set all space stations where you want to use an anchor to load statically. The server owner can set this either in the core.conf or while the server is running using the /gckeeploaded command. On large public servers (with multiple admin staff with command privileges) any admin can use the /gckeeploaded command.

I'm the only admin of my own server and want to keep away from the console as much as possible so that I can play as everyone else would (unless something goes wrong.)

My issue is instead *compatibility* with anchors when dynamically loading is set, for performance reasons or otherwise. Without them loading on start or when the player actually logs in the anchors can't be seen by other mods despite them being there, meaning their placement is pointless. This means the dimension must be forced loaded in order to even get there via any other method besides a rocket, such as using a sync shell.

**Comment by radfast** [comment]
>I have an issue with this with space stations. There isn't an automated way to have them statically load. Even if there was I wouldn't want this. 

I'm confused.  How many space stations do you have on your server?  Why can't you enter their dimensions manually in the config - or use the /gckeeploaded command?  Do this one time only and then they should all statically load every time, unless there's some point I'm missing here?

Having space station dimensions loaded for multiple space stations does not damage performance, because the actual chunks will not be loaded (unless a player is present).

**Comment by radfast** [comment]
The /gckeeploaded command was provided for exactly this type of reason.  It basically auto-adds the dimension to the core.conf config file for you, so you don't have to bother with the config, you can just do it in game.

**Comment by dj3520** [comment]
My point is that having them dynamically load breaks anchors, not the fact
that I could just set them to statically load. Also that they don't load
when the player logs in. And also there isn't a default. I could do it
manually like you say but that takes away the privacy the station provides.
This isn't about what I could do it's about what is happening.

**Comment by radfast** [comment]
> having them dynamically load breaks anchors

Agreed.  That's why GC offers the static loading option.  I still don't understand the reason for your concerns.  You have identified a problem.  GC offers a way to fix this.  What you seem to be asking for is - instead - for all space stations to be static loading *automatically*, or for a config option to enable automatic static loading.  I think it's unlikely that other server owners would want that.  Please bear in mind that on large public servers there can be 100 or more space stations, and Galacticraft has no sensible way to know which ones are space stations which have been carefully constructed with machines etc, and which ones are just a default space station dimension which a guy went to derp around in.

I also don't understand your point about privacy.  You have 2 ways to set the space stations to load statically.  Either the admin can - offline, before the server starts - take a look at the world folder, see what dimension numbers are there (e.g. DIM_SPACESTATION2, DIM_SPACESTATION3, etc) and add those numbers to the core.conf.  That preserves privacy, the admin doesn't know whose is whose and does not need to go there in game.  Alternatively, if that's a pain, it can be done from inside the game (and an admin should be able to type **/gckeeploaded** into chat in game if you have the right permission nodes, it doesn't need to be in the console).

Let's put this another way.  It would take me much longer to code in an option to do what you seem to be asking for, debug it, and document it on the Wiki, than it would take you to add a few dimension numbers to your **core.conf**.  And I'm sure you would prefer me to spend my time fixing other issues and then getting back to work on the planned new features...  :)

However, if you do want to start a forum thread in the Suggestions area to suggest a config option to make **all** GC dimensions static loading by default - including space stations and planets as well - then that might be an idea, we can see how many other server owners say "yes please that would be great".  If there's demand for it, I will reconsider.

**Comment by radfast** [comment]
PS:  On the public server I used to manage, more than 2 years ago now, we actively did not want space stations to be loaded statically, nor chunk loaders.  (However I think there might have been an informal system where donations to the server resulted in some leniency on these rules ...)

Two reasons:

1.  static loading of space stations meant the advanced players could more easily go and hide out in their space station and build a [ridiculously large base](https://www.youtube.com/watch?v=iI4pckWbo6U) far away from (0,64,0) which no other players could see or reach (for example, using /tp or /home commands to get there).  That meant they were not interacting properly with other players on the server, and were almost invulnerable.

2.  if players were allowed to build chunk loaders in their bases that would place excessive load on the server - we had over 30,000 players and 2,000 'active' players (meaning logging in at least once every day).

Skilled players can find a way to build a chunk loader even if blocks like Dimensional Anchors are blacklisted.  Space stations + static loading + chunk loaders = OP.

**Comment by dj3520** [comment]
Looking at this problem again I suppose setting every dimension to static would benefit me all the same since unloading the dimension is essentially the same as unloading all of it's chunks. I suppose that's what I should be doing but I will continue trying to get my point across.

> What you seem to be asking for is - instead - for all space stations to be static loading automatically, or for a config option to enable automatic static loading. I think it's unlikely that other server owners would want that.

I've seen series where after a server gets set up, the admin deops himself and never touches the console again. Usually this is turns into a YouTube series where everyone tries to get as far along in the mods as possible while hindering their enemies in small and mainly inconvenient ways. There are also admins out there who just want to play the game as fair as anyone who doesn't have /op (I'm one of them.) Having a static by default option would be beneficial there I suppose, but not what I'm asking for. I know very well this isn't a place for suggestions. So let's talk about what I'd think would be beneficial. Instead of having the space stations load statically and stay that way, instead *only for a second or two when the server starts* so that mods can access them a bit before disappearing again so that chunk loaders could be found. It's a compatibility issue. This is my first problem and first point. Secondly
>If you don't want each player's chunks to load when they log in, set to false.

This line is from the chunkloading.conf file which, interpreted to me, means setting it to true leads to space stations loading when the player they belong to comes online. This sounded great and after I made a space station I plopped an anchor down that only works when I'm on the server. Now that dimension only exists when I'm online. However I found out the dimension actually loads when the owner reaches orbit, meaning my chunk loader is useless after a server restart. I suppose I could just set all space stations to static, but then I suppose the question changes. What's the purpose of dynamic loading then? At this point it actually makes logical sense all dimensions should be static loaded be default on a small server.
>if players were allowed to build chunk loaders in their bases that would place excessive load on the server - we had over 30,000 players

I'd have to say this isn't only a performance problem. I'm not sure how many space station dimensions could even exist in the first place. Surely there's a limit somewhere. Even the world itself isn't infinitely large due to java's limitations. But that's beside the point. Especially so since the wiki has a method around this.
>To keep some space station fun but with maximum dimension stability, one idea could be to whitelist the server, have your server staff create one or two "public" space stations, set those as static dimensions, then disable space station creation.

This could even be done by editing the space stations to be owned by a person that isn't even looking to the stars yet. This would be a quick method of forming teams by appointing a leader as the owner and giving him/her invite permissions, allowing the player to control who sees the "capital of their nation." I figure this would be the best approach. I even considered this for a sort of Space Mall where gamemode is automatically set to adventure (plus a bit more) pvp is disabled and players could buy, sell, and trade items even when from different teams/factions.

So, in conclusion, I'll try to explain myself more clearly.
* For mod compatibility and chunk anchoring reasons I believe that all dimensions, regardless of dynamic or not setting, should load at server startup **for a short amount of time** for mods to find any chunkloaders or other blocks in the world they might need to know about later on down the road (such  as a teleporter or Sync's shell storage)
* The config option LoadOnLogin has the description "If you don't want each player's chunks to load when they log in, set to false." However when set to true the dimensions don't load when the player logs in, but instead when said player reaches orbit. I currently have an anchor on my space station that only works when I'm logged in. If GC loads that dimension when I log in, and the anchor stops when I log out, that dimension only exists while I'm on the server. However since GC doesn't do this it's impossible to get back to my space station after relogging after the dimension is unloaded (I've switched to an always on anchor recently.)
* In the long run I've come to question the purpose of "dynamically loading dimensions" when minecraft does this in it's own form anyway by unloading chunks.

Time to crack my fingers now. That was a long typing session.

**Comment by radfast** [comment]
I think maybe you don't understand what load statically means, for dimensions.

It *doesn't* mean that all the chunks of the dimension stay loaded.

It only means that the dimension itself is flagged as a loaded dimension, so that any mod or plugin which needs to know about other dimensions [... and which is a badly coded mod so it only looks for the loaded dimensions...] can "see" the dimension instead of producing "dimension doesn't exist" type errors.

To achieve what you want will require these dimensions (any dimensions containing a chunk loader) to be statically loaded dimensions.

**Comment by dj3520** [comment]
I do know what a static loaded dimension is. Which is why I question the
purpose of having dynamic loading ones. Also it seems that all of the mods
I use are "dumb" in your opinion in the sense that they only look through
loaded dimensions. I explained my reasoning behind questioning dynamic
loading in my previous response.

**Comment by radfast** [comment]
I don't think this discussion is serving any purpose.

I very much value your contributions to the issues list, and your superlative screenshots.

But I don't think a discussion of coding details is useful.

FWIW, in my opinion, any mod or Bukkit plugin which is provided with co-ordinates including a dimension ID, and which applies a test so that the coordinates are seen as "bad" if that dimension ID is not currently loaded, is **dumb**.  Reason: dynamically loaded dimensions are a feature of Forge-modded Minecraft.  Therefore all Mods and Bukkit plugins which include dimension stuff should be coded on the assumption that dimensions might be dynamically loaded.  Two major mods, that's Galacticraft and Mystcraft, are well known to use dynamic loading dimensions.  Probably plenty of other mods do as well.

**Comment by radfast** [comment]
I stand corrected ... Forge has provided a way for mods with dynamic loading dimensions, to load the dimensions at server start specifically so as to activate chunk loaders.  I wasn't familiar with that before, but I'll research it and we can probably implement this in Galacticraft in the near future.

**Comment by dj3520** [comment]
Forge does? Wow that's nice. Suppose that is why both Sync and RailCraft
(mods with chunkloaders I run) simply look for anchors in loaded
dimensions. And I don't think iChun or CoverJaguar could mess that up, but
that is me judging them based on their mods. If Forge does the heavy work
this should be simple to add. Thank you sir.

However strictly for discussion and not criticism or anything, but what
benefit does dynamically loading the dimension bring? I'm curious.
