### ISSUE TITLE
Spacestation permissions

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#2003]
Currently its possible only to allow ppl one by one with /ssinvite [name], i think it would be nice to have a command that will allow everyone.

**Comment by EzerArch** [comment]
I said something about it here: #301.

**Comment by radfast** [comment]
:)

I am adding:
```/ssinvite +all``` :- Usable by the space station owner, this opens up his station (only) to all players
```/ssinvite -all``` :- Usable by the space station owner, this undoes that: so it goes back to being only usable by invited players

These commands will obviously not be needed if the global config setting 'Space Stations Require Permission' has been set to ```false``` on the server.

Note that now that GC add-ons are able to add space stations on other planets than the Overworld, the ```/ssinvite``` command applies to **all** of that owner's space stations - in other words, a player can own more than one space station, if they are on different planets.  All have the same permissions.  Galacticraft does not offer a way to allow different permissions for different space stations owned by the same person.

----

At the same time I am adding a new command, which can only be used by Ops / Admins (or anyone in creative).

* ```/ssnewowner```: It will change the 'owner' of an existing space station to a new player, and reset the old player so that he is able to create a space station again.  Useful if 2 people played together on a server and then 1 left the game.  Needs testing, but I think if abused it will also allow 1 player to have 2 space stations around the same planet.

I am also *thinking about* a command ```/ssdelete``` to delete a space station dimension completely.  This is problematic because it will not be reversible and could do huge damage.  It may be unnecessary now that /ssnewowner is included - the reset of the old player is the important thing.

**Comment by JasonMcRay** [comment]
This sounds awesome. Thank you

**Comment by radfast** [comment]
All the above (not ssdelete) included in next build.

The new code will also facilitate manual deletion of a space station: simply delete its folder from the world, and its data from the ```world/data``` folder, and on next player login, Galacticraft will update the player owner's info so that the player can create a fresh space station.  The only thing which cannot easily be changed is that the next space station created will still have its new consecutive dimension ID number, so the dimension ID numbers will rise and rise if space stations are created and deleted manually on a large server.

All the above info needs adding to the Wiki once the main micdoodle8.com site is back.
