### ISSUE TITLE
Mars ores textures too big at 32x32

### ISSUE THREAD

**Issue by Robijnvogel** [micdoodle8/Galacticraft#2032]
The textures for Mars iron, tin and copper are 32x32 pixels, instead of 16x16 pixels (their actual resolution).
This does not directly cause problems, but in combination with other mods it could.
It does, for instance, disable Dense Ores' ability to automatically generate dense textures from the ores' textures.
In the future, this may cause some rendering problems as well.

**Comment by radfast** [comment]
Thank you for raising this.  I have converted these to 16x16 pixels.

The Asteroids ores are still 32x32 textures because the texture of the base rock is 32x32.  If Dense Ores cannot automatically handle those, I'm not too concerned I think - I'm not sure if Dense Ores operates at all in the Asteroids dimension, currently.

**Comment by Robijnvogel** [comment]
I guess I never noticed, because they did not cause a problem for DenseOres.
