### ISSUE TITLE
Glass Panes Not Properly Sealing.

### ISSUE THREAD

**Issue by BumblebeeCannon** [micdoodle8/Galacticraft#2061]
While adding to my space station, I came across a bug where glass panes will act as a full block when sealing. Even when open spaces are visible, the oxygen sealer still counts it as a seal. An example is shown below.

Note: This issue doesn't seem to appear with iron bars.

[http://imgur.com/a/GpowL](url)

**Comment by radfast** [comment]
This is intended behaviour.  The vanilla glass planes are - by default - included in the config for sealable blocks.  http://wiki.micdoodle8.com/wiki/SealableIDs

If you don't want this behaviour, just remove the ID 102 from the config.

**Comment by BumblebeeCannon** [comment]
Oh, my bad then. If I may ask, why is it intended?

**Comment by radfast** [comment]
It's always been this way, since Galacticraft 1.
Glass panes are different from every other vanilla block, in that their configuration depends on what they are next to.  If they have solid blocks all around then they should make a seal.  I think we figured that if the player places a glass plane in the ceiling (so that it "looks" as though air can pass through it) actually it configured itself to make a skylight, it's just the vanilla Minecraft engine not rendering it properly...
