### ISSUE TITLE
small asteroids sometimes not generating

### ISSUE THREAD

**Issue by fayer3** [micdoodle8/Galacticraft#2062]
I just created a world in challenge mode and everything was fine,
then I exited to the menu and created an other world with the same seed, but the small asteroids are missing.
seed: -4647160910241675769
first world:
![2016-02-04_11 47 08](https://cloud.githubusercontent.com/assets/8282299/12813549/f61a85f6-cb38-11e5-97c1-6e5b4dfa4677.png)
second world: 
![2016-02-04_11 47 57](https://cloud.githubusercontent.com/assets/8282299/12813555/00d73f2a-cb39-11e5-8c54-f3d27adfb7fe.png)

Galacticraft version: 1.7-3.0.12.439
Forge version: 10.13.4.1566

fml-client-latest.log: http://pastebin.com/JNxmiUXX
latest.log: http://pastebin.com/6rMwZ5C1

**Comment by EzerArch** [comment]
Created a brand new world. Couldn't reproduce it.

![asteroids](https://cloud.githubusercontent.com/assets/6743303/13903021/61c74b74-ee46-11e5-82c0-c6d549b5a7ea.gif)


I have the feeling that difficulty level can affect the small asteroids spawning. Peaceful = no *new* small asteroids?

**Comment by radfast** [comment]
I think he means the 1 x 1 x 1 asteroid blocks, not the small asteroids.

**Comment by EzerArch** [comment]
> I think he means the 1 x 1 x 1 asteroid blocks, not the small asteroids.

Ah... okay. It's because those floating asteroid blocks are called "EntitySmallAsteroid". Got confused.

Anyway, those *static* 1x1x1 asteroid blocks are being generated in 454 as can be seen in the animated gif.

**Comment by radfast** [comment]
It could be linked with this: "then I exited to the menu and created an other world with the same seed".  Maybe Asteroid world gen is not resetting properly on exit to menu.

**Comment by EzerArch** [comment]
Believe or not, Optifine can be the cause too. I discovered that Fast Math (in Performance Settings) affects the world gen. I noticed my worlds generated less dungeons, ponds and other small structures: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272953-optifine-hd-h3-fps-boost-hd-textures-shaders-and?comment=48330

**Comment by dj3520** [comment]
Woah. Never would have thought Optifine would have that big of an impact on
gameplay.

**Comment by fayer3** [comment]
Just retried with a fresh install and only galacticraft 454 and forge 1448.
This time I have created two different worlds without challenge mode.
In the second world some small asteroids were missing, not all.
![2016-03-21_13 49 17](https://cloud.githubusercontent.com/assets/8282299/13919219/69dceb08-ef6c-11e5-9b82-5adfc30d2e24.png)

**Comment by radfast** [comment]
Thank you, nice MCEdit images, that helps me.

You are saying you created the first world and the second world **in the same Minecraft playing session** using the same seed?  It must be due to something not resetting when you exit to the menu.  It means there are probably other things in Galacticraft, like craters and dungeons, also not resetting when you do that, so this is a huge find.

**Comment by fayer3** [comment]
Yes this happens only, when creating multiple worlds in the same Minecraft session.
The first two worlds were with the same seed, 
the second two with he MCEdit images have different seeds.

**Comment by radfast** [comment]
Found and fixed this, thank you again for reporting.

I have also checked our code for possible similar issues with craters and dungeons - anything stored statically in the worldgen code.  I can't see anything else like this, so that's good!

(Sorry for the long delay, I have been away from the mod for many months for personal reasons.)
