### ISSUE TITLE
problem using bed

### ISSUE THREAD

**Issue by Fabboz** [micdoodle8/Galacticraft#2073]
Using Version #440 during sleeping using a vanilla bed (in overworld don't know if is the same in another dimension) i can see my player standing on the bed (on the foot block of the bed).
All works normal with #437 the one that i'm updating from.

**Comment by EzerArch** [comment]
1. Smart Moving installed?
2. Other mods installed?

**Comment by Fabboz** [comment]
after an insane amount of test with mods i found that the problem comes using the sphax texture pack [](http://bdcraft.net/community/pbdc-patches-rel/galacticraft-t1131.html) and/or opening the inventory with nei... but not 100% sure .

but there is the full list os the mods i was using at the moment when the problem comes after opening the inventory (E) and then sleep and spax pack installed :     Galacticraft 440 version

ID,Name,Version,Custom Container,Disableable,Dependencies
AM2-Preloader,AMCore,0.0.3,true,NEVER,[]
AencEx,AencEx,0.0.1,false,RESTART,[]
AgriCraft,AgriCraft,1.7.10-1.4.6-hotfix,false,RESTART,[]
AnimationAPI,AnimationAPI,1.2.4,false,DEPENDENCIES,[]
appliedenergistics2,Applied Energistics 2,rv3-beta-5,false,RESTART,"[appliedenergistics2-core, Forge@[10.13.4.1448,)]"
appliedenergistics2-core,Applied Energistics 2 Core,rv3-beta-5,true,NEVER,[]
smeltchevsky,Armor Smelter,b3,false,RESTART,[]
arsmagica2,Ars Magica 2,1.4.0.009,false,RESTART,[AnimationAPI]
BuildCraft|Builders,BC Builders,7.1.14,false,RESTART,[BuildCraft|Core@7.1.14]
BuildCraft|Energy,BC Energy,7.1.14,false,RESTART,[BuildCraft|Core@7.1.14]
BuildCraft|Factory,BC Factory,7.1.14,false,RESTART,[BuildCraft|Core@7.1.14]
BuildCraft|Robotics,BC Robotics,7.1.14,false,RESTART,[BuildCraft|Core@7.1.14]
BuildCraft|Silicon,BC Silicon,7.1.14,false,DEPENDENCIES,[BuildCraft|Core@7.1.14]
BuildCraft|Transport,BC Transport,7.1.14,false,DEPENDENCIES,[BuildCraft|Core@7.1.14]
Baubles,Baubles,1.0.1.10,false,DEPENDENCIES,"[Forge@[10.13.2,)]"
BetterAchievements,Better Achievements,0.1.0,false,RESTART,[]
bettervillages,Better Villages Mod,0.3,false,RESTART,[]
BiblioCraft,BiblioCraft,1.11.4,false,RESTART,[]
BiblioWoodsBoP,BiblioWoods Biomes O'Plenty Edition,1.9,false,RESTART,"[BiblioCraft, BiomesOPlenty]"
BiblioWoodsForestry,BiblioWoods Forestry Edition,1.7,false,RESTART,"[BiblioCraft, Forestry]"
BigReactors,Big Reactors,0.4.3A,false,RESTART,"[Forge@[10.13.2.1291,), CoFHCore, ThermalExpansion]"
BinnieCore,Binnie Core,2.0-pre14,false,RESTART,[Forestry]
BiomesOPlenty,Biomes O' Plenty,2.1.0,false,RESTART,"[Natura, Forge@[10.13.4.1566,)]"
AWWayofTime,Blood Magic: Alchemical Wizardry,v1.3.3,false,RESTART,[]
Botania,Botania,r1.8-248,false,RESTART,"[Baubles, Thaumcraft]"
Botany,Botany,2.0-pre14,false,RESTART,[BinnieCore]
BuildCraft|Core,BuildCraft,7.1.14,false,DEPENDENCIES,"[Forge@[10.13.2.1236,)]"
CarpentersBlocks,Carpenter's Blocks,3.3.8_dev_r7,false,RESTART,"[Forge@[10.13.0.1180,)]"
ChickenChunks,ChickenChunks,1.3.4.19,false,RESTART,"[CodeChickenCore@[1.0.3,)]"
chisel,Chisel,2.9.4.10,false,RESTART,"[EE3, ForgeMultipart, Thaumcraft, appliedenergistics2, Railcraft, AWWayofTime, TwilightForest]"
chocolateQuest,Chocolate Quest,1.0,false,RESTART,[]
<CoFH ASM>,CoFH ASM,000,true,NEVER,[]
CoFHCore,CoFH Core,1.7.10R3.1.1,false,DEPENDENCIES,"[Forge@[10.13.4.1448,10.14)]"
CodeChickenCore,CodeChicken Core,1.0.7.47,true,NEVER,[]
ComputerCraft,ComputerCraft,1.75,false,RESTART,[]
CustomChestLoot,Custom Chest Loot,1.1.1,false,RESTART,[]
DamageIndicatorsMod,Damage Indicators,3.2.0,false,RESTART,[]
DeadlyWorld,Deadly World,1.0.2,false,RESTART,[]
dldungeonsjdg,Doomlike Dungeons,1.8.7,false,RESTART,[]
DragonMounts,Dragon Mounts,r41-1.7.10,false,RESTART,[]
DynamicLights,Dynamic Lights,1.3.8,false,DEPENDENCIES,[]
DynamicLights_onFire,Dynamic Lights Burning Entity Module,1.0.4,false,RESTART,[DynamicLights]
DynamicLights_creepers,Dynamic Lights Creeper Module,1.0.4,false,RESTART,[DynamicLights]
DynamicLights_entityClasses,Dynamic Lights Entity Light Module,1.0.1,false,RESTART,[DynamicLights]
DynamicLights_dropItems,Dynamic Lights EntityItem Module,1.0.8,false,RESTART,[DynamicLights]
DynamicLights_flameArrows,Dynamic Lights Fiery Arrows Light Module,1.0.0,false,RESTART,[DynamicLights]
DynamicLights_floodLights,Dynamic Lights Flood Light,1.0.2,false,RESTART,[DynamicLights]
DynamicLights_mobEquipment,Dynamic Lights Mob Equipment Light Module,1.0.8,false,RESTART,[DynamicLights]
DynamicLights_otherPlayers,Dynamic Lights OtherPlayers Light Module,1.0.8,false,RESTART,[DynamicLights]
DynamicLights_thePlayer,Dynamic Lights Player Light Module,1.1.4,false,RESTART,[DynamicLights]
dynamicswordskills,Dynamic Sword Skills,1.7.10-1.7,false,RESTART,[]
EnderIO,Ender IO,1.7.10-2.3.0.423_beta,false,RESTART,"[Forge@[10.13.4.1448,), endercore@[1.7.10-0.2.0.31_beta,), MineFactoryReloaded, Waila@[1.5.10,), Thaumcraft, appliedenergistics2@[rv2-beta-8,)]"
EnderZoo,Ender Zoo,1.7.10-1.0.15.32,false,RESTART,"[Forge@10.13.0.1150,)]"
endercore,EnderCore,1.7.10-0.2.0.31_beta,false,DEPENDENCIES,[ttCore]
EnderTech,EnderTech,1.7.10-0.3.2.405,false,RESTART,"[ThermalExpansion@[1.7.10R4.0.0B1,)]"
ExtraBees,Extra Bees,2.0-pre14,false,RESTART,[BinnieCore]
ExtraTrees,Extra Trees,2.0-pre14,false,RESTART,[BinnieCore]
ExtraUtilities,Extra Utilities,1.2.11,false,RESTART,"[Forge@[10.13.2.1291,), ForgeMultipart@[1.2.0.336,), Baubles, ThermalFoundation, EE3]"
fastleafdecay,Fast Leaf Decay,1.4,false,RESTART,[]
samsfooddetails,Food Details,1.7.10-1.0.0,false,RESTART,[]
Forestry,Forestry for Minecraft,3.6.12.3,false,DEPENDENCIES,"[Forge@[10.13.0.1207,), Buildcraft|Core@[6.1.7,), ExtrabiomesXL, BiomesOPlenty, IC2@[2.0.140,), Natura@[2.2.0,), HardcoreEnderExpansion]"
ForgeMicroblock,Forge Microblocks,1.2.0.345,false,RESTART,"[ForgeMultipart, *]"
FML,Forge Mod Loader,7.10.99.99,true,NEVER,[]
ForgeMultipart,Forge Multipart,1.2.0.345,false,DEPENDENCIES,[]
GalacticraftCore,Galacticraft Core,3.0.12,false,DEPENDENCIES,"[Forge@[10.12.2.1147,), FML@[7.2.217.1147,), Micdoodlecore, IC2, BuildCraft|Core, BuildCraft|Energy, IC2]"
GalacticraftMars,Galacticraft Planets,3.0.12,false,RESTART,[GalacticraftCore]
Genetics,Genetics,2.0-pre14,false,RESTART,[BinnieCore]
GraveStone,GraveStone,2.16.0,false,RESTART,[]
GraviSuite,Graviation Suite,1.7.10-2.0.3,false,RESTART,"[IC2, RedPowerCore]"
HardcoreEnderExpansion,Hardcore Ender Expansion,1.8.5,false,RESTART,[]
inpure|core,INpureCore,1.7.10R1.0.0B9,false,RESTART,[ExtraUtilities]
ImmersiveEngineering,Immersive Engineering,0.6.5.1,false,RESTART,"[Railcraft, ThermalFoundation]"
ImmibisCore,Immibis Core,59.1.4,false,DEPENDENCIES,[IC2]
IC2,IndustrialCraft 2,2.2.811-experimental,false,DEPENDENCIES,"[Forge@[10.13.0.1200,)]"
inventorytweaks,Inventory Tweaks,1.59-dev-152-cf6e263,false,RESTART,"[FML@[7.2.0,), Forge@[10.12.1,)]"
ironbackpacks,Iron Backpacks,1.7.10-1.2.15,false,RESTART,[]
JABBA,JABBA,1.2.1,false,RESTART,"[Waila, NotEnoughItems]"
journeymap,JourneyMap,5.1.3,false,YES,"[Forge@[10.13.4.1558,)]"
LiquidXP,Liquid XP,59.0.2,false,RESTART,[ImmibisCore]
LogisticsPipes,Logistics Pipes,0.9.3.72,false,RESTART,"[Forge@[10.12.1.1079,), BuildCraft|Core, BuildCraft|Transport, BuildCraft|Silicon, IC2, Forestry, Thaumcraft, CCTurtle, ComputerCraft, factorization, GregTech_Addon, AppliedEnergistics, ThermalExpansion, BetterStorage]"
MineFactoryReloaded|CompatProjRed,MFR Compat ProjectRed,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, ProjRed|Core, ProjRed|Exploration]"
MineFactoryReloaded|CompatAppliedEnergistics,MFR Compat: Applied Energistics,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, appliedenergistics2]"
MineFactoryReloaded|CompatAtum,MFR Compat: Atum,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, Atum]"
MineFactoryReloaded|CompatBackTools,MFR Compat: BackTools,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, mod_BackTools]"
MineFactoryReloaded|CompatBuildCraft,MFR Compat: BuildCraft,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, BuildCraft|Core]"
MineFactoryReloaded|CompatChococraft,MFR Compat: Chococraft,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, chococraft]"
MineFactoryReloaded|CompatExtraBiomes,MFR Compat: ExtraBiomes,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, ExtrabiomesXL]"
MineFactoryReloaded|CompatForestry,MFR Compat: Forestry,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, Forestry]"
MineFactoryReloaded|CompatForgeMicroblock,MFR Compat: ForgeMicroblock,1.7.10R2.8.1,false,RESTART,[MineFactoryReloaded]
MineFactoryReloaded|CompatIC2,MFR Compat: IC2,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, IC2]"
MineFactoryReloaded|CompatRailcraft,MFR Compat: Railcraft,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, Railcraft]"
MineFactoryReloaded|CompatSufficientBiomes,MFR Compat: Sufficient Biomes,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, EmasherWorldGen]"
MineFactoryReloaded|CompatThaumcraft,MFR Compat: Thaumcraft,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, Thaumcraft]"
MineFactoryReloaded|CompatThermalExpansion,MFR Compat: Thermal Expansion,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, ThermalExpansion]"
MineFactoryReloaded|CompatTConstruct,MFR Compat: Tinkers' Construct,1.7.10R2.8.1,false,null,"[MineFactoryReloaded, TConstruct]"
MineFactoryReloaded|CompatTwilightForest,MFR Compat: TwilightForest,1.7.10R2.8.1,false,RESTART,"[MineFactoryReloaded, TwilightForest]"
MineFactoryReloaded|CompatVanilla,MFR Compat: Vanilla,1.7.10R2.8.1,false,RESTART,[MineFactoryReloaded]
MagicBees,Magic Bees,1.7.10-2.3.6,false,RESTART,"[Forestry@[3.6,), Thaumcraft, ExtraBees, EE3, ArsMagica, TConstruct, Railcraft, ThermalFoundation, ThermalExpansion, RedstoneArsenal, AWWayofTime, Botania, appliedenergistics2]"
malisisdoors,Malisis' Doors,1.7.10-1.13.0,false,RESTART,[malisiscore]
malisiscore,MalisisCore,1.7.10-0.14.0,false,DEPENDENCIES,[]
Mantle,Mantle,1.7.10-0.3.2.jenkins191,false,DEPENDENCIES,"[Forge@[10.13,)]"
Metallurgy,Metallurgy 4,4.0.8,false,RESTART,"[MetallurgyCore@[4.0.4,], Botania, TConstruct]"
MetallurgyCore,Metallurgy Core,4.0.4,false,DEPENDENCIES,[]
Micdoodlecore,Micdoodle8 Core,,true,NEVER,"[required-after:Forge@[10.12.2.1148,)]"
MineFactoryReloaded,MineFactory Reloaded,1.7.10R2.8.1,false,RESTART,"[CoFHCore@[1.7.10R3.1.0,1.7.10R3.2.0)]"
MineMenu,MineMenu,1.2.0,false,RESTART,"[Forge@[10.13.0.1207,)]"
MineTweaker3,MineTweaker 3,3.0.10,false,RESTART,[]
MTRM,MineTweakerRecipeMaker,1.0,false,RESTART,[]
mcp,Minecraft Coder Pack,9.05,true,YES,[]
Forge,Minecraft Forge,10.13.4.1614,true,NEVER,[]
McMultipart,Minecraft Multipart Plugin,1.2.0.345,false,RESTART,[]
me,More Enchantments,1.3.2.1,false,RESTART,[]
MoreEnchants,MoreEnchants,1.3.0,false,RESTART,[]
MrTJPCoreMod,MrTJPCore,1.1.0.32,false,DEPENDENCIES,[]
MutantCreatures,Mutant Creatures,1.4.9,false,RESTART,[]
Mystcraft,Mystcraft,0.12.3.00,false,DEPENDENCIES,"[Forge@[10.12.1.1083,)]"
NEIAddons,NEI Addons,1.12.11.36,false,RESTART,[NotEnoughItems]
NEIAddons|AppEng,NEI Addons: Applied Energistics 2,1.12.11.36,false,RESTART,"[NEIAddons, appliedenergistics2]"
NEIAddons|Botany,NEI Addons: Botany,1.12.11.36,false,RESTART,"[NEIAddons, Botany]"
NEIAddons|CraftingTables,NEI Addons: Crafting Tables,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|Developer,NEI Addons: Developer Tools,1.12.11.36,false,RESTART,[NEIAddons]
NEIAddons|ExNihilo,NEI Addons: Ex Nihilo,1.12.11.36,false,RESTART,[exnihilo]
NEIAddons|Forestry,NEI Addons: Forestry,1.12.11.36,false,RESTART,"[NEIAddons, Forestry]"
neiintegration,NEI Integration,1.1.1,false,RESTART,[]
NEI-Mystcraft-Plugin,NEI Mystcraft Plugin,02.01.08,false,RESTART,"[*, spacore@[01.05.09,), NotEnoughItems, Mystcraft@(0.11.6,), LookingGlass@[0.1.0.00,)]"
Natura,Natura,2.2.0,false,RESTART,[Mantle]
NotEnoughItems,Not Enough Items,1.0.5.120,true,NEVER,"[CodeChickenCore@[1.0.7,)]"
openmodularturrets,Open Modular Turrets,2.1.9-211,false,RESTART,"[ThermalFoundation, ThermalExpansion, OpenComputers, ComputerCraft, Mekanism, EnderIO, Thaumcraft]"
OpenBlocks,OpenBlocks,1.5.1,false,RESTART,"[OpenMods@[0.9.1,0.10)]"
OpenMods,OpenMods,0.9.1,false,DEPENDENCIES,[OpenModsCore]
OpenModsCore,OpenModsCore,0.9.1,true,NEVER,[]
fodc,Ore Dictionary Converter,1.5.2,false,RESTART,"[Forge@[10.13.0.1200,)]"
PneumaticCraft,PneumaticCraft,1.12.6-149,false,RESTART,"[Forge@[10.13.3.1388,), Forestry, ComputerCraft]"
ProjRed|Compatibility,ProjectRed Compatibility,4.7.0pre10.93,false,RESTART,"[ProjRed|Core, ProjRed|Transmission, ProjRed|Exploration, ProjRed|Transportation, TConstruct, ThermalExpansion, ComputerCraft]"
ProjRed|Core,ProjectRed Core,4.7.0pre10.93,false,DEPENDENCIES,"[ForgeMultipart, MrTJPCoreMod]"
ProjRed|Fabrication,ProjectRed Fabrication,4.7.0pre10.93,false,RESTART,"[ProjRed|Core, ProjRed|Integration, ProjRed|Transmission]"
ProjRed|Illumination,ProjectRed Illumination,4.7.0pre10.93,false,RESTART,[ProjRed|Core]
ProjRed|Integration,ProjectRed Integration,4.7.0pre10.93,false,DEPENDENCIES,[ProjRed|Core]
ProjRed|Transmission,ProjectRed Transmission,4.7.0pre10.93,false,DEPENDENCIES,[ProjRed|Core]
Railcraft,Railcraft,9.8.0.0,false,RESTART,"[Forge@[10.13.0.1199,), BuildCraft|Core[6.1.7,), BuildCraft|Energy, BuildCraft|Builders, BuildCraft|Factory, BuildCraftAPI|statements[1.0,), BuildCraftAPI|transport[1.0,), Forestry[3,), Thaumcraft, IC2@[2.2,)]"
RedstoneArsenal,Redstone Arsenal,1.7.10R1.1.2,false,RESTART,"[CoFHCore@[1.7.10R3.1.0,1.7.10R3.2.0), ThermalExpansion]"
JAKJ_RedstoneInMotion,Remain In Motion,2.8.10,false,RESTART,"[planetguyLib@[1.9,), CoFHCore, BuildCraft|Transport]"
RenderPlayerAPI,Render Player API,1.4,true,NEVER,[]
rendertweaks,RenderTweaks,1.2,false,RESTART,[]
Roguelike,Roguelike Dungeons,1.4.4,false,RESTART,[]
simplyjetpacks,Simply Jetpacks,1.4.1,false,RESTART,"[ThermalExpansion, RedstoneArsenal, EnderIO, BuildCraft|Core]"
spacore,SpACore,01.05.10,false,DEPENDENCIES,[]
SpecialAI,Special AI,1.1.2,false,RESTART,[]
SpecialMobs,Special Mobs,3.2.2,false,RESTART,[]
SquidAPI,SquidAPI,1.1.14,false,DEPENDENCIES,"[ThermalExpansion, Botania, RotaryCraft, appliedenergistics2, WayOfTime, ThaumCraft, RailCraft, uptodate]"
SquidUtils,SquidUtils,2.1.3,false,RESTART,"[SquidAPI, AppleCore, MineTweaker3]"
StorageDrawers,Storage Drawers,1.7.10-1.7.9,false,DEPENDENCIES,[waila]
StorageDrawersBop,Storage Drawers: Biomes O' Plenty Pack,1.7.10-1.1.1,false,RESTART,[StorageDrawers]
StorageDrawersForestry,Storage Drawers: Forestry Pack,1.7.10-1.1.2,false,RESTART,[StorageDrawers]
Thaumcraft,Thaumcraft,4.2.3.5,false,DEPENDENCIES,"[Forge@[10.13.2,), Baubles@[1.0.1.10,)]"
ThaumcraftMobAspects,Thaumcraft Mob Aspects,1.7.2-2A,false,RESTART,"[Forge@[10.12.2.1121,), Thaumcraft@[4.1.1,)]"
ThaumicHorizons,Thaumic Horizons,1.1.9,false,RESTART,"[Forge@[10.13.2,), Thaumcraft@[4.2.3.4,)]"
ThaumicTinkerer,Thaumic Tinkerer,unspecified,false,RESTART,"[Forge@[10.12.1.1112,), Thaumcraft@[4.2.2.0,], IC2, ThaumicTinkererKami, Waila, ForgeMultipart, ComputerCraft]"
ThaumicTinkerer-preloader,Thaumic Tinkerer Core,0.1,true,NEVER,[]
TwilightForest,The Twilight Forest,2.3.7,false,RESTART,[]
ThermalDynamics,Thermal Dynamics,1.7.10R1.1.0,false,RESTART,"[ThermalFoundation@[1.7.10R1.2.0,)]"
ThermalExpansion,Thermal Expansion,1.7.10R4.1.1,false,RESTART,"[CoFHCore@[1.7.10R3.1.0,1.7.10R3.2.0), ThermalFoundation@[1.7.10R1.2.2,1.7.10R1.3.0)]"
ThermalFoundation,Thermal Foundation,1.7.10R1.2.2,false,DEPENDENCIES,"[CoFHCore@[1.7.10R3.1.0,1.7.10R3.2.0)]"
Treecapitator,Treecapitator,1.7.10,false,RESTART,"[Forge@[10.13.2.1232,), bspkrsCore@[6.15,)]"
UsefulFood,UsefulFood,1.4.5,false,RESTART,[]
WR-CBE|Addons,WR-CBE Addons,1.4.1.9,false,RESTART,[WR-CBE|Core]
WR-CBE|Core,WR-CBE Core,1.4.1.9,false,DEPENDENCIES,"[CodeChickenCore@[1.0.4,), ForgeMultipart]"
WR-CBE|Logic,WR-CBE Logic,1.4.1.9,false,RESTART,"[WR-CBE|Core, ForgeMultipart]"
Waila,Waila,1.5.10,false,RESTART,"[NotEnoughItems@[1.0.4.0,)]"
WailaHarvestability,Waila Harvestability,1.1.6,false,RESTART,"[TConstruct, ExtraTiC, TSteelworks, Mariculture]"
witchery,Witchery,0.24.1,false,RESTART,"[Forge@[10.13.2.1277,), MineFactoryReloaded, NotEnoughItems, Waila, ForgeMultipart, AWWayofTime]"
woodstuff,WoodStuff,1.3.2,false,RESTART,"[Forge@[10.13.4.1558,), arsmagica2]"
zettaindustries,Zetta Industries,1.1,false,RESTART,"[ImmersiveEngineering, Forestry]"
zoom,Zoom,1.0.1,false,RESTART,[]
bspkrsCore,bspkrsCore,6.15,false,DEPENDENCIES,"[Forge@[10.13.2.1230,)]"
planetguyLib,planetguyLib,1.9,false,DEPENDENCIES,

**Comment by Fabboz** [comment]
Version 438 is working good too

**Comment by Fabboz** [comment]
with 442 reloading the world fix the issue but after opening the inventory (E) i got that problem. every try the same.

**Comment by Fabboz** [comment]
439 exactly rhe same as 442

**Comment by EzerArch** [comment]
Thank you. The player no longer stands on the left side of the bed (so spooky that it seemed someone was watching me [1](https://cloud.githubusercontent.com/assets/6743303/13201302/35c7ecda-d849-11e5-91b4-169f9def3ae2.png) [2](https://cloud.githubusercontent.com/assets/6743303/13201303/35cb2706-d849-11e5-9903-2d3243a14847.png)), now the player stands in front but still standing up. ;)

1. With SmartMoving:
![2016-02-21_02 53 58](https://cloud.githubusercontent.com/assets/6743303/13201223/8704820a-d846-11e5-944e-f30c7bf9e08b.png)

2. Without SmartMoving (but with PlayerAPI - interesting, player is 1 block closer):
![2016-02-21_03 00 25](https://cloud.githubusercontent.com/assets/6743303/13201250/57d90a40-d847-11e5-9e53-6b98f953bb01.png)

Using r433.

*(Off-topic/Maybe related: I noticed since build 439 I could no longer crawl through 1-block-tall passages, as if the player had always the same 2-block-tall hitbox and disregarded the "laying" position. Related? I could open an issue with details and tests)*

**Comment by radfast** [comment]
oh no

I'll take a look...

**Comment by Fabboz** [comment]
I've solved the issue deleting renderplayerapi that i found its useless in
my pack. Thx :)
Il 21/feb/2016 15:22, "Galacticraft developer" <notifications@github.com>
ha scritto:

**Comment by radfast** [comment]
@EzerArch 
> I'm using r433.

Do you mean 443?

I'm not seeing this in my testing with:
PlayerAPI-1.7.10-1.4
RenderPlayerAPI-1.7.10-1.4
SmartMoving-1.7.10-15.6
SmartRender-1.7.10-2.1

**Comment by dj3520** [comment]
@Fabboz If someone uses your pack with Optifine, PlayerAPI and RenderPlayerAPI should be installed.

**Comment by radfast** [comment]
@dj3520  why do you say that?  Most Optifine issues have now been fixed - one of the big ones was actually caused by Reika's mods not by Optifine at all.

Any remaining Optifine issues I want to know about, and should be able to fix fairly quickly.   Currently the only one open issue with Optifine is #2084.  Possibly, players looking at other players on a multiplayer server is also an issue, that's something I don't often test.  Maybe I should pay the Galaxy Space guys a visit, they did invite me ...

**Comment by dj3520** [comment]
@radfast The optifine issues from my testing a few versions back are as follows when OptiFine U D1 is used:
- Players cannot see their own equipment without PlayerAPI
- Players cannot see other players' equipment without RenderPlayerAPI (which requires PlayerAPI anyway.)

If you'd like I could of course test again with 444.

>Possibly, players looking at other players on a multiplayer server is also an issue, that's something I don't often test :( (maybe I should pay the Galaxy Space guys a visit, they did invite me ...)

From what I understand what usually happens with mod developers is that they don't get to enjoy what they've done. They're mostly focused on development. I'd say there isn't a thing wrong with that, unless it's the only thing that's done. Recently I've been watching DireWolf20's Server Play series, where the developers of 1.8.9 mods witness their mods interacting with each other and being progressed though, getting input from the players and seeing bugs first hand. Even things like BetterThanMinecon have what normally wouldn't show as a performance problem show up after it's been in the code for over a year. Plus everyone can talk about their mod. "Cool particle effects how'd you pull it off?" Kind of thing. I know that if I ever got into modding and was handed an invitation for people's opinion, I'd enjoy hearing it.

Not saying you're close minded or anything of that sort. Instead, if the opportunity is there, why not jump on it?

**Comment by radfast** [comment]
*    Players cannot see their own equipment without PlayerAPI
*    Players cannot see other players' equipment without RenderPlayerAPI (which requires PlayerAPI anyway.)

If you can test this again with latest it would be very helpful.  Especially the first statement.

In our future discussions please use this code:
"PlayerAPI" means PlayerAPI only.
"RenderPlayerAPI" means RenderPlayerAPI + PlayerAPI which it requires
"SmartRender" means SmartRender + RenderPlayerAPI + PlayerAPI which it requires
"SmartRender" means SmartMoving + SmartRender + RenderPlayerAPI + PlayerAPI which it requires

It is a big pain for me to switch between these four different configurations for testing, due to the special way that a development environment has to be set up.  So when reporting issues, **clarity** and **accuracy** about exactly which of these configurations causes the issue, is extremely helpful.  Otherwise I waste a lot of time switching between configurations instead of coding.

**Comment by dj3520** [comment]
Can do. I that method of communication better. As for testing, I use magic
launcher,  which has a nice interface for "turning mods on/off" with simple
check boxes. Different profiles save what mods were chose along with the
usual config options. You could even set up five profiles for Optifine,
PlayerAPI, RenderPlayerAPI, SmartRender, and SmartMoving. The hard part
then becomes waiting for client load.

**Comment by radfast** [comment]
Fixed it for you.  I'm using a development environment.  Like this: https://www.youtube.com/watch?v=BES9EKK4Aw4  I can't just switch mods on and off using MagicLoader.

**Comment by EzerArch** [comment]
@radfast.
> Do you mean 443?

Yes. Now I'm on 444.

Testing now with (Forge 1614):
Galacticraft-Planets-1.7-3.0.12.444.jar
GalacticraftCore-1.7-3.0.12.444.jar
MicdoodleCore-1.7-3.0.12.444.jar
OptiFine_1.7.10_HD_U_D1.jar (no effect)
SmartMoving-1.7.10-15.6.jar
SmartRender-1.7.10-2.1.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.4.jar

![2016-02-23_02 46 05](https://cloud.githubusercontent.com/assets/6743303/13242847/ab902e34-d9d7-11e5-84d0-2d119223a2ff.png)

Log: https://gist.github.com/EzerArch/ebe8ab6fe8f17a23b87a

**Comment by dj3520** [comment]
>I can't just switch mods on and off using MagicLoader.

I'm a bit confused. There's two things I could interpret from this:
- First, you haven't found out how to switch the mods on/off (possible but I somewhat doubt it) or
- Doing so isn't what you intend to do (possible from the including of the word "just")

**Comment by XFactHD** [comment]
He can't use the magic launcher in a development environment because the game is not started with a normal launcher but directly from the IDE.

**Comment by radfast** [comment]
Thank you @XFactHD :)

**Comment by radfast** [comment]
@EzerArch  thank you, I have tested the same set of mods yesterday and beds worked correctly.  I wasn't using Forge 1614 though, maybe it's that ...  Thank you for your patience, I'm sure we'll find a fix in the end.

**Comment by XFactHD** [comment]
np :) I am also developing mods for MC and I know that phenomenon, too.

**Comment by dj3520** [comment]
Ha sorry for that then. Forgot that was even possible.

**Comment by radfast** [comment]
@dj3520 any luck on testing these statements in latest GC?
>     Players cannot see their own equipment without PlayerAPI
   Players cannot see other players' equipment without RenderPlayerAPI (which requires PlayerAPI anyway.)

I'm not seeing the first problem, in my tests.

**Comment by dj3520** [comment]
Apologies, I actually forgot. However in my testing with two lan clients, I've found something interesting.
Yes, players seeing themselves works perfect in all configurations, however:
Anything less than RenderPlayerAPI does not show thermal armor on other players unless removed and added to the player again (to refresh I bet) and no oxygen gear. I'm thinking something might be wrong since I see this _without OptiFine or above installed._ Though doubtful I was doing testing with my modpack's other mods as well.

**Comment by radfast** [comment]
Thank you @dj3520.   Your careful testing has highlighted the true issue here - you are right, Galacticraft was waiting for a gear update refresh in the non-RenderPlayerAPI situation.

Will be fixed in next build.

**Comment by dj3520** [comment]
@radfast You give me more credit than I deserve. I should of tested with only GC, not my modpack.
What's strange to me is oxygen gear did not show even without Optifine...

**Comment by EzerArch** [comment]
Thanks for fixing the "standing up on bed" part in 445. :)

**Comment by radfast** [comment]
The multiplayer gear visibility issue (prior to gear updates) has been in the mod forever, both with +  without Optifine.

In September 2014 micdoodle8 fixed it in a6c491c but - by accident - he put the operative part of the fix only into the GC code that works with RenderPlayerAPI, he forgot to include the same for plain GC.

Until now, people reporting the multiplayer issue have wrongly attributed it to Optifine, so I assumed it was going to be tough to fix.  Optifine is a real pain to troubleshoot, because it is not an open source mod, its .jar is obfuscated like Minecraft, and almost everything it does is based on changing vanilla Minecraft.  Even with good tools it is a slow and painful process.

@dj3520 spotted that the issue occurs even without Optifine and also - crucially - that the issue fixed itself when gear was updated => from that it's easy for me to look at the correct part of the code, spot the code issue and fix it.

That deserves big credit, I would say :)

I very much appreciate the effort from @EzerArch and @dj3520 that goes into spotting issues and making clear reports.  The mod would not be so good without you.

(This is not an encouragement to go looking for more bugs though ... I need to balance the time I have for this between fixing stuff and coding new features)

**Comment by dj3520** [comment]
Optifine sounds like a real pain to mod developers in general, which is kind of a shame since it does wonders for performance. The level of control allows me to increase my framerate by taking some of the graphical features I don't care much about and toning them down, while not sacrificing things I do care for (transparent leaves is a must if you ask me.) Perhaps it's just me and the way I'd do things, or because I've never tried to make a mod for any game, but I'd actively work with other mod makers in order to make everything compatible in some way, possibly even maintaining an API so that my mod doesn't conflict with others, or so people can build on top of mine. Galacticraft is a mod that follows the way I'd go about doing so in nearly every way. So thank you @radfast for the one mod I could not play without (besides OptiFine, sorry lol.)

Also I realize you might be busy adding instead of fixing, but if something isn't right and I notice it I feel like it's my duty to report it. I realize sometimes my reports aren't the most clear sometimes. I apologize and simply ask that any details that aren't understood be asked about. I will try and provide them to the best of my ability.

**Comment by radfast** [comment]
All good.  Keep the reports coming.  I just may not get to them so fast.

There is satisfaction in fixing issues and it makes for a more polished mod.  And really it's essential for features which actually were not working before due to bugs, otherwise all the effort that went into offering the feature in the first place was for nothing!

But from now I am going to be switching more of my attention over to new features, which I think is more interesting for the majority of players, and it's about time Galacticraft had some new stuff :)

**Comment by dj3520** [comment]
Hearing "new feature" from you excites me. And not because there is more to
bug test.
