### ISSUE TITLE
Warning message in startup log

### ISSUE THREAD

**Issue by drock711** [micdoodle8/Galacticraft#2101]
[Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:534)
 [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:501)
 [Client thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.items.GCItems.initItems(GCItems.java:245)
 [Client thread/WARN] [FML]: *  at micdoodle8.mods.galacticraft.core.GalacticraftCore.preInit(GalacticraftCore.java:360)
 [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)...

**Comment by radfast** [comment]
What are you reporting there?  Please provide full log.

**Comment by radfast** [comment]
This was fixed by https://github.com/micdoodle8/Galacticraft/commit/d223868143baac4babdb735bab21829132e939ed ever since Galacticraft build 404, four months ago.

You have not followed the Guidelines for Contributors, link at top of page when you created the new issue.  The guidelines require you to test issues in the latest version of Galacticraft.
