### ISSUE TITLE
[Very Minor] NEI and heavy duty plates

### ISSUE THREAD

**Issue by dj3520** [micdoodle8/Galacticraft#2120]
NEI shows double the expected output of the electric compressor when looking up heavy duty plates.

![image](https://cloud.githubusercontent.com/assets/8284194/13381009/6a8619a8-de1e-11e5-95d1-8ae7600a0088.png)

Actually yields just two heavy plates.

**Comment by radfast** [comment]
Which GC version?
Do you have **Quick Mode** enabled?
What is the actual output of your Electric Ingot Compressor?

A known issue here is that in NEI the **input** should be showing 2 items per stack being used, for **all** the Electric Ingot Compressor recipes - because there is double output in the two output slots.  Galacticraft is telling NEI to use 2-item stacks in the inputs, but due to a bug in NEI, only one item is shown.  [I have not found any workaround for this](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/nei/ElectricIngotCompressorRecipeHandler.java#L46)

**Comment by dj3520** [comment]
GC 445 with NEI 1.0.5.120-universal
No Quick Mode
> Actually yields just two heavy plates.

Output is correct if doubling the materials shown, though without knowing that ahead of time players will think they get 4 heavy duty plates. Strange that NEI doesn't give you this option/has it well known.

Not really a big enough issue to keep open then in my opinion since you already have it commented in the code. I'll leave closing this up to you then since having it open might serve as a reminder to you (I've seen you do this.)

**Comment by radfast** [comment]
Turns out it was an easy fix after all.  I've also corrected the machine name (Electric Compressor) and updated the wiki so it's correct :)

**Comment by dj3520** [comment]
Great news. Looking forward to the things you're working on.
