### ISSUE TITLE
How now to get the name of the parent planet?

### ISSUE THREAD

**Issue by BlesseNtumble** [micdoodle8/Galacticraft#2137]
Good afternoon.
In the latter (446) build in my addon takes place crash due to incorrect name of the parent planet (Mars).

I used to get the name like this:
```
@Override
public String getPlanetToOrbit ()
{
return "planet.mars";
}
```
Now how do I get the name of the planet?

**Comment by Yanniclord** [comment]
@radfast Any idea?

**Comment by Yanniclord** [comment]
By checking the code, everything i find is "planets.mars". Try that Blesse, see if it works. Its planet, but with an "s" on the end, so "planets", "planets.mars" and not "planet.mars"

**Comment by radfast** [comment]
Are you testing this using ```provider.getDimensionName()```?

If so, that changed in 446 from unlocalised to a localised name:
https://github.com/micdoodle8/Galacticraft-API/commit/e4dd47e3ca542565b6734b59eb5c168ef3686fb2

The change was made to support server owners, because some plugins report "XYZ has happened in dimension #NAME" and it seems better if the #NAME is localised.

You can still get the unlocalised name by using ```((IGalacticraftWorldProvider)provider).getCelestialBody()..getUnlocalizedName()```

Hope that helps?

**Comment by BlesseNtumble** [comment]
I did like this. Everything is working.
```
@Override
    public String getPlanetToOrbit()
    {
        return MarsModule.planetMars.getLocalizedName();
    }
```

**Comment by radfast** [comment]
@BlesseNtumble  please revert this change in your add on.  Sorry!!!!

https://github.com/micdoodle8/Galacticraft/commit/930eac93e0cb30d19092e6d7964e21b45648cdac
I changed the dimension names back to **unlocalised** names for internal purposes.
The localised names should only be used by other mods / Bukkit plugins.
If you need the internal (unlocalised) dimension name you can use ```WorldUtil.getDimensionName(provider)```.
