### ISSUE TITLE
[Bukkit server] Parachest interaction not being stopped by Worldguard etc

### ISSUE THREAD

**Issue by Krysinski** [micdoodle8/Galacticraft#2146]
Please, add config option for select default overworld dimention. We need to landing on additional multiverse world where is primary gameplay for all users. 
Users cant build in default world on my server, but can interact with parachest. 
Thanks.

**Comment by radfast** [comment]
1.  I am not very willing to spend development time coding support for specific Bukkit plugins, unless there is widespread demand from many server owners.  Please make this suggestion on the forum and we can see how many people agree it is needed.  Meanwhile why can't you configure your server so the Overworld is dimension 0 and your spawn is in a different dimension?

2.  Are you saying Parachest interaction is not being stopped by Worldguard / Factions type plugins?  That's something we probably can fix.

**Comment by Krysinski** [comment]
1. Parachest interaction in dim0 is not a bug with WG))) It is manualy configured plugin MachineGuardReloaded wich very need to help WG protect all items and blocks from mods. WG prevent players to remove parachest without permissions and that cant be configured in WG config.
2. I find in GC core.conf that string:
 I:"Oil gen in external dimensions"
so i suppose that is not difficult to you to add some like that:
I:"Default overworld dimension"

**Comment by dj3520** [comment]
> Meanwhile why can't you configure your server so the Overworld is dimension 0 and your spawn is in a different dimension?

**Comment by DraksterAU** [comment]
+1 to supporting configuring of the dimension Ids in use by Galacticraft.... For a Cauldron based server this would be an awesome feature.

**Comment by dj3520** [comment]
>configuring of the dimension Ids in use by Galacticraft
This is already a thing in core.conf

    # Dimension ID for the Moon
    I:idDimensionMoon=-28

    # Dimension ID for Overworld Space Stations
    I:idDimensionOverworldOrbit=-27

    # Dimension ID for Static Overworld Space Stations
    I:idDimensionOverworldOrbitStatic=-26

and in planets.conf

dimensions {
    # Dimension ID for Asteroids
    I:dimensionIDAsteroids=-30

    # Dimension ID for Mars
    I:dimensionIDMars=-29
}

**Comment by DraksterAU** [comment]
All that is left is to complete the set ;)
My wording is bad.... Sorry.

**Comment by radfast** [comment]
@dj3520 I have said before, I appreciate that you are trying to help but please don't comment on other people's threads if you do not have the same issue.  It causes confusion.

The configurable Ids for space stations are for the WorldProvider type registry, not the actual dimension Ids.  The actual dimension Ids for space stations will take unused consecutive dimension numbers 2, 3, 4, etc and that is not configurable, and I have no plans to change it.

**Comment by Krysinski** [comment]
@DraksterAU Thank you for detailed description about Multiverse. It has some features on the creation of the additional worlds: new world has own folder with name, example /world/new_world like nether or ender. By default, the game has a one shared folder for all the worlds with dim's in it. And overworld files are in /world, but not in special folder for this dim. That is problem, It is much easier to regenerate a new_world as it is in a separate folder. I plan to periodically regeneration new_world, and the main world with restrictions on construction will continue to exist all time. Its a strange to launch rocket from new_world and landing on main world all time. I can do a lot of worlds in the future, and all of them to determine in the config file with the ability to launch rockets, but cant determine landing world. It's not fair.
Sorry my English.

**Comment by dj3520** [comment]
What I'm understanding from this:
- You want to "archive" a world that is currently dim 0 so that people cannot change things.
- You have made a second Overworld you plan to "periodically regenerate"
- GC has you land on dim 0 (archive world) which is not what you want.
- You want an override of where GC thinks the Overworld is so that it's not dim 0 (archive) but your second Overworld.

What I would do:
- Do not expect GC implementing a configurable overworld as this is more work and more headache on @radfast and would only serve it's purpose in rare occasions like this.
- Backup all worlds in case this doesn't work (I personally use 7zip)
- Make a new folder "archive"
- For every file that shows inside your 2nd Overworld, I'd move your archive world's data into the "archive" folder.
- Move all files in your 2nd Overworld folder into where your archive world's files were originally
- Possibly tweak Multiverse to see your "archive" world and no longer see your 2nd Overworld (I don't mess with Multiverse at all.)

What should happen next if things aren't picky is that your archive world becomes another dimension number and your 2nd Overworld now serves as dim 0. Your dim 0 should always serve as an "active" world, not an archive. Wanting a mod to fix this for you is a bit lazy if you ask me. Dim 0 should serve as "home."

**Comment by DraksterAU** [comment]
@dj3520 You have absolutely no idea what your talking about.

**Comment by DraksterAU** [comment]
@radfast So you know I'm only supporting the idea of the dimension Id being configurable for overworld so we can use whatever dimension we have set as one of our playable (and configurable ) worlds.
This guy is way off.

**Comment by Krysinski** [comment]
Guys, i post this http://forum.micdoodle8.com/index.php?threads/please-add-config-option-for-select-default-overworld-dimention.6437/
as @radfast  say. We can discuss there.

**Comment by dj3520** [comment]
@Krysinski Thank you.

**Comment by radfast** [comment]
@dj3520  I have asked you twice already in the last 10 days: do **not** post on other people's issue reports, unless it's an issue which you are experiencing in **your** game.

So we're clear here:
*  posting new issue reports which describe bugs or mod conflicts not already reported - very welcome
*  posting extra info or screenshots (your screenshots have always been good) on existing issue reports where you also have the issue - very welcome
*  posts which advise other players what to do or ask for additional info from them - not welcome, that needs to come from the devs
*  posts like ^^^^^ giving opinions on what other people should expect from the mod - not welcome.

Hope you understand the reasons for this.

**Comment by dj3520** [comment]
Sorry I actually don't think I saw your first post until now. Either way the discussion is now on the forum so I suppose this can be closed?

**Comment by DraksterAU** [comment]
That is up to the Devs or the person who created the damn issue.

Leave it be.

**Comment by dj3520** [comment]
@DraksterAU 
>I suppose

Not "it should be" meaning I acknowledge it's not my choice.

**Comment by Krysinski** [comment]
Guys, I believe that  tiny part of this issue is a mod conflict against plugin (multiverse).
@radfast can you change postname to actual name if you think that is correct issue for github?
"[Bukkit server] Parachest interaction not being stopped by Worldguard etc" that is not problem really.
To understand me correctly please read http://forum.micdoodle8.com/index.php?threads/please-add-config-option-for-select-default-overworld-dimention.6437/
I am have some difficulty with the English language, sorry.

**Comment by DraksterAU** [comment]
So your saying that world guard blocks access to parachests on multiverse worlds, but not dim0?

How are you using a parachest on a multiverse world - the only way to land on them at the moment would be with a launch pad?

The link you have provided isn't working for me.
Really like your feature request though.

(Just trying to help ID the issue)

**Comment by Krysinski** [comment]
forum is offline from yesterday.
1. dim0 has special WG flag for global region wich prevent build, other dims havnt.
2. WG cant block interaction (using inventory) with parachest in restricted areas like dim0 or private regions in any dims. WG can not do it itself. So player can get his loot from parachest.
3. But player cant remove parachest from dim0 or from private regions in any dims. WG prevent to build. 
All of thats can ba configured with plugins WG and MGR.
So my dim0 is a special. Players must launching from dim11 as they do this now, and must landing on dim11 (or any other, must be configurable).
At this moment GC has this hidden option setting in defaul value dim0. I need to change this value to dim11 (or any other) for own risk.

**Comment by DraksterAU** [comment]
World guard hasn't got anything specific to dimension 0 at all on a cauldron server environment. All global flags can be used on any dimension... You are experiencing an issue with the way you have world guard configured... You need to set priorities and pass through correctly.
Please link a reference the the world guard documentation that states otherwise if I am wrong.
Unless the extra mod you are using does?

If you want players to land on dim 11 as "overworld"  you could switch the world folders around.... For now. So dim 0 becomes 11 and 11 becomes 0.

Players can land on any dimension using a launch controller with set frequencies if that Keeps your players happy though?

Would be nice for overworld dimension Id to be configurable. No real reason it couldn't be unless the developers don't like the idea.... Cauldron servers have many many over worlds haha

**Comment by Krysinski** [comment]
How can i planing a gameplay at first time i launch server? If i wish to make 10 overworld dims and specify world for "landing" or change flags? Swap dims is bad idea, beacose other mods and plugins has configs option to dimmention number too. GC has one for generation oil, AE has too for generate meteorits, and many more. I dont want tell you about all my ideas about gameplay process wich is needed to setup landing world)) 
If you are totally against this way to fix my issue then please close this issue. I try to find other people who can make ugly crutches for server(((

**Comment by DraksterAU** [comment]
The only reason why I suggested you switch the dimensions is because Ae2 and most other mods support config changes whereas Galacticraft doesn't in this case.

It is annoying... But it is possible to do it that way.

I'm not a dev - just trying to help you a bit is all.

@radfast  will probably look into this at some point. Don't take anything I say as what the GC Devs are thinking.

**Comment by radfast** [comment]
I am looking at how easy this is and whether it will break anything.

The last change I made to accommodate a not-totally-unrelated suggestion (changing dimension names seen by Bukkit from e.g. "DIM-28" to "Moon") ended up breaking space station access, including for Galacticraft add-ons.  So with hindsight I regret doing it.

My policy is _approximately_ this:
* Galacticraft supports large server owners, because we think multiplayer is a great way to play Galacticraft.
* We are aware that all large servers use Cauldron or a derivative, therefore we aim for everything to work properly in Cauldron, however there are some areas where that is difficult or really not Galacticraft's fault.  **Robotia** has been really great in pro-actively working with us so that one or two difficult issues have been solved in Thermos.
* We do not support individual Bukkit plugins.  That's getting too specific, and as I see it plugins come after mods - if a plugin is not working with a major mod, the plugin author ought to fix it.

Having said that, if there is an issue with a Bukkit plugin which can be solved quite easily without breaking something else in Galacticraft, and there is obvious demand for it from server owners, then I will look at it.

**Comment by radfast** [comment]
Next build will have a config setting which you can use **experimentally** to change this.

It works in my testing (rockets, celestial map, create space station, drop off space station).

If you encounter problems, set the config setting to its default, 0, and everything should be the same as in earlier Galacticraft builds.

The main issue you are likely to encounter is that existing Space Stations which players have created in your server world will still be orbiting the old dimension ID (0).  So those space stations will become inaccessible if you now change the Overworld to something like 4.  To fix that, you would need to go through each saved ```spacestation_#.dat``` file in the ```data``` folder and edit the ```homeplanet``` of the planet it orbits, using NBTExplorer.  Then, to update the player data (basically to prevent these players from being able to create a second space station orbiting around dimension 4) you would need to use the ```/ssnewowner``` command for each space station with its correct owner name.

**Comment by radfast** [comment]
I am not going to change the accessibility of Parachests - I mean, I am not going to add those to the Forge/Bukkit block opening protection system.

There's a good reason.  If **Player A** takes a rocket and lands on the Moon or Mars or Asteroids in a region which **Player B** has already claimed, then Player A will be unable to extract his own items from the Parachest if the Parachest is protected.

So if Parachests are protected by Bukkit plugins, then a griefer could claim the spot where somebody lands, and basically stop that player from being able to get his own rocket back.
