### ISSUE TITLE
Rocket owner

### ISSUE THREAD

**Issue by mad12345** [micdoodle8/Galacticraft#2147]
Please add config option to break down and use the rocket could only the player who placed it on launch pad (rocket owner). Its very important for multiplayer.

**Comment by Krysinski** [comment]
Its a great idea? i think about too.
Maybe do something like that for buggy (maybe use item "key" to drive it) and preven others from breaking down buggy with player inside.

**Comment by dj3520** [comment]
Suggestions/Feature Requests go on the forum please.

**Comment by radfast** [comment]
Read [notes for contributors](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md), you were given a link when you created this issue.

Closing this because suggestions belong on the forum, not here.

Once you've started a forum thread, I will say this:

"I don't see any need for this, if a player doesn't want his rocket griefed then he shouldn't leave it sitting out on a launchpad, seems obvious.

Also personally I'm also not very into plugins which make griefing 100% impossible, if people want to play like that then they might as well play single player.  If you're on a multiplayer server, you need to think about base protection even if the server has lots of rules."
