### ISSUE TITLE
Galacticraft 451 - Having to Nuke Entities on Space Station

### ISSUE THREAD

**Issue by LokeYourLord** [micdoodle8/Galacticraft#2148]
There seems to be something wrong my Space Station. Everytime i join the server, and go to my Space Station (after a server reboot), there are always the exact same amount of entities on my Space Station. I am nuking (with the LagFix mod its command /nukeents 100000) exactly 24547 entities. Not less, not more. Here a screenshot:
![2016-03-15_05 29 41](https://cloud.githubusercontent.com/assets/5807595/13767792/eaeb5eda-ea6e-11e5-892d-0488ba5c3c19.png)

Wasn't it said that blocks are counted as entities by Sealers so that they can tell the Oxygen to stay inside (don't get me wrong on this, something similar is what i read from radfast, but i cannot remember on what thread that was). Anyways, it seems a bit odd. It does not happen to the Mars Space Station, only to mine above Earth. And again, it's always the EXACT same amount of entities killed (which again most likely is something with the Java Garbage Collector (yes, that is an assumption, its what it seems like to me).

Also, when returning back to the Space Station after a while, the whole server gets a Timeout (and connecting doesn't work anymore). I have to reboot the server after that.

**Comment by radfast** [comment]
Your space station has blocks + machines from many mods, why do you think this is a Galacticraft issue?

No, blocks are not counted as entities.  Please do not comment on technical / internal coding issues unless you are a Java developer.

**Comment by Yanniclord** [comment]
I can tell its Galacticraft, because it first started happening after updating to 450. Before that, the lag existed, but i have never had this issue. Also, doesn't it seem odd at all that the entity amount is the exact same every time? I do not have any logs i could provide. The current fix i found is doing the opposite you recommended me previously, and that is to disable and remove all chunkloaders in the Space Station (the lag does not come back).

**Comment by dj3520** [comment]
I doubt you could figure out what those entities are perhaps?
I think turning on the debug in the config posts information about sealer checks, though it's been awhile since I've checked. If so it spits out how many blocks it looped through. Could you post the largest count here?

**Comment by Yanniclord** [comment]
Ye i can do that the next time this occurs. It is actually not every time, believe it or not, it seems to happen a bit random. Also, without OPIS, finding out what those entities are is harder than with OPIS. But i will take a look. I can also use TickProfiler, i take a look the next time.

**Comment by radfast** [comment]
Like I say, your Space Station is a large base filled with blocks and entities from many mods.  I don't so far see anything pointing to this being a Galacticraft issue.

It's really essential to know what those entities are.

Also maybe make a test base on a different planet with just a few machines and 1 chunkloader, and see what happens there.

**Comment by dj3520** [comment]
Better yet, make a new world and try with only Galacticraft, a mod with a chunkloader, and possibly worldedit (to help make a large base fast.)

@radfast I'm not sure about size, but my space station requires 4 sealers and I am not seeing lag from that.

**Comment by radfast** [comment]
> I'm not sure about size, but my space station requires 4 sealers and I am not seeing lag from that.

Thank you, I'm pleased to hear it :)

**Comment by Yanniclord** [comment]
My Space Station required more than a 100 sealers to be filled with air, so yep.

**Comment by radfast** [comment]
This may also be related to #2134.  I still need convincing that it's a Galacticraft issue.

**Comment by radfast** [comment]
Closing because I can't see any specific Galacticraft issue here.  The issue seems specific to the OP's modpack and build.  It could be created by any mod in the pack.

More generally, we are aware that some players have issues with (a) Oxygen Sealers and (b) Launch Controllers, especially in large builds.  These are not bugs _per se_, but are expected consequences of the way Minecraft loads and unloads chunks.  We are looking at ways we can work around this.  There are other issue reports for these issues so we do not need to keep this open.
