### ISSUE TITLE
Array Out Of Bounds Exception for BlockLandingPad after updating all other mods

### ISSUE THREAD

**Issue by blade1981m** [micdoodle8/Galacticraft#2150]
I tried updating all the mods in a modpack over the weekend and tested on single player without any problems and also verified that the server started back up with the updated mods. However when trying to connect to the server the client crashes with the crash log showing Array Out of Bounds Exception for BlockLandingPad. After getting the error I tried updating to the latest recommended release of galacticraft and still got the error and then updated to the newest release but also still got the same error.

[Crash Report](http://pastebin.com/6WWEdSNm)

**Comment by radfast** [comment]
I can't help you with this.  It's not a bug in the Galacticraft mod, it's because your world somehow got corrupted when you updated your mods.  That can sometimes happen due to block IDs changing when there are updates in mods (for example maybe one of your other mods added a new block).  Normally Forge should be able to handle that, but it's not 100% perfect.

You could try changing your mods back to the versions you had before the weekend, load the world, see if that fixes it.  Make backups of everything, because that could actually make things worse.

Otherwise you will probably have to reset the map in the chunk where this happened, I mean delete the region file.

**Comment by blade1981m** [comment]
Ok, thanks. I was thinking about just reverting back, I just wanted to post here in case it was something in galacticraft that was not working with newer versions of other mods. I am still pretty new at trying to understand the error logs, was there something in there that I missed that shows that so that I don't end up posting bugs on mods that just turn out to be something like this?

Thanks again.

**Comment by radfast** [comment]
You would need to be a Java developer to understand what that log is showing, and you would need to look at the source code of the mod for the top line shown in the log.  Sometimes it's easier.

In this one, the problem is that a BlockLandingPad has metadata "3".  That's impossible in Galacticraft, it can only be 0 or 1 if Galacticraft placed the block in the world.  Experience of seeing similar crashes tells me that it's a corrupted world save file due to a block ID changing.  This is confirmed by the fact that you updated other mods, which can cause that type of problem.
