### ISSUE TITLE
Ore spawning issue

### ISSUE THREAD

**Issue by jeridan** [micdoodle8/Galacticraft#2164]
GalacticraftCore-1.7-3.0.12.446
Galacticraft-Planets-1.7-3.0.12.446
MicdoodleCore-1.7-3.0.12.446

I have added minecraft and thermal foundation ores to the GC core.conf like listed below because the B:"Whitelist CoFHCore worldgen to generate its ores and lakes on planets" set to true does not generate any ores.  The issue is that the ore spawn in stone or in the case of minecraft quartz in netherrack.  I could swear that I have seen ore spawns on the moon and mars in the planet rock base, not overworld stone.  Is this intended or what am I doing wrong?

S:"Other mods ores for GC to generate on the Moon and planets" <
     minecraft:gold_ore
     minecraft:iron_ore
     minecraft:coal_ore
     minecraft:lapis_ore
     minecraft:diamond_ore
     minecraft:redstone_ore
     minecraft:emerald_ore
     minecraft:quartz_ore
     ThermalFoundation:Ore:0
     ThermalFoundation:Ore:1
     ThermalFoundation:Ore:2
     ThermalFoundation:Ore:3
     ThermalFoundation:Ore:4
     ThermalFoundation:Ore:5
     ThermalFoundation:Ore:6
     >

![2016-03-24_20 06 01](https://cloud.githubusercontent.com/assets/5779504/14035462/5dd6fff0-f1fc-11e5-93cf-d24c41d3cc7e.png)
![2016-03-24_20 05 32](https://cloud.githubusercontent.com/assets/5779504/14035461/5dd69326-f1fc-11e5-9282-9c69a7deae13.png)

**Comment by dj3520** [comment]
Galacticraft adds it's own copies of iron, copper, tin, aluminum and
silicon with the moon's dirt behind it. That is probably what you are
remembering.

**Comment by jeridan** [comment]
I went back and just allowed the default ore spawning for GC.  It would be really nice if other ore could spawn with the planet rock as a base, but that may be beyond minecrafts abilities.  Closing issue, thanks.

**Comment by dj3520** [comment]
No problem. I should mention that 446 is a bit behind the newest (454) The official downloads are down but there are some links at #2151 for now.

The issue is that ore textures are stored with the stone background already in place. You'll also see issues with mods that generate overworld ores and a texture pack that changes stone. Because the ores already have the stone background it's impossible to change what the background is unless something fancy is done. (IIRC Railcraft has some sort of system to get around this)
