### ISSUE TITLE
Arc Lamps light through solid block

### ISSUE THREAD

**Issue by TheTerrorByte** [micdoodle8/Galacticraft#2179]
This has been an issue with building a farm at my base. I use arc lamps to light up the area, and if build the farm above, the arc lamps would light up the inside of the farm, even if it is completely sealed up. I am not using any fullbright mod, as you can see by the blocklight level.

http://i.imgur.com/5QtQwe8.png
Inside
http://i.imgur.com/lY2fhXb.png
Outside. The ladder is sealed up to prevent light.

I decided to test this in creative.
http://i.imgur.com/44akv7V.png
Inside with arc lamp
http://i.imgur.com/rCt5K5m.png
Underneath
http://i.imgur.com/E5r8UDO.png
No arc lamp
http://i.imgur.com/GhmHqSb.png
Under it

**Comment by radfast** [comment]
Thanks for reporting.

It's because the Arc Lamp is coded to start its bright lighting from a position around 5 blocks in front of the spot where it's aimed.  In 1.7.10, it doesn't check to see if there are solid blocks between the lamp position and that spot 5 blocks in front.

To overcome this, you'd need to position the Arc Lamps a couple of blocks further away from the room you want to keep dark.

This issue is now fixed in Galacticraft 4.
