### ISSUE TITLE
Galacticcraft sets overworld provider as moon provider when Moon dimid registered by another mod

### ISSUE THREAD

**Issue by zmaster587** [micdoodle8/Galacticraft#2186]
Galacticcraft sets overworld provider as moon provider when Moon dimid registered by another mod.

https://github.com/zmaster587/AdvancedRocketry/issues/100 symtoms described by Furipu13 near the bottom.  
https://github.com/micdoodle8/Galacticraft/blob/b1a8ab3c72143254b4ca60117f917116f035f7a4/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L791
and 
https://github.com/micdoodle8/Galacticraft/blob/b1a8ab3c72143254b4ca60117f917116f035f7a4/src/main/java/micdoodle8/mods/galacticraft/core/GalacticraftCore.java#L560

somehow by the time the client gets the packet here:
https://github.com/micdoodle8/Galacticraft/blob/b1a8ab3c72143254b4ca60117f917116f035f7a4/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L1352
the result is is o = 0, and providerIndex = -28 (obtained using eclipse debugger in a single player world)
this reregisters the overworld with the moon's provider.

Final note: this is not a critical issue as it only occurs when somebody else goofs up anyway, but thought it ought to be reported nonetheless.

**Comment by radfast** [comment]
Thank you for reporting and thank you for that work with the debugger!

I think the issue is caused when there is a dimension ID conflict on the **server** (but not necessarily on the **client**).  5b75a3b client-side will spot any 0 in the data coming from the server and not attempt to reregister the Overworld with the [Moon/Mars/other] WorldProvider.
