### ISSUE TITLE
Plate crafting

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2196]
This is more suggestion than bug. I am having problems getting your machines automated with applied energistics. I've found semi-clog-free solutions using hoppers, but it jams up quickly. This means a trip back to overworld to debug and a trip back to whichever planet.

I was looking to see if you have a recommended method of crafting them with AE, or if I could request alternate recipes (oredict, etc). For example, ic2's Compressor and Metal Former machines.

**Comment by C1ffisme** [comment]
Please use the Galacticraft Forum for suggestions or feature requests.

**Comment by themechman** [comment]
I have been waiting several months for my acct on forums to be authenticated :/

**Comment by EzerArch** [comment]
@themechman, the forum crashed for about 2 months and its database/system got really screwed. What is your user name that you used to register?

**Comment by themechman** [comment]
Same one as here.

**Comment by EzerArch** [comment]
There is no user called themechman, unless the username is different. I think you could try to register with that name.

For instance, this [guy](https://forum.micdoodle8.com/index.php?members/pixelgamerx32.30211/) created an account but hadn't received the email confirmation. I could find this profile page and manually activated it.

Funnily, this another [guy](https://github.com/micdoodle8/Galacticraft/issues/2188#issuecomment-217677590) could not register because the forum was broken. After we had fixed the issue 18 days ago, he could register and received the email confirmation with no problem.

**Comment by themechman** [comment]
Try Stone Rhino

**Comment by EzerArch** [comment]
@themechman, done. Try now.

**Comment by themechman** [comment]
Thank you kindly! I will move this there.
