### ISSUE TITLE
Crash with gcraft and rotarycraft

### ISSUE THREAD

**Issue by hobnob11** [micdoodle8/Galacticraft#2211]
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/484

I know this is an old issue, but its the exact same problem im having now. every time anyone goes near any of the rotarycraft engines, this error happens and the server either crashes or freezes

**Comment by hobnob11** [comment]
I dont really understand how placing a gas engine down causes the crash, but i have come up with a "really bad" soultion that actually works. https://github.com/hobnob11/Galacticraft/commit/fa315ae9dd47aabf37631fcc98a85347011d9a32

Im sure that check is actualy important, and in no way should this be used as a permant fix. but if it helps you find the actual cause of the problem, what i did works. i compiled the mod and ran the server with it. no more crashing.

**Comment by hobnob11** [comment]
Confirmed still hapening on build 460, only happens in MP. rolled back to my fork for now. 
[fml-client-latest.txt](https://github.com/micdoodle8/Galacticraft/files/331486/fml-client-latest.txt)

**Comment by dj3520** [comment]
Those two crashes aren't the same. First one is due to `java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen` but the log you've included is because of `java.lang.IllegalStateException: Invalid machine item for render!`

Also, while I'm no expert at reading crash reports, I'm not seeing anything Galacticraft in the report.

**Comment by radfast** [comment]
The issue at Reika # 484 was fixed in Galacticraft on January 3, 2016.

I am not understanding how / why your fork fixes the issue, please provide a log / crash report showing the issue before your fork.

The client crash report you posted yesterday, looks to be a client side issue in Reika's mod, not a server side issue connected with Reika # 484.

If there is still any problem connected with Reika # 484 then I certainly want to fix it as a priority.  (Your fork simply comments out the relevant code ...)

**Comment by radfast** [comment]
Like I said there, the issue was fixed in ac14b2d - fixed in all Galacticraft 1.7.10 versions since build 406.

The later crash report posted by hobnob11 has no connection with Galacticraft, it's a RotaryCraft item rendering bug.

Closing due to no follow up in more than 6 months.
