### ISSUE TITLE
Astro Miner - GregTech

### ISSUE THREAD

**Issue by JasonMcRay** [micdoodle8/Galacticraft#2215]
I guess it is because GT ores are little bit different than other ores (GT ores are registered as tile entities instead of normal blocks) but Astro Miner when it hits any GT ore will stop, say in chat that it hit Deuterium Ore (nonsense, since it hits for example GT Iron Ore), turn around and will go back.

I understand that it is a hassle to make it compatible with GT, but due to this bug Astro Miner(with being so great and nice looking end game galacticraft miner, that can return to its base on command) is completely unusable in modpacks that have Gregtech installed. GregTech generates its ores in all dimensions (OW, Nether, End) and with an addon called GalacticGreg it also generates its ores on Moon/Mars/Asteroids.

GC: 3.0.12-460
GT: 5.09.21 (GT Source can be viewed here: https://github.com/Blood-Asp/GT5-Unofficial and related code to the GregTech Ores: https://github.com/Blood-Asp/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/blocks/GT_Block_Ores.java)

**Comment by radfast** [comment]
This is a known issue.

I have attempted to fix this, please try out new build 462 and tell me the outcome.

Note I'm not sure this will always mine the correct item, but this is pretty much the best I can do - GregTech ores are **extremely** non-standard.  I have programmed this so the AstroMiner should mine the same item as if the player uses a Fortune I pick on the GregTech block.  Let's hope ...

**Comment by JasonMcRay** [comment]
My friend tested it... Still same result. Stops and sends message that the path is blocked by Tritium Ore (even when the block was some other gt ore) :(

**Comment by JasonMcRay** [comment]
Wouldn't be possible to make it work same way as RC Tunnel bore? In the core it is the same, no? Digs straight 3x3

**Comment by radfast** [comment]
The AstroMiner is more sophisticated than a Tunnel Bore, it is programmed not to mine 'machine' blocks, that's to say anything with a `TileEntity`.  This stops the AstroMiner from accidentally mining up someone's base (it can maybe mine through the walls of a base, but it will stop mining when it encounters any machinery or chests).  It also stops it from destroying dungeon chests etc.

The problem here is that GregTech - unlike all other mods - makes its ore blocks have TileEntities.  That's difficult / impossible for other mods to work with, especially when there is no API function to access the ore blocks, and it is not an open source mod.

I will spent limited additional time to try to get this working, because I thought I had achieved it in 462, but if I can't get this working in a short amount of time then I am not going to bother, because I see the problem as fundamentally caused by the non-standard approach used in the other mod.

**Comment by JasonMcRay** [comment]
The GregTech source is open. https://github.com/Blood-Asp/GT5-Unofficial (for GT5).
Just a ping to @Blood-Asp if he would like to and would be able to help out :)

**Comment by radfast** [comment]
Thank you, I found the problem - different GregTech builds seem to have different mod ids (or else we were always using the wrong one, I don't know).

I have fixed and tested this is working now.  It will be in next Galacticraft build in the next couple of days.
