### ISSUE TITLE
schematics disapeared

### ISSUE THREAD

**Issue by Cronosus** [micdoodle8/Galacticraft#2218]
Hello
I have little broblem.
When player dies on my server, all his schematics disappears from his workbench

server difficulty 2
used GC: last (460)
addons: galaxyspace,blankplanet,moreplanets,extraplanets,pixelgalaxy

**Comment by radfast** [comment]
I cannot reproduce this problem in standard Galacticraft.

It may be caused by one of the add-ons.  Or a conflict between the add-ons.  They are not necessarily designed to work together.

Please test your server without add-ons (backup your world first, as deleting mods will damage your world) and see if the problem still occurs.

**Comment by radfast** [comment]
I also saw your post on issue #1085.

Is there anything else you can add about when this happens?  And do you have any Bukkit-type plugins which affect how a player respawns after death?

**Comment by Cronosus** [comment]
i use thermos on server
i tried everything to stop this, but nothing.. changed
i not found plugin or mod affecting respawn
