### ISSUE TITLE
Oxygen sealers causing chunk updates to slow down

### ISSUE THREAD

**Issue by 23Link89** [micdoodle8/Galacticraft#2238]
While I was creating my massive bio-dome, I placed down a large amount of sealers to finally seal the dome. After waiting a minute or so, I couldn't open my inventory, blocks wouldn't update, airlocks wouldn't open, etc. And checking my chunk updates showed that I was getting (most of the time) 0 chunk updates. I finally unsealed the dome and everything returned to normal. But thing is when I seal a small room it works just fine unlike my bio-dome. Might be related to #2228 

Bio-Dome
![bio dome](https://cloud.githubusercontent.com/assets/8294697/17166323/d70da670-539b-11e6-8b3e-cb5dea90f5a7.png)

Bio-Dome with F3 and it sealed
![0 chunk updates](https://cloud.githubusercontent.com/assets/8294697/17166345/15d0d742-539c-11e6-955d-0c92990f60ac.png)

**Comment by ktole1999** [comment]
you have all those sealers checking every few seconds on seal status. try changing the scan time so it doesnt scan as often. unless something else is causing it

**Comment by dj3520** [comment]
>try changing the scan time so it doesnt scan as often

Not sure that's an option in the config. Instead I'd try changing `Enable Sealed edge checks` in `core.conf` to `false`.

>you have all those sealers checking every few seconds on seal status

Actually they should see each other and act as one large sealer with only one "master" triggering the check.

Turning on `Enable Debug Messages=true` in `core.conf` prints sealer check info to the console (and therefore the logs.)

**Comment by ktole1999** [comment]
but will that flood the log with sealer checks? I was thinking there was a setting that determined how frequent the scan took place.

**Comment by dj3520** [comment]
>but will that flood the log with sealer checks

It would, but I was suggesting running the server with it on just for a bit to get some info and then turning it back off.

>I was thinking there was a setting that determined how frequent the scan took place.

IIRC there used to be in 1.6.4 something of the sort. A quick look through the configs just now and I'm not seeing it.

**Comment by ktole1999** [comment]
gotcha. so enable Sealed edge checks will turn off seal checks for good? gonna test that out.

**Comment by dj3520** [comment]
it won't turn off the seal checks but instead not trigger them on block updates

**Comment by 23Link89** [comment]
So disabling "Enable Sealed edge checks" seemed to fix the problem. But in console it shows that every four(ish) seconds it does a seal check with it enabled, I'm not sure if that's the problem. 

Here's what I get with "Enabled Sealed edge checks" disabled.

[14:52:12] [Server thread/INFO] [Galacticraft/]: Oxygen Sealer Check Completed at x-20 y65 z-8
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Sealed: false
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Loop Time taken: 0.002816ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Place Time taken: 0.107264ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Total Time taken: 0.11008ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Found: 1 sealers
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Looped through: 1 blocks
[14:52:12] [Server thread/INFO] [Galacticraft/]: Oxygen Sealer Check Completed at x-20 y65 z8
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Sealed: false
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Loop Time taken: 0.002816ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Place Time taken: 0.006656ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Total Time taken: 0.009472ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Found: 1 sealers
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Looped through: 1 blocks
[14:52:12] [Client thread/WARN] [FML/]: [Baubles API] Could not invoke baubles.common.lib.PlayerHandler method getPlayerBaubles
[14:52:12] [Client thread/WARN] [FML/]: [Baubles API] Could not invoke baubles.common.lib.PlayerHandler method getPlayerBaubles
[14:52:12] [Server thread/INFO] [Galacticraft/]: Oxygen Sealer Check Completed at x40 y69 z-2
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Sealed: true
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Loop Time taken: 11.290356ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Place Time taken: 1.840638ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Total Time taken: 13.130994ms
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Found: 23 sealers
[14:52:12] [Server thread/INFO] [Galacticraft/]:    Looped through: 27986 blocks

**Comment by EzerArch** [comment]
@23Link89, I had the same "Oxygen Sealer Check" message: https://github.com/micdoodle8/Galacticraft/issues/1978#issue-123770828

**Comment by 23Link89** [comment]
After playing with "Enabled Sealed edge checks" disabled, it seems I still get lag. But a lot less of lag.

**Comment by dj3520** [comment]
Are the machines near the outer corners of the dome also sealers? If they are I think they're too far away to "network" with the 23 I see around the tree, and since the ones around the tree provide enough to form a seal they'd be redundant.

The entire check shows as taking about 13ms, and if this is done every four seconds like you say, that's still just under 1tps, though I'm pretty sure oxygen checks are done in a separate thread, meaning they won't affect server performance. Right now the only thing I can think of is re-testing with vanilla glass blocks instead of what you're using (I don't know actually.)

Lastly I'd make sure you're running a newer version of Galacticraft, preferably the newest (atm is 462 [found here](https://ci.micdoodle8.com/job/Galacticraft-1.7/).)

**Comment by 23Link89** [comment]
Yes the machines on the outer dome are also sealers. And I counted the amount of sealers I have and I have a total of 23 in the room, just like the log says. I'm using a block called "Obsidian Glass" from Extrautilities in which I had to edit "core.cfg" so it'll see it as a sealable block. But it's using metadata from thickened glass which is also not sealable.

Long story short there are eleven different variants in the glass none of which are sealable in which they should be. "Obsidian Glass" is "ExtraUtilities:decorativeBlock2:5".
After updating to .426 it seems to have fixed the problem mostly with only a few lags spikes here and there from the sealers.
This is what I add to the config file at "External Sealable IDs"
        ExtraUtilities:decorativeBlock2:0
        ExtraUtilities:decorativeBlock2:1
        ExtraUtilities:decorativeBlock2:2
        ExtraUtilities:decorativeBlock2:3
        ExtraUtilities:decorativeBlock2:4
        ExtraUtilities:decorativeBlock2:5
        ExtraUtilities:decorativeBlock2:6
        ExtraUtilities:decorativeBlock2:7
        ExtraUtilities:decorativeBlock2:8
        ExtraUtilities:decorativeBlock2:9
        ExtraUtilities:decorativeBlock2:10
        ExtraUtilities:decorativeBlock2:11

**Comment by radfast** [comment]
I don't see any issue here, everything is working as intended.

You should always update to the latest version of Galacticraft before reporting issues.

For anyone else who comes across this issue report:
* sealer checks are not currently in a separate thread
* sealer checks do not take much time, the logs here show 13ms every 4 seconds, thats 0.003 of server time for a "massive bio-dome"
* what **does** take a lot of server time and cause lag is if you have a bad set up so that it is switching between sealed and unsealed often
* this can happen either if you don't have enough oxygen / power, or if you are moving around so much that crucial chunks for your power network are being unloaded, so there is temporarily no power (most likely to happen with a large base and a small chunk loading radius, especially if you don't respect chunk boundaries when building power systems) - machines from every mod will have problems if you build like this, but you notice the problems more with Oxygen Sealers because they are doing such a large task
