### ISSUE TITLE
minecraft wont launch because of the mod and every time I try to play it says MicdoodleCore should always be at the same version Severe issues can be caused from not updating when I have updated them to the same and latest versions please help

### ISSUE THREAD

**Issue by 720Dman** [micdoodle8/Galacticraft#2244]

**Comment by dj3520** [comment]
Please change title

**Comment by 720Dman** [comment]
no not unless you can help me

**Comment by dj3520** [comment]
Make sure MicDoodleCore is version 462 as well as Galacticraft.

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md

https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide

Make sure you have the correct Galacticraft versions - and only those versions - in your /mods folder.

Closing, because this is the user's setup, not a big in the mod.
