### ISSUE TITLE
Launch Controller causes Oxygen Storage Modules to create huge TPS drops

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2249]
Related to #2129 

(**_EDIT:_** Skip to https://github.com/micdoodle8/Galacticraft/issues/2249#issuecomment-245832746 for a better visualization of the problem)

I went AFK in the space station dimension for 15 minutes. I got 421.0 ms/T. Restarting won't fix it. Normally all I have to do is to visit the Overworld for a few seconds, the mean tick time goes down to 7.00 ms/T, and then go back to the SS for another 5-10 minutes play. 

But this time was different. The lag kept building up no stop even visiting the OW:
![2016-08-14_17 59 35](https://cloud.githubusercontent.com/assets/6743303/17652030/447f2cc2-6249-11e6-84ec-58e65ff9c7b8.png)

After restarting the game:
![2016-08-14_18 09 41](https://cloud.githubusercontent.com/assets/6743303/17652090/5c4f269e-624a-11e6-8654-c1bcfc2f72f7.png)

**Comment by EzerArch** [comment]
Now THIS IS a game-breaking issue. Once the game starts lagging in the SS dim (you can tell that by looking at the sun), you can no longer use the rocket. You'll get stuck y=1200. You can't dismount the rocket, you can't break it, restarting the game won't help. I had to kill myself. 

![2016-08-21_17 25 59](https://cloud.githubusercontent.com/assets/6743303/17839648/81972486-67c4-11e6-81aa-056b43affb32.png)

**Comment by dj3520** [comment]
Still confused why I've never had this issue.

**Comment by EzerArch** [comment]
> Still confused why I've never had this issue.

Does your space station have a sealer at 0,64,0? My OSS has a sealer at that very coord and keeps failing even if it is connected to infinite supply of oxygen and energy.

Another detail: in fact, I don't need just to be in the OSS dim to cause lag. While I was messing around with [satellites for MCHeli](https://twitter.com/EzerArch/status/769041818617077760), I was very far away from the space station structure, and had been there for about 1 hour, no lag at all. I'm starting to think it is something in my space station that is causing the lag.

**Comment by EzerArch** [comment]
> Can now confirm it is not the Sealer causing issues.

I'm 99.9% sure it's the Oxygen Storage Module to blame.

Another test:

1. I switched off all sealers and removed the sealer and the oxygen storage in the arrival room (0,64,0), the lag went down from 120,000 ms to 5 ms.

2. Then switched back on all the sealers, except I didn't put back the the sealer and the oxygen storage in the arrival room. The sealers are now directly connected to their suppliers (solar panels and ox. collectors). The mean tick time (MTT) still as low as 4 ms.
![2016-09-06](https://cloud.githubusercontent.com/assets/6743303/18326461/3ba8d2c0-751c-11e6-9d2e-99f096495430.png)

3. Put a Mekanism Energy cube and a sealer in the arrival room. Left my MC running for 10 hs straight. MTT still 4.2 ms.
![2016-09-07_11 39 00](https://cloud.githubusercontent.com/assets/6743303/18326693/74cc100c-751d-11e6-8124-f9e0950af137.png)

4. Put an Oxygen Storage Module between the arrival room's sealer and the oxygen collectors. 2 hours later, MTT = 233 ms.
![2016-09-07](https://cloud.githubusercontent.com/assets/6743303/18326754/b9929f3a-751d-11e6-8d34-c21584e081f7.png)
![2016-09-07](https://cloud.githubusercontent.com/assets/6743303/18327388/a441dbb6-7520-11e6-9b4a-f24aac15cf3b.png)

5. Removed the Oxygen Storage Module. After 30 minutes, a whopping MTT of 2,148.00 ms.
![2016-09-07_17 32 38](https://cloud.githubusercontent.com/assets/6743303/18327596/ae91eec0-7521-11e6-96a6-37d96f257ae5.png)

(EDITING...)

**Comment by EzerArch** [comment]
I think I managed to isolate the problem actually is and figure out a workaround: oxygen storage modules cannot be placed in a launch controller's loaded chunk.

I noticed the problem had gone after I removed the launch controller from the chunk where the sealer and the oxygen storage module were located in. I had all working with 4-5 ms, until now when I put back the launch controller and the mean tick time skyrocket from 6 ms to 250 ms in 5 minutes right before my eyes.
![2016-09-09_03 14 24](https://cloud.githubusercontent.com/assets/6743303/18377441/9e2b85d8-763d-11e6-804b-64d189511e87.png)

![2016-09-09_03 17 08](https://cloud.githubusercontent.com/assets/6743303/18377433/9718eec0-763d-11e6-9ba8-ba9d248476f8.png)

Workaround: don't place oxygen storage module and a launch controller in a the same chunk.

**Comment by radfast** [comment]
Possibly connected with #2385 

My theory (not yet tested) is somehow certain tile entities located in the same chunk as the Launch Controller are multiplying to huge numbers on the server, after the server has been running for some time.

**Comment by radfast** [comment]
@EzerArch thank you for isolating this to the OSM.  I'm not convinced it's that - that is a fairly simple machine - but it could more generally be "anything" with a TileEntity in the same chunk as a Launch Controller.

A couple of questions please:

1.  When you said your server was running for 10 hours, was that with you playing on it, moving around a lot (so that chunks load and unload) and transferring between dimensions?   Or was that literally the server just running with no player logged in?

2.  What type of server are you using?  + which Forge version?

**Comment by EzerArch** [comment]
>  I'm not convinced it's that.

I've changed my mind since when I opened this issue because I've experienced the same lag in many other different situations, but still all outside the Overworld. E.g., the simple fact of standing still on Mars. 

> When you said your server was running for 10 hours (...)

I left the game running overnight and went to sleep. The player had been standing still until I woke up and "oh, it's still here". The computer was on maintenance mode so it didn't shut down. It wasn't on a server, it was on single player with no other players.

(EDITING....)

**Comment by radfast** [comment]
>  I've experienced the same lag in many other different situations

Was a Launch Controller nearby, in all these situations?
What about Oxygen Sealers nearby?

We have maybe 10 open issues involving these two things, reporting various TPS / lag / out of memory issues.  There's obviously something going on here.  But it's very hard for me to see what it is, because these items are working perfectly in my own test builds.

**Comment by EzerArch** [comment]
> Was a Launch Controller nearby, in all these situations? What about Oxygen Sealers nearby?

It was, for both questions.

> Are you able to reproduce this problem in the current version of Galacticraft? (...) If you are able to reproduce it, please enable debug logging on the server and have a look at the message "Number of launch controllers updating each tick" - is that number staying steady?

Sure. I can also pack my world save with a minimal install (mods, config, etc) and send you when the lag gets really bad. Does it help? :)

**Comment by radfast** [comment]
> Sure. I can also pack my world save with a minimal install (mods, config, etc) and send you when the lag gets really bad. Does it help? :)

Yes please, would be awesome.  If we see a difference in lag after that, it must be due to machine / OS / Java / JVM settings...  I think it's possible!  Garbage Collection in Java is a major cause of lag spikes.  (You can see the Garbage Collector working when your memory usage in F3 suddenly drops by 200 MB.  I always find articles about how the Garbage Collector works very confusing, because it is normally abbreviated to GC ...)

**Comment by radfast** [comment]
Hi Ez, please see what I wrote on other related issues:
------

Anyone affected by this or similar issues:

My current **theory** is it's related to this combination of factors:
* players leaving and returning to the dimension in rockets or other ways (teleport, nether portals, etc)
* the dimension has a chunkloader (GC Launch Controller,  Railcraft Anchor, ChickenChunks Chunk Loader, Witchery shelf etc)
* when all players leave the dimension, the chunks _outside_ the chunkloaded area are _supposed_ to be unloaded
* the player has built machinery / wires / pipes / itemducts which crosses the boundary from the loaded chunks to the chunks which are _supposed_ to be unloaded
* another mod - most likely a wiring / pipes / itemducts mod, so look at Mekanism-EnderIO-Thermal Expansion-IC2 etc... - wrongly reloads, over and over, those chunks which are supposed to be unloaded
* tile entities somehow get duplicated in the chunks which are being force loaded and unloaded over and over

This explains why the issue only happens / or gets worse when the player leaves the dimension.

-----

I still need help from you guys so that I can actually see this issue happening on my test systems.  Especially, I need to know the smallest combination of mods and build which can make this occur.

Anyone who sees this issue in future, please:
1.  Provide a full mod list, highlighting wire / cable / pipe / itemduct mods
2.  Provide screenshots of the base which is lagging, with chunk boundaries shown
3.  Especially in your screenshots show any chunkloaded chunks, and the connections they have with the chunks next to them
4.  Try to force the problem to occur, by all players taking a rocket or teleporting to another dimension, and leaving the base unoccupied (but still loaded by the chunkloader)

**Comment by radfast** [comment]
I think you're my best hope at fixing this, as your build is cleaner and easier for me to follow  :)

**Comment by EzerArch** [comment]
> I think you're my best hope at fixing this, as your build is cleaner and easier for me to follow :)

Oh, I feel important. 🥉 I managed to generate enough lag.

![2017-03-08_07 51 39](https://cloud.githubusercontent.com/assets/6743303/23701182/73661992-03d4-11e7-87fd-d2ff13b5ed2a.png)

I'm going to send you the package once I get around to.

**Comment by EzerArch** [comment]
Done. File sent via forum.

**Comment by radfast** [comment]
Thank you, I'll take a look :)

**Comment by radfast** [comment]
On investigation, this is an issue in the JustAFewFish mod.  It seems to be spawning way too many fish in the Overworld oceans, when the player is away from the Overworld.

No connection with Galacticraft.

**Comment by EzerArch** [comment]
Just to let you know: I've posted a bug report [on JAFF topic](reported http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2508671-just-a-few-fish?comment=232).

Thank you. :)

**Comment by radfast** [comment]
Did whitelisting only still water fix it?

That ravine was very deep, maybe 30-40 blocks descent all flowing water from the ocean.  And there was other flowing water nearby (a waterfall flowing into the ocean?)

**Comment by EzerArch** [comment]
I did both: changed the config and sealed that ravine.

![2017-03-15_22 22 48](https://cloud.githubusercontent.com/assets/6743303/23977828/5108634a-09cf-11e7-8cd9-052174554c8c.png)

![2017-03-15_02 59 00](https://cloud.githubusercontent.com/assets/6743303/23977283/14f30ae8-09cc-11e7-969b-bea329b24077.png)

:)

**Comment by EzerArch** [comment]
_**(Not a bug report) To whom it may concern.**_

> On investigation, this is an issue in the JustAFewFish mod. It seems to be spawning way too many Cod fish in the Overworld oceans, when the player is away from the Overworld.

>

It seems there was something else causing the huge lag. Even with the white-list solution, the lag ended building up after almost a hour rendering the game unplayable. Then I discovered this in the _jaff.cfg_:
```
general {
    # If this is true, alternate code will run to attempt to fix a bug
    # with optifine. Note that this code may cause issues and crashes,
    # so disable it if anything bad is happening. [default: true]
    B:"Attempt Optifine Fix"=true
}
```
Set it to false. It did wonders. ❤️
