### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by runescapejon** [micdoodle8/Galacticraft#2250]
Hello my server keep crashing randomly is there a way to fix it here the crash report 
http://pastebin.com/FR34YXde

**Comment by SportsFan10** [comment]
Just a Couple things:
-Please list your forge and galacticraft versions as it is needed by the mod authors in order to help

Now I don't know much, but it appears that the crash is coming from the MineFactoryReloaded Grinder, and a Galcticraft entity, the Slimeling.  

Try and further explain what you were doing with these two things.  This will also help the mod authors in solving the issue.  (BTW, I am not a mod author/dev.  Just trying to help out a bit as I love this mod.)

**Comment by runescapejon** [comment]
hmm thanks you for trying to help, but the Forge version an dthe Galacticcraft versions are in the crash report

**Comment by radfast** [comment]
I see what you're doing, @runescapejon.  You can't hide.

Your player is:

* killing innocent Slimelings in a MFR Grinder
* generating Slimelings (I guess with a MFR Spawner) which are carrying an inventory bag with items in it

Looks like this is an attempt at a kind of dupe exploit.  The player wants to duplicate the items in the Slimeling inventory bag, over and over.

Nice.  I hope you kicked this guy from your server!

But yes, Galacticraft will crash if this happens, we did not build in functionality for duplicated Slimelings.  (The problem is each Slimeling should have a player who is its 'owner')

I will fix this now.

**Comment by radfast** [comment]
The crash is fixed.
The potential dupe is also fixed.

This will be in GC version 3.0.12.467 and later

For earlier versions, servers with MFR and Galacticraft are advised to blacklist Slimelings from spawning in the Auto-Spawner (this can be set in MFR configs).  It's the same for other creatures which can carry items - for example Luggage, Pech, Kobold.
