### ISSUE TITLE
Can't connect in multiplayer

### ISSUE THREAD

**Issue by THEJean-Kevin** [micdoodle8/Galacticraft#2258]
hello everyone, 

I have a problem with you mod. let me explain, I used galacticraft 1.7-3.0.12.375 and I had no problem. I wanted to add moreplanet so I updated galacticraft, and since, nobody can reach the server, they have this error message no opengl context found in the current thread. So I went to the old version and it works again.

This is the last log when we have the problem : http://pastebin.com/caGMbecP

**Comment by dj3520** [comment]
'The client has sent too many requests within a certain amount of time'

Also many, many texture errors.

**Comment by radfast** [comment]
This seems to be an installation or setup issue generally.  That startup log is full of many errors from many mods, files not found, textures not found, can't connect to download sites, etc.  

To fix this type of issue, you need to:
1.  take **all** mods out of your mods folder
2.  make sure Minecraft with Forge is starting properly and players can connect (no mods, except Forge and FML)
3.  now start adding back mods one by one, and keep checking that it works

Fix your setup.  If you still have a problem and it is caused by **Galacticraft** please re-open this thread.
