### ISSUE TITLE
Machines are switched off but still operate and drain power.

### ISSUE THREAD

**Issue by MeSoLost** [micdoodle8/Galacticraft#2260]
I have levers on some of my oxygen collectors at my main earth base so i can shut them off to save on the power drain but even when off they continue to drain power and produce oxygen -.- The interface even says the machine is off but it still continues to work as if it were still enabled.\

Pictures how collectors off and still draining power, oxygen liquefier is setup to pull continuous oxygen and still the machines are generating even though they are clearly set to off.

![2016-09-01_20 43 15](https://cloud.githubusercontent.com/assets/20606168/18192232/3fb268ca-7087-11e6-82b7-61e2feadd816.png)
![2016-09-01_20 43 20](https://cloud.githubusercontent.com/assets/20606168/18192235/3fb6190c-7087-11e6-878e-6f12db05558b.png)
![2016-09-01_20 43 48](https://cloud.githubusercontent.com/assets/20606168/18192233/3fb37774-7087-11e6-8431-15fb7b6afa83.png)
![2016-09-01_20 46 29](https://cloud.githubusercontent.com/assets/20606168/18192236/3fb7c9d2-7087-11e6-8fc5-ba4d4585b1c6.png)
![2016-09-01_20 51 17](https://cloud.githubusercontent.com/assets/20606168/18192234/3fb6111e-7087-11e6-873b-673e7f237158.png)

**Comment by C1ffisme** [comment]
I also have this problem, it happens when a machine is on but idle. (e.g, a Fuel Loader without any fuel or rocket.)

**Comment by dj3520** [comment]
Redstone control was (unfortunately) reverted in build 449 or so.

**Comment by Barhandar** [comment]
In the meantime, given you're using Immersive Engineering, you can use Breaker Switch to shut off the power to them, instead.

**Comment by C1ffisme** [comment]
@dj3520 Will we see a return for Redstone Control, or is it gone for good? (Just out of interest.)

**Comment by dj3520** [comment]
@C1ffisme That's not something I can say with certainty since it's not something I can't control. I'm all for the redstone control since it allows for automated setups, but it was taken out due to possible chunk loading. I'm not sure what methods were used to implement the redstone control, but I think with all of the mods out there that do something of this sort, there should be a solution out there.

Also it appears the code wasn't completely disabled since some machines still respond to redstone, just not actually shutting down (show DISABLED in GUI)

**Comment by radfast** [comment]
This is a GUI problem, the GUIs are still showing the machines as "off", even though **Oxygen Sealer** and **Oxygen Collector** currently have no redstone control.

If you want to switch these machines off, currently the only way is to cut off their energy. Either break the wires or use a Breaker Switch (or other electricity control methods?)

I am thinking about introducing Galacticraft's own version of the Breaker Switch, that could be quite nice.

**Comment by dj3520** [comment]
>I am thinking about introducing Galacticraft's own version of the Breaker Switch, that could be quite nice.

A person like me likes the redstone control so much I've forked the mod just to add it back in.

**Comment by radfast** [comment]
Redstone control will make some bases very laggy, due to bad coding in vanilla Minecraft.  There's not much we can do about that.  That's why redstone control was disabled for Oxygen Collectors and Oxygen Sealers (because many space bases will have many of those machines, quite spread out).

The best solution is just to have enough power.  Maybe we need a Tier 3 energy source in Galacticraft, I'll talk to micdoodle8 about some ideas for that.

**Comment by radfast** [comment]
The machine status (off / idle / processing) should be correctly shown in all these machines, from next version 3.0.12.467.  If there are any similar problems in future - machine showing as working when it shouldn't be - please re-open this.

**Comment by dj3520** [comment]
>Redstone control will make some bases very laggy

I haven't personally seen this myself, though I'm not saying other people might not have this issue.
