### ISSUE TITLE
Evolved Skeletons don't drop bones

### ISSUE THREAD

**Issue by benknight04861** [micdoodle8/Galacticraft#2263]
Using GC mods version 1.7-3.0.12.463 (and at least a few versions before it too for what that's worth) evolved skeletons do not drop bones when they die/are killed.  Hadn't particularly noticed this before the Asteroid Challenge because you rarely need bones in space when you've started your game on the OW, but with the Challenge bone meal is _really_ important for improving the odds of survival.

To reproduce:
1 - Start any world.
2 - Use a spawn egg to place a bunch of Evolved Skeletons.
3 - Wait for them to burn to death and notice lots of arrows but no bones.

Why I think this is a bug:
1 - The GC wiki lists Bones as a drop of Evolved Skeletons.
2 - The Asteroid Challenge is insanely difficult without bone meal.

**Comment by radfast** [comment]
Thank you.  Great issue report, nicely expressed.  Sorry we have taken a long time to get to this, I have been away for many months due to real life issues.

You are right, it is intended for Evolved Skeletons to be able to drop bones as a standard drop.  This is fixed from next build 3.0.12.467.  (Probably too late to help you, but it will help someone else.)

If you have any other feedback on Asteroid Challenge, I'd be happy to hear it.  I have played a couple of games in it for several hours myself, and found it fun and challenging.
* The main issue I still don't like is the darkness (but that maybe depends on your monitor).
*  It's also too easy to fall if you just use 1 block wide walkways between asteroids, because any mob can knock you off.  We need to look at some kind ofwalkway / rope system you can't fall off of.  [Walkways](https://wiki.micdoodle8.com/wiki/Walkway) are too costly, they're a rich man's toy, and they don't stop you falling off.
