### ISSUE TITLE
Titanium ingot unlocalized name duplicate

### ISSUE THREAD

**Issue by Wyrrrd** [micdoodle8/Galacticraft#2270]
Hi, uncommon request for 1.7.10 here:

I am trying to change the name and behaviour of Galacticraft's Titanium Ingot with Minetweaker.
Strangely the QuantumFlux Ingot responds to every name change I apply to the GC ingot, while the GC ingot always takes the ore dictionary entry of the QF ingot.

Critical mod setup:
- Galacticraft 3.0.12
- QuantumFlux 1.3.4
- Minetweaker 3.0.10B

I am not sure where this is coming from (my suggestion is, they have the same unlocalized name), so I am filing issues on QF and Minetweaker, too.

[QuantumFlux Issue](https://github.com/joekaiser/QuantumFlux/issues/111)
[Minetweaker Issue](https://github.com/stanhebben/MineTweaker3/issues/376)

Thanks in advance,
Wyrrrd

![unbenannt](https://cloud.githubusercontent.com/assets/11527443/18447132/a0a67846-7925-11e6-80cc-7dcea20c8675.png)

**Comment by micdoodle8** [comment]
Hey, were you able to remove the other ore dictionary entry using MineTweaker? 

I'm not sure how I would fix this problem on my end, other than to break the "ingotName" convention in the ore dictionary.

**Comment by Wyrrrd** [comment]
I tracked down the issue a bit, it is not a problem in the ore dictionary. Actually I can remove the entry, but the same unlocalized name of the ingots from GC and QF causes the other ingot to apply the removal too. Same for additions.
This was verified to be true by stanhebben, MineTweaker uses these unlocalized names to distinguish between similar items.

**Comment by radfast** [comment]
Right, so the **real** problem here is:

1.  Another mod, QuantumFlux, has an `ingotTitanium` which is easier for players to obtain than Galacticraft Titanium, but accepted in Galacticraft recipes because OreDictionary says they are the same

2.  MineTweaker does not provide functionality to disable just one of the `ingotTitanium` because it works using unlocalised name _without the modname: prefix_ (seems weird to miss off the modname prefix)

I don't think we want to change the ingotTitanium name, that might break other stuff.

What we can _maybe_ do is add a config to Galacticraft so that it accepts only its _own_ space metals in its recipes and not oredict equivalents - best to cover all of them (Meteoric Iron, Desh, Titanium) I think.  Hmm, maybe that should even be the _default_ behaviour, as these recipes are intended to reflect the planets you have visited.

**Comment by radfast** [comment]
This issue is fixed from next version 3.0.12.467
