### ISSUE TITLE
I can't launch to the Moon

### ISSUE THREAD

**Issue by Rolys2004** [micdoodle8/Galacticraft#2290]
Sorry my english is not so whell. My gc version is 1.7-3.0.12.463, if I press on launch nothing happens.
I play with a big modpack I do not know what is the reason. 

Can anybody help me please ? :-)

**Comment by dj3520** [comment]
* Is the rocket fully fueled?
* Are you attempting to launch from somewhere besides the overworld? (DIM0)

**Comment by Rolys2004** [comment]
No I start in the overworld and in the rocket is 100% fuel
And if I start with a tier 2 rocket minecraft crashes

**Comment by Brycey92** [comment]
Are you on a server that this is happening? I had this issue for a while before we found the fix. If you want, I can try to find the old github issue with it.

**Comment by radfast** [comment]
1. Do you have standard Minecraft keyboard settings, or did you change something?  Normally it's SPACE to launch.

2.  **Please provide the crash report for the tier 2 rocket**

**Comment by radfast** [comment]
@Rolys2004 it would be really good to get that crash report.

I know this was from October 2016, but maybe you still have it in `.minecraft/crash-reports` - look for `crash-2016-10-16...`

**Comment by radfast** [comment]
It's also possible this is a localization / button position issue similar to #2070.

Please provide a screenshot of the Launch button.

**Comment by radfast** [comment]
Closing due to no response.  I can't troubleshoot this without the missing info and crash report!  It sounds like something is wrong with the whole setup ... could be anything from a bad install, bad configs, mod conflict, localization issue, or a rare + previously unknown bug in Galacticraft, I have no way to know...

Please re-open if it happens again or if any more info becomes available.

In general, it's also a **very good idea** to update to the latest Galacticraft version.
