### ISSUE TITLE
Launch pad dummy block not updated

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2292]
![2559-10-16_23 25 07](https://cloud.githubusercontent.com/assets/6128413/19418907/eee44000-93f7-11e6-907d-dd266848483a.png)
![2559-10-16_23 25 26](https://cloud.githubusercontent.com/assets/6128413/19418908/eee9cc6e-93f7-11e6-8417-6a6140437bb2.png)

Tested on dev environment (Eclipse).

**Comment by SteveKunG** [comment]
![2560-04-12_08 03 41](https://cloud.githubusercontent.com/assets/6128413/24936807/ae54d9ec-1f56-11e7-9ca6-cf1dd301f125.png)

Please re-open this issue, Its back again. (Dev test)

**Comment by radfast** [comment]
probably caused by my commit today https://github.com/micdoodle8/Galacticraft/commit/407ab16aa6b442b36742c33a4f2b37939c3f89bd

this is [WIP] - I will continue looking at this tomorrow

**Comment by radfast** [comment]
Now fixed, thank you.

The root cause of this is in Minecraft 1.8.9+:
 if a ```TileEntity.update()``` sets a new block ```ITileEntityProvider``` in a ```BlockPos pos``` where there was an existing ```ITileEntityProvider```, the **new** tileEntity will be removed from the world, immediately after the end of the ```.update()``` tick.  (Randomly.  It depends if the *old* tileEntity in that position was already iterated in ```World.updateEntities()``` or not.)

See:
>
                   this.getChunkFromBlockCoords(tileentity.getPos()).removeTileEntity(tileentity.getPos());

in ```World.updateEntities()```
