### ISSUE TITLE
[1.7.10] GCCoreOxygenSuffocationEvent.Pre is not cancelling the invalid oxygen HUD message

### ISSUE THREAD

**Issue by benfah** [micdoodle8/Galacticraft#2319]
Galacticraft version: 3.0.12.463

`
@SubscribeEvent
public void onOxygenSuffocation(GCCoreOxygenSuffocationEvent.Pre event)
{
	event.setCanceled(true);
}
`
I don't take damage as expected, but the "Warning! Invalid Oxygen Setup" message shows up anyway.
The Javadoc of GCCoreOxygenSuffocationEvent.Pre states:

> IF THE PRE EVENT IS CANCELED, THE "WARNING: OXYGEN SETUP INVALID!" HUD MESSAGE WILL NOT BE SHOWN 

![2016-11-08_15 56 53](https://cloud.githubusercontent.com/assets/11573260/20103913/15fad4c0-a5cc-11e6-97ff-9461d44e3b78.png)

**Comment by radfast** [comment]
Thanks, I think this should be fixed by the commit I just made, but will need you to test please.

The issue was that the HUD message is shown all the time when there is no oxygen, but player damage from a suffocation event is only tested in some ticks (the ticks when a player should take damage from suffocation).

The GCCoreOxygenSuffocationEvent.Pre event will now be triggered every tick, not only in the ticks when a player takes damage.

As before the GCCoreOxygenSuffocationEvent.Post event will still only be triggered in the ticks when a player actually takes damage from lack of oxygen.
