### ISSUE TITLE
Kicked for "Flying is not enabled in this server" using Grapple Hook

### ISSUE THREAD

**Issue by altrisi** [micdoodle8/Galacticraft#2348]
If you are in a server (in singleplayer works well) and you use a Grapple Hook (for example in Asteroids) for a while, you will be kicked for "Flying is not enabled in this server". I think that event can be cancelled if the player is using the Grapple Hook in that moment.

## Other mods: _NotEnoughItems-1.7.10-1.0.5.120_ (with _CodeChickenCore-1.7.10-1.0.7.47_)

**Comment by dj3520** [comment]
I've managed to see this myself by going to the moon and getting hit by an evolved skeleton's arrows on purpose. Each arrow pushes be back, and if at the right angle, upwards consistently, keeping me almost in place. Then I get kicked for flying.
A short term fix is changing the server.properties to `allow-flight=false` Any long term fixes will more than likely be for a newer minecraft version since development has become focused there.

**Comment by altrisi** [comment]
Yes, I know I can change that setting, but I also know that the kick event can be cancelled by the mod.

**Comment by xarses** [comment]
Same problem with the Jetpack (and the grapple) on 1.7-3.0.12.462

It happens mostly when you perform maneuvers in such a way that you don't start raising or falling within a specific threshold (~2sec)

> A short term fix is changing the server.properties to allow-flight=false Any long term fixes will more than likely be for a newer minecraft version since development has become focused there.

That will also allow client side flight hacking.

The protection is avoided by IC2, Gravitation Suite, Ender IO, Erebus, Extra Utilities, Adventurer's Amulets

**Comment by radfast** [comment]
> The protection is avoided by IC2, Gravitation Suite, Ender IO, Erebus, Extra Utilities, Adventurer's Amulets

and by [Galacticraft](https://github.com/micdoodle8/Galacticraft/blob/23a24fb4cea52d0848e233d9451f47e6131064ff/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L1314).  Please search the repository.

**Comment by radfast** [comment]
This is fixed in next 1.7.10 release version 3.0.12.466
