### ISSUE TITLE
Duplication Gitch with slimeling

### ISSUE THREAD

**Issue by HeyZeer0** [micdoodle8/Galacticraft#2354]
Steps to reproduce:
1. Open a slimeling with a inventory upgrade inside 
2. Put any item in the Inventory 
3. Move the mouse to the item slot and press Q key. The item will be dropped but not actually removed from the container, so you can drop more and more. 

Video Demo:
https://youtu.be/kiY9UBR9cb4

Mod: GalacticraftCore-1.7-3.0.12.463
Forge: 1614

**Comment by radfast** [comment]
thank you.  I've been away for a long time, now back (I hope...).  I will try to look at this as a priority.

**Comment by radfast** [comment]
This will be fixed in the next version 3.0.12.466.

Thank you for bringing it to our attention.  I don't see it as a major risk for servers, as a player would have to travel to Mars to have a pet Slimeling.  Realistically, in standard gamemodes, only a small minority of players ever progress that far.
