### ISSUE TITLE
[1.7.10] Respect WorldBorder plugin borders

### ISSUE THREAD

**Issue by vadimyer** [micdoodle8/Galacticraft#2392]
Hey there,

I wonder if this is possible to rewrite teleportation system (looking for coordinates to land on) respecting WorldBorder borders? This would be really helpful.

Take GC with some planets addon, there's lot of planets thus lots of disk space needed. WorldBorder solves the problem with space completely, but you need to have planets and Overworld the same size, otherwise if the Overworld is e.g. 5000x5000 and the Moon is 1000x1000, when you try to land on moon you might end up at borders with your rocket flying outside the borders where you can't catch it.

Is it possible?

**Comment by dj3520** [comment]
Fairly certain that the moon lander descent always starts at 0,0

**Comment by vadimyer** [comment]
Hm, we've always had landing coords set to similar departure coords from Overworld, maybe because it's Thermos/Cauldron idk.

**Comment by EzerArch** [comment]
> Fairly certain that the moon lander descent always starts at 0,0

Always, no. This happens if you're using creative dimensiontp command. If it's a normal lift-off/landing, this is more precise:
> We've always had landing coords set to similar departure coords from Overworld.

**Comment by radfast** [comment]
It's not possible.

Bukkit plugins are loaded _after_ Galacticraft so we have no way to see what the worldborder is.

Plus, your theories about disk space are not correct.  Disk space is only used by map chunks which a player has visited.  Unless you have players visiting all parts of all your planets, Galacticraft will not increase the disk space needed for the server by much.

Presumably, if a player teleports to a planet to a location outside the worldborder, the plugin will quickly move him back inside the borders?

**Comment by radfast** [comment]
>  Someone, besides micdoodle8 (because he's focused on 1.8.9), needs to code some kind of "travel ratio defined via server cfg" and submit the change so we can merge it for the next release.

Hmm, I'm thinking about it some more, maybe we can do this config very easily - it can be kind of like how Nether Portals work (1:8 ratio for them).

@vadimyer :  I strongly support owners of big servers (30+ players online simultaneously) running modpacks.  It's a personal goal for me to have Galacticraft make life **easier and better** for owners of these servers.  Please do keep reporting issues you have and I will look at them.

But, like I said earlier, Galacticraft (+ its plugins) does not hurt servers by having a lot of planets, unless you have so many players that they visit all parts of all planets.  Galacticraft actually **helps** server performance in some ways.  With a busy server, it's easier for the server to split the players between different dimensions.  That's because game tick time for a few of the slowest tiles / entities increases in proportion to N^ 2 where N is the number of players / entities / tileEntities / chunks loaded in a dimension - so with 30 players it's better to have 10 players on the Overworld, 10 players on the Moon and 10 players on Mars (total of N^2 = 300) instead of all 30 on the Overworld (total of N^2 = 900).   Galacticraft **wires** and other **energy components** are also higher performance than any other wires from any other mod, if you have players making large complex builds (more than let's say 40 energy tiles, where 1 energy tile is a wire or machine).

  **Normally** most players never go to other planets, because they need so many resources and so much game time, and it's just too hard on a multiplayer server.

**Comment by radfast** [comment]
A new config for this will be in next build 479.
