### ISSUE TITLE
[Meta-issue] The number of issues is too damn high!

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2413]
I was looking through the issues list and noticed a large number of old issues needing more info or a follow-up, or which aren't reproducible, or aren't even caused by Galacticraft. Since having so many of these issues makes finding real issues a pain, I propose for these such issues to be closed, where appropriate.

Of course, to avoid being hypocritical, please close this issue once its relevance has run out.

**Comment by dj3520** [comment]
>aren't even caused by Galacticraft

Could you mention some here?

**Comment by Brycey92** [comment]
[These](https://github.com/micdoodle8/Galacticraft/issues?q=is%3Aissue+is%3Aopen+label%3A%22not+a+Galacticraft+issue%22) are the issues I was referring to with that.

**Comment by radfast** [comment]
Hi Brycey92

You are correct.  I have been away from the mod for many months (almost a year) due to real life issues.  Micdoodle8 is focused on the planned update to 1.8.9.  Meanwhile there are all sorts of historic issues still sitting here, some valid, some not so valid.

I am slowly going through the list to see which ones can be closed.  For coding solutions, I think the focus needs to be on issues reported in the last 4 months, as the people who reported them are maybe still around for any follow up which is needed...

There are also a few known-but-hard-to-fix issues, which we leave open, however old, in the hope that a solution can eventually be found.  Here [1](https://github.com/micdoodle8/Galacticraft/commit/3542330a46edd3a4cd98d8e470b2a5ab3a289d60) [2](https://github.com/micdoodle8/Galacticraft/commit/d87b74afc4689edde26ab2acef04196d8c47083a) are two examples of people recently solving these with PRs, which is great.

**Comment by dj3520** [comment]
@radfast I'm actually watching you through my own fork and my inbox. Glad you're back and your reputation of rapid-fire fixes is back with you.

**Comment by Brycey92** [comment]
From my perspective, you never left, since my last contributions to Galacticraft were more than a year ago. Glad to hear you're back, though!

**Comment by radfast** [comment]
Don't worry about 1.8+.  We will port any fixes which are accepted to the 1.7 branch, to 1.8.  (This is normally not too hard to do, and the number of fixes is small.)

1.7 branch will probably now only be updated with bugfixes, not new features.

I expect 1.7 branch will stay active in bugfix terms for a long time, because a lot of servers have to use 1.7.10 - there's no later Cauldron/Thermos AFAIK.

**Comment by radfast** [comment]
I will leave some of the long term issues open for now, because I suspect there may be some kind of issue connected with chunkloading, which we may eventually find and solve.

**Comment by micdoodle8** [comment]
Also, if you look at pulse there's been 29 issues closed in the last month and only 3 issues remain open from this time period. Decent progress I'd say :)

**Comment by radfast** [comment]
If I close this, that's 38 closed issues and 2 new open issues :D
