### ISSUE TITLE
What happned with the pt_BR and pt_PT lang files?

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2423]
Is this correct, merge 1.7.10 **_into_** master? https://github.com/micdoodle8/Galacticraft/commit/8f6d4b0880cd160411a6caabd05a582bdac07e99

I mean, today I thought of translating some lang files from master branch. Before starting, I used [my little tool](https://github.com/EzerArch/MCLangMatch) that syncs a lang file with en_US, it showed me a huge list of deprecated entries. I then noticed lots of 1.7.10 entries are back. The lang file is 2x longer than en_US.

This commit (https://github.com/micdoodle8/Galacticraft/commit/8f6d4b0880cd160411a6caabd05a582bdac07e99) did something that the lang files are now twice as bigger. Compare: [prior to the commit](https://github.com/micdoodle8/Galacticraft/blob/46fda845a2c22da75555a30c2a1484e65cd09487/src/main/resources/assets/galacticraftcore/lang/pt_BR.lang) with [after the commit](https://github.com/micdoodle8/Galacticraft/blob/8f6d4b0880cd160411a6caabd05a582bdac07e99/src/main/resources/assets/galacticraftcore/lang/pt_BR.lang).

**_EDIT:_** With more examination, I see it's only pt_BR and pt_PT that look abnormally doubled. It lead me to think the problem is bigger than it really is. I suppose nothing bad happened with the other files. As to the offended lang files, what could I do?

**Comment by radfast** [comment]
To bring the master branch up-to-date with the past 6 months bugfixes etc in 1.7.10, micdoodle8 did an automatic merge.  Usually git is able to figure out what changed in the 1.7.10 and bring those same changes into master.  Unfortunately it failed badly with the pt_BR and pt_PT language files, so it has marked the whole files as needing manual attention!  (Likely reason is large scale changes to the order of lines in the files, or at least to the first few lines, so it is unable to figure out the sync.)

As you say, this only happened for the Portuguese language files, I guess because those are the only ones with changes in 1.7.10.

To ensure that the master branch builds correctly for now, I have reverted the change.  So the language files on the master branch are now the same as how they were yesterday.

The consequence is that your major update https://github.com/micdoodle8/Galacticraft/commit/abc845cbc770ce8b79d2129155438ca1221b8c58 is not yet included in the master branch.  We don't have a way to bring this in automatically.  Would it be a big pain for you to go through that manually, copying those changes from 1.7.10 to master as needed?  Sorry if that's a big pain, I can see it's 220 lines of changes - though some of them are whole sections being moved, or multi-line changes like the config settings labels.

**Comment by EzerArch** [comment]
Okay. I will:
1. compare 1.7.10's pt_ with 1.7.10's en_, just to be sure.
2. compare 1.8.9's pt_ with 1.8.9's en_, to make sure pt_ lang files have all en_ entries.
3. compare 1.7.10's pt_ with 1.8.9's pt_, to copy the translation changes from 1.7.10 to 1.8.9.
Then I suppose all will be good. :-)

**Comment by radfast** [comment]
Sorry it's so much work!
I think if you do 3 before 2, it can be easier.
Does your en_ -> pt_ comparison tool accept lines in a changed order?
You are welcome to make use of this if it helps you: https://gist.github.com/radfast/93d9437672f8e29c43f3

**Comment by dj3520** [comment]
`System.out.println("hi");` seems like something I'd do

**Comment by EzerArch** [comment]
@radfast:
> Does your en_ -> pt_ comparison tool accept lines in a changed order?

I think it does. The tool uses en_US.lang as a template (incl. titles, comments and spaces) and then search the xx_XX.lang to copy the translation strings -- if not found, it will use the en_ string as placeholder with "## needs translate ##" tag. Any xx_XX.lang entry not found in en_US.lang is printed at the end of the lang file as deprecated.

@dj3520: `print("hello, this is Python.")` ;)

**Comment by radfast** [comment]
> Any xx_XX.lang entry not found in en_US.lang is printed at the end of the lang file as deprecated.

nice

**Comment by radfast** [comment]
Thank you for the #2429 fixes, I think we can close this now - I guess you will make the same update to pt_PT?

**Comment by EzerArch** [comment]
I will. And probably for MC1.7 as well.
