### ISSUE TITLE
Galacticraft Issue regarding spawn

### ISSUE THREAD

**Issue by HGeorge0103** [micdoodle8/Galacticraft#2428]
Ive started a personal server with Galacticraft as my core.  However, it spawns everyone on the moon and makes Earth unreachable.  I want to have all players start on Overworld.  Any ideas if it is a config issue?

**Comment by radfast** [comment]
See also #2195 

Possible causes:

1.  bad Galacticraft configs on the server

2.  Multiverse (or similar) plugin, not properly configured

3.  maybe a Galacticraft add-on mod, not properly configured, which messes with the dimensions

4.  maybe another mod entirely

----

> Any ideas if it is a config issue?

No configs provided -> no ideas

To progress this please provide: server log (from startup to player spawn), server configs
Please also tell everything relevant to server setup, eg. Thermos, Bukkit plugins.  If possible, test the same server as a plain Forge server (not Thermos/Bukkit)

**Comment by radfast** [comment]
Closing, because the missing info has not been provided and it's been over 1 month.

@HGeorge0103 if you are still having problems, please provide all the info requested:

* server log (from startup to player spawn)
* copy of Galacticraft configs on server and client
* tell me everything relevant to server setup, eg. is it a Thermos or Cauldron server?  are you running any Bukkit plugins?
* if possible, test the same server as a plain Forge server (not Thermos/Bukkit)
