### ISSUE TITLE
[1.7.10] [FTB Inventions] Fatal Error disconnect/crash upon returning from space station

### ISSUE THREAD

**Issue by R9000** [micdoodle8/Galacticraft#2431]
Hi,
I'm running a server with a modified version of the FTB Inventions pack, to which I added Galacticraft and a few other mods. I'm running the latest version of Galacticraft at the moment, **3.0.12.465** Every time I return from an overworld space station, (on SP or MP) I am disconnected from the game, with "A fatal error has occurred, this connection is terminated". When I log back in, I'm floating down as usual with my parachute, but there is no para-chest, and so my rocket and landing-pad is gone. Sometimes, before the disconnect, I get a glimpse of loading into the overworld, so I'm definitely getting there, just getting DC'd straight after.
As far as I know, there's no crash log given for this, however if I try to use a launch controller to get back (which means I will land in my rocket as opposed to with my parachute), the server crashes, with this crash log: http://pastebin.com/QSsjgjhV though this doesn't seem like a very useful report to me. If I log back in, I'm landing in the rocket, exactly as if the crash never happened.
Other things to note:
-This never happens on any other landing. I've been to the Moon, Mars, and Asteroids without issue.
-This happens to all players (as far as I can tell), not just me, who built the space station.
-Renaming the space station seems to have no effect.
-I can get to the station just fine. It's just getting back that causes the problem.
If you need any other files, please let me know. Thanks,
Rory

**Comment by R9000** [comment]
Update: After further examination of the server logs, it's a WAILA crash, caused by the mod sending a broken packet, it seems. I've uploaded the relevant fragment of the log here: http://pastebin.com/4beJZnSH
Sorry to waste your time, but it's odd this only happens on this event (when coming back from a space station). For anyone with the same issue, the WAILA version I'm using is **1.5.10-1.7.10**.

**Comment by R9000** [comment]
Update again: Removing WAILA from the server has prevented the disconnect when leaving the station manually, but **not** when using a launch controller. The same issue as before persists. Relevant part of server log: (full log is over data limit for pastebin) http://pastebin.com/ZfqPXtnP
Crash report: http://pastebin.com/hkAXsphK

**Comment by dj3520** [comment]
Not seeing any Galacticraft code in the crash reports, so even though it's happening with space stations it's unlikely Galacticraft is the actual issue.

Meanwhile, Galacticraft has updated to v467

I am also using walia 1.5.10 on my server and haven't see this myself. It _could_ be a mod using the API for walia.

**Comment by dj3520** [comment]
Looking through all of your logs it seems like the same thing happening over and over again. More than likely you'll have to do a binary search.

1. Backup your current world on the server. A simple copy into a new folder will do great.
2. Remove half the mods on the server, removing them on the client as well.
3. Attempt to cause the crash again.

If it doesn't happen, restore the world from backup and remove a different half.
If it does, the mod/mods that are causing this are somewhere in the list of mods you removed. Cut that list in half, then try again. Eventually you'll find it.

**Comment by R9000** [comment]
Thanks. I'll try that tomorrow and see what I get (It's getting pretty late here).

**Comment by dj3520** [comment]
Reminder: This isn't a chat room. Everyone subscribed receives an email for every post.

**Comment by radfast** [comment]
Hi @R9000 

When the player returns from the space station to the overworld, he is changing dimension - Galacticraft does this dimension change in a very similar way to how a Nether Portal functions.

It's possible that this dimension switch can confuse another mod.  There is also a sudden height change (y=64 on the space station to y=255 on the overworld) but I can't think that that should normally affect things.

Your issue is hard to troubleshoot because you have something like 100 mods installed, and it could be something in any one of them, interacting with GC in this way.  We do need your help to narrow this down, please.  It could also be specific to your world / your configs / the specific mod versions you are using.  If you have time, please for a start make a simple test world, with only Galacticraft and WAILA in the mods folder.  (Never run an active, built world when you are changing the mods in your mods folder: changing mods around will destroy blocks and items in your world.)

If you can create a simple setup where the error still occurs, please describe it exactly (Forge version, other mod version, etc) and I can try to reproduce the problem here, which puts us a good way towards fixing it.

One more thing you can do: in `configs/galacticraft/galacticraftcore.conf` set Enable Debug Messages to true.  This gives a bit more information in the logs around that dimension change.

----

@dj3520  maybe don't subscribe?  I don't, and I don't miss it.

**Comment by radfast** [comment]
Also you didn't say whether this is a standard Forge server, or KCauldron or Thermos with Bukkit plugins.

If possible, please test on a standard Forge server, no Fastcraft, no KCauldron, no Thermos etc

**Comment by R9000** [comment]
No Bukkit, just straight Forge with Fastcraft. I'll test without it.

**Comment by dj3520** [comment]
@radfast I was speaking for the others that _do_ subscribe. Posting "I'll get back to you on that" is kind of worthless without results.

**Comment by EzerArch** [comment]
"Subscribe" is not the correct term, it's "watching". If you are watching a repo, you'll get every post/reply via email thereof.

_To whom it may interest_: You can go here (https://github.com/settings/notifications) and uncheck "Email" under "Watching" but keep checked "Email" under " Participating", you'll get emails _**only if**_ you have posted in the issue or you are called with @.

**Comment by radfast** [comment]
> No Bukkit, just straight Forge with Fastcraft. I'll test without it.

Fastcraft doesn't usually give problems, you could probably skip this step and go straight to mod isolation with WAILA and others.

In principle I certainly would like to have Galacticraft 100% compatible with everything in FTB Inventions (I thought it was already...)

**Comment by dj3520** [comment]
@radfast They must have broken things while you were gone. Shame on them.

**Comment by radfast** [comment]
@R9000 thank you for reporting, I've experienced the [same crash](https://github.com/micdoodle8/Galacticraft/issues/2459#issuecomment-286758353) myself, now found and fixed it in new build 4.0.12.478

Please try that and hopefully it's all good for you now.
