### ISSUE TITLE
[1.8.9] Parachest Rendering issue

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2450]
Forge: Same as Galacticraft Uses
Galacticraft Version: Latest (up to this commit b06042c)

Spawned in world by taking rockets
![](https://i.gyazo.com/3f6cdae9224b015c27d5c7a089fc5de5.png)

In inventory (spawned in from creative)
![](https://i.gyazo.com/0d97a79ec5ca3fc1224ae5f420de3975.png)

**Comment by radfast** [comment]
As you know, some block models have changed in 1.8.9 to simpler and blockier versions of what was in 1.7.10.  This is partly to make the game run faster (higher framerate) and partly because it is so *^T$% hard to make the old models compatible with 1.8.9. 

We can tweak the models as time goes on but I think they are mostly looking good now - the simpler models actually have more of a Minecraft feel to them.  Display Screen and Cryogenic Chamber are good examples.

I'm not sure of micdoodle8's intentions here (I will ask him).

For the Parachest, my guess is that this model is supposed to signify a chest with its parachute crumpled on top of it.  Looks like there are different parachute colors, the default is grey-white but the inventory item happens to use a red parachute.

**Comment by MJRLegends** [comment]
@radfast No problem, just wanted to make sure you are aware of the issue 👍

**Comment by radfast** [comment]
If it doesn't look good to you, then it probably doesn't look good to other people too.  So we should pay attention to this... :)

**Comment by MJRLegends** [comment]
@radfast No problem take your time :D

**Comment by MJRLegends** [comment]
I know how you feel about models/json files stuff, they are causing me pain haha
