### ISSUE TITLE
galacticraft breaking extra utilities soul fragments

### ISSUE THREAD

**Issue by 252rer** [micdoodle8/Galacticraft#2456]
Can't use either soul fragment to regain max health from extra utilties with galacticraft installed.
Using an etheric sword from ExU makes a soul fragment and that reduces your max health but if galacticraft is installed you can't change your mind or use the rare drop souls to get your life back as the right click functionality breaks. Remove galacticraft and works as intended.
GalacticraftCore-1.7-3.0.12.465
MicdoodleCore-1.7-3.0.12.465
extrautilities-1.2.12

**Comment by dj3520** [comment]
Unlikely this will fix it but can you retest with the newest Galacticraft version, v477?

**Comment by 252rer** [comment]
Same issue with 3.0.12.477

**Comment by radfast** [comment]
Thank you, I'll take a look.

One question: do you have PlayerAPI installed?  If you don't have it, you can download it from [here](http://www.mediafire.com/?b8tgyx21fvecr4n).  Just put the downloaded file in your .minecraft/mods folder, it works silently in the background helping inter-mod compatibility - it won't add any new blocks or items to the game.

**Comment by 252rer** [comment]
Tried playerapi and it does work as a workaround for fixing the issue, thanks.

**Comment by radfast** [comment]
OK great.  That's not a workaround then!  It's the intended solution to this type of compatibility issue!

If it works with PlayerAPI this also confirms that the reason is something in ExtraUtilties code which is "locked" to the EntityPlayerMP class instead of its sub-classes.  It folows from this that any fix for this _without_ PlayerAPI would have to come from ExtraUtilities.

I've added this to [our Wiki notes](https://wiki.micdoodle8.com/wiki/Compatibility#Extra_Utilities), thank you for giving us the info.

**Comment by radfast** [comment]
https://github.com/rwtema/extrautilities/issues/1368
