### ISSUE TITLE
No way to clear small amounts remaining in gas tank of Gas Liquefier

### ISSUE THREAD

**Issue by Brycey92** [micdoodle8/Galacticraft#2462]
In Asteroid Challenge mode, you're able to use the gas liquefier to make fuel from methane gas. However, the input does not accept methane gas from the methane synthesizer. Also, a gas liquefier that has been used for oxygen must be broken and replaced before it will accept methane canisters.

**Comment by radfast** [comment]
Which Galacticraft version?

Please provide a screenshot of how you are trying to connect the Methane Synthesizer to the Gas Liquefier, because I don't understand you.

**Comment by Brycey92** [comment]
Ah, sorry, 1.7.10, build 475. I placed the gas liquefier so its input was directly against the methane synthesizer's output, since there are no methane pipes.

**Comment by dj3520** [comment]
I don't think they automatically output. pump it like fluid and the problem should be solved

**Comment by Brycey92** [comment]
Weird, other machines have automatic outputs. Why not this one?

**Comment by radfast** [comment]
The reason is this:
> since there are no methane pipes.

The other machines can push oxygen and hydrogen to each other because there are oxygen and hydrogen pipes - it's basically like a pipe of 0 length.

You're supposed to use Canisters for methane, or use pipes from another mod.  [RTFM](https://wiki.micdoodle8.com/wiki/Methane_Synthesizer#Output)  You could maybe do something with hoppers, I realise that is less pretty.

In Galacticraft 4 the setup you built might work - I haven't tested - because Galacticraft 4 has fluid pipes which can accept many types of liquid and gas, not only oxygen and hydrogen.

----

If someone wants to code a Pull Request so these two machines can directly transfer methane between themselves in 1.7.10 we canl probably accept it.

**Comment by radfast** [comment]
> Also, a gas liquefier that has been used for oxygen must be broken and replaced before it will accept methane canisters.

I guess there is 1 oxygen remaining, for some reason?  We maybe need a way to clear that.

**Comment by radfast** [comment]
> Also, a gas liquefier that has been used for oxygen must be broken and replaced before it will accept methane canisters.

I'm not seeing this, works fine in all my testing.  And the machine is already coded to clear any final 1mB of a gas remaining.
