### ISSUE TITLE
Isn't compatible with oil in GregTech

### ISSUE THREAD

**Issue by akiractre** [micdoodle8/Galacticraft#2476]
When i use machines of Gregtech,oil cannot be imported

**Comment by radfast** [comment]
Have you reported this issue to Gregtech?  I see it as "Gregtech oil isn't compatible with Galacticraft"

**Comment by bballboy2002** [comment]
GregTech decided to drop power compatibility with other mods, maybe Greg did the same for oil

**Comment by radfast** [comment]
I'm no Gregtech expert, but I **think** they have many different types of oil with different names, from light, medium, heavy, extra-heavy - maybe crude though I didn't see that when I took a quick look.  Galacticraft oil  is obviously supposed to be crude oil as it's found in reservoirs underground.

**Comment by radfast** [comment]
I'm closing this because I don't see it as a Galacticraft issue.

If Gregtech has a Forge fluid named "oil" then we are compatible with it.  If not, then that's a deliberate decision by Gregtech to break compatibility.

Some of our machines - for example Refinery - will accept any type of oil, so you might find that you can put buckets of Gregtech oil **of any type** into our Refinery and it will refine them...

Any further compatibility patches here, I'm going to need @Blood-Asp or somebody else who understands the inner working of Gregtech to show me exactly where GT Crude Oil is registered and what its internal name is.

**Comment by Blood-Asp** [comment]
IMO the compatibility comes from the usage of "fuel" in the rockets. So no need for GT oil in GC refineries if you can use the GT fuel in GC rockets. 

The other direction, using GC oil in GT distilleries should work fine.
But also GC should be able to use GT oil through the conversion: light/medium/heavy oil can be converted into "oil" in the distillery. There is some loss for GT processing this way, but compatibility with other mods should be fine this way.

**Comment by radfast** [comment]
Hey Blood-Asp, thank you for bringing your expertise to bear.

I'm not a GT player and not set up to test it (partly because I expect that GT is a very complex mod and I'd need to spend an hour or two learning the mod before I can test it properly!)

Galacticraft **Fuel Loader** is currently programmed to accept any Forge-registered fluid which has "fuel" somewhere in it's name.  This includes Rocket Fuel from EnderIO and would also probably include biofuel liquids from any mod - maybe a bit unrealistic but it's only a game!

The Fuel Loader auto-converts any fuel it accepts, into Galacticraft fuel inside its internal tanks.  So it correctly gives Galacticraft rockets the fuel that they need.

So long as the GT fuel has "fuel" in it's (internal, Forge-registered) name, then the Fuel Loader should accept it and therefore the rockets should accept it!

I think the OP is reporting that GT distilleries are not accepting Galacticraft oil.   I'm OK with that, for the reason explained - it must be a deliberate decision by GT not to accept oil registered by other mods.

**Comment by Dream-Master** [comment]
@radfast there will be a new chemistry update soon wich include extra rocket fuel. Is it possible for Galacticraft 1.7.10 to add a option where i can choose what i want to use in the rocket?

https://github.com/Blood-Asp/GT5-Unofficial/pull/1030

**Comment by Blood-Asp** [comment]
The rocket fuel got added by me a few updates back and is fluidname compatible with enderIO rocket fuel. So it does work automaticly with GC. The new update only changes the recipe for it to be more realistic.

**Comment by Dream-Master** [comment]
Ok but if Rocket fuel works normal fuel should not working anymore because no one will make more expencive fuel for no benefit.

**Comment by radfast** [comment]
@Dream-Master
I have added to my "todo" list a config option for GC to blacklist fuels from the Fuel Loader - maybe including Galacticraft's own - so that a player or modpack can force the use of the most expensive fuel.

No promise, but I will aim to add that the next time that I update configs code.

**Comment by Dream-Master** [comment]
@radfast ok cool thanks.
