### ISSUE TITLE
[1.11.2] Hidden/overlapping Galacticraft Inventory tab if CustomNPCs present

### ISSUE THREAD

**Issue by Agentx49** [micdoodle8/Galacticraft#2497]
in the 1.11.2 version there seems to be no inventory slots for the parachute and everything

**Comment by radfast** [comment]
Thanks for beta testing!

We'll take a look at this.  Please can you give your whole modlist, or post up your **fml-client-latest.log**.  Do you have Tinker's Construct or NPCs?

**Comment by radfast** [comment]
See MJRLegends comment: https://github.com/micdoodle8/Galacticraft/issues/2512#issuecomment-292675387
maybe only loses the slots after player death and respawn?

**Comment by Agentx49** [comment]
I had custom npcs I think that was it

**Comment by ThomasAunvik** [comment]
The GUI for the GC Inventory is there. Also, there is a bug (posted at #2515) when shift clicking any items to the gui crashes the game.
Also, i have installed CustomNpcs and it seems that the galacticraft tab overlaps Custom NPCs tabs. The faction tab.
![1](http://i.imgur.com/y7uKfEy.png)
![2](http://i.imgur.com/60IIkdv.png)
![3](http://i.imgur.com/k3UwCuF.png)

**Comment by radfast** [comment]
These different tabs are supposed to respect each other.  Originally the tab system was developed by Tinker's Construct.  It's possible that it just won't work properly until there is a TConstruct.  But we can look at this.

@Agentx49 do you have the inventory tab OK if you run Galacticraft 1.11.2 **without CustomNPCs**?

**Comment by EzerArch** [comment]
If these CustomNPCs tabs are not important or necessary for you:

1. Open CustomNpcs.cfg.
2. Find `InventoryGuiEnabled=true`
3. Change it to `InventoryGuiEnabled=false`
4. Done.

**Comment by radfast** [comment]
hey guys

As mentioned in #2645, I've been in touch directly with **Noppes** (author of CustomNPCs and MorePlayerModels).  We've chatted on Skype.  This problem will be fixed by a change on his side, he'll be including this in the next builds of his mods.

I don't know when his next builds will come - looking at his download page, it looks like he makes new builds around monthly or even less often, so I guess it will be a few weeks yet for this.
