### ISSUE TITLE
[1.10.2] Crash Advanced Solar panel

### ISSUE THREAD

**Issue by NerdCraft** [micdoodle8/Galacticraft#2507]
4.0.0.53-beta
https://pastebin.com/qECEHUSu

**Comment by ThomasAunvik** [comment]
Duplicate of https://github.com/micdoodle8/Galacticraft/issues/2500

**Comment by radfast** [comment]
Thank you for beta testing!

Yes, this is the exact same issue as #2500, just being triggered by **The One Probe HUD** instead of by WAILA.

We're on it, I'm sure there will be a new Galacticraft version some time in the next day or so.  Closing this as the issue is already reported, but you are welcome to comment here.
