### ISSUE TITLE
[1.11.2] Fluid Tank Bug

### ISSUE THREAD

**Issue by ThomasAunvik** [micdoodle8/Galacticraft#2518]
**Bug 1:**
Water/Lava Buckets wont be consumed/turn into normal buckets when right clicked in the fluid tank.

**Bug 2:**
Galacticraft Fluid Buckets wont be accepted into the tank.

- Oil Bucket
- Fuel Bucket
- Bacterial Sludge Bucket
- Sulphuric Acid Bucket

[Bug 1 and 2 gif](http://i.imgur.com/oURbdqb.gif)

**Comment by radfast** [comment]
Not an issue in 1.8.9, looks like this is 1.10+ only.

**Comment by radfast** [comment]
Thanks for testing these things.

All bucket issues in 1.11 are fixed in next build 77.

**Comment by ThomasAunvik** [comment]
This is actually fixed in build 76... thats suprising.

**Comment by radfast** [comment]
For info:

Forge for Minecraft 1.11.2 changed the way all buckets and other fluid containers work internally (actually they made the change already in 1.10.2 but they kept the old system in 1.10.2 as well, in "deprecated" form).

There are a few problems with Forge's systems:

1.  in the new system for buckets, there is literally **no way** to have an empty bucket (a vanilla bucket) fill with a custom fluid, unless you use Forge's 'bucketfilled' a.k.a. Universal Bucket.  I don't like Forge's 'bucketfilled':

* it has a rounded icon model, basically it's the bucket from Tinker's Construct, and an antique look to it, so it's not very "Galacticraft"
* it renders the bucket contents using the in-game colour for the fluid - but we prefer to use brighter colours for the buckets and the graphics inside GUIs showing fluid tanks, and duller/more translucent colours for the in-game fluids
* in the Creative mode inventory, it places the Forge bucket at the end of the vanilla Items tab (the tab with the lava bucket) - but I think all Galacticraft items should go on the Galacticraft tab
* the item name in game doesn't have the beautiful blue colour which you might notice we give to all Galacticraft items, so you know they're from us and not from some other mod :)

2.  although the old system for buckets and other containers is retained in 1.10.2, actually Forge doesn't do anything with it, making any mod items coded the old way kind of useless

Therefore now from **build 77** we do this:

A.  In 1.11.2, offer our own Galacticraft buckets **and** the Forge bucket.  The Galacticraft buckets work with all Galacticraft machines and that's the item you'll get if you use a vanilla bucket to scoop up a fluid block in the game.  The Galacticraft buckets can also be _emptied_ into other mods tanks.  If you fill an empty (vanilla) bucket from the Galacticraft machines, you get the Galacticraft bucket item.  If you fill an empty (vanilla) bucket from another mod's tank holding fuel / oil / bacterial sludge / sulphuric acid, you get the Forge bucket item.  The buckets are basically the same - both work - they just have a different look.  This is the best we can do, without hacking Forge to change the way all mods' buckets work, and that would ~probably~/certainly give compatibility issues with some other mods.

B.  In 1.10.2 we offer only our Galacticraft bucket, not the Universal Bucket.  Our Galacticraft bucket will work correctly with all our own machines and tanks.  With other mods tanks I'm not so sure, it depends how they coded it, but like in 1.11.2 it should usually be able to _empty_ into their tanks, maybe not fill again.  What we **do** offer in 1.10.2 is complete crossover compatibility of all our tanks and fluid-handling machines with **both** the old system and the new system, so we at least will be **compatible with every other mod's items**.

This sounds more complicated than it is in game.  In game, buckets basically "just work", at least until you try clicking an empty (vanilla) bucket on another mod's tank, then what you get is up to Forge and the other mod.

In constrast to the niggles with buckets, **Canisters** now work superbly well.  These are very smart items, for example they are useful for emptying a tank which has less than 1000mb of fluid in it.  They can do everything which buckets should do, and more, and they can be filled from every other mod's tanks (if the other mod is properly coded).

I wil talk to micdoodle8 about removing buckets completely from our mod, so that players have to use Canisters.  I always liked Canisters more ...   (One thing currently is that the empty canisters don't stack, but that is a possibility for the future.)

**Comment by ThomasAunvik** [comment]
I see.

**Comment by radfast** [comment]
(this is also for bringing micdoodle8 and other contributors up to date with what I've changed this week, I am sending them links to this post!)

**Comment by radfast** [comment]
[Build 77 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)
