### ISSUE TITLE
[1.10.2] workbench

### ISSUE THREAD

**Issue by Agentx49** [micdoodle8/Galacticraft#2521]
is the workbench
![2017-04-08_09 50 08](https://cloud.githubusercontent.com/assets/26726223/24829508/1b6fd7de-1c41-11e7-9a96-f2f58c762593.png)
 supposed to look like this?

**Comment by ThomasAunvik** [comment]
Duplication of https://github.com/micdoodle8/Galacticraft/issues/2504

**Comment by radfast** [comment]
Thank you for beta testing.

Yeah, it's not supposed to look like that!  But this issue is already open at 2504, so I will close this.

Please do post up any other issues you notice today in 1.10.2.  But ... we will be making a new release 56, probably later today or tomorrow, which will fix a few things so you might want to wait for that before spending a lot of time testing!
