### ISSUE TITLE
1.11.2 Mod Incompatibilities

### ISSUE THREAD

**Issue by EmosewaGamer** [micdoodle8/Galacticraft#2535]
It seems that version 58 for MC 1.11.2 of GC is incompatible with a few mods and looking at the crash log it seems that they're all because of the same reason. By incompatible I mean that the game crashes when loading and the ones I currently know of are:

- Hopper Ducts https://pastebin.com/rW4Ezjh4

- GraveStone Mod https://pastebin.com/RAu3R631

- Advanced Generators https://pastebin.com/as5L061e

**Comment by radfast** [comment]
I looked at all three logs.

The problem here is simply that your modpack, in total, is **too large**.  So you have more than 4096 different block types, with all the mods added together, and Minecraft can't handle that.  The only solution is to remove some mods.  Don't blame Galacticraft only because we are the latest mod you added to your pack!  (The "straw that broke the camel's back", lol)

There is no incompability shown in the logs you posted.  Remove a few mods from your pack, try it again, and Galacticraft should work fine with all three of those.

**Comment by EmosewaGamer** [comment]
Woops. I'm sorry then.

**Comment by ThomasAunvik** [comment]
This kind og error can be easily fixed by installing [Not Enough IDs](https://minecraft.curseforge.com/projects/notenoughids)
It extender the max id to 65535
