### ISSUE TITLE
Open Spaceship Inventory key conflict [1.11.2]

### ISSUE THREAD

**Issue by willtree8** [micdoodle8/Galacticraft#2582]
The 'Open Spaceship Inventory' key (F) conflicts with the default 'Swap Item In Hands' key.

**Comment by radfast** [comment]
Thank you for beta testing!

The default setting of this key was changed to 'G' as of build 63.  But, if you didn't regenerate your Galacticraft config, then your config file will be overriding that default setting with an 'F'.

I guess this is going to be a problem, because a lot of Galacticraft players will still have their same old Galacticraft config from 1.7.10 days.

**Comment by micdoodle8** [comment]
Maybe the config key should be changed.

Most people won't want to keep it as the previous default F, which will be what the majority have it set to in their config.

**Comment by radfast** [comment]
Done.
