### ISSUE TITLE
Build 64 1.11.2 Cryogenic Chamber bug

### ISSUE THREAD

**Issue by ElSaam** [micdoodle8/Galacticraft#2587]
"Exit bed" button not working in Cryogenic Chamber.

**Comment by ThomasAunvik** [comment]
Another issue: The cooldown for the Cryogenic Chamber is also very slow:
Timer is set to 40 ticks instead of 20 ticks in the seconds.

Solution?
Change 1 to 2?
`stats.setCryogenicChamberCooldown(stats.getCryogenicChamberCooldown() - 1);` in https://github.com/micdoodle8/Galacticraft/blob/99761a1c1e9c3092d534e13db40bbf4ea6199d54/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCPlayerHandler.java#L1235

**Comment by radfast** [comment]
See also #1159  ... it's an issue in 1.7.10 as well.   I guess one we haven't prioritised, there's been so much else!

**Comment by micdoodle8** [comment]
Will be fixed in the next build, thanks!
