### ISSUE TITLE
1.7.10 Oxygen Sealer not sealing (When it should)

### ISSUE THREAD

**Issue by tpunko** [micdoodle8/Galacticraft#2599]
When I went to air sealer a room in my Moon base the Oxygen Sealer said the area is too big / unsealed. yet I tested it and I made a bigger room and its sealed. Also there was no holes in the walls. I don't know why it will not work. Here's a picture of the room.
![2017-04-15_23 15 38](https://cloud.githubusercontent.com/assets/27605957/25069009/a03b8094-2231-11e7-8322-7b246307ad6e.png)
The glass and other odd shape are blocks from the Carpenter's Blocks Mod and I have tested if it was because of them but its wasn't. (And yes the Oxygen Sealer in the picture does have a infinite battery and infinite oxygen in it). Now I'm out of ideas in how to fix it and slow dying of lack of oxygen. S.O.S. Please help

**Comment by dj3520** [comment]
One type of block might not be seen as sealable.

**Comment by radfast** [comment]
It's most likely the blocks from Carpenters' Blocks.  Galacticraft cannot currently recognise as **sealable** a block which is:
  A.  not a regular cube shape (_because_ it's from Carpenters' Blocks)   **and** at the _same time_
  B.  transparent, for example a non-vanilla type of glass.

We can handle one or the other of these on its own, [but not both](https://forum.micdoodle8.com/index.php?threads/oxygen-sealer-custom-ids-not-working.5790/#post-41018).

I also noticed you have holes in the floor (those Walkways have holes) - but I think the issue here is most likely your fancy glass.

You can **try** figuring out what those Carpenters Blocks are and adding them to Galacticraft's config yourself, as explained [here](https://wiki.micdoodle8.com/wiki/SealableIDs#Isn.27t_there_another_way_to_get_block_names.3F).

If that doesn't fix it then you'll probably have to use either Carpenters Blocks with the vanilla glass texture, or use your same glass in regular cube shapes.

I'm closing this issue report because the Oxygen Sealer is behaving correctly, as currently intended.  You're welcome to keep on discussing this here though.  I'm interested to know how you fix this.

**Comment by tpunko** [comment]
Ok, ya I'll start looking at the Carpenters Blocks and the glass is in fact vanilla, it's the coloured glass. Also on the FTB page it didn't list Carpenters Blocks on the non-sealable list. But i'll look more into the glass. (Also I did notice the Walkway blocks have hole and underneath them is a layer of blocks).

**Comment by tpunko** [comment]
After more testing on the Carpenters blocks and glass I have found out the problem. The Carpenters Blocks used in any shape with still seal. The glass block on it's own will also seal, But if you place on the Carpenters Blocks the seal gets broke. Now the hard part fixing the problem.

**Comment by tpunko** [comment]
...Oh no. I think I have broke my Mob Pack it well no longer run, it crashes before its launchers. I would think it's better if I know what I'm doing first before I start messing around with the config. So I would like to fix this problem. (Also any type of glass with make it unsealed). I think the problem when I put in the blocks name the spacing was wrong because I had to use TAB/SPACE to line up the words.

**Comment by radfast** [comment]
you don't have to use TAB/SPACE to line up the words!  Java programs don't usually care about spacing.  But if you're going to do that lining up, always use spaces, not tabs.   tabs can break things.

If it is still crashing, you can delete the Galacticraft core config.  The mod will automatically remake a good config next time it starts.

---

Like I said, Galacticraft can seal Carpenter's blocks unless they are made of glass.  (Vanilla plain glass should be OK, but looks like coloured is not.)


I

**Comment by tpunko** [comment]
Thank you for all the help I was able to keep the light blue colour I just needed to just panes on the Carpenter's block not the block and the stairs didn't work either way so I just used solid blocks. Now I can continue building my moon base.
