### ISSUE TITLE
Thermal padding chestpiece visual bug (1.11.2 Build 66)

### ISSUE THREAD

**Issue by ElSaam** [micdoodle8/Galacticraft#2600]
Rigt arm missing texture
![2017-04-16_11 50 49](https://cloud.githubusercontent.com/assets/16359905/25070034/1134bed2-229b-11e7-9c29-04191951259a.png)

**Comment by EzerArch** [comment]
> Right arm missing texture

The funny thing is, both arms have never got the "glove" part since the introduction. Which makes sense in my opinion (as this is not an armor).

There's something else I noticed: the thermal padding is significantly _fatter_ now than in 1.7.10, specially on the arms.

1.7.10:
![2017-04-19_07 12 47](https://cloud.githubusercontent.com/assets/6743303/25414862/8a11d558-2a0a-11e7-82a0-6ff154a6ce89.png)

1.10.2:
![2017-04-23_23 09 06](https://cloud.githubusercontent.com/assets/6743303/25414893/bcccc87c-2a0a-11e7-8a33-cf89bd62e39e.png)

Depending on the mod/armor, e.g. Modular PowerSuits, the thermal padding "sticks" out, goes above the armor.

**Comment by Agentx49** [comment]
OMG! That has always been so annoying because I go to wear this really cool armor and be able to survive in space but then the thermal sticks out and I have to choose

**Comment by radfast** [comment]
Fixed in next build 79.

**Comment by micdoodle8** [comment]
Fixed with e3a84db237e715013129cf45631f9dcee0002e86. 

The thermal armor model is now bigger because there's a new skin layer which would poke through the armor. It would look very strange if part of the player skin was poking through the thermal armor.
