### ISSUE TITLE
World created but not loaded

### ISSUE THREAD

**Issue by ZeroApoc** [micdoodle8/Galacticraft#2615]
I created a private mod pack and started a game. The world seems to gen just fine. But it dropped to the main menu immediately. It doesn't crash the client. I looked through the log but can't figure out which is the relevant red text to look at to determine the error. I have the RAM set to 5Gb's. Can someone better with error logs than myself please look at it and tell me which error is the culprit. Thanks.

[https://paste.ee/p/46wQc](url)

**Comment by ZeroApoc** [comment]
I tried to change the memory settings and I figured a new log couldn't hurt. Here it is.
[https://paste.ee/p/B6evG](url)

**Comment by radfast** [comment]
your problem here is a plugin **GalaxySpace**.   it's been configured to give anotherplanet **BarnardsSystem** a biome ID of 300.   only biome IDs 0 ->255 are allowed.

Go report it to the GalaxySpace developer please, not here.  Or maybe you can fix it yourself by changing configs.

Worst case:  uninstall **GalaxySpace** and your problem should be fixed.

**Comment by ZeroApoc** [comment]
Thank you. :)

**Comment by ZeroApoc** [comment]
Thank you. :)
