### ISSUE TITLE
[1.10.2] Crash During Mining

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [micdoodle8/Galacticraft#2616]
I'll be honest I dont have a clue what this means, but here you go. Happened right after I mined Copper ore from this mod.

https://pastebin.com/wYqvCAVM

**Comment by radfast** [comment]
Your log shows you, this is a bug in **GravityMod** made by mysterymayhem.co.uk.

Please show the log to the GravityMod developer.  Their mod is calling block.getPickBlock(target, world, pos, player) at a pos which no longer contains a block of that type, because it's been broken (set to air).  That's daft.
