### ISSUE TITLE
Crashes on Dedicated Server

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2624]
[crash-2017-04-22_14.18.49-server.txt](https://github.com/micdoodle8/Galacticraft/files/948927/crash-2017-04-22_14.18.49-server.txt)
using forge 2282, 1.11.2.

**Comment by radfast** [comment]
Thanks very much  for reporting.

You must be the first person to try Galacticraft 1.11.2 on a dedicated server, because this crash would have affected everyone!

Fixed in next build 70, probably available later today.

**Comment by kenijey** [comment]
i'm a lover of Galacticraft, i just learned TODAY it's on beta and open for testers. I will be the greatest tester, trust me :D im playing it since my chilhood. and really need b70 right now :D

**Comment by radfast** [comment]
build 70 will be available in the next 30 minutes from posting this

**Comment by kenijey** [comment]
okay! waiting :)

**Comment by radfast** [comment]
ok 30 minutes was a bit too optimistic, but very soon today

**Comment by kenijey** [comment]
well, waiting patiently :D btw can you tell me will there be more planets and other galaxies in future? it would be lovely. maybe you know, there is a mod called "extra planets" that galacticraft 3 addon. it adds andromeda galaxy with upper tier of rockets, etc. in my opinion, i wouldn't want to install that mod as an extra, i would like to galacticraft include it itself. it would be really lovely and cool; more galaxies in galacticraft. i can help about ideas, if you guys care me :D thanks for response btw

**Comment by Agentx49** [comment]
I prefer galaxy space and amunra

**Comment by kenijey** [comment]
i just gave an example; i mean more galaxies with more planets with more planet biomes and more technology. such as starbound game :p

**Comment by Agentx49** [comment]
Yeah totally

**Comment by radfast** [comment]
lols, we're not short of ideas!  we have lots of exciting things of our own planned, I think it's important that the other planets "feel" like other planets, so they're not just differently colored stone and sky.  we also like to add things which make playing Minecraft more **dangerous** :)  otherwise there's no challenge for good players

If you want to help, practical ways to help with Galacticraft development:

1.  If you spot issues, give very clear issue reports (this one was perfect, because you posted the crash report in the first post)

2.  Language files:  most languages in Galacticraft except for en_US, Russian, Portuguese, Thai can do with some updating now.  We can't do this without help!  OK, I can probably manage to do en_GB ...

3.  **Textures**:  are you a good pixel artist?  If you can improve any of our [textures](https://github.com/micdoodle8/Galacticraft/tree/master/src/main/resources/assets/galacticraftcore/textures), you're welcome to have a go.  If your work is good, and it looks consistent with Galacticraft's overall look, it's likely to be accepted.  If you come up with something new, we could also create a new block for it, like a new type of decoration block or rock.

4.  **Minecraft building**:  _(probably the most fun!)_  Take a look at the Abandoned Space Base, currently you can find it in the **Asteroids** dimension close to where you first spawn in the dimension, it's at y height around 190-200.   Go inside it.  It's currently unfinished, there are just these empty rooms.  If you can build something which looks great, we can make the game re-create your build for everyone.  Some things to think about:

a.  the build has to be coded in, similar to a Minecraft village, so it's best to keep elements fairly simple - a really complex build with 40 different blocks all positioned just-so will be too complex to code, probably

b.  it can only use vanilla and Galacticraft blocks

5.  **Pixel art again**:  I'm looking to add to the Paintings which Galacticraft offers.  Especially, scenes of alien planets, or space battles, or othersci-fi type stuff, to decorate the Abandoned Space Base interior.

**Comment by kenijey** [comment]
> we also like to add things which make playing Minecraft more dangerous :) otherwise there's no challenge for good players
yes, exactly, i agree that.
- well, i'm learning Java (in eclipse) in school(university) yet, but i'm not good at making or coding mod especially in minecraft. but maybe i can learn fast with some help :p but i'm good at c++
- i'm a good bug reporter, you can trust me as i said :D 
- about the pixel art, maybe i can draw better textures or add more planet biome typed blocks (rocks, dirts, etc) with some help about which program i should use.
- and more about pixel art, if i learn; i can design biomes for other planets in other galaxies. (because all planets already designed in solar system?)
thanks for response!

**Comment by kenijey** [comment]
oh, b70 just came out. trying!

**Comment by radfast** [comment]
Pixel art is hard if you're not an artist - it seems like it should be easy, but it's really not. I suck at it!

If you know Java you're welcome to help with the coding - anything you spot which can be corrected, just make a Pull Request.  I use Eclipse to code Galacticraft, nothing else.  Micdoodle8 uses IntelliJ Idea, he prefers that over Eclipse.  (OK we do also use a few performance monitoring tools for checking code performance, and modelling apps and some small custom tools we made for checking stuff.)

**Comment by radfast** [comment]
OK [build 71](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) is now available

And I should also say - we especially appreciate people testing it on dedicated servers, because we don't usually test so much on servers ourselves

**Comment by kenijey** [comment]
well i downloaded b71 and it works fine with ded. server :)

**Comment by kenijey** [comment]
ah, about pixel art; you mean drawing great textures pixel by pixel on 16x16 image, isn't? i did it before. at least i did a 35x15 cape in advanced capes mod :D 
okay for Eclipse, (i don't know IntelliJ Idea) if i can, i will try to make a pull request. 
about testing, i will test it everytime because i made a modpack and i have to test everything on every update/version :D 
and most of the crashes/bug reports is coming up on updates.
