### ISSUE TITLE
[1.10.2] Power Issues

### ISSUE THREAD

**Issue by tabepic** [micdoodle8/Galacticraft#2628]
When connecting a Solar Panel (Basic or Advanced) to an Energy Storage Module, the internal energy bar in the Solar Panel decreases quickly, as if it's discharging properly.
However, when it hits zero, it climbs again, as if it wasn't connected anymore.
I checked the Energy Storage Module, and it was still receiving power.
When I removed the connection, the energy bar (inside the Solar Panel GUI) showed the correct value again.

This problem happens when using both Aluminum Wires, and using Beams

GC Build 70
(There's no difference between 70 and 71, right?)
I am using other mods, let me know if you want me to post a list.

**Comment by radfast** [comment]
other mods shouldn't make a difference to GC's own power, that's internal.  If I can't reproduce this in GC alone I might ask for a list.

(There's no difference between 70 and 71 for Minecraft 1.10.2.   But there is no version 70 for 1.11.2, something went wrong, so we had to bump all versions up to 71 to fix that.)

**Comment by tabepic** [comment]
Thought so, thanks for clarifying.

**Comment by tabepic** [comment]
Another (related) bug I just found:
The same solar panels report that they're generating power at 41gJ/t *at night time*
They also still have the tops pointing west, not covered.

**Comment by radfast** [comment]
Thanks for reporting, I can see **three** different things happening here.


**Issue 1: internal energy bar climbing again when it 'should' be outputting everything**

The solar generator is working correctly in reality ("in reality" = on the server side).  The GUI on the client was showing the wrong thing in one situation (all generated energy output the same tick, so it stayed 0 on the server).  This is a minor consequence of recent network performance changes.  Great to catch it now, it also affects a couple of other generators.  Fixed in next build :)

**Issue 2: the solar panel was not turning to its "covered" status**

That was my bad, I thought that was an error when I saw it turn upside down like that so I switched that off recently.  But I now see that it's intended.  So this behaviour is back next build :)  And slightly improved - it responds to sunrise a bit better.

**Issue 3: solar generator showing generating power at 41 gJ/t _at night time_**

I can't reproduce this.  It should be impossible, it means there is a high amount of **packet loss** between the server and client.  This is interesting ... it means packet loss is likely also the cause of your issue on the Moon #2559.  Please can we discuss more about your setup on that thread, not here, because the issues in this thread are now fixed.

**Comment by tabepic** [comment]
The solar generator showing 41gJ/t at night time I believed was the same issue as Issue 1
It was on a local LAN game. not a dedicated server

**Comment by radfast** [comment]
ok, looks like I jumped to the wrong conclusion then ... a LAN game shouldn't have packet loss
