### ISSUE TITLE
[1.10.2] Oxygen sealer oxygen use varies in build 66

### ISSUE THREAD

**Issue by themechman** [micdoodle8/Galacticraft#2635]
I see that the oxygen sealer when it is attempting to detect the seal consumes oxygen at 240/sec. When it seals, it changes to 40/sec, is this a visual glitch?

![2017-04-23_21 53 35](https://cloud.githubusercontent.com/assets/2990361/25319803/6b2bf5fc-286f-11e7-811b-60c0675ef903.png)
![2017-04-23_21 53 37](https://cloud.githubusercontent.com/assets/2990361/25319802/6b25ccae-286f-11e7-9fc3-5e554af0eed9.png)
![2017-04-23_21 53 47](https://cloud.githubusercontent.com/assets/2990361/25319804/6b312ffe-286f-11e7-8983-444a905eb31d.png)

Next question. What is the cubic meters that each sealer now seals? The reason I ask, is that I need four sealers for an area that should need only two. It seems more than before, but I am going to check a few other constructs.

**Comment by themechman** [comment]
It appears that the sealer is able to seal a medium room, but the area i was sealing before was bigger than i thought. Just didnt think it was 4 sealer worthy.

Any way to make a single sealer consume oxygen and power at a rate commensurate with the room it is located in?

**Comment by radfast** [comment]
What you're seeing is fully intended behaviour.

If the Oxygen Sealer is in a not sealed space, it will spew oxygen like crazy (240 / s) and waste it.

It's your job as a player to seal the room before using the Oxygen Sealer, or don't connect your main oxygen supply until you're ready.

The main reason for this design is to eliminate the server lag when people build a base with **just about enough oxygen** for their sealers but not quite enough, so that the sealers flip between sealed and unsealed all the time.  Now, if the player doesn't have enough oxygen, the sealer will go unsealed and will stay that way, because when it goes unsealed it will lose oxygen even faster than before.

I also think it's kind of realistic.

A **planned feature** to help you build is a leak detector.  Actually the game already knows exactly where the leak is, I just didn't have time to make a system which draws it for you the player.

**Comment by themechman** [comment]
Excellent. Thank you.
