### ISSUE TITLE
Server Crash Build #76 Version 1.10.2

### ISSUE THREAD

**Issue by jobensingh** [micdoodle8/Galacticraft#2647]
Crashes the second start up is finished. Console reads that a single server tick took 64.5 ticks or something like that.

Crash Report:
https://pastebin.com/yna6kEHJ

**Comment by jobensingh** [comment]
Figured out that its an issue with sponge, works when I remove it, could compatibility possibly be added?

**Comment by radfast** [comment]
**Galacticraft is compatible with Sponge.**

You can fix this problem as explained [here](https://github.com/micdoodle8/Galacticraft/issues/2612#issuecomment-295057307)

As you can see from your logs, the problem is simply that generating the map around the spawn areas is taking a long time, takes around 4-5 minutes the very first time you start the server, but it only has to happen once.  Your server will be fine after the spawn areas are generated.

If you don't want to change your server properties, just keep on re-starting the server, it should be able to generate a bit more map each time, until it is finished.

I can't believe we're the only mod to have this issue... ultimately it's a bug in Sponge, not Galacticraft - Sponge will take a long time to generate spawn maps when there are many Forge mods with many dimensions present.  We register our dimensions with Sponge as "don't generate spawn" but Sponge generates the spawn anyhow, that's the bug.  I have spent literally 1 whole day of my coding time last week trying to find the bug in Sponge so that we can workaround it, but I didn't find it yet.

**Comment by jobensingh** [comment]
Thanks! Had a bunch of plugins for sponge made to work with a space race Im hosting. Didnt want to let 25 people down!

**Comment by radfast** [comment]
ok, let us know how it goes.  You are welcome to report any other issues, sounds like you will be testing Galacticraft hard.

(The mod **is** still in beta in 1.10.2, there may be minor issues still.  And more blocks and worldgen will be added still, though it's unlikely that the Moon or Mars will be changing.)

**Comment by radfast** [comment]
https://wiki.micdoodle8.com/wiki/Tutorials/Space_Station_for_Server_Admins

**Comment by jobensingh** [comment]
It worked out, but there are a few issues, im doubtful they are related with sponge, so I posted them in a new issue, other than that everything is great! Thanks again for the help.
