### ISSUE TITLE
[1.10.2] [Gravestone mod] Crash landed on top of Gravestone. Goes back. Infinite entities duplicating.

### ISSUE THREAD

**Issue by Axiom1999** [micdoodle8/Galacticraft#2648]
No error log.
Just a ton of entities being created (thousands).
My game started lagging after around 6k entities. Had to shutdown my server.

**Comment by radfast** [comment]
More details please.

1. Type of server (vanilla / Sponge / other).   Is it a dedicated server or a Minecraft client switched to become a LAN server?

2.  Exact Forge (+ Sponge) versions

3.  Please provide your full server-latest.log to cover the incident, so that I can see your other mods and also Galacticraft standard logging.

4.  Is the problem reproduced if you log in to the server again?  If so, please enable Galacticraft's debug logging (in configs) and provide the log.

5.  Perhaps most importantly: **what entities are these, the ones being created?**

**Comment by Axiom1999** [comment]
Restarted server. And re-logged. The entities are gone.

**Comment by radfast** [comment]
good news.  Though I'd still like to investigate this, if it's happened to you it could happen to someone else (assuming Galacticraft is the cause...)

Any chance of the info 1-3 and 5?

**Comment by Axiom1999** [comment]
2. Around BETA 71 (compiled myself for latest fixes).
5. I honestly don't know. There were items from the explosion. I immediately typed '/kill @e[type=!Player]' which destroyed the items, but not the entities being created.

**Comment by radfast** [comment]
but ... but ... that /kill should kill all entities **except** players.  So this suggests it was spawning thousands of players?

This is a serious issue if it's doing that.  Galacticraft does have a poke at the player spawning code, to make sure we get a GCEntityPlayerMP always.  Any other mods installed?  Anything which could modify standard Forge classes?

**Comment by Axiom1999** [comment]
I do have Gravestone mod installed. In which when broken it spawns a ghost of a player. Perhaps that is the issue. Since I had a Gravestone directly where the impact was.

**Comment by radfast** [comment]
lol, you could have said that at the start!  Very likely connected.

**Comment by radfast** [comment]
I've looked at this some more.  I think it's an issue in the Gravestone mod.  The problem was the player was dying in an explosion, and the **same explosion** also destroyed the existing gravestone in the exact same spot.

Please report it to the Gravestone mod author.  I think it can probably be reproduced with vanilla TNT explosions, as long as you can line things up to hit the exact same spot.

The Galacticraft lander doesn't do anything weird here, it just creates an explosion with force 12 when it hits the ground, that's a bit larger than one TNT. 

In this case because you were testing our mod, you spawned landers over and over and they hit the ground in the exact same spot each time, creating an explosion in the spot where the last death was - and with Gravestone installed, that spot is going to have a gravestone on it.
