### ISSUE TITLE
Compatibility With Actual Additions

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#2664]
please support that mod, i'm trying to connect coalgenerator to crusher with laser relay from actually additions, but no work. thanks...
1.11.2

**Comment by ThomasAunvik** [comment]
I think this 'support' also applies to other RF and Testla. I think GC just need to get Forge Energy support.

**Comment by kenijey** [comment]
yeah, it would be lovely ^^

**Comment by dj3520** [comment]
Support all the things. Convert all the things. Unify all the things.
```- Galacticraft 4™```

**Comment by kenijey** [comment]
not all the things, saying that would be rude. It's just forge energy, which is a popular energy.

**Comment by radfast** [comment]
Guys you're both a bit confused, there is no "Forge energy"!!

RF energy is an API made for power transfer between CoFH mods like Thermal Expansion and Big Reactors etc.  Because it's a small API and therefore simple for mod authors to use without having to think too much about electricity and physics, a large number of other mods like EnderIO picked it up.  Now most mods use it, with some grand exceptions: IC2 has its own systems which some other mods are compatible with, and Gregtech refuses to be compatible with anyone.

Galacticraft solves these problems for players by being compatible with **both** RF energy **and** IC2 energy.  Galacticraft has been compatible with RF energy for 2-3 years now.  It's fully covered on our wiki!

The Coal Generator output not connecting was just a bug, fixed in [Build 80](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) which is now available.

**Comment by kenijey** [comment]
oh... really weird. did i only try coal generator... hmm... i think... so, thanks!
