### ISSUE TITLE
lander not spawning until re-log to server [Sponge versions 2160 and later] [1.10.2]

### ISSUE THREAD

**Issue by jobensingh** [micdoodle8/Galacticraft#2668]
For some reason whenever the server is loaded, the first time the player enters a planet such as the moon after the startup, its as if they don't exist unless they disconnect from the server and reconnect. What usually happens when I player enters from a spaceship, after the select a planet they want to go to, they are just floating in the sky with no shuttle to take them down, and they cant do anything but move around unless they, as I said before relog. Iv tried teleporting straight to the world instead of using a space ship as well with the same problem, except im not floating in the sky, Im just unable to doing anything but move around from the area I teleported. Also I can post video of this if it would help. The only other mods I have are mekanism and sponge. Thanks

**Comment by radfast** [comment]
Please update to BETA build 79, let us know if that fixes it.  (Server and clients must both update, obviously)

If it's still a problem in build 79, please provide more details:
* Forge version
* Server details (including Sponge etc if present)
* Other mods installed
* If possible please test Galacticraft build 79 for your server and players with no other mods installed - or try to reduce your modlist to a minimum combination of mods which triggers this problem.

**Comment by radfast** [comment]
I have a test server set up with Sponge in Minecraft 1.10.2, and the dimension transfers are working properly on that, so I'm trying to figure out what's different about your setup....

**Comment by jobensingh** [comment]
Im updating right now, deleted the previous world just to be safe, Ill let you know in a few minutes how it turns out

**Comment by radfast** [comment]
please also test standard **Nether Portals**, do you get similar problems after a player passes through them?

What we do in Galacticraft isn't too far different from how Nether Portals work.

**Comment by jobensingh** [comment]
Forge Version: forge-1.10.2-12.18.3.2281-universal
Server Details: Not sure what to put besides minecraft 1.10.2 and sponge version which is spongeforge-1.10.2-2281-5.2.0-BETA-2274
Works with only galacticraft, does not work when sponge is added.
Noticed a stack trace error when the bug occurs: https://pastebin.com/eqBG7nqb
No Problem with nether portals

**Comment by radfast** [comment]
ok that stack trace error is the key to this I think

we'll take a look.  meanwhile I guess your players will just need to quickly re-log when changing planets, sorry

**Comment by radfast** [comment]
I can't seem to reproduce this on my Sponge test server.

Please can you zip up your entire ```.minecraft/config``` folder from the **server** for me.

Also if I could get the whole of that log which you posted an extract from.  (I assume that was a ```fml-server-latest.log``` or from server console?)

**Comment by jobensingh** [comment]
Here is the config: https://www.dropbox.com/s/6l4b4wu9pa7logd/config.zip?dl=0
Here is the log: https://www.dropbox.com/s/k21tjixmkwflaav/fml-server-latest.log?dl=0

**Comment by radfast** [comment]
thank you!  i'll post again if I need anything else.  reproducing the issue is the problem here, once I can reproduce it then with any luck I can fix it

**Comment by radfast** [comment]
sorry one more question - you did check that it still produces the problem without your spaceracescore pluging.  I don't see that collecting spacerace data could have any impact, but best check to be sure, as that is one obvious difference between your setup and my test server.

**Comment by radfast** [comment]
ok I've been able to **reproduce the problem**.  Looks like it's a problem in latest Sponge versions only.  If you're able to roll back to an older Sponge, the problem is not there.

I'm currently trying to figure out which exact Sponge update broke this.

Anyhow, shows it's not a Galacticraft issue.

**Comment by jobensingh** [comment]
Alright, when you figure out what version let me know, so I can rollback before it. Thanks

**Comment by radfast** [comment]
In my tests:

spongeforge-1.10.2-2202-5.1.0-BETA-2099 **does not** have the issue
spongeforge-1.10.2-2221-5.2.0-BETA-2212 does have the issue

Please try 2099 and see if it's OK for you too.  Obviously, you'll need the matching Forge version 2202...

_Note of caution:_  I didn't update my client-side Forge versions to match, to avoid the need to keep re-starting the client.  All tested using Forge version 2239 clientside.   If your testing shows something different from my testing then it could be related to Forge version mismatch between server and client, and not Sponge at all....  But for now I'm going to assume it's Sponge.  Also because your testing shows the issue didn't happen without Sponge.

**Comment by jobensingh** [comment]
That  did fix the issue, however some of the mods within the server don't support the downgrade in forge, so I guess for now my players will just restart their games, I'm gonna try and see if I can respawn their entities upon reaching the planet to see if that might fix it.

**Comment by radfast** [comment]
don't respawn their entities, that almost certainly won't work
Their entities need to be spawned by Galacticraft.

I've now tested **spongeforge-1.10.2-2221-5.1.0-BETA-2113**, this one works OK.   So you can use Forge 2221 if that helps at all.

**Comment by jobensingh** [comment]
Ill try it out, thanks for letting me know

**Comment by jobensingh** [comment]
Hmmm, what I figured out while testing is that the player is only required to relog if he traveled between dimensions via rocket, If they use commands to teleport only then they are fine. If they use a rocket and then use commands, commands will have the same effect as the rocket

**Comment by radfast** [comment]
I'm glad you have a workable solution for now.

It's clear that Sponge has broken something, I have figured out which version now.

Everything up to Sponge version **spongeforge-1.10.2-2221-5.1.0-BETA-2158** is OK with Galacticraft.
Sponge version 2160 breaks the rocket lander spawning.

**Comment by radfast** [comment]
I should be able to fix this fully from next build 80, I think.
I'll let you know when that's ready for testing, might be a day or two.

**Comment by radfast** [comment]
I've figured out you can workaround this issue in **any** version of Sponge including the latest versions just be including one thing on your command line when you start the server.

That thing you need is:
>
     -Dsponge.causeTracking=false 

Example of a complete server launch command line with this:
>
    java -Xmx2G -Dsponge.causeTracking=false -jar forge-1.10.2-12.18.3.2281-universal nogui

**Comment by radfast** [comment]
The issue is now fixed for all Sponge versions in [Build 80](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/)

You probably don't even need to use that command line (it's working without it in my testing).  But it's worth remembering that command line as a potential fix for other future problems.  It also increases server performance by 3-4% in my testing.  Basically, Sponge's "cause tracking" makes better crash reports, but slows down all internal actions of the server slightly.

Also fixed the other EntityTracker stacktrace error you posted above.

@jobensingh thank you very much for your help reporting these issues and testing, it's really helped the mod.

**Comment by jobensingh** [comment]
Thanks for fixing it glad I could help, be sure to report any other bugs I come across!
