### ISSUE TITLE
[1.11.2] [80 BETA] shift clicking a dye into painter crashes the game

### ISSUE THREAD

**Issue by vos3464** [micdoodle8/Galacticraft#2674]
Shift clicking an item or a dye into Painter crashes the game.
[Crash Log](https://pastebin.com/ydQwXzkT)

**Comment by radfast** [comment]
Thank you for beta testing this!

Found and fixed, it will be in next build 81.  I guess you can manage without shift-clicking into the Painter?

In fact currently shift-clicking dyes would have no effect (it does nothing in 1.8.9 and 1.10.2), that's because you can actually put a wide variety of blocks and items into the 'Mix Colors' slot, the machine can take color from most things.  Try it with dirt, stone, wool, etc.

**Comment by radfast** [comment]
[Build 81](https://ci.micdoodle8.com/job/Galacticraft-1.11/81/) now available
