### ISSUE TITLE
[1.10.2-Build-80] Forge bucket load infinite fuel

### ISSUE THREAD

**Issue by bortooo** [micdoodle8/Galacticraft#2677]
When you put a fuel bucket from GC, it loads 1 bucket of fuel and gives back an empty bucket.

![2017-05-04_20 15 07](https://cloud.githubusercontent.com/assets/28114042/25718535/c3f853c0-3106-11e7-95ba-8542b2983316.png)

When you put a forge bucket, it loads infinite fuel and doesn't give back the empty bucket.

![2017-05-04_20 15 32](https://cloud.githubusercontent.com/assets/28114042/25718616/0a47bd16-3107-11e7-92a7-0ee01eda083e.png)

**Comment by radfast** [comment]
Thanks for reporting.   This will be fixed in next build 81.

(The issue was that the Forge bucket of Rocket Fuel didn't think it could supply "fuel", so Forge didn't empty the bucket.   Because the bucket didn't empty, every tick the game found a full bucket in that slot and filled the tank from it again -> infinite fuel!)

**Comment by radfast** [comment]
[Build 81](https://ci.micdoodle8.com/job/Galacticraft-1.11/81/) now available

Please let me know if you spot any more bucket issues.

**Comment by bortooo** [comment]
Sure! I like to help you, but I'm so sad that I can't  use this bug anymore :c
