### ISSUE TITLE
[1.11.2] Latest build crashes with Optifine.

### ISSUE THREAD

**Issue by booski2005** [micdoodle8/Galacticraft#2693]
This didn't happen with earlier builds and the last I've tried is probably 81, where Optifine worked. Now, using build 84, the game crashes when I try to join a world with Optifine. I'll try to specify the build where the problem started later but this is what I have for now. It happens for both creating and loading worlds. I'm sorry for not being able to attach a crash log but my computer is having problems with github right now.

**Comment by radfast** [comment]
Please provide that crash log when you can, I can't do anything without that.  You haven't said which Optifine and Forge versions, though those will be in the crash log when you post it.

Generally I'd suggest don't use Optifine unless there's a reason you absolutely have to.  It breaks compatibility with a lot of mods and the Optifine developer's attitude is ... unhelpful.  And it's not really necessary for performance reasons ever since 1.8.9.

**Comment by booski2005** [comment]
Crash Log:
https://hastebin.com/efijegoqeg.md

**Comment by radfast** [comment]
Thanks for the log.

I've looked at this.  Doesn't look like there is any connection with Galacticraft.  The "NoSuchMethodError" is being reported on a part of vanilla Minecraft which is not used anywhere in our mod.

Most likely, it's a bug in the latest version of Optifine.
