### ISSUE TITLE
[1.11.2] Two different types of fuels.

### ISSUE THREAD

**Issue by ZetronPlayz** [micdoodle8/Galacticraft#2694]
![fuel](https://cloud.githubusercontent.com/assets/28192726/25785355/288f8512-3376-11e7-9d0c-5144315c2d99.png)
Build 84

**Comment by ThomasAunvik** [comment]
Alerady reported.

**Comment by radfast** [comment]
It's one type of fuel and 2 types of bucket.

As explained elsewhere, the bucket on the right is the Galacticraft bucket used by our mod.  The bucket on the left is a Forge bucket, provided for compatibility reasons only, because Forge in Minecraft 1.11.2 broke the ability to have other mods fill a Galacticraft bucket.  I think the Forge bucket looks ugly, and their new system is less good than their old system, but unfortunately that's how it has to be.

**Comment by radfast** [comment]
thank you @ThomasAunvik  :)
