### ISSUE TITLE
[1.10.2-1.11.2] server cpu at 100%

### ISSUE THREAD

**Issue by silent-mobious** [micdoodle8/Galacticraft#2695]
Whenever I start a new server with only the Galacticraft latest build 84 for both 1.10.2 and 1.11.2 I get a core on the server that pegs at 100%.  Nothing appears to be logged out of the ordinary.

**Versions tested**: build 84 and several back through 75, all exhibiting the same behavior
**Forge versions used**: for 1.10.2 both forge-1.10.2-12.18.3.2185-universal and forge-1.10.2-12.18.3.2281-universal.  For 1.11.2 forge-1.11.2-13.20.0.2296-universal.
**Java installed**: OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-4-b13) on Ubuntu 17.04
**Start script**:  java -jar forge-1.11.2-13.20.0.2296-universal.jar -Xms8G -Xmx8G nogui
**Behavior**:
![image](https://cloud.githubusercontent.com/assets/12705402/25785760/3b88e868-3356-11e7-97a2-6236548086f6.png)
**Log**: https://pastebin.com/8vQDtMVk

**Comment by radfast** [comment]
This is intended behaviour, not a bug.  It's actually processing at full core speed.  It will be like this for around ~1 hour after first starting the server.
* for a vanilla server that 1 hour is cumulative, for example you could run the server 12 times for 5 minutes each and it would do what it wants to do
* for a Sponge server, that has to be 1 hour solid, because Sponge somehow messed up our progress saving on server shutdown, I didn't yet figure out which stage Sponge skips

I reckon most people these days have a CPU core to spare for this.  But if you don't and so this is a problem for you, just run the server overnight for an hour or two with no players online, Galacticraft will do the background processing it needs to do, save it, and then your server will be good to go.

[Further reading](https://wiki.micdoodle8.com/wiki/Sponge)

**Comment by silent-mobious** [comment]
Ok, cool!  I originally had the minecraft box as a vm guest on one of my esx servers, I hadn't ever let it run for more than 10 min or so before shutting it down and continuing to troubleshoot.  I just don't like cpu's pegged for unknown reasons.  :)  I finally figured it was something with the environment, even though I'd never had issues before, and spun up another Ubuntu server on bare metal but got the same behavior.  Looks like the cpu went back to normal after about 25 min on this one, though.  Is this a one-time behavior, or will Galacticraft need to do whatever processing it's doing again as the server is used in the future?  Like if I chunkgen a few million chunks overnight to populate the map?  Yeah I've got cores for days, but like I said I like knowing what they're doing.  :)

Thanks!

**Comment by radfast** [comment]
Like I wrote already, here or on the wiki, Galacticraft needs to do it **one time only**, at the first server start.

If it's taking 25 minutes not 1 hour that I wrote, that's probably because your boxes are a bit quicker than average :)  On my development PC, it's between 52 minutes and 1 hour, depending on world seed and other mysterious factors.

You can see when it's done by checking the world save folder on the server, or by logging in with a client and then checking the assets folder.  In more detail:
* On a Sponge server, look in the world save folder for the file ```galacticraft/overworldMap/Overworld1536.bin```, that only gets created when its done.
* On a standard Forge server, look for that same ```Overworld1536.bin``` file and you'd need to use a hex editor to examine the last couple hundred bytes in the file, if they are all zero apart from a 4-byte signature at the end then it didn't finish yet but it's saved its progress into the file.  When the file is fully populated with non-zeros then it's finished.
* On a client, after playing on the server for 30 seconds to 1 minute or so, look for the file ```.minecraft/assets/galacticraftMaps/large.jpg``` - if that's present then the server finished generating the map, sent it across to the client over the network in compressed form (~1.5MB), and the client successfully constructed it and made a .jpg which is purely (for now) for preview purposes so we can check this is working OK
* But if the client is running OpenJDK, the .jpg file probably won't get generated, this is due to a known bug in OpenJDK with the JPEG libraries - it's possible this bug has been fixed, I last researched it 2 years ago, but if Galacticraft detects the bug Galacticraft will report in logs, and disable this .jpg creation on the client.  That won't affect planned future gameplay, it simply means you don't get the preview .jpg file saved to disk.

For completeness, I should say that Galacticraft runs the same background mapping thread every time you place down a Display Screen in a fresh spot.  But for Display Screens it's only generating a local map, which is very quick, probably less than 2 seconds on your servers.  So you might see CPU briefly redline to 100% on one core when you place a Display Screen.  Again, because it's fully multithreaded code, it should have zero impact on game performance, assuming you have a core free.

**Comment by radfast** [comment]
I'll move some of the above info to the wiki when I have time to format it properly...

**Comment by silent-mobious** [comment]
Ok, very cool, didn't see the page regarding Sponge on the wiki at all.  Thanks a lot for your help!

**Comment by radfast** [comment]
Pleasure, we like to support servers.  You'll presumably be running Sponge eventually?  I've looked at Sponge in some detail, I think it's a great project, though the devs aren't that quick at fixing issues and it looks like a few Forge mods currently have problems with it.  I'm sure eventually every mod will have to be compatible with it.

**Comment by radfast** [comment]
[Build 85 now available](https://forum.micdoodle8.com/index.php?threads/looking-for-1-8-9-1-10-2-1-11-2-beta-testers.6555/) - fixes the compatibility with Geographicraft.

**Comment by radfast** [comment]
Note:  with either Geographicraft or Biomes o'Plenty present, the background map generation is slower.  So your 25 minutes of 1 core at 100% on a fresh server might now be 35-40 minutes, at a guess...

**Comment by silent-mobious** [comment]
Sweet...  Will give it a try now. Thanks a lot!

**Comment by radfast** [comment]
Please use [build 86](https://ci.micdoodle8.com/job/Galacticraft-1.10/).  (Build 85 had a bug)
