### ISSUE TITLE
[1.8.9] Memory usage increased immediately after creating world (Normal world type)

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2698]
Before create new world.
![1](https://cloud.githubusercontent.com/assets/6128413/25829376/d2503592-347f-11e7-841e-8a3b137e10c9.png)

After create new world and my Minecraft get not responding.
![2](https://cloud.githubusercontent.com/assets/6128413/25829377/d299f326-347f-11e7-9029-8864a3a33d69.png)

Debug config.
![untitled](https://cloud.githubusercontent.com/assets/6128413/25829419/29703c00-3480-11e7-97fc-1ed1d6fd0cbd.png)

Caused by this? https://github.com/micdoodle8/Galacticraft/commit/83fe9554bd1b1d97fa623b2413b3aa00c3475843

**Comment by radfast** [comment]
This is WIP, it may not be stable yet, in between Jenkins builds.

**Comment by radfast** [comment]
You will also need to pull the matching MicdoodleCore ... that has changed.

**Comment by radfast** [comment]
Yes to confirm, the reason for what you saw was - I'm sure - not having the latest ```MicdoodleCore```.

(Without the matching MicdoodleCore, the background mapping code which runs on a new server would have called for aints from IntCache in vanilla code, but never reset that IntCache because we now maintain two IntCaches is parallel, one for vanilla threads and one for our background mapping thread.  

The system works correctly without memory leaks so long as you have the matching MicdoodleCore.)

**Comment by radfast** [comment]
Sources are now stable after the background mapping changes in last 1-2 days.  Please make sure to update again to latest ```MicdoodleCore```

**Comment by SteveKunG** [comment]
Thank you very much for your hard working :D

**Comment by radfast** [comment]
:)

need to update ```MicdoodleCore``` again, there was a [typo](https://github.com/micdoodle8/MicdoodleCore/commit/0391b40082d2d79c9efde2af9f4e189e3dfcfdec)
