### ISSUE TITLE
[1.11.2] Rocket HUD not visible in 1st person view

### ISSUE THREAD

**Issue by fayer3** [micdoodle8/Galacticraft#2722]
when entering a Rocket and being in 1st person view the countdown and the height meter is not shown
![3rd person](https://cloud.githubusercontent.com/assets/8282299/26198273/bda9dbd2-3bc5-11e7-9958-fcfa65f8cfcc.png)
![1st person](https://cloud.githubusercontent.com/assets/8282299/26198276/beb76922-3bc5-11e7-86f1-7e65f4a1cadf.png)

using: galacticraft 1.11.2-4.0.0.91-BETA

**Comment by SteveKunG** [comment]
It is intended feature?

**Comment by fayer3** [comment]
I just noticed that this also affects the moonlander speed display.

**Comment by radfast** [comment]
Thank you @SteveKunG 

Yes this is [intended](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tick/TickHandlerClient.java#L250)   Been this way since at least [Galacticraft 2](https://github.com/micdoodle8/Galacticraft/blob/MC1.6/common/micdoodle8/mods/galacticraft/core/tick/GCCoreTickHandlerClient.java#L435)

I think it's for immersion.  One specific reason is that people using 3D / Virtual Reality systems (Vivecraft etc) normally want the first person view for rockets and an extra GUI can look strange "floating in the air" on those systems.
