### ISSUE TITLE
[1.10.2]  Lighting Panels end up "face" down on restart or chunk unload/load

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2743]
I tested all of them, placing them to face different directions and leaving them or using wrench to rotate them. It doesn't happen all at once but will all eventually end up facing down.

Minecraft 1.10.2
Forge-12.18.3.228

GalacticraftCore-1.10.2-4.0.0.84-BETA
Galacticraft-Planets-1.10.2-4.0.0.84-BETA
MicdoodleCore-1.10.2-4.0.0.84-BETA

ModList
https://pastebin.com/QpQ9ff3x

**Comment by radfast** [comment]
Please update your Galacticraft to the latest BETA version 99, and let us know if it's still a problem.  I think most likely this has been fixed.

**Comment by radfast** [comment]
Presumably the blocks are also losing their **color**, and reverting to white light and the TIn Deco Block look?

Technical note for devs: the only possible cause of this is that the TileEntity for the block is being invalidated server-side.  If it's invalidated, on re-creation it won't have any of the saved NBT data - see ```world.getTileEntity()```.

The real question here is what is invalidating this?

**Comment by radfast** [comment]
@TheQuadShot another question for you, are you seeing any other issues **at all** in your base where this is happening, like machines "forgetting" their settings or being found empty when you thought they had items in?

Can you post a screenshot identifying all the blocks which are next to these Lighting Panels?

**Comment by TheQuadShot** [comment]
The blocks in the immediate area are vanilla stone bricks/stone slabs/dirt, and GC machines, Storage Drawers, and a Refinded Storage terminal/receiver setup. In the same chunk I also have a some Immersive Engineering lights and turrets (powered by Draconic wireless power crystals, all of my GC machines are powerd by GC advanced solar panels) in the area around the landing pad (where I have the panel blocks and my GC workshop) and I am currently looking at a problem with the IE turrets. They lost all of the ammo I had in them and now with a ticking entity problem. https://github.com/BluSunrize/ImmersiveEngineering/issues/2117

I hope that helps. If not let me know and I'll provide what ever I can.

**Comment by radfast** [comment]
OK, the IE turrets "losing" all the ammo you had in them is the **same** issue as the Lighting Panels.

The Lighting Panels are not broken or bugged, and the IE turrets are also not broken or bugged.

**Something else** in your modpack is destroying the TileEntities for these blocks so they lose saved info.  For Lighting Panels, saved info is their orientation and color.  For IE turrets, saved info is their ammo.  (Probably other machines or blocks nearby may also be losing saved info or contents, or maybe you don't have anything else with contents saved?)

It's **extremely unlikely** that this is a Galacticraft issue, I already checked all our code and fairly sure we don't have anything which could do this.

The best thing for you to do is try to figure out what's **really** causing this.

Two ways to approach that.  You could make a smaller series of test bases / test rooms - they can be simple, you don't need more than one Lighting Panel and IE turret in each one.  Put them in different chunks.  Put one or two different things with each one, try out different elements of your base.  Play normally for a while, and see which ones out of these rooms "forget" their saved info.

The other way is the same advice for anyone with a problem in a large modlist, first make a backup of your world, then start pulling mods out of your modlist in groups, restart your world, play a bit, see if the issue still occurs.  If the issue has stopped, then you know it was a problem with one of the mods you just pulled out of the list.  You could divide your modlist into fourths or 8 parts to do this.   You could also start at the other end, make a test world with just Galacticraft and IE and see if that plays OK, then start adding mods back in in groups untli you notice the problem starting.  Obviously, you'll need to write notes so you know which mods you most recently added or removed.

Closing this because I'm fairly confident it's **not** a Galacticraft issue, but we can easily re-open if it is.  I'm happy to continue talking about it, or if you have some results from doing the type of testing I just wrote about, we can follow up from that.

**Comment by radfast** [comment]
Please also update to the latest Galacticraft version 99, that's a good idea anyhow.

**Comment by radfast** [comment]
BTW, you know you can change those Lighting Panels to look like (almost) any block just by shift-right click?

Grass is about the only block this doesn't work for, you'll get this weird grey grass, not green (it's because vanilla Minecraft grass takes its green color from the biome).
