### ISSUE TITLE
[1.11.2] All blocks changed

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#2755]
When I upgraded from build 99 to build 100 all my aluminum wires turned into green shulker boxes! My metallic crafting table turned into a oxygen detector, my NASA workbench turned into launch pads and fluid pipes, and much more. my world is now fully messed up! Are you able to fix this or should I create a new world?
BEFORE:
![2017-05-27_19 30 30](https://cloud.githubusercontent.com/assets/28928887/26525653/08300768-4313-11e7-8b83-2b920782a3e0.png)
AFTER:
![2017-05-27_08 27 00](https://cloud.githubusercontent.com/assets/28928887/26522464/47a428b4-42b6-11e7-9dab-baa12363a793.png)

**Comment by radfast** [comment]
Can you post your log from the game session when this change happened?

Did Forge save a backup of your world as a zip?

**Comment by marcus8448** [comment]
Nope no log. And forge did not make any backup I have a vrey very old version of the world (if that helps?) And I have not added any mods for a while.

**Comment by radfast** [comment]
There's nothing we can do to help, I think.  It's a big mystery why this happened, because, like I said, Galacticraft has not added or removed any blocks between versions 99 and 100.

I think the best advice is for you to go into Creative and fix up your world, deleting all the blocks which changed and replacing them with what's intended.  Will probably take you much less time than creating a whole new world!

**Comment by marcus8448** [comment]
Just wondering but, @radfast maybe your commit to fix #2746 may have made the shulker boxes/change the blocks? Cause in the crash report it says something about shulker boxes 
`-- Block entity being ticked --
Details:
	Name: minecraft:gc air compressor // micdoodle8.mods.galacticraft.core.tile.TileEntityOxygenCompressor
	Block type: ID #229 (tile.shulkerBoxPurple // net.minecraft.block.BlockShulkerBox)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-673,43,620), Chunk: (at 15,2,12 in -43,38; contains blocks -688,0,608 to -673,255,623), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,0,512 to -513,255,1023)
	Actual block type: ID #229 (tile.shulkerBoxPurple // net.minecraft.block.BlockShulkerBox)
	Actual block data value: 3 / 0x3 / 0b0011`

And you see the purple box in the corner? It was a oxygen compressor...

**Comment by radfast** [comment]
Not possible that that commit caused it.

The issue here is connected with Minecraft or Forge translating a saved world file into the wrong block types, it's not specifically connected with Galacticraft.

Maybe changing or updating a mod (including Galacticraft) caused a problem with an existing saved world - normally updating a mod does not cause this problem, but once or twice I've seen large scale changes, or adding or deleting a large number of mods from a modpack, have similar effects.  It's recommended you don't make major changes to your modlist with existing worlds.

Another possible cause, if you were playing on a server, is mismatched Forge or mod versions.  This can probably be fixed by ensuring client mod versions match the server.
