### ISSUE TITLE
[1.7.10] exception java.lang.IllegalArgumentException: Could not get provider type for dimension -30, does not exist

### ISSUE THREAD

**Issue by PantACRO4life** [micdoodle8/Galacticraft#2766]
I own a modpack called boundless skies also a server but from my modpack on my server never get any crash.... when we try to play singleplayer its all the time crash because of an exception of dimension -30 see the crash-log.txt
also from the latest.txt start from line [4394]

[crash-log.txt](https://github.com/micdoodle8/Galacticraft/files/1034327/crash-log.txt)

[latest.txt](https://github.com/micdoodle8/Galacticraft/files/1034328/latest.txt) line [4394]

**Comment by radfast** [comment]
The usual cause for this type of issue is conflicts between 2 different add-ons for Galacticraft.

You are trying to combine 4 Space and Extra Planets.  That may not be possible, or you may need to carefully adjust configs for both so that they work together - I'm sorry I don't know details, I don't play either myself, you can ask their authors on their Githubs.

If it's working on your server but not working in single player, then maybe the configs are different on the server?

**Comment by PantACRO4life** [comment]
sorry for the delay and also yes this is what im trying to do 4space + extraplanet so ill ride one out ... Should it fix my case ?

**Comment by radfast** [comment]
yes, taking one out should normally fix the problem  (if things are really messed up, you might want to also delete the configs from all these mods and let them auto-generate fresh configs)

**Comment by PantACRO4life** [comment]
Alright thanks
