### ISSUE TITLE
[1.8.9] game crash with energy.grid.NetworkFinder

### ISSUE THREAD

**Issue by creeerik** [micdoodle8/Galacticraft#2767]
i run a forge server with Galacticraft on my laptop.
and if i or my friends break a Galacticraft block in survival then our game chrashes .
here is the crash report.
https://github.com/micdoodle8/Galacticraft/files/1034338/crash-2017-05-28_18.50.47-server.txt

**Comment by radfast** [comment]
This is a strange one.

Has Galacticraft worked for you before in 1.8.9, or this is the first time you're trying it?  If it worked before now, which was the last version which was OK?

**Comment by creeerik** [comment]
It has never worked for me before. This is the first time I have played the mod. Even I'm single player it chrashes.

**Comment by radfast** [comment]
I'm sorry, I know how frustrating crashes can be.  As I say, this one is strange because Galacticraft has been fairly thoroughly tested in 1.8.9 by now and nobody else has reported anything like this.

Can I check a few things with you:

(1)  It's only the server that's crashing, and not the client?

(2)  Do you get the same issue if you make a new world on the server (obviously, first backup or rename your current ```world``` folder)?   So delete/rename the ```world``` folder, start the server and let it generate a new world, then place down a few of the same blocks in Creative, switch to survival, break them, what happens?

(3)  The issue appears to be something connected with Aluminium Wires, are you seeing the crash only when you break wires or is it for any Galacticraft block, for example Rocket Launch Pad?

(4)  Please check that server and client both have the exact same versions of Galacticraft and the same versions of Forge.

**Comment by creeerik** [comment]
when i opened the folder i saw there were three zip files called world-a lot of numbers so i removed them and erplaced my world folder with a world of my old server. when i broke a Galacticraft block and it worked jaj!!!!!! after putting the world that was in the folder before, i started the server and joined. i broke a Galacticraft bolck and it worked to. i can't tel if it were the other (world-a lot of numbers) zip files or replcing the worrldor back. but my server works again and thank you for your time :-)

**Comment by radfast** [comment]
OK,  that's good news

Please use latest Galacticraft, version 4.0.0.102, it's the best.

**Comment by radfast** [comment]
Build 104 now available.
