### ISSUE TITLE
Shield Controller as uncraftable item loot

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#2770]
> Besides the Breathing Equipment, the player must be also wearing Tier 2 Thermal Paddings and a Shield Controller in order to survive in the hostile environment once outside the Entry Pod.
 
From: https://wiki.micdoodle8.com/wiki/Venus#Accessing, §2.

I wrote that assuming it was a requirement because... why I would want to lose my armor and be exposed to mobs? Now I've just found out it's an uncraftable item (NEI/JEI doesn't show any recipe) which is given as reward.
<details> 
  <summary>Obtaining the Shield Controller</summary>

The Shield Controller is found in the Tier 3 Treasure Chest after beating the boss, which reinforces my suspicion the item is actually uncraftable.

![2017-05-28_17 29 51](https://cloud.githubusercontent.com/assets/6743303/26531961/5eb15f20-43cb-11e7-89e5-2f4e2a26b7c0.png)

Sometimes the Treasure Chest has only the Volcanic Pickaxe, instead.
-----</details>

The problem with that is that even my Titatium armor set will be gone in matter of minutes, likely way before managing to obtain the Shield Controller.

I propose (1) using Beam Core and Titanium Ingots as part of the crafting recipe, or (2) as tradable item with titanium ingots (to force the player to visit the Asteroids dimension).

**Comment by radfast** [comment]
The Shield Controller is a more powerful item now, because it protects your armor from **all** damage.

It's intended to be a non-craftable treasure item, and because your armor is damaged without it, we hope players will appreciate it even more.

Our intention is that you should use "disposable" armor on the way to getting the Shield Controller, and you probably don't need any armor on Venus in daytime until you get to a dungeon.

If players are advanced enough in the game to reach Venus then basic resources should be plentiful, the player may even have automatic mining set up.  For example, maybe Heavy Duty Armor is disposable for these players.

Maybe there are other options.  Overall, it's intended to present a challenge, even for players who have plenty of resources.
