### ISSUE TITLE
[Issue Resolved] [1.8.9] No rockets will launch.

### ISSUE THREAD

**Issue by SillyMan0108** [micdoodle8/Galacticraft#2772]
I'm not sure why, but NONE of the rockets will launch. I can list the mods if necessary. I am currently using a dev build (I think) version 1.8.9-4.0.0.102. I have tried the latest stable build and some other builds, but I can't get the rockets to launch. As I said before, I can list the mods if it's necessary.

**Comment by radfast** [comment]
Build 102 is good, you should use that.

Nobody else is reporting rockets not launching, so I'm wondering what is different about your setup...

Are you playing single player?  Please post your **fml-client-latest** log, you can post the full log text up as a Gist here at Github or using paste.ee or similar sites.

**Comment by SillyMan0108** [comment]
I'm playing singleplayer, I just don't know where that file is.

**Comment by radfast** [comment]
That one's not from today!  That one looks to be from January 2017.

Normally the logs should be in your ```.minecraft/logs``` folder.   (It's different with TechnicLauncher modpacks, but you're obviously getting the mod direct from us if you're using build 102.)

**Comment by SillyMan0108** [comment]
That's strange, it was updated today.

**Comment by radfast** [comment]
That log looks like you're maybe playing a world which you've updated from Minecraft 1.7.10  (or maybe an ultra-early beta of Galacticraft 4?)

Kudos to you if you've made that work, I didn't think it was even possible.

If it's that, please can you try starting a **new world** in Minecraft 1.8.9 and seeing if rockets will launch in the new world?

In your log I can see a few block/texture loading issues in other mods (mainly Bloodmagic), there's nothing you can do about that except wait for the mod author to fix it and update.

I can also see a lot of sound issues, like even some vanilla sounds are not working in your game?  No idea what's causing that.  It seems unlikely but I guess it's possible that this sound problem is something affecting Galacticraft rocket launches - rockets have sounds.

**Comment by SillyMan0108** [comment]
I did the new world, but I agree that it's the sound issue. The rockets still wouldn't launch. I'll remove some mods I never even use to try to get sounds to work. I'll also mess around with sound settings to try and fix it.

**Comment by radfast** [comment]
just to be clear, you're saying this was a 1.7.10 world before?  You might like to make a post at http://forum.micdoodle8.com/ explaining what you did to make the world update work, because I'm sure other players would be interested to know how to do this (i'm guessing you had to break a few blocks at least?  There are definitely some Galacticraft blocks which would need to be broken and placed again to work correctly on an update like that.)

yeah, if rockets are not working in a new world then it's definitely worth now trying to fix the sound issue.  I can't _promise_ that's the cause of the rocket launch issue, but I think there's a good chance it is.

I guess you know about the binary search method, you can pull mods out of your modlist in groups, keep a note of which ones were in the group you just removed, if things work without that group then try putting back in half of the group.  (If I ever have to do this, I just move the mods into different folders so I know which group I'm dealing with.)

**Comment by SillyMan0108** [comment]
It was actually a 1.8.8 world. I'll actually try re-creating the world...I might be able to fix the sound like that.

**Comment by SillyMan0108** [comment]
Ok, Issue Resolved. The problem was the graveyard mod.

**Comment by radfast** [comment]
OK, good job
