### ISSUE TITLE
[1.10.2] Mekanism API changed in final 1.10.2 Mek version

### ISSUE THREAD

**Issue by thommy101** [micdoodle8/Galacticraft#2780]
There's an issue with the current version of the Mekanism API you're using.
It crashes with the following log:
https://pastebin.com/H4Yq1e19

The Mekanism API has changed a bit and the interface you're using isn't anymore in the API. ~I'll look whether it's moved or deleted ;)~
The interface ICableOutputter has changed in https://github.com/aidancbrady/Mekanism/commit/cf6a04a65daa413179e777a19bb9f7a8ba5c30e0 to (not 100% sure) IStrictEnergyOutputter

Reference: aidancbrady/Mekanism#4403

**Comment by radfast** [comment]
I'm looking at this, would appreciate some help from you guys on which Mekanism versions this newer API is used in.

I think we are one of the only major mods which takes the trouble to use Mekanism's energy API for energy compatibility, we've been doing that a long time (3+ years) so I'm a _bit_ surprised that @aidancbrady didn't think to notify us of this API change.

**Comment by thommy101** [comment]
The master branch targets 1.11.2 and is the only version with the changed api. Mekanism does support rf, tesla and forge energy out of the box. Do you assume another energy format for which you add compatability?

**Comment by radfast** [comment]
Our mod is similar to Mekanism with an **internal** energy system which is not RF.  When connecting to other mods, we convert to RF if we detect RF is present, we also convert natively to Mekanism's energy system and IC2's energy system, for compatibility **even if no RF mod is present**.

It's been this way for a long time!   Back in the day, Galacticraft and Mekanism started out pretty much the same, I think AidanCBrady and Micdoodle8 co-wrote the energy system and both used it.  There have been divergences since - I re-wrote our internal system for higher performance.

**Comment by thommy101** [comment]
I'm not so familiair with the history of Mekanism and Galacticraft, good to know that they support each other without any 3th party mod installed.

**Comment by radfast** [comment]
You'll see micdoodle is named as a contributor on Mekanism's Github home page (next to your name!)

**Comment by thommy101** [comment]
I've seen his name ;) Quite familiar with Galacticraft, used it a lot back in the (if I remember correctly) times before 1.7.
I'm just a contributor helping with Mekanism since a couple months ago, don't know all the code, all the relations and so, excuse me for that.

Think the change needed is quite easy, changing all references of ICableOutputter to IStrictEnergyOutputter. It's that I don't have a pc with a the capability of starting an dev environment right now, otherwise I would've tried to update the API for you.

**Comment by radfast** [comment]
That's no problem, easy enough to do change in 1.11.2 now that I know it's needed.   Thanks for your help.

**Comment by thommy101** [comment]
No problem and thank you for the quick response!

**Comment by thommy101** [comment]
Just a heads up, Mekanism has released a new (and final) version for 1.10.2 which contains a backported of the changed api. We forgot the backwards compatibility, but it should be easy to solve. 

I'm willing to create a pull request to the 1.10 branch tomorrow ;)

**Comment by radfast** [comment]
@thommy101 thanks for the update re Mekanism

What happens if a player has a newer Galacticraft and an older (pre final) version of Mekanism for 1.10.2?

Can happen easily if a player / modpack is happy with Mekanism but updates Galacticraft to fix a bug.

It's kind of problematic for us if a mod has two different APIs in the same Minecraft version.

**Comment by thommy101** [comment]
Uh.. Using the latest Mekanism version and an older Galacticraft version would work (well, won't crash) as the old api is included (luckily) and deprecated. It's not used, so functionality will break. 

The other way, using the latest version of Galacticraft and not the latest of Mekanism would cause problems as the required classes aren't in that version. 

Merging the PR would mean that everyone who uses a combination of Galacticraft and Mekanism would have to be om the latest version of Mekanism. 

I do apologise for the change, there's limited I can do to make all versions work.
