### ISSUE TITLE
[1.11.2] Crash with asteroid start set

### ISSUE THREAD

**Issue by Dominance** [micdoodle8/Galacticraft#2782]
https://paste.ubuntu.com/24722699/

Happened when you turn on 
`# Set this to true for a challenging adventure where the player starts the game stranded in the Asteroids dimension with low resources (only effective if Galacticraft Planets installed).
    B:"Adventure Game Mode"=true`

   ` # Add together flags 8, 4, 2, 1 to enable the four elements of adventure game mode. Default 15.  1 = extended compressor recipes.  2 = mob drops and spawning.  4 = more trees in hollow asteroids.  8 = start stranded in Asteroids.
    I:"Adventure Game Mode Flags"=8`
 
This does not happen on every new world. so far 2 out of 5

Also I think I have these settings correct. I want to make players start here without being in adventure mode. This was a option in build #99 

With that said as a request. Could you make it so that the drop pod is empty or better yet contents configurable.

**Comment by Dominance** [comment]
Also cannot figure out how to open the chest or drop-pod. in 99 i am sure it was just a right click.

**Comment by Dominance** [comment]
Well if I could just toggle the contents off completely that would work as well. I plan on using the feature outside of it's original goal for the next beyond reality pack. There will be a pregenerated​ building that a player will go to.

**Comment by radfast** [comment]
I'm happy to give you a flag 16 to turn the contents off completely.

If you want some kind of basic item set in there (e.g. thermal cloth) let me know before I code the flag.

Just testing this gamemode for myself for the first time in GC4.  And wow, it's  so hard to survive the first 2 minutes in survival.  I wonder if mobs spawn at a higher rate in these more recent Minecraft versions or something?

Another issue seems to be the landing pod de-spawning after a player death, are you seeing that?

**Comment by Dominance** [comment]
Yeah I did notice that as well. The flag is fine I think. I didn't want to alter recipes, and without looking as I'm on my phone. Would that flag combine the other changes as well? As for the mod spawning yeah there is a ton, I've also noticed there is more in Minecraft altogether.. question how would this work in multiplayer?

**Comment by radfast** [comment]
ok, looks like the landing pod is only de-spawning on the **client** after deaths, a relog fixes it.

the flag 16 will combine with the other changes, no problem - it will only have an effect if flag 8 is set (otherwise there won't be a lander to spawn empty!)

The way Asteroids currently work in multiplayer is each player lands on their own individual landing Asteroid.  The landing Asteroids are all part of the dimension obviously but the game spaces the players apart, I don't remember what the exact spacing is but something like 150 blocks - kind of like a Sky Block map.

In this adventure game mode it's the same, each player first spawns above that player's own landing Asteroid.  So if you're able to travel to another players Asteroid by jumping or whatever, you can team up, or you can grief the other player's stuff.  (Servers would obviously need to use some kind of grief prevention system if they want no griefing.)

There's a strong element of luck (as in the vanilla game) - some spawn locations are way better than others.  Most people will want to find a hollow Asteroid early on, for the trees and the farming possibilities.  Some ores will be a lot more useful than others in the early game.  And there are rare "Abandoned Bases" which have plenty of mid-game or advanced blocks to loot.

**Comment by radfast** [comment]
Build 106 now available.  Sorry, I didn't do the flag 16 yet, that will be in build 107.

**Comment by Dominance** [comment]
ok no problem, Thanks alot! do you all have a discord channel by any chance?

**Comment by radfast** [comment]
Personally I don't chat while coding as I get half as much done.  Not sure about micdoodle8.  Best communication channel for me is this issues list if it's an issue, or PM at the Galacticraft forum for anything you don't want to say publicly.
