### ISSUE TITLE
[1.11.2] [WearableBackpacks] Backpacks don't render on players

### ISSUE THREAD

**Issue by copygirl** [micdoodle8/Galacticraft#2784]
### Mods
- **Forge** 13.20.0.2296
- **Galacticraft** 4.0.0.106
- **WearableBackpacks** 2.4.1 ([Download](https://github.com/copygirl/WearableBackpacks/releases/tag/v2.4.1))

### Summary
Hello. I come to you as the author of the mod mentioned above. Someone has pointed out to me that my backpacks do not render on players in their custom modpack, and I figured it could only be Galacticraft. After throwing together an instance with just the two mods I confirmed this.

My backpacks render on players using a `LayerRenderer`. One of the reasons for this is that it's also supposed to work with other entities. I believe I looked at Botania for inspiration of how to do this when porting the feature from the old BetterStorage mod.

Since Galacticraft is a pretty big mod, finding the code related to this issue and making sense of it would take a long time. I was hoping you could help me along here. Are custom `LayerRenderer`s supported at all? Would they need to be registered in a special way? Or perhaps I'm just stupid?

I'll happily provide any information or clarification if needed and am looking forward to resolving this issue together with you.

### References
[ProxyClient:87](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/ProxyClient.java#L87-L89), where I register the layer renderer.
[RendererBackpack:70](https://github.com/copygirl/WearableBackpacks/blob/master/src/main/java/net/mcft/copy/backpacks/client/RendererBackpack.java#L70), the layer renderer class.

**Comment by radfast** [comment]
Hello @copygirl, thank you for these details.  We certainly would like to have full compatibility between your mod and ours if that's possible.

Even when we get this working, there will inevitably be some render clash at times because Galacticraft oxygen tanks are also worn on the player's back.  I hope players can live with that, I don't think we'd want to not render the oxygen tanks...  !

We replace the ```RenderPlayer``` with a custom [RenderPlayerGC](https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerGC.java) because we make many changes to the player animation (the ModelBiped) in space dimensions or when parachuting, as well as adding several equipment layers.

Previously in Minecraft 1.7.10 we offered the option of **RenderPlayerAPI** compatibility, so we auto-switched to using that instead of the custom RenderPlayer if that API was present.  In Minecraft 1.8.9 up to 1.11.2 versions we are not yet doing this, partly because coding for it is a big task, partly because the 1.11.2 version of RenderPlayerAPI is not yet even available AFAIK!

Long term, RenderPlayerAPI will be the best solution to RenderPlayer mod compatibility issues like this, but we won't be there for I guess at least 2-3 months yet.

Even without RenderPlayerAPI, our custom RenderPlayer ought to respect your ```.addLayer(new RendererBackpack.Layer())``` code.  I'm not sure right now why that's not working, but I'll grab your deobf version and take a proper look later today and see what we can do.  If we need to request any changes on your part, I'll let you know :)

**Comment by radfast** [comment]
I think I've figured it out ... it's just a question of mod loading order.

So you're adding your layers in ```init()```.  We are replacing the RenderPlayer with our custom one in ```postInit()```, so your added layers get forgotten.  I'll look and see if we can copy across the layer information when we replace the RenderPlayer, shouldn't be a problem.  If that works then you don't need to do anything.  And it will probably help other mods too :)

**Comment by radfast** [comment]
Fixed in our build 107 :)

![backpack crop](https://cloud.githubusercontent.com/assets/6842258/26703881/bae24d12-4723-11e7-9e65-445b67daf9bf.png)

**Comment by copygirl** [comment]
Sweet! Thanks a lot for identifying and resolving this issue so quickly ❤️

**Comment by radfast** [comment]
You're extremely welcome.
