### ISSUE TITLE
Fluid Pipes in GC4 dont move some fluids between tanks and machines

### ISSUE THREAD

**Issue by AgentKnightfall** [micdoodle8/Galacticraft#2796]
I've tried the new fluid pipe system, but the only fluids that can be transported are Oxygen and Hydrogen. no other fluid will be moved either between machines that process them or between fluid tanks

**Comment by radfast** [comment]
* Which version?
* Please say fluids + machines which you're seeing **not** working
* A screenshot could be helpful.  You can drag and drop a screenshot into the comment box here at Github.

**Comment by AgentKnightfall** [comment]
Oil from fluid tanks doesn't flow through pipes to refineries
fuel from refineries doesn't flow through pipes to empty fluid tanks or fuel loaders
Water from fluid tanks doesn't flow to Electrolysers
Electrolysers do pump out hydrogen to fluid tanks and methane synthesizers (this is the only set up with fluids that I've found to work) but the fluid tanks cant release the hydrogen to the synthesizers
The synthesizer wont release the methane to a gas liquifier
![2017-06-06_07 49 59](https://cloud.githubusercontent.com/assets/29184278/26804883/f047a58a-4a8c-11e7-9972-e0029b6e809b.png)
![2017-06-06_07 50 03](https://cloud.githubusercontent.com/assets/29184278/26804885/f080e976-4a8c-11e7-9ffe-2d9083d5f473.png)
![2017-06-06_07 50 10](https://cloud.githubusercontent.com/assets/29184278/26804886/f095384a-4a8c-11e7-843b-ed9fe9e67fae.png)
![2017-06-06_07 50 13](https://cloud.githubusercontent.com/assets/29184278/26804887/f09caa76-4a8c-11e7-8bb7-147880886ad5.png)
![2017-06-06_07 49 39](https://cloud.githubusercontent.com/assets/29184278/26804888/f09e7f40-4a8c-11e7-89ba-78d6bae17a71.png)
![2017-06-06_07 49 47](https://cloud.githubusercontent.com/assets/29184278/26804889/f0a4d598-4a8c-11e7-8dbc-2bae4f676913.png)
![2017-06-06_07 49 57](https://cloud.githubusercontent.com/assets/29184278/26804890/f0a789aa-4a8c-11e7-8670-3a07a98bb024.png)

**Comment by radfast** [comment]
[RTFM](https://wiki.micdoodle8.com/wiki/Galacticraft_4#New_features)

You need to click the pipes with a wrench to have them pump out of tanks or in-build machine tanks.

A few machines such as Water Electrolyzer will pump out fluids automatically - broadly some machines can pump out oxygen and other gases automatically (but I'm not sure if we got to them all yet, I'll take a look at the Methane Synthesizer).  But for oil, water, and other liquids, you have to set the pipe to "pull mode" with the wrench.  And to pump out of a tank the same, otherwise the pipe doesn't know whether you want to put fluid into the tank or take it out.

Closing.  If there's a machine where the pipe is not working in pull mode, please let us know/
