### ISSUE TITLE
[1.11.2][Build 107] Not finding meteors on Moon

### ISSUE THREAD

**Issue by SpikybumJolteon** [micdoodle8/Galacticraft#2797]
I have been on the Moon for a few hours now and have not seen any meteors fall. I saw on Github that the meteor frequency coding was tinkered with recently. Maybe something happened with that?

I tested this without other mods installed to make sure it was not a mod conflict and did not see a difference.

**Comment by SpikybumJolteon** [comment]
Never mind. By the third lunar night I finally started seeing them.

It was very different from my experience in 1.7.10 a year ago where they didn't seem that uncommon.

**Comment by radfast** [comment]
Yes, meteors are not too common at present.  The recent code change **increased** their frequency on the Moon but maybe that's still not enough.  Meteoric Iron is a crucial ingredient to make some of the next stage items in Galacticraft.

Compared with your experience a year ago, you should find that the meteors are faster to mine than before if you use the proper tools - hint: something heavy duty :) - and they have a random chance of dropping two meteoric iron instead of one.

Some other [gameplay differences](https://wiki.micdoodle8.com/wiki/Galacticraft_4#Gameplay_differences) are listed here.  Smaller things which are not listed, but generally our intention is to improve "quality of life" while playing Galacticraft.

Waiting for meteors to spawn on the Moon is probably one of our biggest quality of life barriers at present.  Personally I don't much like anything in a game which makes you grind for it, mining for metals in Minecraft is already bad enough!  People who live on the Moon and have large Moon bases usually have no problem finding enough meteors.  But players who don't live permanently on the Moon will find it tough to get enough Meteoric Iron to progress to Mars.

**Comment by dj3520** [comment]
@radfast Any way the meteors could show on the sensor glasses? For me it would be worth a pair if I could finally find a lot of meteors more easily. That's what holds me back from progressing more most of the time.

**Comment by radfast** [comment]
You should already be able to add a Fallen Meteor block as a valuable block in the config.  Although the range of the glasses is limited, so that won't achieve anything very useful.  I think what you're really asking for is a 100 block+ range for detecting Fallen Meteors.  I don't think we can do that as that would be very damaging in performance terms (the game would need to search approximately 100x100x100 blocks to see if a Fallen Meteor is there, that's a million block search).

micdoodle8 and I are planning something new to help with Fallen Meteors, so you might have to wait for that

meanwhile thanks to @SpikybumJolteon's comments I'm probably looking at turning up their frequency another 20% on the Moon only, so there should be one every 4 minutes.  Anyone who spends a decent amount of time building a Moon base should get plenty of meteors.  And if players aren't interested in building a Moon base, should they really be playing Galacticraft?  :)

**Comment by dj3520** [comment]
>You should already be able to add a Fallen Meteor block as a valuable block in the config.

I've tried this before a while back with no success. Don't even remember what I put in the config it's been too long. Was probably not correct anyway. What would the proper value be?

>if players aren't interested in building a Moon base

Well when you've built up your infrastructure on the overworld and have *insert long list of machines here* there and they're a pain to move, just visiting the moon sounds nicer than moving everything there. That and oxygen. But I digress.
