### ISSUE TITLE
[Help Request, not bug]How to use API

### ISSUE THREAD

**Issue by TheUnderTaker11** [micdoodle8/Galacticraft#2798]
I mainly mod 1.10.2, which uses capabilities and the like to get data from entities. I'm not sure how I would get the IEntityBreathable from the player, so I can set the value to true. The purpose of this is for the androids from matter overdrive to not need oxygen in space (Since why would they?). This is a mod request, and help would be appreciated!

**Comment by radfast** [comment]
Hmm, this is actually quite tricky.

In our own mod we would do this for another mod's interface by including an annotation ```@RuntimeInterface``` which adds the interface to our entity class only if the target mod is loaded.  That's a feature which our core mod, MicdoodleCore, gives us.  But I'm guessing your mod does not include a core mod with that annotation feature.

In that case the only way currently for you to do this is to include the Galacticraft interface (```IEntityBreathable```) in your mod's distribution as a hard dependency, meaning you would need to include [this API class](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/api/entity/IEntityBreathable.java) in your mod's .jar file as well as your workspace.

It's totally fine to include that in your .jar file:
* it won't break our mod for yours to distribute that API class
* that API class doesn't include anything else from Galacticraft, so it will always compile OK as a standalone
* that API class won't break anything if Galacticraft is not installed, it just won't have any function
* we won't change or refactor this API interface because we know other mods are using it

The only thing wrong with this approach is it's a bit untidy, but we can live with that so long as everything works!

-----------

One other approach [used in the past](https://github.com/micdoodle8/MicdoodleCore/blob/1.7/src/main/java/micdoodle8/mods/miccore/MicdoodleTransformer.java#L203) was that we automatically applied IEntityBreathable to the vanilla ```EntityGolem``` and all its sub-classes.  So if your mod has the androids as **sub-classes of EntityGolem** then they would automatically not need oxygen in space, and you don't need to do anything else.

It looks like this functionality is currently not included in Galacticraft for 1.10.2, probably because it got overlooked in the huge number of things that had to be done to update the mod for 1.10.2.  We should look at adding that back in.

I'll leave this issue open for now as a reminder for us to do that.

**Comment by TheUnderTaker11** [comment]
Ah I guess I wasn't clear enough, androids are not their own entity, which is why I wanted to get it from the player, you see the mod that adds androids has an easy way to check if the player is an android, so all I would need out of galacticraft is to be able to make the player not need air if that boolean is true. (Which I could do on a player tick or something.) Obviously the stuff you said would be very useful for custom entities, but I'm just talking about on the player in this case.

**Comment by radfast** [comment]
oh I see.  Now that you mention it, I think this question about androids was asked before on the [forum](https://forum.micdoodle8.com/index.php?threads/matteroverdrive-android-no-air-consumption.6618/#post-42673)

Can you show me exact code for checking whether the player is an android and we can maybe incorporate this in our ```CompatibilityManager```, I'd probably want to do it by Java reflection so I need to see an exact code sample of what's needed.  Something like [this](https://github.com/simeonradivoev/MatterOverdrive/blob/1.7.10/src/main/java/matteroverdrive/handler/PlayerEventHandler.java#153-L154)?

**Comment by radfast** [comment]
I guess I have to do in Galacticraft, as I don't think there's any way for another mod to apply IEntityBreathable to the player entity, and it's actually easier for me to do this than to code a new event.

This change will only be for the player though, not other forms of android (if others are even possible).

It's also been suggested that we should switch off thermal damage to androids - does that make sense in the logic of your mod?  I'd prefer to switch off **all** thermal damage including on very hot / very cold planets like Venus.

**Comment by Jacob345k** [comment]
Yes, thermal damage should NOT be applied. Thanks for helping btw

**Comment by TheUnderTaker11** [comment]
He is the server own who requested it by the way, he has been keeping up with the comments and didn't realize it was out of context to hop in.

**Comment by Jacob345k** [comment]
Yea, sorry lol

**Comment by radfast** [comment]
We're always happy to hear from server owners.  Server owners are usually well informed about mods and compatibility, and are also thinking about things like game balance and progression, which are an important part of a mod's design.

**Comment by Jacob345k** [comment]
Oh thanks, I did have a question, you said you were going to do it to Galacticraft? Does that mean this is getting a hotfix, and if so, could we have an eta?

**Comment by radfast** [comment]
How about now, @Jacob345k :)

https://github.com/micdoodle8/Galacticraft/commit/2205a2c1e11bd5dcd8a0c28e29cafcc47d7a4340
