### ISSUE TITLE
Crash When Loading World (1.10.2)

### ISSUE THREAD

**Issue by StevieBranscum** [micdoodle8/Galacticraft#2799]
Hey guys. I'm back with another issue I found. Don't know what caused, so maybe you guys do? (Not really good with Java.)
Pastebin: https://pastebin.com/D5xPnJMD

**Comment by radfast** [comment]
Looks like you have forgotten to put **galacticraftcore** and **galacticraft-planets** in your /mods folder.

You have **micdoodlecore** but not the other two files.

You need all three files for the mod to work propertly.

**Comment by StevieBranscum** [comment]
New problem. 
https://pastebin.com/pYL81QyU

**Comment by radfast** [comment]
This "new problem" is again caused by something wrong in your installation.  It's hard to say exactly what's wrong as I can't see the ```/mods``` folder for your PC and check your files.

But in your log, this looks wrong:
>
     GalacticraftCore-1.10.2-4.0.0.107 (1).jar

That file name shouldn't have a (1) at the end of it.  That suggests you have 2 copies of the same file now.

I guess it's also possible you have an **incomplete** download of galacticraftcore...

[Installing Galacticraft really isn't hard](http://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide).  You just have to put our 3 files in your /mods folder.  Maybe do this now:
- check your ```/mods``` folder (also check the subfolder ```/mods/1.10.2```)
- carefully delete _all_ files named micdoodlecore, galacticraftcore, galacticraft-planets
- download fresh copies of all three files from our download site 
- make sure the downloads are 100% complete
- move the three new files into your /mods folder

**Comment by StevieBranscum** [comment]
The (1) was the new downloads. And I found out the problem. It was biometweaker.

**Comment by radfast** [comment]
OK good job.

**Comment by StevieBranscum** [comment]
Do you think that Galacticraft may have an incompatibility with BiomeTweaker? Or is that something with me?

**Comment by radfast** [comment]
From memory there was a problem on BiomeTweaker's side a few months back.  Looks like they updated in version 1.10.2 2.3.239 to fix it, try that one.
