### ISSUE TITLE
Galacticraft Power Sources won't output power through Mekanism Cables (1.10.2 Build 106)

### ISSUE THREAD

**Issue by SportsFan10** [micdoodle8/Galacticraft#2802]
Galacticraft Version: 1.10.2-4.0.0.107
Mekanism Version: 9.2.2.301

I'm not sure if this is intended behavior but it previously worked.  I placed a Galacticraft solar panel down and tried to connect it to both an energy cube from Mekanism, and a energy storage module from Galacticraft using Universal Cable from Mekanism.  Power would not be transferred through the cable however they did connect to the machines.  Using Galacticraft Aluminum wire going into the Mekanism machine does work.

**Comment by radfast** [comment]
>  Using Galacticraft Aluminum wire going into the Mekanism machine does work.

Use that for now.  It is intended that our power sources can output into Mek cables.  I have been in dialogue with the Mek dev team because they changed their API, but they told me that was only in 1.11.2.  Sounds like one element at least may have changed in 1.10.2 also.

Does Energy Cube -> Universal Cable -> Galacticraft machine work OK?

**Comment by SportsFan10** [comment]
Yes that works perfectly fine.

**Comment by SportsFan10** [comment]
On another note which probably is from the same situation of Mek changing their API, pressurized tubes no longer work in transporting Galacticraft Gas.  Assuming this is the same situation as before and is not a major issue.

**Comment by radfast** [comment]
Thanks, the pressurized tubes is probably the same root cause.  Mekanism in 1.8.9+ uses a mcmultipart system for its cables and pipes, so we have to haul the cable or pipe out of there before we can do anything with it...

Next build 108 will - I hope - work with the Universal Cables.  If that works OK, we can fix the pressurized tubes later.

**Comment by SportsFan10** [comment]
Ok sounds good!  That McMultipart thing seems to have some real issues as of recently.  I keep getting this weird crash on my server if I'm the only one online and I load/unload a dimension.  For example when I return from Mars/go to Mars my server crashes due to something with Multipart and Mekanism's cables.  I already reported this to both of those devs.  Hope a fix comes soon from one of them.

**Comment by radfast** [comment]
The Mek guys are good, I'm sure they'll get that sorted.  Our cable problem wasn't a bug in mcmultipart, just we needed to update our GC4 code to take account that they're now using that for their cables instead of the old system.  Our updated code should work now.
