### ISSUE TITLE
Asteroids dropping my players fps down to 0.2

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2809]
I know it's not a problem with their PC because I have a great Computer And still have terrible fps
Using build 105 1.11.2

**Comment by radfast** [comment]
That's not happening for me.

Can you be **much more specific** about how to see this:
* Do you see the same fps issue in Single Player?
* View distance
* Other video settings (screenshot them?)
* Anything specific on screen when this is happening?
* Anything specific the player is doing when this is happening (fighting, building, etc?)
* Anything else you can do to make it stop happening?

I suggest test with different view distances.

A known issue is that the **vanilla lighting engine** has really bad performance in the Asteroids dimension, because it doesn't deal well with the amount of empty space (like huge caves).  But this mainly affects block placement, it shouldn't affect you if you're just flying around the dimension and not building.

**Comment by MrEyeballs29** [comment]
Is this a performance Issue?

**Comment by radfast** [comment]
It's a "cant reproduce" issue @MrEyeballs29 

If you're also seeing the issue in your game, it would help us to have details of what steps we can take to see the issue.

**Comment by SixtyFourWarrior** [comment]
We get a huge fps drop (drops to 0-3) in asteroids in server with render distance 12. Reducing it to 2 is fine but still getting 0 fps while rendering new chunks, fps drop is not that big on singleplayer, but still exists.

**Comment by radfast** [comment]
thanks for the update, please give more info (for example, Sponge version) so I can test a similar setup

do you know how to run a CPU profiler on a running Java application?  for example **VisualVM** which is part of the Java 8 JDK you can download from Oracle?  (there are also Minecraft-specific tools like Opis and WarmRoast, not sure about 1.11.2 versions of those)

It would be very useful if you can run a CPU profiler on the server and show me the results.  In VisualVM, I would make a "Snapshot" for around 20 seconds then take a look at what it shows.

Also check the memory, if it's heading up above 90% of available memory on the server then you might be able to fix this just by giving it some more memory.

**Comment by SixtyFourWarrior** [comment]
Well, I don't have access to files so I don't know Sponge version, sorry :/ But maybe Seba will tell you I think.

**Comment by SebaSphere** [comment]
https://images.discordapp.net/attachments/315630594509766666/324660325074993152/2017-06-15_00.21.17.png?width=771&height=449

**Comment by radfast** [comment]
Thanks for the F3.  7 fps doesn't look good.

Memory looks fine.  

Please try it **without Optifine** ...

**Comment by lukacat10** [comment]
I can tell that for a long time I had severe issues with the astroid dimension (performance wise). My PCs (yes I have tested it in more than one) are not the best, but have mid grade nvidia gpus. Recently after going 0.5 fps for a while I managed to get a nice crash. I have attached the fml crash report.

I got the crash while trying to get out of the map (after failing to launch from the astroid dimension)

I will also save a copy of all the logs in case you need them. Just ask.

[launcher_log.txt](https://github.com/micdoodle8/Galacticraft/files/1482685/launcher_log.txt)

**Comment by TheQuadShot** [comment]
It looks like the old cascading worldgen bug that has been fixed, Please update to the latest build (118).
https://micdoodle8.com/mods/galacticraft/downloads

**Comment by radfast** [comment]
@lukacat10  sorry for time taken to respond to this, I wasn't watching this thread for some reason

The crash is simply due to not enough memory for Java - you need to [increase the memory you give the JVM](https://wiki.micdoodle8.com/wiki/Tutorials/Galacticraft_Installation_Guide#How_much_JVM_memory_do_mods_need.3F)

        Exception: java.lang.OutOfMemoryError

**Comment by radfast** [comment]
@SebaSphere and others reporting this:  one more thought is it could be Optifine-related, if possible please try the same game world with and without Optifine.

We really need a Java profile to resolve this, but I can't do that unless I can re-create the issue in my own game.

I have a gaming PC which is definitely not powerful (32 bit Windows, old 3.0GHz Athlon64 CPU, NVidia GTX 750) but it can easily maintain 50-60fps in the Asteroids dimension.
