### ISSUE TITLE
Alien Villager not trading on server

### ISSUE THREAD

**Issue by SebaSphere** [micdoodle8/Galacticraft#2819]
Players are not able to trade with villagers on my build 105 minecraft server.

**Comment by SportsFan10** [comment]
Update to build 106+

**Comment by radfast** [comment]
Thanks @SportsFan10 you're right, this issue was probably fixed in build 106.

@SebaSphere  you can safely update the server to build 106 **even if your player clients remain on build 105** - those two builds are 100% network compatible and nobody needs to know :)

(But don't update your server to build 107 without your player clients also updating to 107 at the same time.)

**Comment by EzerArch** [comment]
MC 1.11.2 with build 114, on LAN.

"Can't trade with villagers": https://forum.micdoodle8.com/index.php?threads/cant-trade-villagers.6795/

**Comment by radfast** [comment]
I guess we need to re-open this then, thanks Ez :)

**Comment by QuantumStatement** [comment]
I think I could to reproduce this bug
Bug occurs in Singleplayer LAN mode when client (game host don't have this problem at all) visit Moon for the first time

Minecraft 1.11.2
Forge 13.20.1.2386
Galacticraft 4.0.1.139
No other mods installed

**Comment by radfast** [comment]
Thanks guys, I'll look for a fix this week.

**Comment by radfast** [comment]
@QuantumStatement please can you check the logs of the **host** for when this happened - I'm looking for this line in the log:

>      Warning: Could not find player base server instance for player

**Comment by QuantumStatement** [comment]
> Warning: Could not find player base server instance for player [NAME]
I don't find this string in logs
