### ISSUE TITLE
Missing dimention

### ISSUE THREAD

**Issue by MIGA2001** [micdoodle8/Galacticraft#2848]
Mod messes up my dimentions please help, I want to add galacicraft to my mods really much
[crash-2017-06-21_13.25.49-server.txt](https://github.com/micdoodle8/Galacticraft/files/1091343/crash-2017-06-21_13.25.49-server.txt)

**Comment by radfast** [comment]
Seems to be another mod causing that crash.  Galacticraft is not the cause.

Maybe another mod changed its dimension IDs when it saw Galacticraft is loaded?  Galacticraft 3 uses dimension IDs -26, -27, -28, -29 and -30.   Most other mods do not use those, because most people know that Galacticraft uses them.

If necessary you can change Galacticraft dimension IDs in ```configs/Galacticraft/core.conf``` and ```planets.conf```, but this should not normally be necessary.  I suggest you start by looking at your other mods with dimension -22.

The specific crash is caused by a ChickenChunks chunk loader, so you might also need to think about which dimensions have chunk loaders.
