### ISSUE TITLE
Fluid pipes at length of 1, pulls from both ends

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2856]
Galacticraft-Planets 1.10.2-4.0.0.107
GalacticraftCore 1.10.2.4.0.0.99
MiccdoodleCore 1.10.2-4.0.0.107

Galacticraft-Planets 1.11.2-4.0.0.106
GalacticraftCore 1.11.2-4.0.0.106
MiccdoodleCore 1.11.2-4.0.0.106

http://imgur.com/a/cifuJ

**Comment by radfast** [comment]
Also, a "pull" fluid pipe connected to two different fluid tanks (with different fluids) can maybe pull from both of them?!

I think the way to fix this will be to have the "pull" fluid pipe pull from one direction only, and wrenching it again will change that direction.

**Comment by dj3520** [comment]
Two other options would be the EnderIO way (wrenching changes pull/push per sided connection) or something like the 1.7.10 gas pipes (try to detect if we're connected to a machine's input/output and auto-config that way, reverting to a different behavior if tank/can't determine)

**Comment by micdoodle8** [comment]
The EnderIO way would require a microblock implementation because having a wrench click cycle between all possible sides would take a huge amount of time. If my calculation is correct there are 721 possible combinations if there are acceptors on all 6 sides of the pipe.

Although not ideal, I think the next best option to a microblock implementation would be having it pull from a single side only. I don't believe having the pipe auto-config and revert in some cases is a great way of doing it.

**Comment by radfast** [comment]
The Wiki now has some explanation for this, with screenshots
https://wiki.micdoodle8.com/wiki/Fluid_Pipe

In practice connecting a fluid pipe in "pull" mode to 2 different tanks seems OK.  The pipe can only hold one type of fluid so it will only pull from one of the tanks (if the tanks have different contents).

Thinking about it more, I don't really like clicking again to change the side - the Fluid Pipes are supposed to have a simple mechanic where right-click switches them immediately between pull and regular mode.  That's the beauty of Galacticraft - compared with the dedicated pipe and powerduct mods like Buildcraft, EnderIO or Thermal Dynamics, our pipes and power systems are very simple and practical to use.  They "just work" (TM).

One thing I think we **can** do is disable the pull on a side if the connected machine says it has no output on that side - most machines (including all of our fluid handling machines) will respond correctly.   That's kind of what @dj3520 was suggesting, although maybe a more limited version - we will look only for whether the machine has an output or not.

BTW - it's the small things :) - I made it so the "pull" connection renders closer to and touching the Galacticraft Fluid Tank, where a Fluid Pipe abuts a Fluid Tank, as in the screenshot here.

**Comment by radfast** [comment]
>   One thing I think we can do is disable the pull on a side if the connected machine says it has no output on that side - most machines (including all of our fluid handling machines) will respond correctly.

I made some experimental code to test this idea - see https://github.com/micdoodle8/Galacticraft/commit/d6b7e7f822d722a02339fe4415483ab417f00e6c (note, this code is not currently in the actual mod).

The results are unsatisfactory for 2 reasons:

1.  Some machines and tanks say that they "cannot" be emptied when they are empty, then as soon as you put some fluid in them, they "can" be emptied.  This causes the status of the **pull mode** end of the fluid pipe to change depending on whether there is fluid in the tank or not, and that's not nice to see.  (I can cure it by having our tanks say they can _always_ be emptied, but there's no guarantee other mods will do the same - in fact it's likely they will not do the same.)

2.  The pipe length 1 in pull mode really only works properly in one limited situation: where it is emptying a tank and the other side is connected to a machine input, like Refinery oil input side.

A length 1 pipe does not work when pulling from a machine output into a Galacticraft **Fluid Tank**.  That's because the Fluid Tank can be both filled and emptied by pipes, so a "pull mode" pipe has no way to know which one it should be doing, if it's allowed to do both.

So this situation:
![2018-01-31_05 18 01](https://user-images.githubusercontent.com/15654765/35617481-534321bc-0646-11e8-964f-f52ffbb3211c.png)
I can make it so that the **left hand** pipe moves oil, but I cannot make it so that the **right hand** pipe moves fuel.

I don't like an asymmetry like that, it just seems too confusing for players.  It's better to have a simple rule: don't use pipe lengths 1.

So in conclusion, I think this is a problem which cannot easily be fixed.

Possible solutions:

 - a microblocks approach with a GUI  (like EnderIO) - I hate this type of GUI, a pipe should work intuitively without needing a GUI

 - 721 different possibilities for clicking the pipes - obviously not feasible

 - like **micdoodle8** said, change the wrench-click mechanic so you can click specific sides of the pipe and have it pull from those sides - that is possible, and intuitive for players, but it will be a big pain to code for two reasons - first, it needs complex raytracing to figure out which side of the pipe is being clicked, second it would need careful thought to make sure there is no _breaking change_ to the pipe blocks already in player worlds.

For myself I don't feel it's worth my time to code this change, when there's so much else on my "Todo" list in terms of new features to add and other things to fix - even the Wiki needs fixing, there are a few missing pages and [lots of stub pages](https://wiki.micdoodle8.com/index.php?search=stub&go=Go).  I feel that players have an easy solution which is to make a pipe of length 2.  This is covered [in the Wiki](https://wiki.micdoodle8.com/wiki/Fluid_Pipe) and also in the in-game JEI "info" page for the Fluid Pipe.

But, micdoodle8 may think differently?  Also if you or someone else wants to code this in future, I'm sure we will be happy to accept a pull request (as long as it works ...) :)

For now I'm going to call this "won't fix", sorry!

See also #3139 and #3209 which are kind of duplicates of this.

**Comment by TheQuadShot** [comment]
Just a thought, What if you make the change like micdoodle8 said, and by default the "pull" end is on the "left", and the wrench wack just "flips it"(ie, skip the raytrace check) . I hope that makes sense,I think Embers has a "pump" block/pipe that works like that.

**Comment by radfast** [comment]
So it would cycle between (a) (b) pulling as between the 1 or 2 directions where there are tanks it can pull from, or (c) not pulling at all?  Kind of like micdoodle8's first suggestion but with 3 permutations not 721?

I can see that's tidy and intuitive, but a couple of issues spring to mind, see what you think?

- It would mean that players would have to place the tank before the pipe, as an unconnected pipe wouldn't be able to go into "pull" mode like this - if when the pipe is clicked it auto-selects the first direction which the pipe can validly pull from, actually there might not be any valid direction at all when a solo pipe block is placed

- It might reduce functionality for people who want to use 1 pipe block in "pull" mode to draw from 2 adjacent tanks - I'm 
not sure how common that build is, but it would certainly be a possible build under the current system.

**Comment by TheQuadShot** [comment]
What I would like and am envisioning, (img from op: http://imgur.com/a/cifuJ ) is that I could sneak place the block and the "pull" end would abut to the block I'm facing(ie away from me), if I'm not in sneak and just place, the "pull" to the left (or right) and I could whack it with a wrench to have it flip direction. I see this as a "worse case scenario" https://imgur.com/a/kR9k2 in which case you would just "rotate" the "pull" end to each of the block (cw/acw).
I'm not sure what you mean by adjacent tank, I'm may be thinking this wrong. I see a pipeline as a "bus" with multiple outputs but only one input.
