### ISSUE TITLE
buildcraft compat

### ISSUE THREAD

**Issue by AEnterprise** [micdoodle8/Galacticraft#2858]
Today someone notified us that apearenly GC is recomending it's users to not use the latest BC version but the older 7.99.3 version (https://wiki.micdoodle8.com/wiki/Compatibility)

The reason would be some compat issue that is aprearently assumed to be on the BC side yet nobody ever reported this to us.

I searched through the issues here but couldn't find a report of this eighter. Could we get the information about the bug as to what is going on? The wiki sais something about the oil bucket on servers yet we do not have a custom bucket or anything so i do not see where the issue might be.

Are there any other incompatebilities between BC and GC that we don't know about? We would also apreciate it if in the future we would get notified if there are any issues instead of just telling users to use an older version.

**Comment by radfast** [comment]
Hey, sorry, you're right we should have notified you.  That was recently added to the wiki page in the last few days as a quick fix to a reported issue.  [Here](https://forum.micdoodle8.com/index.php?threads/fatally-missing-blocks-and-items.6778/) is the report, I have not had time to investigate it further and I don't know whether the cause is on BC's side or ours.

**Comment by AEnterprise** [comment]
alright, it is a bit of a weird issue and i'll take a look later if to make sure that we are registering our oil stuff correctly on both ends

also is there any specific reason GC still has it's own oil bucket item? if it doesn't do anything special other then the regular bucket you might want to removing it and having the forge universal bucket take over. This would not be the proper fix for this issue but it would mean that GC no longer needs to check if another mod adds a oil bucket or not.

**Comment by radfast** [comment]
The issue is most likely connected with our detection of whether Buildcraft|Energy is present giving different results server side and client side, not the oil registration, but I will give you more specific info once I've taken a look at this issue properly myself, you might want to hold off until I've done that.

We keep our oil bucket primarily because I don't like the rendering on Forge's bucket.  But our oil bucket will automatically not register as an item if Buildcraft|Energy is present, we have had this system for the past 4 years and it has been fine until this reported issue.

**Comment by AEnterprise** [comment]
one issue i spot with that already is that the modid doesn't match, it is`buildcraftenergy` none of the modids contain `|` anymore so that could be part of the problem but that give a false negative on both the client and the server

another thing you might want to keep in mind is the 1.12 registry rewrite. The offical stance of the forge team is that you should always register everything so registry contains everything. To hide these from the creative tabs and mods like JEI you can hide the items by not adding it in the getSubItems function

**Comment by radfast** [comment]
Thanks for that, we'll make the necessary changes to the modids, and maybe that will resolve this.  Please do not spend any furthe time on this for now, I'll notify you if we think there is any Buildcraft issue.

**Comment by AEnterprise** [comment]
semi related: we figured out a long standing bug with oil from worldgen becomming unpumpable (eighter BC or another kind) if there are multiple mods that add oil: if the dominant oil isn't used in said wordgen then it results in a false negative from forge when asking the fluid. Only the dominant liquids are in the map.

We worked around this now by having the pump check for fluid blocks and extract get what fluid it is that way

and no we didn't find this looking for the earlier mentioned bug but since we had oil compat issues with GC in the past i thought you guys would like to know

**Comment by radfast** [comment]
GC oil shouldn't be a thing, if BC is installed.  We literally don't even register the fluid "oil".  At least, we don't so long as we got the name of your mod correct...

**Comment by radfast** [comment]
Mod name is now correct in 1.11+ https://github.com/micdoodle8/Galacticraft/commit/fe475039043877cdb91aa3741926d74cd042353a

I've removed the passage on our wiki recommending the outdated BC version 7.99.3.  In our latest version, I can't reproduce the issue which the person on our forum was originally complaining about, but we'll keep an eye on that.  I think this can be closed.

@AEnterprise you are most welcome to raise any BC / GC compatibility issues, however minor - our goal is 100% Buildcraft compatibility, as it has been for the last 3-4 years :)
