### ISSUE TITLE
A fatal exception occurred during the server about to start event

### ISSUE THREAD

**Issue by 23Link89** [micdoodle8/Galacticraft#2862]
When I have Galacticraft installed on my modpack and try to load up a world I get this crash: 
[fml-client-latest.zip](https://github.com/micdoodle8/Galacticraft/files/1106151/fml-client-latest.zip)

I first went to the forge forums for help on the crash: http://www.minecraftforge.net/forum/topic/58551-a-fatal-exception-occurred-during-the-server-about-to-start-event/#comment-270395

Which they redirected me to CodeChickenLib, so I reported it and they said it was a niche problem I was having myself: https://github.com/TheCBProject/CodeChickenLib/issues/56

So I disabled my most recently installed mod (Galacticraft) and the game started up like normal. Let me know if you'd like a copy of my modpack for testing. Best of luck.

**Comment by TheQuadShot** [comment]
This is a CodeChickenLib issue. They said as much, they also said it's fixed in 1.11, and "not easy to port back to 1.10."

**Comment by radfast** [comment]
There is no Galacticraft issue here, it's a CCL issue.

Maybe removing Galacticraft looks like it fixes it because you just have too many mods and Galacticraft is a big mod and one you recently added, I really have no idea, but there's nothing we can do to help with this issue.

Your log file also discloses a large number of loading issues with other mods like ProjectRed and Mekanism, you maybe will find things improve if you can reduce the number of errors generally - either use more recent versions of those mods, or remove some of the mods you're not really using.
