### ISSUE TITLE
[Sponge] error on server shutdown - relating to dim -1

### ISSUE THREAD

**Issue by zerisius** [micdoodle8/Galacticraft#2864]
hey there. everytime my server stops this error will be generated. https://pastebin.com/xmeaZguJ

Galacticraft-Planets-1.10.2-4.0.0.109.jar
GalacticraftCore-1.10.2-4.0.0.109.jar
MicdoodleCore-1.10.2-4.0.0.109.jar
(ExtraPlanets-0.5.1-Beta-Build.jar)

minecraft: 1.10.2, java 8 
sponge version: spongeforge-1.10.2-2281-5.2.0-BETA-2414
forge version: forge1.10.2-12.18.3.2316

**Comment by micdoodle8** [comment]
Does the error occur without Galacticraft? It seems there's an error unloading the Nether, which is unlikely to be an issue on our side.

**Comment by radfast** [comment]
+ you're not using the right Sponge version anyhow, please read [our documentation](https://wiki.micdoodle8.com/wiki/Sponge)

**Comment by zerisius** [comment]
hey. sorry for the lack of information. it does not occur without galacticraft. 
im now using your recommended spongeforge-1.10.2-2254-5.2.0-BETA-2250 instead of 2414 and it does not fix this problem. 

console log: https://pastebin.com/AeTJHhJ4
fml latest log is attached:
[fml-server-latest.txt](https://github.com/micdoodle8/Galacticraft/files/1111004/fml-server-latest.txt)

**Comment by radfast** [comment]
Looking at the logs, it appears you have two Nether dimensions, I'm not sure why.  That's because I'm seeing this line twice:
>
    Saving chunks for level 'DIM-1'/Nether

The likely cause of this is a dimension ID conflict between two other mods.  You're saying it only happens when Galacticraft is installed, but you also have **ExtraPlanets** installed.  Does the issue still occur if you remove ExtraPlanets?

If removing ExtraPlanets fixes it, then I suggest you take a careful look at the dimension IDs added by ExtraPlanets and look for potential conflicts, maybe try some config changes.  For further help please ask the ExtraPlanets author.

**Comment by MJRLegends** [comment]
I'd say this is sponge or the sponge related plugins your using as that would make more sense to why its breaking as the gc devs said there is no connections to Galacticraft or my addon in fact but to the nether dimension

**Comment by zerisius** [comment]
the error occours without extraplanets. the error log is the same. i will try without sponge

**Comment by define-evil** [comment]
@radfast I just want to add that this error hangs the server with newer forge versions and I had to kill the process every time I stop the server. Are there any work arounds? Thanks.

**Comment by define-evil** [comment]
This issue no longer exists with forge 2705 and sponge 1.12.2-2705-7.1.0-BETA-3136
