### ISSUE TITLE
[1.10.2] Lightning Panel doesn't apply color value from Block (e.g. Grass Block)

### ISSUE THREAD

**Issue by SteveKunG** [micdoodle8/Galacticraft#2865]
![2560-06-27_05 46 36](https://user-images.githubusercontent.com/6128413/27636576-67f36d48-5c36-11e7-9967-635de96c24d2.png)

**Comment by TheQuadShot** [comment]
Could this be related to #2837.  I'm just trying to figure things out, and I'm not sure how void biomes work.

**Comment by radfast** [comment]
Not related to that other issue (except that other issue may also be connected with biome colors).

This issue is simply that what you're seeing there is the actual texture of a Grass block.  Vanilla then tints that in parts with a green color - different greens in different biomes.  We can probably replicate that on Panel Lighting, I'll take a look.

**Comment by radfast** [comment]
I've found a way to fix this in 1.10+, in next build 172.
(Not possible to fix in 1.8.9, but nobody plays that anyhow ...)
