### ISSUE TITLE
[1.7.10] Time out causes parachest not to spawn on space station.

### ISSUE THREAD

**Issue by PlayTheFallen** [micdoodle8/Galacticraft#2884]
Upon reaching the upper atmosphere of the overworld, I made the choice to travel to the space station in orbit above the planet. Occasionally, I along with a few other members of the server would timeout upon entering the dimension of `SPACESTATIONX` *as documented*. When trying to reconnect to the server, I enter the dimension (space station) and the chest doesn't spawn due to presence issues on the server.

**Comment by radfast** [comment]
This is the same issue as #1195.

It seems to be rare.  It's not clear what is causing the time outs.

Please state:
* exact Galacticraft version
* Forge version
* server setup (Thermos / Cauldron etc)

Please provide a **server log** covering the +/-3 minutes from the disconnect and reconnect.

Is there a trigger event which causes the time out every time - so that I can set up a test server and see the time outs happening on my system?

**Comment by PlayTheFallen** [comment]
Galacticraft Version - `7.10.99.99`
Forge Version - `3.0.12`
Logs - *TBC, waiting for server owner to retrieve log file.*

PS: Sorry about the wait for the logs. Either myself or the server owner will post them here.

**Comment by radfast** [comment]
> **Galacticraft Version - 7.10.99.99**

That's not a Galacticraft version!  Please state the ```GalactictcraftCore``` file name.

**Comment by PlayTheFallen** [comment]
![](https://playing-games.while-at.work/b99aed.png)

Logs - https://pastebin.com/Y6KsGPUS

**Comment by radfast** [comment]
Thank for that.

>  Please state the GalactictcraftCore file name in your /mods folder.

Look in your .minecraft/mods folder and tell us the Galacticraft file name.

**Comment by PlayTheFallen** [comment]
> Please state the GalactictcraftCore file name in your /mods folder.

`GalacticraftCore-1.7-3.0.12.501.jar`
I believe that this is the filename that you requested.
