### ISSUE TITLE
[1.7.10] Compatibility of Can of Food with HungerOverhaul

### ISSUE THREAD

**Issue by nidico100** [micdoodle8/Galacticraft#2889]
I'm using Galacticraft(latest) and AppleCore, HungerOverhaul and The Spice of Life as combination in my modpack and I saw, that the Cans of Food aren't compatible. I asked the programmer of AppelCore and he said, that Galacticraft has to be updated to be compatible. The link he said:
https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore

Would be great, if this little tweak could be added to 1.7.10.

**Comment by radfast** [comment]
I'll see what can be done, thanks for the link.

**Comment by nidico100** [comment]
hey, just wanted to ask for news, if the feature is easy and possible, because if it's too much work, it's not that important, then i would just minetweaker the cans out of the modpack :)

**Comment by radfast** [comment]
This is now implemented in Galacticraft 4 for Minecraft 1.8.9 through to Minecraft 1.12.2.

It's going to be too difficult to backport this change to Minecraft 1.7.10 due to the need to keep compatibility with existing saves (existing cans of food in player inventories, chests etc).  And in general, we are not now adding new features to 1.7.10.
