### ISSUE TITLE
[1.11.2] Key mappings not working

### ISSUE THREAD

**Issue by cdaragorn** [micdoodle8/Galacticraft#2895]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0
Forge version: 13.20.0.2366

Single player (SSP) or Multiplayer (SMP)? Both

Galacticraft add-ons and other mods installed? Using Tekkit Updated ModPack

Galacticraft's mapping of the galaxy map to 'M' is conflicting with VoxelMap's use of that key in this modpack. I've tried changing the setting in the core.cfg to KEY_N in both the client and server configs, but Galacticraft is ignoring this and continues to respond to the M key. N doesn't do anything, either.

**Comment by radfast** [comment]
Thanks, we'll take a look.

Once we get this fixed, it will need @SleepingTea98 to update the Tekkit Updated pack, if you're able to contact him/her and bring this Galacticraft issue tracker to his attention that would be great.  (Generally it will be a good idea to update Galacticraft every few weeks anyhow, as we are still picking up various bugfixes and compatibility fixes.)

**Comment by radfast** [comment]
After careful tests, our config is working **correctly**.

However, Minecraft **also** saves key bindings in the game settings (the `options.txt` file).  This includes mod key bindings.  These can then be changed using the in-game menu (`Esc`, Controls).  They can also ... not be changed.  So if you first load Galacticraft without changing the Galacticraft config, then the Galaxy Map becomes set to key M.  Minecraft saves that M and it thinks that is what you want...

If we tried to override this behaviour then players would not be able to change the keys in game.

To avoid confusion, I will remove the key bindings from the in-game config GUI because really they do nothing there.
