### ISSUE TITLE
Tesselating block model (stack overflow on lighting panel)

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#2900]
Minecraft 1.10.2
Forge 12.18.3.2316

Galacticraft-Planets 1.10.2-4.0.0.114
GalacticraftCore 1.10.2-4.0.0.114
MiccdoodleCore 1.10.2-4.0.0.114

Mod List
https://pastebin.com/Nd8eHxFm

Crash log w/FoamFix
https://pastebin.com/wRC08m2v		

Crash log W/O FoamFix
https://pastebin.com/FnPqHxgZ

I set up a long dark dungeon hallway (about 60-80 blocks) with lighting panels in the overhead about every 4th block, I placed them via sneak/clicking to take on texture of blocks (dark prismarine). I have a few repeaters(vanilla redstone only) between each so that they light up at about the pace you walk the hall, this worked fine and I had completed the timing/testing. Then I put in a turn to a dark hall with a wall of panels(3x3) that were suppose to light up about 10 blocks into it(ie. suddenly blinded by light). I was doing the redstone for the wall, and had completed the top row and broke a block to the side of the top left (as seen from standing behind) to bring the redstone down for the other rows (and some pistons). That's when I crashed. I tried to disable Optifine, however the mod pack won't run without it. I've also disabled my shaders/resource packs. I can't open the world anymore and I'm not sure how to fix it short of ripping out GC.

**Comment by radfast** [comment]
Appears to be a duplicate of #2869 but I'll keep both issues open, as you have given more info.

Unfortunately, it's not normally a high priority for me to fix issues caused by Optifine, as these are very hard issues to fix, but I'll see what we can do here.

**Comment by radfast** [comment]
The problem is that - for reasons I don't understand - the chunk has a Panel Lighting block without the tileEntity it should have to go with it.

This is some kind of bug in vanilla/Forge chunk saving or server/client sync which I don't understand, but anyhow we can work around this so there will be no more crashes.

Fixed in 115.

(The Panel Lighting blocks in faulty chunks might revert to their default look, though: nothing we can do about that)
