### ISSUE TITLE
Rocket Dupe Problem

### ISSUE THREAD

**Issue by BreeOge** [micdoodle8/Galacticraft#2902]
Minecraft 1.11.2
GalacticraftCore-1.11.2-4.0.0.114
Galacticraft-Planets-1.11.2-4.0.0.114
MicdoodleCore-1.11.2-4.0.0.114
forge-1.11.2-13.20.1.2393

When I place the rocket on the pad, It places it, but never removes it from my hands, so it gives me two rockets.  Dupe's the original rocket.. I now have 4 rockets by just flying to the moon.

**Comment by TheQuadShot** [comment]
Need more information, Which rocket? Does it have storage? Can you post a mod list and provide a link along with your latest.log file(maybe from the session that the dupe occurs)? I can't repro this in my test world on 1.10.2 or 1.11.2, I didn't try all combinations though.

**Comment by BreeOge** [comment]
Ill get you a video or something.. sorry RL keep me busy..

**Comment by radfast** [comment]
@BreeOge any more information?

SSP or SMP?

And if it's SMP, is the server running Sponge, if so which version?

**Comment by radfast** [comment]
We think this may be an issue that only occurs on Sponge servers ...

If so, it should be fixed in latest Galacticraft build 117, so please ask your server owner to update to that.

Closing in the hope that that fixed it.

If you are **not** playing on a Sponge server, please comment or re-open this and give further info so that we can investigate some more ...

(Obviously, we don't want people to be able to dupe these valuable items.)
