### ISSUE TITLE
[1.10.2] Spin Manager Crash

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#2924]
Minecraft version: 1.10.2
Galacticraft version: Build 114
Forge version: 2316

Single player (SSP) or Multiplayer (SMP)? Sponge Server (spongeforge-1.10.2-2281-5.2.0-BETA-2464)

Galacticraft add-ons and other mods installed? Yeah loads :D Space Astronomy 2 Mod pack https://minecraft.curseforge.com/projects/space-astronomy-2

Please provide screenshots / crash report / log as needed.
Crash log: https://pastebin.com/K3ixxRk8

**Comment by MJRLegends** [comment]
I really not sure about this crash and cant reproduce it, im hoping posting it here will shine come information on it :D Feel free to close it if its a waste of time and a only time only bug @radfast @micdoodle8 :P

**Comment by radfast** [comment]
Someone has built a space station reaching down to y == 0 (should be impossible because the player will fall down to the Overworld below y == 30) or up to y == 255.

Sorry, it looks like Galacticraft has always been coded to crash when those limits are reached.  Maybe your player is the first person ever to build a space station like this.

We'll fix this now, will also be an issue in 1.7.10 and all other recent versions.

**Comment by MJRLegends** [comment]
Ok he had a water source flowing down to y 0 if that is the cause

**Comment by radfast** [comment]
That'll be it then, though that's strange because plenty of people have that.

I'll also fix it so that liquids are ignored in these checks.

A long-term goal is to have liquids not "flow down" in space stations but instead make floating balls/globules of liquid, but don't expect that any time soon ....

**Comment by MJRLegends** [comment]
Thank you

**Comment by radfast** [comment]
Will be fixed in 116.  No promise when that will come, but next 1-2 days likely.

**Comment by MJRLegends** [comment]
Ok sounds good

**Comment by MJRLegends** [comment]
@radfast Just wondering is there a ETA on that build 116 as im thinking about updating my mod pack soon and wondered if its worth me waiting out for it :D sorry to bother you again :D

**Comment by radfast** [comment]
build 116 probably out later tonight, just trying to solve some Mek compatibility issues in 1.11.

**Comment by MJRLegends** [comment]
@radfast Thank you :P

**Comment by radfast** [comment]
build 116 is now available
