### ISSUE TITLE
Basic Solar Panel generates more power than Advanced Solar Panel on Venus

### ISSUE THREAD

**Issue by andylizi** [micdoodle8/Galacticraft#2927]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.115
Forge version: 13.20.1.2425

Single player (SSP) or Multiplayer (SMP)?  SSP

Galacticraft add-ons and other mods installed?
- IndustrialCraft 2.7.81-ex111
- OptiFine HD_U_C3
- JEI
- Waila
- Wawla
- WorldEdit
- bspkrsCore
- ArmorStatusHUD

## At sunset
![at sunset](https://user-images.githubusercontent.com/12008103/28772032-8cb31cdc-7617-11e7-9709-13bf549e3e57.png)

Basic Solar Panel generates 21gJ/t :

![Basic Solar Panel at sunset](https://user-images.githubusercontent.com/12008103/28772085-a8c3e8ca-7617-11e7-8f85-4e9bb5c66951.png)

Advanced Solar Panel generates 1gJ/t :

![Advanced Solar Panel at sunset](https://user-images.githubusercontent.com/12008103/28772114-c5f76fc0-7617-11e7-8693-bde96aa49528.png)

## At noon
![at noon](https://user-images.githubusercontent.com/12008103/28772174-f0705b7c-7617-11e7-8e64-e1cd870724b3.png)

Basic Solar Panel generates 106gJ/t :

![Basic Solar Panel at noon](https://user-images.githubusercontent.com/12008103/28772205-0c9de404-7618-11e7-876b-ff33b23884ce.png)

And Advanced Solar Panel.....

![Advanced Solar Panel at noon](https://user-images.githubusercontent.com/12008103/28772267-3b6da832-7618-11e7-9ec3-3ec3ece235ca.png)

105gJ/t.

On the other planets they both work fine.

**Comment by radfast** [comment]
good spot, thank you we can look at this.

**Comment by radfast** [comment]
This is fixed from build 151.

Thank you, before this the solar panel generation levels were slightly messed up even on the Overworld.

The main issue was that on Venus the sun position rotates backwards through the sky, and we had the panels being drawn to track that correctly, but forgot that the power generation levels should do the same  - so that's why things were most messed up for the Advanced Solar at sunset or sunrise on Venus.

I also now added a small height boost to generation on Venus - or at high altitude it's less terrible than it otherwise would be.
