### ISSUE TITLE
[1.10.2] Deconstructor destroys rockets

### ISSUE THREAD

**Issue by SamDaywalker** [micdoodle8/Galacticraft#2984]
Minecraft version: 1.10.2
Galacticraft version: 4.0.0.117
Forge version: 12.18.3.2254

Single player (SSP) or Multiplayer (SMP)? Both

Galacticraft add-ons and other mods installed? Yes (FTB-Modpack)

The deconstructor "eats" any GC rocket without giving back anything, other GC blocks or items work correctly. This seems to be not intended, following the galacticraft wiki where it says "The Deconstructor is primarily intended to take apart your old Tier 1 and Tier 2 Rockets". What use is it to take it apart when all material is lost?

**Comment by marcus8448** [comment]
It works on almost all rockets in 1.11.2 just not the Pre-fueled rockets.

**Comment by TheQuadShot** [comment]
Well that explains why I couldn't repro this, It works fine with all of the rockets(1.10/1.11), EXCEPT for the Creative Pre-fueled rockets which I didn't test until now and they don't return anything, I would expect that to be by design.

**Comment by SamDaywalker** [comment]
I did some further testing. There seems to be an issue with the "Extra Planets" mod. Disabling the mod will make the recycling work again. However higher level "Extra Planets" Rockets can be recycled.

So I guess it is a bug in "Extra Planets" - so maybe I should report it there.

**Comment by MJRLegends** [comment]
Im doing nothing more than what @radfast told me to do for API hooks for it. 
![](https://i.gyazo.com/2d293061a29741cff831d636645adcd8.png)

I also matched this with how the Mars and Asteroids code is for doing this. So nothing wrong on my side....

**Comment by MJRLegends** [comment]
Galacticrafts adding
![](https://i.gyazo.com/97d03879959d581e638f64fad8f9b268.png)

What @radfast said to me to do 
![](https://i.gyazo.com/b97905baf73fcd7bc8bd4c58e6f319a8.png)

**Comment by MJRLegends** [comment]
Im also registering them in the FMLPostInitializationEvent not any earlier

**Comment by SamDaywalker** [comment]
Then it does not seem obvious to me what's going wrong here. It somehow looks as if Extra Planets overwrites the standard recipes with an empty recipe, but that's for the both of you to find out where that happens specifically. I am really wondering why that only happens to rockets but any other recipes stay intact.

**Comment by radfast** [comment]
The Creative-only rockets return nothing, by design.  (It's also because they have no recipe.)

The Extra Planets issue I can't troubleshoot without a link to the relevant Extra Planets source code.  Please can you take another look at this @MJRLegends, maybe run the code with some logging lines entered - there is already (this)[https://github.com/micdoodle8/Galacticraft/blob/MC1.11/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityDeconstructor.java#L222] if you enable debug messages.  It's possible you deleted the basic rocket recipes, or you deleted the basic metal plating from the ```salvageable``` list, maybe check both?

**Comment by MJRLegends** [comment]
@radfast My source code is all here https://github.com/MJRLegends/ExtraPlanets/branches

and all im doing with this machine is the following 
![](https://i.gyazo.com/2d293061a29741cff831d636645adcd8.png)

**Comment by MJRLegends** [comment]
@radfast From my debugging with break point it seems both the salvage list and the recipes list do still have GC added stuff in.... So im not sure....

**Comment by MJRLegends** [comment]
@radfast From my debugging with break point it seems both the salvage list have GC added stuff in but the recipes list is being cleared for reason... any ideas to why me using the same method to how GC is adding them it causing this issue

**Comment by MJRLegends** [comment]
@radfast also I tried both adding them at init and post init and nothing changed

**Comment by MJRLegends** [comment]
Ive found a solution, its messy one but works

If i add the GC recipes to the known recipe list as i do mine they work
![](https://i.gyazo.com/d38765141cee1b4d37454eda66a88d0a.png)

**Comment by radfast** [comment]
that solution sounds OK, but it won't respond if we change the known recipe list in GC in future.

I can't search your repo for the code for this because it's not in the master branch - please link to the actual code you are using to manipulate the known recipe list.  If it's clearing the list, it's most likely a bug your side.

**Comment by SteveKunG** [comment]
@MJRLegends I've try with WorldEvent.Load event, and its work fine.

![2017-10-02_05 31 12](https://user-images.githubusercontent.com/6128413/31059888-f6cfc4b6-a732-11e7-8ed1-36bf6c8e6e95.png)

**Comment by MJRLegends** [comment]
Registering things on events is a weird way

**Comment by MJRLegends** [comment]
@radfast ive posted a screenshot of my code for it about 3 times in this issue im doing nothing else than my screenshot shows

**Comment by MJRLegends** [comment]
Tbh this just needs a api hook, adding and changing weird stuff on my side isnt going to be what i want to do

**Comment by radfast** [comment]
not seeing your screenshots?!

please can u give me a link to the class and line of code on your repo.

**Comment by MJRLegends** [comment]
Something is wrong with your browser as i saw on a different issue too that you said about a screenshot when the user already posted one haha 

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.10.2/src/main/java/com/mjr/extraplanets/ExtraPlanets.java#L553

**Comment by radfast** [comment]
ok thanks for the code link.  not sure what's wrong with my browser, it's the latest Firefox, but i'm not going to troubleshoot that today!

The issue here is you are calling ```RegisterDeconstructorCompatibility()``` at a time before Galacticraft Core and Planets have registered their recipes in GalacticraftRegistry.  Therefore when the GC core code uses .addAll for RocketT1Recipes, that's a null list at that time.  (Your reference to TileEntityDeconstructor.knownRecipes will automatically activate the static code in TileEntityDeconstructor.)

Looks like GalacticraftCore and Planets do not register recipes until postInit phase.  Your mod's postInit phase will come first, because Extra Planets is earlier in the alphabet than Galacticraft.  

If you can defer your call to ```RegisterDeconstructorCompatibility()`` until after GalacticraftCore / Planets postinit phase, that will be best.  Probably why it's working for SteveKunG leaving it as late as the WorldLoadEvent.

I actually don't know why recipe registration is deferred until postInit - maybe it's to ensure all other mods have completed init phase, including oredict registrations?  I don't want to change the timing of that in case it breaks something unrelated to this issue.

**Comment by MJRLegends** [comment]
Registering the recipes on world load will just cause them to keep getting added and added as the user leaves and joins other worlds. I feel like a proper api hook is needed

**Comment by radfast** [comment]
I edited my post, see above ^^^^^^^^^^^^^^^

Now fixed on our side, you don't need to change anything.  @SteveKunG you can now register your Deconstructor recipes in PostInit instead of world load.
https://github.com/micdoodle8/Galacticraft/commit/6f52dbee607b750d052068ef073f29502fa0639a

**Comment by MJRLegends** [comment]
@radfast thanks, for simple amd cleanness please could you add the recipe registering and add salvage items to the GalacticraftRegistry class this would make more sense since are already using it for the actual NASA workbench recipes

**Comment by radfast** [comment]
no, sorry, I'm not going to make unnecessary code changes, your existing code works as it stands.

It is inevitable that full-scale add-ons like yours will have to refer to internal Galacticraft code sometimes, so I don't see any advantage in theoretising everything out to the API.

For a more detailed answer: the major problem with moving things out to the API is that you then have references in API code to internal Galacticraft classes, and this creates problems for people who just want to use the API in their projects without having all the Galacticraft sources.  To solve that we would need to use reflection for everything in the API, which is less transparent for people who don't know Java reflection, as well as having performance issues and taking more coding time and potentially introducing new errors (e.g. if core code is updated but the reflection code in the API is not updated, there will be runtime errors, not noticed at compile time because of course the reflection code does not error at compile time.)

**Comment by MJRLegends** [comment]
@radfast No problem, i will make mine a minimum requirement of build 118 for the next ExtraPlanets updates for MC 1.8.9 and MC 1.10.2 and MC 1.11.2
