### ISSUE TITLE
[1.11.2]/dimensiontp from AromaDimension to Overworld stuck

### ISSUE THREAD

**Issue by Arkyo** [micdoodle8/Galacticraft#2986]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.11.2
Galacticraft version:117
Forge version:2476

Single player (SSP) or Multiplayer (SMP)?Multiplayer

Galacticraft add-ons and other mods installed? Advanced Rocketry

Please provide screenshots / crash report / log as needed.
https://pastebin.com/AsmBEk2r

**Comment by TheQuadShot** [comment]
This looks like an OMT problem (OpenModularTurrets), unless there is much more in the log that didn't get posted.

**Comment by radfast** [comment]
Like @TheQuadShot said.

The problem is a crash in OMT - do you have turrets in the Overworld location where you should be landing at?

Please report this to the OMT developers, and meanwhile maybe try playing without that mod.

If the OMT developers want to test without Galacticraft installed, try using Nether portals around turrets, there would likely be the same issue - Galacticraft transfers players between worlds in basically the same way that Nether Portals do it.  One other thing I can think of: when you transfer to the Overworld, the player first spawns very high up, and parachutes down from there.  Maybe the turrets are freaking out because the player is so high?
