### ISSUE TITLE
[1.11.2] Power not compatible with FE

### ISSUE THREAD

**Issue by AugiteSoul** [micdoodle8/Galacticraft#2998]
That. I hate needing to use crappy GC solar panels to power everything.

**Comment by TheQuadShot** [comment]
What is FE? and how are you trying to connect them?

**Comment by KingNut** [comment]
I think FE=Forge Energy, is incompatible with GC. I dont know this mod or a source.

AugiteSoul, your Issue need MUCH MORE details to be solved...

**Comment by AugiteSoul** [comment]
FE is something that allows machines from nearly every tech mod to share energy with other tech mods. And currently, GC doesn't allows FE-generating machines to power its Oxygen Sealers (and other machines) or to power a FE-using machine using a GC solar panel, like it used to be in 1.7.10 with Redstone Flux.

**Comment by radfast** [comment]
@AugiteSoul which other mod are you using and experiencing problems with.  Please provide screenshots if possible.

Yes, Galacticraft is currently not compatible with "FE", but I was not aware this was a real problem as none of the other major tech mods uses FE exclusively.  This appears to be a Suggestion / Feature Request rather than a bug report.

**Comment by AugiteSoul** [comment]
Well, try to use something from GC with something from any mod that uses FE. Here is my list:
-Actually Additions
-Correlated
-Extra Utilities 2
-Extreme Reactors
-Fluxed Redstone (wires connect, but don't actually work)
-Immersive Engineering
Maybe add a converter block?

**Comment by AugiteSoul** [comment]
Fine, then. Just gonna use coal as fuel for my base in the Asteroids. Sounds so spacey and futuristic. /s

**Comment by radfast** [comment]
There should be Forge Energy compatibility in the next build released, though it will be used only if other energy systems like Mekanism, IC2 and RF are not present.

There appear to be minor issues caused by other mods, for example Extra Utilities 2 generators will put FE energy into adjacent Galacticraft machines even if the input side of the GC machine is not facing towards the generator.  There's not much we can do about that, it's not a bug on our side.  The Forge Energy system is fairly basic, it's like a "lowest common denominator" system which is why authors of advanced tech mods don't like it.  (Actually it can do sided inputs, looks like EU2 is just not checking for that with their generators.)
