### ISSUE TITLE
[1.11.2] Astro Miner Base texture going blurry when viewed from a certain angle

### ISSUE THREAD

**Issue by AugiteSoul** [micdoodle8/Galacticraft#3000]
![2017-10-01_21 17 53](https://user-images.githubusercontent.com/16467639/31058110-6c84424e-a6ee-11e7-979e-aa0b5aa332cd.png)
Title says all.

**Comment by SteveKunG** [comment]
This may caused by Astro Miner laser rendering, I will check this out later.

**Comment by SteveKunG** [comment]
@radfast What happened if I remove `GL11.glTexParameteri` ? I don't see any different of rendering. (I'm not expert at LWJGL.)

**Comment by radfast** [comment]
Thanks for reporting, this is fixed.

@SteveKunG  that parameter affects the hoverpad rendering.  .NEAREST is the normal Minecraft look: every pixel in the texture is shown.  .LINEAR is the blurred / averaged pixels look seen in most other PC games - and it's this one we need for nice looking glow effects on the hoverpads.

The issue here was a strange one, where [this vanilla method](https://github.com/micdoodle8/Galacticraft/blob/917c9678d23e9bfc0d3bebfa27fb557fe6269a4e/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/client/render/entity/RenderAstroMiner.java#L222) locks in the currently set ```GL11.glTexParameteri``` even though we change back ```GL11.glTexParameteri``` to .LINEAR later on.
