### ISSUE TITLE
[1.11.2] An issue with refined storage

### ISSUE THREAD

**Issue by Diamond45123** [micdoodle8/Galacticraft#3002]
There is an invalid item in the storage system that crashs me instantly when i open the grid. I had the same problem with mekanism here : https://github.com/aidancbrady/Mekanism/issues/4731 but it got fixed, now im getting this crash.
Crashlog : https://pastebin.com/kgUUvwam

Minecraft version: 1.11.2
Galacticraft version: 4.0.0.116
Forge version: 13.20.1.2425

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Refined Storage : 1.4.20

**Comment by radfast** [comment]
The root cause of this problem is:

1.  This **Refined Storage** contains an invalid item: the item id + damage combo does not exist

2.  Either it's a bug in Refined Storage, or another possible cause is that you added or removed a mod or updated a mod which added new items to the game, and so some of the item ids assigned by Forge changed - I think that can happen, not sure how common it is though

3.  **Refined Storage** can fix this problem for all mods simply by including ```try ... catch``` error trapping in ```GridStackItem.getName()``` at line 60, or some other sensible place

It is **NOT** a Galacticraft bug.  The other bug was **NOT** a Mekanism bug.   @raoulvdberge was wrong to say that Mekanism messed up the naming system.

I do not see any advantage in coding a workaround for this specific item in Galacticraft, as that will not fix the issue - i.e. wrong item id and damage value - it would just prevent this specific crash for this specific item, but it won't stop a similar crash for any of 100s of other Galacticraft items.

It is not a bug in our mod if the mod crashes when you try to pass in an item with a damage value which is outside the range of registered sub-types for that item.

**Comment by radfast** [comment]
I'm sorry, I don't agree with you on that.

The code which sets or changes the damage value of an ItemStack is the code which should do the sanity check.  I think our code is entitled to assume that our own mod's items have damage values within the range we assign as legal in the item class.

As said earlier, the root cause here is that Refined Storage is creating invalid items.  Whatever else they are (even if there was a sanity check which, for example, return a damage value of 0 for any invalid damage value), they are not going to be the same items that the player placed into the storage.

**Comment by Diamond45123** [comment]
@radfast @thiakil I tried removing a drive and got this : https://imgur.com/a/43jVm, lots of invalid items from thermal foundation and mekanism... thermal foundation items are called INVALID ITEM (DELETE ME) and mekanism has their normal names but broken texture..
i think its time to delete this world xd

**Comment by thiakil** [comment]
@radfast you can determine the validity however and wherever you like. The issue is that you're blindly passing an invalid array index, causing a crash. Damage values *can* be edited by other stupid mods, and you should handle this.

**Comment by raoulvdberge** [comment]
Keep in mind that you can also use /give to give items. If you give the wrong metadata by accident, you'd crash. Sanity checking is always needed for stacks.

**Comment by radfast** [comment]
> If you give the wrong metadata by accident, you'd crash.

If you do that, you deserve the crash.  Again, you've created an impossible item so what is the game supposed to do.

And even if there were universal sanity checking in our mod and all others for every place where an itemstack damage value is used, you've still got the problem in Refined Storage that you are (a) giving players items different from what they put into the storage (b) creating invalid items.

**Comment by thiakil** [comment]
> so what is the game supposed to do

Fail *safely*

**Comment by raoulvdberge** [comment]
> If a player does that, he deserves the crash. The player has created an impossible item using a hack, so what is the game supposed to do?

/give is not a hack.

The problem in RS is separate from this IMO, you still need to sanity check. Even if RS gives a invalid stack (which I am not sure if it's RS even).

**Comment by Diamond45123** [comment]
Hey, So it's been a long time since this situation, but I've done some decent progress on a new world, so my question, How do I prevent this whole issue to happen again?

**Comment by zekejusonu** [comment]
> Hey, So it's been a long time since this situation, but I've done some decent progress on a new world, so my question, How do I prevent this whole issue to happen again? As I'm planning to make an RS System anytime soon and I don't want this thing to happen again, cause it sucks.

2019 same error lol ,
 I transfer everything to another mod ,I advise you not to risk with RS
