### ISSUE TITLE
[All versions] Weird Issue with Mars Mining Levels for Surface and Sub Surface blocks

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3008]
Hello,

The Mars Blocks are called Rock but require a shovel to be mined?

Its getting players of my mod pack confused to the fact its called rock but uses a shovel to break it

Code in question here

https://github.com/micdoodle8/Galacticraft/blob/4d1f2271456217a56eedb07d6a1db52e077dedaf/src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/MarsBlocks.java#L72

and 

https://github.com/micdoodle8/Galacticraft/blob/4d1f2271456217a56eedb07d6a1db52e077dedaf/src/main/java/micdoodle8/mods/galacticraft/planets/mars/blocks/MarsBlocks.java#L73

**Comment by EzerArch** [comment]
Well, that's weird. So we should pick either:
* Call it dirt (or gravel, regolith if top soil), and make behave like dirt, be mined like dirt, look like dirt, and sound like dirt. This means that step sound and texture should also change to match the shovel usage (Currently Mars top layer looks/sounds like stained clay).
* Call it rock, and so and so. This means less change: pickaxe would be then the minimum tool, to make more sense BTW.

**Comment by MJRLegends** [comment]
Yeah just seems conflicting ideas

**Comment by radfast** [comment]
I've updated the English language files to:
**Mars Regolith** in place of Mars Sub-Surface Rock
**Mars Fine Regolith** in place of Mars Surface Rock

That's [reasonably scientifically accurate](https://en.wikipedia.org/wiki/Martian_soil)

I guess originally Micdoodle8 didn't want to use the name Regolith because it's too technical for little kids, but I think it's OK - there's all kind of weird names in Minecraft, we have other technical names in Galacticraft, and hey, maybe the kids will learn something here.

**Comment by radfast** [comment]
What I would really like to do is improve our Mars worldgen and surface decoration so that it starts to look more like (a block version of) this:
![Mars](https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/PIA17944-MarsCuriosityRover-AfterCrossingDingoGapSanddune-20140209.jpg/1280px-PIA17944-MarsCuriosityRover-AfterCrossingDingoGapSanddune-20140209.jpg)

**Comment by MJRLegends** [comment]
Nice @radfast the change should work great :D

**Comment by EzerArch** [comment]
> What I would really like to do is improve our Mars worldgen and surface decoration so that it starts to look more like (a block version of) this.

Excellent!
