### ISSUE TITLE
[1.11.2] Galacticraft causing mipmap flickering

### ISSUE THREAD

**Issue by chaNcharge** [micdoodle8/Galacticraft#3009]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.118
Forge version: 13.20.1.2513

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? Galacticraft, Galacticraft Planets, MicdoodleCore, JEI

Please provide screenshots / crash report / log as needed.

Hard to get a proper video showing it, but here's how to reproduce it.
1. Launch Minecraft with above mods installed
2. Set mipmaps to any level other than 0 (most visible on level 4)
3. Open any world
4. Open your inventory, and in the JEI search bar, type "@ galacticraft"  (without the space) to display all galacticraft items
5. Close your inventory, and the mipmaps should be broken and flickering.

**Comment by TheQuadShot** [comment]
iirc... mipmap settings (as of a forge pull 3300ish) should be "forced applied" and render correctly with the exception of a block/s that is/are not "mipmap friendly"(texture being an odd size or not divisible by 2). Have you tried this with no "mods" installed? ie no mod that adds a block, just a "mod-able" build, like Forge, NEI/JEI WAILA. I also don't understand why opening anything should matter since the mipmap should be happening in real time, not applied after opening a crafting session/chest...

**Comment by chaNcharge** [comment]
Well the thing is, a similar issue happened to Draconic Evolution, except that's been fixed as of now. However the issue also reproduces with this mod.

**Comment by chaNcharge** [comment]
Now that I did more testing, it's hard to tell what's really causing the issue. I'm starting to doubt that GC is causing the issue. I'll look more into it

**Comment by chaNcharge** [comment]
I narrowed down the results more and it appears that it's something broken with Black Hole Storage. I tested Black Hole Storage with just JEI and OptiFine and the issue successfully reproduced. I don't know why it originally happened with Galacticraft before, but I'll close it assuming the issue is resolved. I'll reopen it if it returns for whatever reason.
