### ISSUE TITLE
I can't get in any rocket

### ISSUE THREAD

**Issue by Chuck240607** [micdoodle8/Galacticraft#3011]
Minecraft version:1.10.2

Galacticraft version:3. 

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? yes

Whenever I try together in a rocket, it breaks.

**Comment by Chuck240607** [comment]
Minecraft version:1.10.2

Galacticraft version:3. 

Single player (SSP) or Multiplayer (SMP)? SSP

Galacticraft add-ons and other mods installed? yes

Whenever I try together in a rocket, it breaks.

**Comment by TheQuadShot** [comment]
Unfortunately you haven't provided any information that is helpful. Please read the the information listed on the page the tells you what needs to be in a bug report (the stuff you ignored and deleted). Otherwise no one can help you.

**Comment by Chuck240607** [comment]
I'll send u a vid tomorrow

**Comment by Chuck240607** [comment]
here is the issue: https://youtu.be/Xvr2MO6qikw

**Comment by Chuck240607** [comment]
Here is the issue https://youtu.be/Xvr2MO6qikw

**Comment by MJRLegends** [comment]
@Chuck240607 You can get in a rocket if there isnt one, your videos show you looking at a pad and typing in chat. Please show the bug happening with GC rockets & we can help you out.

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by Chuck240607** [comment]
There is the issue

**Comment by Chuck240607** [comment]
Hello, MJRLegends , did u receive the link

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by Chuck240607** [comment]
https://youtu.be/S-RILzAlX9w

**Comment by dj3520** [comment]
Spamming the issue tracker is likely to annoy a ton of people and end up with the developers will be somewhat irritated with you. It also **won't** result in your issue getting fixed faster.

**Comment by Chuck240607** [comment]
Ok, but the issue has persisted for 4 days

**Comment by dj3520** [comment]
That's not enough justification.

**Comment by Chuck240607** [comment]
why

**Comment by TheQuadShot** [comment]
well for one thing you still haven't provided the INFORMATION NEEDED...
READ THE PAGE... (the one you ignored, then ignored again when you were asked, and will probably ignore this time as well)
https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md

I'd also add that this most likely isn't an issue with the mod, it's something on your end, since: if this were a bug then it would have been found long ago and be resolved...

**Comment by EzerArch** [comment]
**_"My rocket is broken, fix it"_**

You know, it's like @MJRLegends or any other developer has the obligation to stay 24/7 on github working for free to fix bugs on demand with almost no info, context or detail (yes, we know we have _some_ info now, thanks, but you're expected as per [contributing guidelines](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) to provide them from the start for a faster debugging).

**Comment by Chuck240607** [comment]
@EzerArch ok

**Comment by dj3520** [comment]
Most importantly though, this isn't a chat room.

**Comment by radfast** [comment]
@Chuck240607 in that video, were you in Creative Mode or normal Survival game mode?

The rocket did not disappear from your player inventory when placed, so it appears you may not be placing the rocket item on the pad correctly...    so you're seeing a ghost rocket on the pad, not an actual rocket you can climb inside.

Likely cause for this is a conflict from another mod.  Maybe something to do with player respawning.  What happens if you log in fresh to your world and immediately try to place a Galacticraft rocket on a launch pad?

**Comment by Chuck240607** [comment]
creative

**Comment by radfast** [comment]
I'm still struggling to understand what **issue** is being reported here.  The rocket not disappearing from inventory is normal in Creative mode.  You should be able to get in the rocket by right-clicking it, same as how you get in a **Minecart** or a **Boat**.

Can you get in a rocket in Survival mode?

Can you get in a Minecart or a Boat?

What about if you have a new world with Galacticraft as the only mod installed?

**Comment by Chuck240607** [comment]
I can in Survival, then I go back to creative

**Comment by radfast** [comment]
Closing due to stale issue and lack of essential information like:
* exact Galacticraft version
* full modlist
* Forge version
* logs

Even if this is a conflict with another mod, there is no chance we can fix it unless the person with the issue narrows down which mod is conflicting.
