### ISSUE TITLE
Question about oil

### ISSUE THREAD

**Issue by Antillar** [micdoodle8/Galacticraft#3024]
Minecraft version:1.7.10
Galacticraft version:3.0.12.502
Forge version:1614

In the past Galacticraft used to have a fluid called "oilgc", which was different from normal oil added by BuildCraft. Currently it seems that GalactiCraft uses the normal oil. However, old cross-mod integration between GalactiCraft and GregTech 5 Unofficial exists on GregTech side, and GT is still trying to add oilgc. My question is: is oilgc still used somewhere in GalactiCraft? If not, this integration should be updated.

**Comment by radfast** [comment]
In Minecraft 1.7.10, Galacticraft still has the option to use oilgc.

There's a config setting which should switch it over to this (also another setting for fuel):

```Use legacy oilgc fluid registration=true```

But, I think not many people are using this, because any recently recreated 1.7.10 world should work ok using the standard "oil" setting, even if Buildcraft is present.  The reason for the legacy setting is that a long time (~3 years) ago, Galacticraft auto-switched to using ```oilgc``` for its own oil if Buildcraft was present.  That meant you could have a 3 year old world with a lot of tanks and buckets filled with oilgc, and you would lose all that in your world if you updated to a newer Galacticraft.  The legacy setting was provided to prevent this loss of resources.

Hope that answers the question, please comment here if not.
Or you can start a discussion on the Galacticraft forum and maybe get more input from other GC players.
