### ISSUE TITLE
1.12.2 Branch

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#3037]
Can you create a 1.12.2 branch please? I want to update it on my forked side then make a pull request. 
Thanks :)

**Comment by radfast** [comment]
Maybe ...   tell me more about this pull request?

**Comment by kenijey** [comment]
What exactly xD just a 1.12 port
I know it will be hard, we just want to try our best :D 
if you dont want to do it, ok... i just wanted to help GC to port newer versions of Minecraft

**Comment by MJRLegends** [comment]
@radfast see my message on forums before doing this

**Comment by radfast** [comment]
@kenijey  MJRLegends is already doing some work on this.

We'll also need to check and update MicdoodleCore which is complex every time there is  a MC version update, because it changes the code at Java bytecode level and the Minecraft obfuscation usually changes.

Maybe in 2 weeks from now we will have something that is stable enough to open up as a 1.12.2 branch on Github.  At that stage it will be really great to have your help with coding and making it playable - there's bound to be stuff that breaks even if the code looks error-free...

**Comment by kenijey** [comment]
oh, that is good to hear. i wasnt aware of somebody is already working on it.
yeah, i will help with my best when that stable branch opened. thanks for replying with care.

**Comment by kenijey** [comment]
2 weeks passed :D

**Comment by kenijey** [comment]
can we see it soon or anytime?...
indeed, i highly recommend skipping 1.12 due to 1.13. it's so close to 1.13 be released. so...

**Comment by EzerArch** [comment]
> can we see it soon or anytime?...

Hmmm, to whom it may concern: Christmas is nigh. Kind of hard to expect anything these days -- unless something edible XD.

**Comment by MJRLegends** [comment]
@EzerArch yeah well said

(PS please see my pms on GC fourms) :D

**Comment by radfast** [comment]
1.12.2 is now available to [download](https://www.micdoodle8.com/mods/galacticraft/downloads)

**Comment by kenijey** [comment]
yeah i'm playing it and reporting issues as much as i can. good work!
and btw, mojang just merged 1.13 and 1.14 but it will be released on 1.14's time (Q2 2018) so its not an important issue anymore :D
