### ISSUE TITLE
Cargo Rocket Not Landing and Frozen Above the Space Station

### ISSUE THREAD

**Issue by TehDerpyChild** [micdoodle8/Galacticraft#3063]
Hello! I've been using this mod for a while now (best mod ever tbh) and I came across a rather weird bug and glitch in the cargo rocket when its sent to a space station. Every time I launch a cargo rocket to a space station the rocket seems to never land and if you fly high enough (around 800 blocks) you can see the rocket moving up and down constantly, using fuel and is unbreakable (unless you use the kill entity command). The game doesn't crash, and restarting the game doesn't fix it.

Minecraft version: 1.11.2
Galacticraft version: 1.11.2-4.0.0.119 (Latest)
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP.

Galacticraft add-ons and other mods installed?
Optifine
Just Enough Items (JEI)
Xaero's Minimap

Please provide screenshots / crash report / log as needed.

https://youtu.be/tVdBQguY4_Y

**Comment by radfast** [comment]
Thanks, we'll investigate.   Thank you for the excellent video, it's very helpful for us to see the issue reproduced like that.

It's possible that Cargo Rockets have not been thoroughly tested with Space Stations in 1.11.2... :-o

Please keep an eye on this issue (or your email inbox) in case we have any questions that might help solve this.  May be a week or more before we get back to you with any kind of fix, I am travelling at the moment for holidays.

**Comment by TehDerpyChild** [comment]
Not wanting to sound like an impatient arsehole but i'm curious, is there going to be a fix for this bug soon?

**Comment by radfast** [comment]
Yes :)

**Comment by radfast** [comment]
Should be fixed in next build 148.  Thanks for your patience.

BTW:  even with an active Launch Controller, a Space Station dimension will not stay loaded if no player is there.  So now the cargo rocket will hang at the Space Station **until a player goes to the station** - when a player goes to the station, the cargo rocket will land on the station correctly.

This is the behaviour with default configs.  You can change it in 3 ways: include your space station dimension (e.g. 3) in the list of dimensions to keep loaded.  Use the /gckeeploaded command.  Or there's a setting for **all** newly created space stations to stay loaded.  (I think I will make that default to `true` in future.)

The reason for this is on large servers with 50+ players creating space stations, they don't want them all loaded all the time when the player is offline.

**Comment by radfast** [comment]
Build 148 is now available - enjoy :)

**Comment by TehDerpyChild** [comment]
Thank you!
