### ISSUE TITLE
Issues with issues

### ISSUE THREAD

**Issue by DeinoRaptor** [micdoodle8/Galacticraft#3076]
There is an Issue with the Issues. The Issue is that I post a crash (related to Galacticraft), but my post gets moderated and closed. I need help, but no one is helping. So thats the issue with Issues. Instead of shutting and moderating the post, help them, then shut it down.

**Comment by MJRLegends** [comment]
Dude stop making issues you are just spamming now

**Comment by DeinoRaptor** [comment]
never

**Comment by radfast** [comment]
you have been spamming for a few days now

I already told you, the issues list is not for personal help requests with Minecraft or your modpack, so don't complain that "nobody helped you".

The issue you are trying to get help with does not appear to be a Galacticraft issue, so it is not appropriate to report it here and there is no more action we can take for now.  If you can show - by careful, diligent testing - that it is an issue caused by the Galacticraft mod then we can reconsider this.

Please also note carefully that the tone of your posts has annoyed me and other people.  If you carry on like this, we can block you from this Github completely.
