### ISSUE TITLE
OpenGL Error with new 121.

### ISSUE THREAD

**Issue by chezpaul** [micdoodle8/Galacticraft#3102]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.10.2
Galacticraft version: 121
Forge version: 2511

On Server

Galacticraft add-ons and other mods installed? Extra Planets 0.9.0

https://gyazo.com/79a78903af8f0b301bb94c83a0fe109d

I get this new error with 121 but not with 120. Only Galacticraft version has been changed.

**Comment by MJRLegends** [comment]
Do you have optifine?

**Comment by chezpaul** [comment]
Yes I do. But Galacticraft normally is okay with Optifine? Isn't it?
I have read around that it's usually a graphics card driver problem. I'm on a mac so I have the latest driver and 120 works fine.

**Comment by MJRLegends** [comment]
Yeah thats your issue. optifine is a vanilla tool and this is the kinda of issues that you get when using it with modded which it isnt made for

**Comment by chezpaul** [comment]
Well, I must admit that without it, I wouldn't be able to play. Too much lag.

**Comment by chezpaul** [comment]
btw, optifine is a mod so you can't really say that it's for vanilla minecraft. You can only use it if you've modded minecraft...

**Comment by MJRLegends** [comment]
@chezpaul To put it in simple turms, if it is ExtraPlanets sorry to say but i dont provide any support as all for Optifine for any of my projects. The amount of things optifine screws up is insane as a mod pack dev with over 700k+ and 150k+ on another and with over 1,000,000 downloads on ExtraPlanets ive seen that optifine can do and theres no way to fix them on a forge side. 

The fact that you can use it with forge isnt down to any forge dev or forge mod dev, its due to fact the optifine devs try to support it but only works 25% of the time fully.

Optifine has a optional support for forge you can use it with vanilla mc without forge. The issue is with the ability of custom open gl code that you can get in forge mods which optifine doesnt know how to handle or changes.  The fact that Forge on its own works is because its not much different from vanilla. It adds close to 0 new features just hooks and registries and api classes for mods to use

**Comment by MJRLegends** [comment]
Also on a side note you have a screenshot for a error which shows no link to any minecraft mod, ive also kmow optifine to error over vanilla too. Unless you can show a direct link to any mc mod it will be extremely hard for even someone to even find the cause of the issue

**Comment by chezpaul** [comment]
I wasn't trying to blame Extra Planets for not working with Optifine. 
I totally understand your position and respect it. 
I was just trying to understand why all of a sudden I get the error.

**Comment by radfast** [comment]
@chezpaul 

1. can you give any context for this error, like what is on screen (blocks, mobs, vehicles) when it happens?

2. does the game still play after the error, or is there a crash?   if crash, please post crash report

3. anything else in logs?  check the whole log, like maybe something did not register correctly?

4. can you give exact steps to trigger the error, for example it always happens if you go to X spot in your world?

5. do you get it with a reduced modlist, or with Galacticraft alone?

6. do you get it **without Optifine**


I'm surprised that you say the game is laggy without Optifine.  Minecraft 1.8.9 have a re-written rendering engine which is faster than 1.7.10 and before, so that it is difficult for Optifine to make any more improvement.  Most of what Opftifine does now is give specific control over finer details, like switching them on or off.

If a specific conflict between Galacticraft and Optifine is shown, that's something I will look at, but it's low priority for me because you can run the game without Optifine.

If you have lag problems, I suggest:
(a) remove mods you don't use
(b) use **FoamFix**
(c) look at other performance enhancing mods like **FastCraft**
(d) lower your render distance by a couple of chunks - more importantly, this also reduces the server load (on the integrated server in SSP) because not so many chunks are loaded

**Comment by radfast** [comment]
I think this is **probably** not a Galacticraft issue, but I'll leave it open for now.  If further investigation shows that it is a Galacticraft / Optifine interaction (which I doubt) then I will remove that label, of course.

**Comment by MJRLegends** [comment]
It was a ExtraPlanets thing, it has been fixed for the next update, @chezpaul @radfast please close :D

**Comment by chezpaul** [comment]
Great. Thanks
