### ISSUE TITLE
Realistic Torches Support (1.12.2)

### ISSUE THREAD

**Issue by kenijey** [micdoodle8/Galacticraft#3124]
i hope you help for it :D 
![2018-01-25_18 04 39](https://user-images.githubusercontent.com/24831406/35395053-560681be-01fa-11e8-83a6-b9097d53846c.png)
more explanation: if realistic torches mod is installed, lit torch(normal coal torch) burns in moon. but vanilla torch does not. but realistic torches mod deletes the vanilla torch recipe, and adds glowstone paste to craft vanilla torch.
so the support i want is, if the realistic torches mod installed, can you replace lit torch with vanilla torch please? i mean, vanilla torch should burn in moon. because it made from glowstone paste. BUT lit torch, its made from coal and it already has unlit torch...

please help for it. thanks..
or should @MattCzyr help about it at his side?...

**Comment by radfast** [comment]
This is a problem on our side, because Galacticraft mechanics for vanilla torches replaces a "lit" torch with an "unlit" torch when there is no oxygen (similar to Realistic Torches when it rains), but GC then automatically replaces an "unlit" torch with a "lit" torch if there is oxygen again.

Realistic Torches I think will want to use the flint'n'steel mechanic for unlit torches, so the player must walk around lighting them.

Best solution will be if @MattCzyr can implement our Oxygen API for his mod's torches, at the same places in his code that he does an "Is it Raining?" check.  

API links:
```[OxygenHooks.checkTorchHasOxygen(World world, Block block, BlockPos pos)](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/world/OxygenHooks.java#L141)```
```[OxygenHooks.inOxygenBubble(World worldObj, double x, double y, double z))](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/api/world/OxygenHooks.java#L173)```

Best practice will be for Realistic Torches to call both methods, on its torch block update ticks.  ```inOxygenBubble``` should be called with parameters set to the center of the torch flame e.g. xPos+0.5, yPos+0.6, zPos+0.5.
