### ISSUE TITLE
[1.10.2]failed to find matching world "moon.moon" 

### ISSUE THREAD

**Issue by ytyyy** [micdoodle8/Galacticraft#3128]
Minecraft version: 1.10.2
Galacticraft version:  1.10.2-4.0.0.119
sponge version:
I've tried  1.10.2-2202-5.1.0-BETA-2039 and 1.10.2-2477-5.2.0-BETA-2793

The problem occured in the server and I guess it's caused by sponge

Here are some mods I installed:
 Cavern_1.10.2-v1.8.3
ExtraPlanets-0.8.5
GalacticraftCore-1.10.2-4.0.0.119
Galacticraft-Planets-1.10.2-4.0.0.119
More-Planets-1.10.2-2.0.9-GC117
MicdoodleCore-1.10.2-4.0.0.119

the problem is:

when I tried to move to moon the server notice:

Server thread/ERROR [ Galacticraft]: Error occurred when attempting to transfer entity to dimension : moon.moon
Server thread/INFO [Galacticraft]: Failed to find matching world for 'moon.moon'

and my client was stuck
but I can move to mars

I checked the server and there has Dim-28 in the /world/

Then i tried to re-generate the moon so I change the core.conf and set moon to DIM-70

The second problem is : then the moon can't be generated and the DIM-1(nether) become an another space-station——I can jump from the nether to earth
I change the moon to Dim-28 but the Dim-1 hasn't recovery

the problem has not appears in client.

how can I fixed these problem?

**Comment by MJRLegends** [comment]
Try uploading all your mods to latest version and try with latest spongeforge

**Comment by ytyyy** [comment]
I've already use the latest spgongeforge
And when I try the latest GC the server crashed
[crash-2018-01-27_10.44.37-server.txt](https://github.com/micdoodle8/Galacticraft/files/1669715/crash-2018-01-27_10.44.37-server.txt)

I want to know where the GC save the messages so I can fix my nether world
and If there is somewhere I can matching the DIM-28 with the moon.moon
Maybe the problem can be solved

well...I found the config of sponge has  
portal-agents {
            "minecraft:default_nether"=DIM-1
            "minecraft:default_the_end"=DIM1
        }
 if I add something there Can I fix the first problem?

**Comment by MJRLegends** [comment]
Your Extraplanets & More-Planets is still out of date in that crash log you posted

**Comment by ytyyy** [comment]
Thank you
I've already update all these mods
and nether become normally

but the first problem still appears.

27.01 11:43:00 [Server] Server thread/ERROR [Galacticraft]: World not found when attempting to transfer entity to dimension: moon.moon
27.01 11:43:00 [Server] Server thread/INFO [Galacticraft]: Failed to find matching world for 'moon.moon'

what can i do for this?

**Comment by radfast** [comment]
In ```.minecraft/config/sponge/worlds``` try deleting all the configs for galacticraft and add-ons so that Sponge will remake them.

Let us know if that fixes it (it can help other people in future).

If that doesn't fix it, you must still have dimension ID conflicts.  Look again at all the dimension IDs, try to fix it, if you can't then maybe you will have to uninstall one out of More-Planets / ExtraPlanets

**Comment by ytyyy** [comment]
I have delete the more-planets and Extraplanets and then delete the /config/sponge

but the same thing has happened again
even the nether become a space station again...

How can I check the dimension IDs? There is dim-28 in ./minecraft/config/sponge/worlds/galacticraftcore/moon
and dim-33 is also there(add-on's old file) but it has worked normally

**Comment by radfast** [comment]
On the server, again delete ```/config/sponge``` (delete everything and all subfolders) and ```/config/galacticraft``` (delete everything).

It should work correctly if it rebuilds all the configs.

**Comment by ytyyy** [comment]
I delete /config/sponge/ , /config/galacticraft/  and /config/MorePlanets.cfg and /config/ExtraPlanets.cfg
but has not delete /world

and delete these two add-ons
but the problem has not been solved...

**Comment by radfast** [comment]
It's so hard to help because I cannot see your /world and /config folders on the server ...

Two things to try:
1)  Make a .zip file of your whole ```/world``` folder on the server - you can take out the **Overworld** (DIM0) if you want to make it smaller, I don't need to see the overworld - and upload to the cloud somewhere

2)  Make backup copies of your /world, /config and /mods folders and just keep deleting stuff and restarting until it works ... you can delete Sponge for example, try running the same server without Sponge

One more question - do you have **any Sponge plugins** which can affect dimensions, like spawn world or multiworld plugins?

**Comment by ytyyy** [comment]
Well..I checked the config and found that the difference is "Enable if this world should be loaded on startup".
if I turned it to false the nether will become a spaceport.
but I still can't go to moon.

I think I have not install plugins like multiworld plugins,and I just found one DIM-28 in config.

However, I don't want to delete my saves. So I give up and use Minetweak to make a new recipe of rocket- so I can skip the moon and then travel to the mars.

But I wonder if there is someone who meet the same mistake I met, so if you have free time you can access to my FTP server.

ftp://wt.k.mcmiao.com/
username:q1195808754.886
password:qa5678137

It's a little dangerous so if you also give up please reply ASAP

**Comment by radfast** [comment]
Sponge dev team are normally slow to respond to dimension issues (like months).

These settings shouldn't be able to make such a difference to the Nether, I think the problem here is you have messed up your world or configs in some other way, from the earlier problems.

If I have time I will access your FTP server.  _I noted your password and edited the message to hide it now._  Not today, I have internet problems today for a stupid reason - rain and floods in my city so there is water in my telephone line :(

**Comment by MJRLegends** [comment]
Yeah i can say 100% that i dont get these issues with Galacticraft and sponge forge
