### ISSUE TITLE
Problems With Astral Sorcery

### ISSUE THREAD

**Issue by Zer0Lyfe** [micdoodle8/Galacticraft#3131]
Minecraft version: 1.12.2
Galacticraft version:
GalacticraftCore-1.12.2-4.0.1.128.jar
MicdoodleCore-1.12.2-4.0.1.128.jar
Forge version: 14.23.1.2604
Singleplayer (SSP) or Multiplayer (SMP) singleplayer
Galacticraft add-ons and other mods installed?
no
these are Jenkins builds
Please provide screenshots / crash report / log as needed.
Github Post from AS: https://github.com/HellFirePvP/AstralSorcery/issues/451
this post has a lot of infomation of the bug.

And this URL is pointing out to the AS Dev that bug has Re-appeared after the fix: https://github.com/HellFirePvP/AstralSorcery/issues/534

This was a problem with AS and Twilight Forest and Advanced Rocketry but is now fixed with those mods but not this one.

**Comment by radfast** [comment]
It's hard for me to understand what you are reporting here.

By the sounds of it, Galacticraft is working correctly and as intended.  Other planet dimensions are registered, but by default the dimensions are not loaded by Forge unless a player is present.  Galacticraft also offers config options (and a command) to keep dimensions "statically" loaded.  So you can do that if you want.

Also, Forge and vanilla Minecraft do not have a problem if a dimension is loaded but has 0 loaded chunks.  That basically makes zero tps overhead for the server, because there are no chunks to update.  So if Astral Sorcery mod behaves strangely when dimensions are loaded with 0 chunks, that's something for the AS devs to fix.
