### ISSUE TITLE
Duplicate stat id (1.12.2)

### ISSUE THREAD

**Issue by Zer0Lyfe** [micdoodle8/Galacticraft#3144]
Minecraft version: 1.12.2
Galacticraft version:4.0.1.128 and occurs in the newer versions as i was testing if it was happening in the earlier versions
Forge version: 14.23.2.2611

Single player (SSP) or Multiplayer (SMP)?
Neither
Galacticraft add-ons and other mods installed?
no just Galacticraft and dependencies
Please provide screenshots / crash report / log as needed.
https://gist.github.com/Zer0Lyfe/514cfa71e7a2fe9a47c296ef096d8962

**Comment by Zer0Lyfe** [comment]
most probably interaction with Enderman Evolution mod

**Comment by radfast** [comment]
Sounds like the reason, yes.

Please report it to **Enderman Evolution** to fix.  They are a small mod and they created this problem first in November 2017.  We've already had Evolved Endermen in Galacticraft for a long time before that.  They need to change their ```Entity``` name to something different so there is no conflict.

**Comment by Zer0Lyfe** [comment]
ok. no problem

**Comment by p455w0rd** [comment]
Evolved Enderman are from my 1.9.4 version of p455w0rd's Things. There is no repo to prove this, as I deleted and move things around several times. But here's where I made the change in the lang file for the 1.10.2 version of p455w0rd's Things (from Sept 2017). It was long before this when they were actually created. Enderman Evolution is just these mobs pulled from the 1.10.2 version ported to their own mod in 1.12.2 since I had requests to do so and have no interest in porting the entire mod. Instead of being egotistical, why not try working together on a solution? To be honest we're both at fault here. I was unaware of your mod having these Enderman, however, neither of us should use an arbitrary naming convention for our mob names. I'll definitely get this done on my side by changing the `entityName` parameter for `EntityRegistry#registerModEntity` for all of my entities to be `MODID:ENTITY_NAME`. It would be wise for you to do the same to avoid this in the future. The size of a mod or who did it first makes no difference. We're both doing it wrong. At least I can admit I suppose. Have a good one :)

**Comment by radfast** [comment]
@p455w0rd I am sorry, it appeared from your repo that your mod very recently created these entities

On our side changing the registered entity names is not straightforward as to help with localisation we aim to have all our ```.lang``` files the same across versions 1.8.9 through 1.12.2.  Forge changed the way they construct entity names, this results in code like [this](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/util/GCCoreUtil.java#L228-L256)

**Comment by p455w0rd** [comment]
at any rate, it's fixed on my end..this will no longer be an issue from this mod and hopefully none going forward..as with this, I plan to start changing all my lang keys to incorporate my modids as this is likely to happen again at some point if I don't...I was surprised because I took it for granted that the `entityName` param was essentially obsolete and that registry names would now be used since this is what has happened for pretty much everything else..very silly of me to assume

**Comment by radfast** [comment]
I think ```TileEntity.register()``` has a similar issue with its keys, Forge does not add the modID.
