### ISSUE TITLE
Inventory tab and TechGuns

### ISSUE THREAD

**Issue by roboderpy** [micdoodle8/Galacticraft#3152]
~~Galacticraft still use *very* old patches to display inventory tabs, causing massive conflicts with other mods (as reported by others), starting from 1.7.10 or even earlier there is an API in Forge to define multiple player tabs~~

Scratch that, Galacticraft seems to introduce tabs api, not forge.

![bad](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-00-49.png)

Minecraft version: 1.12.2
Galacticraft version: 132 build
Forge version: 2599 build

**Comment by radfast** [comment]
Or ... we co-wrote the tab system and provide the current API for it, and the other mods can use it if they want to.

**Comment by roboderpy** [comment]
I won't argue you all did wrote an API (because without API nothing can be done 😄 ), but in Forge it is shared and mod-free/API dependency

**Comment by radfast** [comment]
I will investigate and then decide what to do here.  I agree that inter-mod compatibility is important.

**Comment by radfast** [comment]
hmm, I don't see a tab API in forge.

Please give more specific detail of each of the following statements:

>   Galacticraft still use very old patches to display inventory tabs

why do you say "very old patches"?

>   causing massive conflicts with other mods (as reported by others)

which other mods, which other reports - please give links to the other reports

>   starting from 1.7.10 or even earlier there is an API in Forge to define multiple player tabs

please link to the API in Forge, or any discussion of it, because I cannot find it

-------

Currently I think the actual situation here is:

1.   TConstruct made the original tabs API, we contributed to it and updated it from 1.7.10 to 1.12.2, and after TConstruct abandoned it we moved it to Galacticraft's API so that people can use it

2.  The other major mods using the tabs API are CustomNPCs and MorePlayerModels, and they use our API - I chat to Noppes about this every time the API gets updated

3.  It looks like Techguns has implemented its own (bad quality) version of the tabs instead of using our API like it should, if it wants compatibility with us, CustomNPCs and MPM

Therefore you should report this to Techguns, not to us.

**Comment by roboderpy** [comment]
There isn't any API? Hmm, i thought it was. My bad. And it already was reported - https://github.com/pWn3d1337/Techguns2/issues/14
