### ISSUE TITLE
[JEI] recipes, oredicts, and other JEI issues on 1.12.2

### ISSUE THREAD

**Issue by roboderpy** [micdoodle8/Galacticraft#3153]
![yea](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-06-49.png)
Should display `Accepts Any: itemSilicon`:
![should display Accepts Any itemSilicon](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-13-40.png)

Idk how *long* issue about oredicted recipes stands (i even remember it in 1.7.10), but still, much of recipes are not being shown as oredicted

Also Oxygen Collector's, ..., Oxygen Compressor's recipes needed to be shown in JEI (suggestion), like, checking uses of Oxygen Collector will bring user to page with Oxygen Collector interface where power bar decreases and oxygen level decreases while something like `Surrounding leaf blocks` counter decreases or something

![enchanting](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-11-05.png)
Oxygen tanks and other stuff can be enchanted, ~~or you can even fill oxygen tank in Blood Chest, like repairing a regular tool~~ nope. To fix this Oxygen tank just need to store it's fill state in NBT tags.

NASA Workbench has big amount of tabs ![bad](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-10-13.png)
when all recipes should be in one tab

Minecraft version: 1.12.2
Galacticraft version: 132 build
Forge version: 2599 build

**Comment by radfast** [comment]
Thanks for the report, some of these 4 things should be easy to fix, some not so easy.

There's a lot of items in JEI which show up as enchantable, I don't know if that's only our mod.

**Comment by roboderpy** [comment]
Not just JEI, you *can* put an Oxygen tank in actual Anvil and enchant tank with Unbreaking

**Comment by roboderpy** [comment]
Also i think `compressedCopper` and other `compressedX` should be oredicted to `plateX`

**Comment by radfast** [comment]
hmmm, I'm not sure that we will change the oredict name of our own mod's items - changes like that will break compatibility for other mods which have by now implemented ```compressedCopper``` etc

**Comment by roboderpy** [comment]
Nope, instead of changing existing oredicts, you can add to existing oredict names new oredicts like you all did even with some of blocks of Galacticraft
![block with 2 oredicts](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-47-45.png)

**Comment by roboderpy** [comment]
About enchanting tanks: ![enchanted](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-52-28.png)

**Comment by roboderpy** [comment]
And JEI recipes are telling truth - i can't use oredicted silicon in recipes:
![visual bug](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_06-55-01.png)
This is clientside prediction bug (maybe?)
When i close inventory of fabricator or stay in it's inventory long enough while holding silicon in corresponding slots, silicon either dissapears and drops on ground on close, or just comes back to inventory.

**Comment by radfast** [comment]
You can use silicon in the machine, but you need to set Galacticraft correctly.  We don't know the oreDict name for the silicon set by the other mods (there is more than one name).  By default we use ```itemSilicon``` but you can change that in Galacticraft config.

**Comment by roboderpy** [comment]
???
![it is](https://i.dbot.serealia.ca/2018/02/javaw_2018-02-07_07-04-46.png)

**Comment by roboderpy** [comment]
Silicon from all other mods is oredicted as `itemSilicon` but still can not be used in fabricator

**Comment by radfast** [comment]
ok thank you that is helpful, sounds like a bug in our server handshake which sends that specific config (and a few other recipe-related configs) to the client.

**Comment by radfast** [comment]
1.  Multiplayer silicon issue **should** be fixed in build 138, but I'll need help checking it.  As you have noted, it is not a JEI issue, JEI is telling the truth!  It was a problem of clientside recipes not updating dynamically when joining a server.

2A.  Some Galacticraft items shown in JEI as enchantable in 1.11.2+  - this is still an issue

2B.  Enchantability of items with Unbreaking III in an anvil is **not** a bug - almost every item in Minecraft can be enchanted with Unbreaking spells in an anvil.

3.  NASA workbench - these different tabs **cannot** be combined, because each tab is drawn with a different background texture.  AFAIK, JEI tabs cannot use different background textures for different output items within the same tab.  (If you know of a mod which is currently doing this, please let me know ...)

4.  Oxygen Compressor - yes this needs a JEI tab, so does Electric Furnace and one or two other machines.

5.  Oxygen Collector - I don't plan to give this a JEI tab because it does not output any item, and the oxygen it produces is not a Forge fluid.

**Comment by radfast** [comment]
ok more precisely in build 138:

issue 1 is fixed in actual gameplay in all Galacticraft 4 versions - meaning, the Circuit Fabricator accepts the correct silicon items.

Issue 1 is fixed in JEI only in our Minecraft 1.11.2 version currently.  It is not working in 1.10.2 or 1.12.2 due to bugs and bad decisions in JEI.  I am looking at workarounds for these problems in our next build.

**Comment by radfast** [comment]
1.  Multiplayer silicon issue: fixed properly in next build 139, all Galacticraft versions

2.  Some Galacticraft items shown in JEI as enchantable in 1.11.2+ - fixed in 139

(Many "singleton" items such as oxygen tanks, batteries, grappling hooks, were being detected by vanilla code as enchantable.)
