### ISSUE TITLE
[1.12.2] Important Request!

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3170]
Hello, 

Any chance its possible to register planets and moons all in the pre int, because i have a new mod which works great for all other mc versions but in MC 1.12.2 because im using the GalaxyRegistry#getRegisteredPlanets() and GalaxyRegistry#getRegisteredMoons() to create items based on each one that is in them. 

But in 1.12.2 because the item register is between the pre init and init i cant do it currently as the registering on planets and moons for GC is in the init method

**Comment by MJRLegends** [comment]
I only ask this because i really dont want manually have to hard code Galacticraft planets/moons in to my items :D 

It should be possible because in ExtraPlanets i register them all in the pre init :D Also great work once again on your work with Galacticraft

**Comment by radfast** [comment]
I'm not sure that it is possible to move all of that in 1.12.2...  The registration of the planets and moons also includes registration and construction of their WorldProvider and Mob SpawnLists, and it sounds dangerous to do those things before biomes, blocks and entities have been registered.

In addition, GalacticraftCore preInit runs before all addon preInits (and before Galacticraft-Planets module preInits) so it can't be done in GalacticraftCore preInit as that would before the planets and moons are even set up.

Three alternatives:

1.  You can try moving things around in ```GalacticraftCore``` in your own development code - I'm not sure where to, given the comment I've just made - and see if it works.  Then if you've tested it super carefully, including in a **server/client** environment and with **Sponge** and with a few **other mods**, and everything still looks stable, please submit a PR.

2.  Just register the item later, the "manual" way.  The item registry can be accessed its just not approved of.  You'd have to look at Forge item registration code and duplicate the steps, I think a call to ```GameData.register_impl()``` is likely involved.  Look at https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/util/RecipeUtil.java#L58-L74

3.  Modify your code so that you have a single item to register, and everything else is done using damage values or (probably better) **ItemStack NBT data**
