### ISSUE TITLE
Gas Liquefier doesn't accept gases from pipes

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3178]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.138
Forge version: 13.20.1.2386

Single player (SSP) or Multiplayer (SMP)?
SSP

Galacticraft add-ons and other mods installed?
None

Please provide screenshots / crash report / log as needed.
![2018-02-18_14 14 44](https://user-images.githubusercontent.com/35406698/36382346-a3df6ca4-1599-11e8-84ce-76aecc730cce.png)
![2018-02-18_14 14 56](https://user-images.githubusercontent.com/35406698/36382349-a73684a0-1599-11e8-8352-3db47e37f1dc.png)
![2018-02-18_14 15 10](https://user-images.githubusercontent.com/35406698/36382355-a9580510-1599-11e8-89f3-b69aae9938b7.png)

**Comment by QuantumStatement** [comment]
It seems like Gas Liquefier only accept Methane Gas from pipes and this is [intended behavior](https://wiki.micdoodle8.com/wiki/Gas_Liquefier)

**Comment by dj3520** [comment]
Should also accept oxygen and hydrogen gas, possibly more.

**Comment by radfast** [comment]
It is intended for it to accept:

- Methane

- Oxygen

- Liquid Oxygen

- Nitrogen

- Liquid Nitrogen

I don't remember about Argon, I don't think we have that in gas form currently in Galacticraft.

The Gas Liquefier does **not** accept Hydrogen gas and it cannot liquefy it.  That's intended.  In real life, liquefying Hydrogen is a much more complicated industrial process because Liquid Hydrogen is so cold (and a few other science reasons specific to Hydrogen).  If Liquid Hydrogen is ever included in Galacticraft in future there will be a different or enhanced machine for liquefying hydrogen.

If it's not accepting one of the ones listed above through a Fluid Pipe, that's a bug which I need to investigate.

**Comment by dj3520** [comment]
_Was thinking of Nitrogen instead of Hydrogen._

**Comment by radfast** [comment]
Turns out the Gas Liquefier was accepting the oxygen gas from pipes in theory, only the amounts were so small that it was 0 every time when converted back into integer math.

Fixed from next build 139, thank you for reporting.
