### ISSUE TITLE
Mod Compatibility issue (EIO sag mill, AA crusher)

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3204]
Not all GC Ore's work with EnderIO Sag Mill or Actually Additions Crusher 

I have quarry's pick up the ore and I use Silk Touch on it so I can ore double the resources via 
EnderIO/AA/Tinkers. I'll hazard a guess, EIO has powdered ore's for some of them (iron/copper) and not others which is why they work and the others don't. I can understand sapphire, however AA's crusher will work with diamond/emerald and it does double them(iirc).

Minecraft: 1.10.2
Forge: 12.18.3.2511

Galacticraft-Planets-1.10.2-4.0.1.142.jar
GalacticraftCore-1.10.2-4.0.1.142.jar
MicdoodleCore-1.10.2-4.0.1.142.jar
EnderCore-1.10.2-0.4.1.66-beta.jar
EnderIO-1.10.2-3.1.193.jar
ActuallyAdditions-1.10.2-r105.jar

The following ore's Aren't compatible
Aluminum
Cheese
Desh
Galena (EIO "processes" but outputs nothing)
Ilmenite
Sapphire
Silicon

**Comment by radfast** [comment]
Any solution requires individual coding for each ore, for each of those machines - and that's assuming that EnderIO and AA provide an API for their machines.

**Galena** is probably because EIO can accept any lead ore (Galena is OreDicted to "oreLead") but you have no mod installed offering a **Lead Dust** item - please confirm?  I expect that if you did have a mod with Lead Dust - for example Thermal Foundation - then EIO would produce Lead Dust from Galena without us needing to do anything more.  So that sounds like a bug in EIO - it should not process an ore if it cannot find any corresponding dust.

For Aluminium Ore - as you know :) - from build 140 Galacticraft includes Aluminium Dust and its other ore by-products, and specific code to allow it to be processed by the IC2 and AE2 machines.   Now that the Aluminium Dust item exists in the game, I am happy to look at adding recipes for Aluminium Dust also to EIO and AA machines (if there's an API for them, which I don't know right now).  That shouldn't be too hard.

Depending on how easy it is to use their API, I guess we might also be able then to implement it also for some of our ores which drop non-ingots.  It would be good to know - from Wiki or in-game testing - exactly what outputs those machines yield from the following:
- Coal Ore
- Redstone Ore
- Diamond Ore (AA Crusher)
- Emerald Ore (AA Crusher)

**Ilmenite** I don't think we can do.  That ore specifically has the shard mechanic where it drops both iron and titanium shards.  Those shards can produce 2 ingots already, or 4 if you smelt the shards in an Electric Arc Furnace.  I think that's enough metal from 1 ore.  And it seems doubtful anyhow whether EIO and AA machines have any way to produce 2 primary outputs from 1 single ore.  I don't play those mods so I'm not sure.

EIO is fairly low priority for me right now, as they do not have 1.11.2 and 1.12.2 versions out yet.  So if your time is limited please look at AA first.

**Comment by TheQuadShot** [comment]
test runs done with stack of ore (64)

AA (I know some of his recipes do have chance results ie 1 gravel = 1 flint + %50 chance for 1 additional)

Diamond Ore -> Crushed Diamond (128)
Emerald Ore -> Crushed Emerald (128)
Coal Ore -> Coal (192)
Redstone Ore -> Redstone (640)
NetherQuartz Ore -> NetherQuartz (192)


EIO (using flint)

Diamond Ore -> Diamond (100) Cobble (14)
Emerald Ore -> Emerald (101) Cobble (14)
Coal Ore -> Coal (228) Coal Dust (57) Cobble (16) 
Redstone Ore -> Redstone (577) Silicone (78) Cobble (12)
NetherQuartz Ore -> NetherQuartz (154)

**Comment by radfast** [comment]
We don't have Crushed Sapphire  (and I'm not too sure what we would do with it if we did!)

Silicon Ore, Cheese Ore and Desh we can probably make behave like Coal Ore / Redstone Ore / Nether Quartz in AA.

Although Cheese Ore is actually most valuable in its pure (silk touch) form, as it is an essential ingredient in the Orion Drive.

**Comment by TheQuadShot** [comment]
The crushed gems can be smelted into the gem hence double gems. Just had a thought, do moon villagers "melt" down to sapphires? (Like Overworld villagers in a TiC Smelter) 
Yeah silk touch... There's this mod I love to play and the mod author Requires silk touched Ore's... Damn him!! (Love ya guys!) That's one reason I always go with silk touch on my quarries (since 1.7.10).  ;-) 

I ran into this problem a while back with another mod and when I was talking to the guy's at EIO they said the mod author just has to supply the recipe. I don't think it's that easy though, I think you have to register the dust as well ie dustIrion or dustLead then you "just have to add the recipe". I have looked at their config\enderio\SAGMillRecipes_Core.xml and it looks pretty straight forward. I don't understand why aluminum doesn't work since it is in the .xml file. It may be that the dust isn't getting registered in the oredict, but I'm guessing.

**Comment by radfast** [comment]
Oh!  Then we can probably enable **Aluminum Ore** in the SAG Mill very easily.  Currently we only [register](https://github.com/micdoodle8/Galacticraft/blob/MC1.10/src/main/java/micdoodle8/mods/galacticraft/core/GCItems.java#L168) the Aluminum Dust if IC2 or AE2 mods are present ... so if one of those is installed, probably Aluminum Ore already works in the SAG Mill.  I can easily extend that registration to cover EIO as well.

> Just had a thought, do moon villagers "melt" down to sapphires? (Like Overworld villagers in a TiC Smelter)

No!  Doesn't sound like a good plan for interplanetary relations!

Seriously, to do anything like this we would need to register a new liquid with TiC - same for our various other metals and things.  That's not high on my list of priorities, I'm afraid, while there are still 50+ things I plan for our own mod and 100 open issues.  If somebody who is not me wants to figure out how to do it, make a texture for the new liquid (probably quite easy by re-coloring the most similar existing liquid), and make a PR then it can happen much sooner.

**Comment by radfast** [comment]
https://github.com/micdoodle8/Galacticraft/commit/e17799dc74b9632dfc48a3bb4d069e8b75b89b1b

Please try it out once new build 145 becomes available!

**Comment by radfast** [comment]
Build 145 is out now.  I haven't tried it with these mods myself, so this may be a bit ... experimental!

AA recipes are provided by Galacticraft code.
EnderIO is going to be completely dependent on SAG Mill config.
