### ISSUE TITLE
Rocket becomes invisible if the base of it is outside the visible frustum

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3232]
Minecraft version:1.12.2
Galacticraft version:4.0.1.150

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP, SSP not open to LAN
Galacticraft add-ons and other mods installed?
Voxelmap, scenter, ecology mod, JEI
Please provide screenshots / crash report / log as needed.
![2018-03-06_19 04 46](https://user-images.githubusercontent.com/33905242/37048691-49e69a9e-2177-11e8-83ad-a839ad042610.png)

Found an interesting bug with rockets of 1-3 levels. This bug works on Mars and on the Space Station. On Mars, this bug only works on rockets of 2-3 levels. But on Space Station with 1-3 levels. And so the essence of the bug is that if, for example, a player is in a rocket of level 3 on Mars, and if he looks from the interior at an angle of approximately 45 ° or at an angle of 90 °, then the missile disappears as on the screen. I hope you understand the essence of the bug. If not, fly for example to the Space Station, install a missile of level 1, go into it, and look just up (90 °) and you'll see that the missile is gone. But when your angle is less than 45 °, the rocket will reappear.

**Comment by MJRLegends** [comment]
This is due to a vanilla mc change it happens with every entity

**Comment by Romsik788** [comment]
More please

**Comment by radfast** [comment]
Minecraft only draws entities which are inside the [frustum](https://en.wikipedia.org/wiki/Viewing_frustum)

When you look up high, vanilla Minecraft "thinks" that you can't see the rocket because you are looking "up", but the base of the rocket is "down"  (outside the frustum).

It is the same if you stand inside another player, or inside a large mob like a Ghast.

I will leave this open for today in case I can find some way of telling Minecraft "hey, the rocket is up here also" but I think we have looked at this before and it is not possible.  (Something might have changed in 1.12.2)

**Comment by EzerArch** [comment]
> I will leave this open for today in case I can find some way of telling Minecraft "hey, the rocket is up here also" but I think we have looked at this before and it is not possible. (Something might have changed in 1.12.2)

A bit of it reminds me of a bug related to big paintings: if the painting is big enough, it would stop rendering if its anchor (the painting insert point) is off the field of view (FoV) even if part of the painting is inside the FoV.

I can't find the JIRA issue; can't remember if Mojang managed to fix it either. :<

**Comment by radfast** [comment]
The FoV issue can be fixed easily, Minecraft already has a system for that (which it uses for fishes for example - I don't know why fishes need it, maybe their tails can be outside the entity's bounding box?)

Checking ours, I've discovered a **minor** issue where a rocket with fins which stick out a lot - like a Tier 2 Rocket - can sometimes not be drawn if only a corner of the fin is in the FoV.  I can fix that next build...

The problem issue which @Romsik788 is seeing happens when the base / anchor point of the entity is in a different "Y chunk" from the player's head.  Y chunk boundaries are y=32, 48, 64, 80 etc...

This can happen very  easily at a standard world height of 63 blocks - so place a Rocket Launch Pad at y=63, and you can see the rocket sometimes disappear if you look up depending on your head angle - you don't even have to be inside the rocket.  Basically as soon as you look high enough so that no blocks at y=63 are inside the FoV, the issue can start to occur.  (I'm not sure why it stops when you look straight upwards - that one is weird, but maybe its because no blocks are drawn at all?)

The problem code is deep inside vanilla Minecraft and we probably can't fix it, though I would like to.  Like I said, the same bug will affect any tall entity like a Ghast, maybe even a player if you can get the angles right.

(I tried a hack where we tell Minecraft the rocket is in both the Y chunk where its base is and also in the Y chunk above, but that made my FPS drop from 60 fps to 5 fps ... so I don't think we want to do that!)

**Comment by radfast** [comment]
hmm, wondering what would happen if we change the rocket anchor position to be higher (matching the player's eyes) so it is always in the same chunk with the player - this would need all our other code for rockets (launching and docking, etc) to be updated.  Seems worth a try.  (Tomorrow!)

**Comment by EzerArch** [comment]
> Seems worth a try. (Tomorrow!)

_And there he go for another coding adventure.._. :D

**Comment by radfast** [comment]
:D 

OK even testing that approach, there's **still** the issue with vanilla Minecraft - whatever the rocket position, there is always **some** view angle where the vanilla game engine refuses to even try to draw it.

Another problem is that if we implemented that change, then all rockets placed by players already in the game (I mean rockets on landing pads) would suddenly be positioned wrong, like the lower half of the rocket would be embedded in the pad...   not good.

I'm going to declare this one unfixable, sorry.  If you want to see it fixed, please report it as a bug to Mojang using something in the vanilla game, like a Ghast or a Horse or something like that - any tall entity.

**Comment by Romsik788** [comment]
Explain how to cause a similar bug with Ghast. I will then go to mojang with this problem.

**Comment by radfast** [comment]
Spawn Ghast.  Look up.

**Comment by Romsik788** [comment]
If I have a pirate minecraft, can I still report this bug?
