### ISSUE TITLE
Galacticraft seems to hold references to files even after the world is unloaded, preventing world deletion.

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#3244]
Minecraft version: 1.12.1
Galacticraft version: 4.0.1.153

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? [Full List](http://www.modlister.com/user/brisingraerowing) 
(Might take a few minutes to update)

Please provide screenshots / crash report / log as needed.

This pops up every delete attempt:
```text
[18:43:23] [main/WARN]: Couldn't delete file C:\MC-Tools\MultiMC\instances\Forge 1.12.2\.minecraft\saves\World 1\galacticraft\overworldMap\Overworld1536.bin
[18:43:23] [main/WARN]: Couldn't delete directory C:\MC-Tools\MultiMC\instances\Forge 1.12.2\.minecraft\saves\World 1\galacticraft\overworldMap
[18:43:23] [main/WARN]: Couldn't delete directory C:\MC-Tools\MultiMC\instances\Forge 1.12.2\.minecraft\saves\World 1\galacticraft
[18:43:23] [main/WARN]: Unsuccessful in deleting contents.
```

**Comment by radfast** [comment]
Writing to the file `Overworld1536.bin` in that folder would be one of the final things Galacticraft does during game shutdown, if this is a world which you have not played much (less than 30-40 minutes game time in the world).

Galacticraft requires probably around 200ms to do that - exact time depends on your OS and your hard drive, but it is minimum 90ms.

This normally works fine in Forge.  It's possible that MultiMC is causing this by "rushing" the game exit somehow instead of waiting until everything is finished.  Can you test for us without MultiMC?

If this is happening, it's likely also that the file will be corrupted, because the only way the file can still be open is - I think - if the save operation did not complete.

**Note: to test this, you need to use worlds which you have newly created or only played a short time - less than 30 minutes game time.  After that, this file will no longer be saved on exit because that task will already be complete.**

**Comment by BrisingrAerowing** [comment]
It works with just GC, so I think this is caused by another one of my mods (somehow). Possibly Biomes O' Plenty, as that is the world generator I usually use, though it refuses to load in my testing instance, so testing that might be a bit harder (game starts then immediately stops with no output other than some MultiMC startup stuff and an exited with code 0 message. Without BoP it loads fine).

**Comment by radfast** [comment]
If there's some kind of crash (even if unlogged) while the server stops, so that our code is not allowed to complete, that can maybe affect this.

Like I say, it's connected with giving things time to complete their saves properly, versus forced exit.

I haven't tested BoP myself in 1.12.2, I'm using Natura in my test game.  I find it interesting how both actually increase the game difficulty, by making all the vanilla biomes rarer, so if there's one specific thing you need from a vanilla biome then it's going to be hard to find.
