### ISSUE TITLE
Galacticraft's electrical system is not yet compatible with BuildCraft MJ in 1.12.2

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3246]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:4.0.1.153

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Galacticraft add-ons and other mods installed?
BuildCraft, Optifine, JEI, NEI, CodeChinkenLib, EnderStorage, MrCrayfish's Furniture, CodeChickenChunks

Galacticraft's electrical is COMPLETELY incompatible with BuildCraft's electrical system in 1.12.2. It was highly likely to be caused by the "semi-rewrite" they had with the 1.12.2 alpha. Fluid seems to be fine.

The wooden pipe no longer connects to the GC cables as well. (Not included in screenshot)

Please provide screenshots / crash report / log as needed.
![image](https://user-images.githubusercontent.com/29967594/37381182-052f8d2a-26f9-11e8-8293-82c958ff018a.png)

**Comment by radfast** [comment]
Thanks for the report.

This is likely, because Buildcraft re-wrote things to bring back MJ, I think (can you confirm?)

It shouldn't be **too** hard for us to fix, because we had full MJ compatibility in Galacticraft 1.7.10.  But I will need to study Buildcraft's latest code.  So will be a few days before this is fixed.

**Comment by radfast** [comment]
Also ... can you try creating all the Sealable buildcraft pipes?   The gold energy (Kinesis?) pipe looks OK in your screenshot, does it pass energy into Buildcraft machines OK?

-----

Generally, please can you keep that world you built in the screenshot, so that when we release an update with a fix, you can make the same screenshot showing it all working :)

**Comment by kouwei32** [comment]
It is not passing any energy to any machines. The engines don't even want to output. The sealable ones are behaving just like the normal ones. And sorry, I already destroyed the test structure, since it was in the way of my construction stuff :(  

A lot of other things were broken too. Wrenches are no longer universal, fuel is not either...

(I could build it again though...)

**Comment by kouwei32** [comment]
It has also been confirmed that BuildCraft is bringing back MJ since 1.11 (or earlier). RF and FE is no longer supported.

[https://www.reddit.com/r/feedthebeast/comments/7ezn3t/buildcraft_1122_alpha_released/](url)

**Comment by radfast** [comment]
Don't worry, don't rebuild it.

And when you say confirmed, I'd expect to see something from the mod developer ... not some random posting on reddit :p

**Comment by radfast** [comment]
Anyhow, this is good for us, because Galacticraft prides itself on offering energy compatibility and conversion with every other major mod ... so once we have fixed this, people will be able to use Galacticraft to do BC / IC2 / RF conversion.

**Comment by kouwei32** [comment]
Thanks! I’d really like to stick a few solar panels on a quarry. It just makes life so much easier. 😁

**Comment by radfast** [comment]
Full Galacticraft / Buildcraft compatibility in our next build 159, should be available for download about 10 minutes from now.
