### ISSUE TITLE
Galacticraft-Planets 1.12.2-4.0.1.151 - 155 crash on start

### ISSUE THREAD

**Issue by paduser** [micdoodle8/Galacticraft#3248]
Minecraft crashs while start but only when Galacticraft-Planets is in my mods folder. As soon I remove it MC+GC starts fine. Tested all versions from 151-155. My latest working version is 150.

Minecraft version:1.12.2-forge1.12.2-14.23.2.2627
Galacticraft version:1.12.2-4.0.1.151 - 155

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
No, only Galacticraft.

Please provide screenshots / crash report / log as needed.

My crash report:
https://paste.ubuntu.com/p/ytSk4NG5Dd/

**Comment by radfast** [comment]
Thanks for reporting.   Please can you also paste a copy of your config file `configs/Galacticraft/planets.conf` - it seems like there may be some issue connected with your specific file.

**Comment by radfast** [comment]
and **after** you've given us that file - please! - you can try just deleting that `planets.conf` config file and starting the mod without it, normally it should recreate it for itself.

But I do want to see your current file because if there's something wrong here, maybe it can affect other players too.

**Comment by paduser** [comment]
Sure, here is my planets.conf
https://paste.ubuntu.com/p/Bkdbd8KNjG/

**Comment by paduser** [comment]
regenerating planets.conf fixed the issue, Can you tell me what was wrong with my config?

**Comment by radfast** [comment]
Nothing wrong except that your config was very old (maybe from 1.6.4 or early 1.7.10 days?) - so it had a few whole sections of config which are no longer used, like the entity IDs.  Our new "config cleanup code" in Galacticraft 4 builds 151-155 tries to tidy up configs, but I forgot to code it to be able to cope with complete sections which are no longer used.

Fixed in next build 156, so nobody else should have the same problem.
