### ISSUE TITLE
Breaking Bedrock with Volcanic Pickaxe?

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3252]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.156

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- FancyBlockParticles
- ItemPhysic
- and others

Please provide screenshots / crash report / log as needed.
Is this bug?
https://www.youtube.com/watch?v=rbkSbkpBAgo

**Comment by TheQuadShot** [comment]
The vid doesn't show the bedrock blocks getting picked up in you inventory/toolbar like the cobble, or are they stacking in your inventory and just not showing(thinking that nbt is screwed up somehow).
Although I have mixed feeling about breaking bedrock, since there are mods that will let you break it, and I'm not sure if they ever fixed the exploit of mining up from the nether using a tree.

**Comment by radfast** [comment]
Thanks guys.

Although the Volcanic Pickaxe is one of our most powerful items, it was not intended for it to be able to break bedrock.  The ability for a player to **obtain** bedrock would be dangeously OP in a multiplayer PvP/raiding server, as it would allow players to build impregnable bases.

At the same time I've also added in a few other checks, so that the Volcanic Pickaxe shouldn't (I hope) cause unintended damage to Command Blocks - not too sure about that, I'm not a Command Block expert - and also should now be correctly checking for protections from other mods and server plugins, e.g. factions, WorldGuard etc.
