### ISSUE TITLE
Square around the sun

### ISSUE THREAD

**Issue by Romsik788** [micdoodle8/Galacticraft#3253]
Minecraft version:1.12.2
Galacticraft version:4.0.1.156

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP not open to LAN
Galacticraft add-ons and other mods installed?
Scenter, VoxelMap, Ecology mod, JEI.

Please provide screenshots / crash report / log as needed.

![2018-03-16_17 26 32](https://user-images.githubusercontent.com/33905242/37530706-dbb14b4a-2942-11e8-8bee-d7356d9e7256.png)
![2018-03-16_17 30 15](https://user-images.githubusercontent.com/33905242/37530711-deb18f6c-2942-11e8-91f9-1276ba987ba8.png)
![2018-03-16_17 23 18](https://user-images.githubusercontent.com/33905242/37530759-feed35ec-2942-11e8-80e2-b86e0627769b.png)

On planets, moons and a space station without an atmosphere, a square around the Sun is noticeable. on one of the pictures I marked it with an arrow. Watch very carefully

**Comment by EzerArch** [comment]
# @_@
Really, in all honesty, I need to congratulate @radfast for making Galacticraft _so nearly_ perfect that some people are now nitpicking absurdly small details. XD

I had to download the screenshot and use an image editor to find out what you mean:

![bruh](https://user-images.githubusercontent.com/6743303/37537760-4b583104-292d-11e8-9076-24d00d57924e.png)

K... the procedurally generated space background is full black (#000000) while the [orbitalsun.png](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/textures/gui/planets/orbitalsun.png) background has pixels that subtly ranges inward from #060003 to #180D13, but I presume this is necessary because the sun glows. What we can do is to paint the 1st outmost pixels #000000 and make even subtler transition to white.

**Comment by radfast** [comment]
@Romsik788  do you have time to edit that [orbitalsun.png](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/resources/assets/galacticraftcore/textures/gui/planets/orbitalsun.png) file in an image editor of your choosing (GIMP is good) to reduce this problem?

There still needs to be some glow.  Something like this - but **square** of course

<img src=https://blogs.scientificamerican.com/observations/files/2013/07/earth_and_sun.png>

**Comment by Romsik788** [comment]
@radfast I will try to make this square smoother.

**Comment by Romsik788** [comment]
![orbitalsun](https://user-images.githubusercontent.com/33905242/37554269-b424f9cc-29de-11e8-8f44-a4364d6a0cd4.png)
In 2 hours of work in Photoshop (I'm not kidding), I finally made a normal glow around the sun

**Comment by Romsik788** [comment]
@radfast you manually merge with the branch? Or should I make a pull request?

**Comment by radfast** [comment]
That's amazing work, thank you, the quality is very high!  I'm not surprised it took you 2 hours, might have taken me even longer.

I merged it manually.  This will be in build 158 all versions
