### ISSUE TITLE
Can't log in before crash.

### ISSUE THREAD

**Issue by manuwwa** [micdoodle8/Galacticraft#3257]
I' can't log in to game before my game crash while i was flying rocket. It was right before planet menu should pop up. I thing it could be something about null dim. 

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1.156

Multiplayer
other mods:
[mods](https://pastebin.com/LwiBWiuL)

log:
[log](https://paste.ee/p/6NBoi)

**Comment by SteveKunG** [comment]
> [12:06:01] [main/ERROR] [FML]: Parsing error loading recipe harvestcraft:minecraft_pumpkinseeds
> com.google.gson.JsonSyntaxException: Unknown item 'harvestcraft:harvestpumpkinitem'

This is not Galacticraft issue, It's HarvestCraft.

**Comment by radfast** [comment]
No no, @SteveKunG, that is a standard game loading logging message from harvestcraft - not a crash.   There can be many of those errors in unfinished mods.

@manuwwa  your log does not help us figure out the crash, because of this at the end:

>   MultiMC stopped watching the game log because the log length surpassed 10000 lines.


Please can you try your game **without MultiMC**  (maybe you will have to copy the whole game folder to .minecraft?)  or else change the MultiMC setting to allow a log much longer than 10000 lines, try 999999.

If you can give us the longer log, I promise that we **will** fix this crash for you (if it's Galacticraft related).  But right now, I can do nothing :/

**Comment by radfast** [comment]
@manuwwa  also please try without Extra Planets and More Planets and any other mods adding planets - maybe there is a conflict between them, can easily happen if both add the planet Pluto for example.

**Comment by MJRLegends** [comment]
ExtraPlanets and More Planets i knkw for sure dont have id conflicts 1.8+ unless they have been changed to conflict

Im pretty sure without the end of that log showing i dont think anyone can find out the problem.

I suggest removing pams harvestcraft so it stops filling the logs and retest which should create a log with the full outputting needed to see the issue

**Comment by radfast** [comment]
> ExtraPlanets and More Planets i know for sure dont have id conflicts 1.8+ unless they have been changed to conflict

@MJRLegends that's good to know :)   And your tip of removing Pam's HarvestCraft to give a cleaner log is sound :)

I think there are still occasional reports of dimension conflicts, maybe because players have
- different configs (maybe including old configs for mods from before 1.8) 
- a third or fourth add-on like GalaxySpace or AmunRa or one they are developing privately
- other mods with dimension ID conflicts

Maybe we need at the game start some kind of full dimension conflict check, with a helpful error message or - even better - simply disabling the conflicting dimensions.  I guess it's down to Galacticraft to do that, as being the "core" mod here.  But I would appreciate your help in understanding where the conflicts actually arise - as far as you know, is it a dimension **ID** conflict or a dimension **type ID** conflict?  Maybe you have configs for a setup which is known to crash?

**Comment by MJRLegends** [comment]
I believe nothing has conflicts between More Planets and Extra Planets for 1.8+,  GalaxySpace or AmunRa are currently still 1.7.10. the only other addons could be my other addons but they are small and are designed to work with More Planets and Extra Planets by default

**Comment by manuwwa** [comment]
Thank you all for such wonderfull dedication to fixing this. I've managed to collect full logs this time.
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1830675/latest.log)
[fml-client-latest.log](https://github.com/micdoodle8/Galacticraft/files/1830676/fml-client-latest.log)

I've conducted some more tests on multiple machines and multiple accounts, and here are the results:
Let's say we have account A(my) and account B and machine A(my) and machine B:
Account A + Machine A = crash
Account A + Machine B = crash
Account B + Machine B = no crash (we've tried multiple times)

Difference between account A and B, is that A has matter-overdrive (mod) android overlay. I'll try to reproduce this in some more situations : eg. changing my character back to normal steve (so overlay is gone), changing other character to android (to see if this bug will reproduce)
I think that it will be impossible for me to reproduce this behaviour on new server instance (withot more planets and extra planets). Should I try anyway?

**Comment by MJRLegends** [comment]
Your error is with matteroverdrive

**Comment by MJRLegends** [comment]
Your error is matter override 

See 
```
java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19) ~[gm.class:?]
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:137) ~[fy.class:?]
	at net.minecraft.entity.Entity.func_174823_aP(Entity.java:2810) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_145748_c_(Entity.java:2742) ~[vg.class:?]
	at matteroverdrive.client.render.RenderMatterScannerInfoHandler.renderEntityInfo(RenderMatterScannerInfoHandler.java:208) ~[RenderMatterScannerInfoHandler.class:?]
	at matteroverdrive.client.render.RenderMatterScannerInfoHandler.renderInfo(RenderMatterScannerInfoHandler.java:137) ~[RenderMatterScannerInfoHandler.class:?]
```

Personally i dont see any connection to why this would be a Galacticraft or addon issues or how it was thought it be one

**Comment by manuwwa** [comment]
Because game was crashing when i've entered space, so I thought it was galacticraft. I'll report it on correct github than.

Thanks for help

**Comment by MJRLegends** [comment]
It could still be a issue for GC, have you tried with just matter override and GC?

**Comment by MJRLegends** [comment]
From the error is seems a entity that is trying to be rendered is returning something as null which isnt allowed to be null

**Comment by manuwwa** [comment]
I'm building a pack with galacticraft+matteroverdrive right now. I'll test it and as soon as it's done, I'll post the results here.

**Comment by manuwwa** [comment]
Unfortunately, I was unable to crash the game with galacticraft+matteroverdrive only. 
I've tried both going to space and opening space map while I was on the overworld.

Here are the logs:
[fml-client-latest.log](https://github.com/micdoodle8/Galacticraft/files/1830879/fml-client-latest.log)
[latest.log](https://github.com/micdoodle8/Galacticraft/files/1830880/latest.log)

What should I try next?

**Comment by radfast** [comment]
>  matteroverdrive.client.render.RenderMatterScannerInfoHandler.renderEntityInfo(RenderMatterScannerInfoHandler.java:208) ~[RenderMatterScannerInfoHandler.class:?]

MatterOverdrive here tries to scan and give info about every entity - at minimum, the entity's name.

It's **possible** Galacticraft caused this crash, because we have one invisible entity which has no name.  This is an invisible vehicle which holds the player for as long as you are looking at the Celestial Map, so that the player does not fall or other bad stuff ...

I'll try giving that entity a name, see if that fixes the problem for you.  Please try Galacticraft build 163 when it's available (maybe today, maybe tomorrow).

(MatterOverdrive could also fix the problem by making sure their mod doesn't crash if the entity has no name.)

**Comment by radfast** [comment]
@manuwwa build 4.0.1.163 is now available to [download](https://micdoodle8.com/mods/galacticraft/downloads)

**Comment by manuwwa** [comment]
it works. Thanks a lot. 
I checked

- galaxy map by pressing m
- rocket launch on survival 
- log in log out while selecting destination planet on map
