### ISSUE TITLE
RPG Inventory Compatbility Issue

### ISSUE THREAD

**Issue by ArtixAllMighty** [micdoodle8/Galacticraft#3259]
**related issue :**
ArtixAllMighty/Rpg-Inventory-2016#10

**Minecraft  version:**  1.12.2

**Mods**
GalacticraftCore-1.12.2-4.0.1.158
Galacticraft-Planets-1.12.2-4.0.1.158
MicdoodleCore-1.12.2-4.0.1.158
rpginventory-1.12-5.3.0.0
subcommonlib-sublib-1.12.2-1.2.0.4

Galacticraft add-ons and other mods installed?
**YES**

**Please provide screenshots / crash report / log as needed.**  

If you have any Necklaces, Gloves or Cloaks worn while having Galacticraft installed... the worn models won't follow the player's movement but instead will remain static-like as seen in the image down below.
![](https://user-images.githubusercontent.com/3628535/37590935-1b33d606-2b6a-11e8-8a41-7da4b154b711.png)

**_I do not thinkit is a problem on my end. 
I use Forge's provided LayerRenders to render these items onto the player. 
Does galaccticraft mess with the player model in any way ? 
thanks for the info_**

**Comment by radfast** [comment]
Hi @ArtixAllMighty  thank you for looking in  :)

Yes we mess with the player model in a lot of ways, because we have tight control over the player limb positions and crouching as soon as the player goes to space.

Could even happen on the Overworld ... : 

![flag](https://user-images.githubusercontent.com/6842258/37594598-9725438c-2b6d-11e8-8b1b-f752b3d4e149.png)

Normally we should [pick up](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/client/render/entities/RenderPlayerGC.java#L138-L163) all the `LayerRenderers` from other mods.

I'll take a look and see why we are not picking up your 'LayerRenderers'.

Do you have a deobf version of your 1.12.2 .jar?  Or you can link me to the part of your source code which adds your 'LayerRenderers'?

In 1.7.10-1.11.2 we offered an alternative compatibility solution which is that we are 100% compatible with PlayerAPI and RenderPlayerAPI, but those weren't publicly available for 1.12.2 last time I looked - and it needs the other mods to be using those also ... this was mainly for compatibility with **SmartMoving** mod.

**Comment by ArtixAllMighty** [comment]
I do can give you the code. everything is available on my github   

 [Client Proxy  - addRenderLayers](https://github.com/ArtixAllMighty/Rpg-Inventory-2016/blob/master/src/main/java/subaraki/rpginventory/handler/proxy/ClientProxy.java#L106-L117)
here is the part where I Add the layers

  ```
		String types[] = new String[]{"default","slim"};

		for(String type : types){
			RenderPlayer renderer = ((RenderPlayer)Minecraft.getMinecraft().getRenderManager().getSkinMap().get(type));
			renderer.addLayer(new LayerRpgNecklace(renderer));
			renderer.addLayer(new LayerRpgGlove(renderer));

			LayerRpgCloak cloak = new LayerRpgCloak(renderer);
			renderer.addLayer(cloak);
```

here is the folder with all three layers available, would you want to know some details about the movement or anything else :  
[LayerRender folder](https://github.com/ArtixAllMighty/Rpg-Inventory-2016/tree/master/src/main/java/subaraki/rpginventory/render/player  )

**Comment by radfast** [comment]
thank you, the problem was on our side.  I've fixed it from next Galacticraft build 162
![rpggala](https://user-images.githubusercontent.com/6842258/37630179-ef8feb54-2bda-11e8-9f57-cf1fd6bbf2e5.png)

By the way, flags is not the only time we change the arms ... we have:
- waving goodbye when watching a rocket launch
- two arms up while parachuting
- arms by sides when standing in rocket
- two arms up when holding heavy items overhead
- arms by sides while freefalling in zero-G
- slower limb motion when jumping and bounding in low gravity
- _maybe more, I don't remember...._

All of these will now work with RPG items :)
