### ISSUE TITLE
Incompatibility with Applied Llamagistics in 1.12.2

### ISSUE THREAD

**Issue by olavjens777** [micdoodle8/Galacticraft#3265]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP.

Galacticraft add-ons and other mods installed?
Applied Llamagistics and Applied Fluidics, both the newest version, and a few others.

Please provide screenshots / crash report / log as needed.
[crash-2018-03-21_16.36.25-client.txt](https://github.com/micdoodle8/Galacticraft/files/1833982/crash-2018-03-21_16.36.25-client.txt)
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Galacticraft Core (galacticraftcore)

**Comment by radfast** [comment]
It's similar to this https://github.com/thiakil/Applied-Energistics-2/issues/91

The problem is that we are targeting AE2 compatibility, but Applied Llamagistics uses a different API.  (See other issues on Applied Llamagistics issue tracker tagged "AE2 API incompatibility".)

I'll see what we can do to fail silently here instead of crashing, but that may be all we can do on our side.

**Comment by thiakil** [comment]
> it makes no sense at all for a forked mod to be using a similar, but crucially, different, API

Did you even read that thread you linked? The api was changed *after* the fork happened. A fork is not required to play catch up.

**Comment by radfast** [comment]
@thiakil:

Other mods are going to make themselves compatible with the official 1.12.2 AE2.  Not your fork.  If you want to make an unofficial fork, it's up to you to make it API compatible with the official version for this Minecraft, whether the official version changed before **or** after your fork.

Any other behaviour is basically you setting out for **deliberate** incompatibility with other mods which is not good for the community, or for players.

I can see similar issues reported on your issues list several times.  In my experience it's best to accept issue reports with humility and grace, and do something to fix them.  If players are reporting issues, there are probably 100x as many players having the same issues, not reporting them, and just uninstalling your mod in frustration.

**Comment by thiakil** [comment]
> Other mods are going to make themselves compatible with the official 1.12.2 AE2.

Ahh, but you see that's a two way street, it is *your* choice (and also your prerogative) to do one, and not account for the differences/incompatibilities.

> Any other behaviour is basically you setting out for deliberate incompatibility with other mods

Again, same goes for you. "not my problem because someone else's code isn't compatible to my unsafe integration"

**Comment by radfast** [comment]
ty @MJRLegends 

Other mods are obviously going to look for compatibility with the _official_ mod, not the _unofficial_ fork.  Out of respect for the original mod authors if nothing else.

It's not clear how @thiakil expects this to be resolved.
- Does he think AE2 is going to change its API backwards to be in line with its state when he forked it?  It's not going to happen.
- Does he think other mods are going to choose compatibility with his fork instead of the official mod?  Again, it's not going to happen.

**Comment by MJRLegends** [comment]
I think it would be wise to either move the mod from a fork to a whole project of its own and then compatibility for your version would be needed, but that depends if your allowed to make it your own.

or maybe it would be wise to just pull request your changes to the official version and help support them in there version, i dont see an advantage of a forked ae2 for 1.12.2 when the official is now out. It was great when that wasn't around and im sure people are very thankful for your work @thiakil on the fork

**Comment by TheQuadShot** [comment]
@thiakil Not trying to sound like a jerk, but Why did you fork and change instead of making a plugin/add on?

**Comment by MJRLegends** [comment]
@TheQuadShot i believe it was forked before AE2 had no official 1.12 version

**Comment by thiakil** [comment]
> There should be no reason that you cant include the ae2 api

You seem to have no idea how things actually work. The internals are substantially changed.

What neither of you seem to realise is that a fork is a *diversion of development*, there is no reason they *have* maintain compatibility. *You* are being a lazy coder by going down the 'one or the other' mentality.

> Does he think other mods are going to choose compatibility with his fork instead of the official mod? 

are you dense? it is possible to support both, or otherwise silently fail if its not the rv5 you're looking for. Llamagistics is rv3/4 compatible.

> maybe it would be wise to just pull request your changes to the official version

yueh would likely never accept it

@TheQuadShot indeed, there was no AE2 even for 1.11 when I released to Curse. Yueh had even said that he 'could not accept even a PR in good conscience due to lack of time'. Suddenly after I released he found the time. Win-win if you ask me.

**Comment by MJRLegends** [comment]
```
You seem to have no idea how things actually work. The internals are substantially changed.

What neither of you seem to realise is that a fork is a diversion of development, there is no reason they have maintain compatibility. You are being a lazy coder by going down the 'one or the other' mentality.
```
i appreciate this yeah, i meant in my post that maybe your fork could include AE2 api as well as your own, this way you will get every mods compatibility with ae2 to work with your. I understand its not as easy as throw it in the folder and call it added, but this will benefit your mod very much using hooks existing already in mods to advance your compatibility with other mods. Many modders like @radfast will not see much advantage of supporting a fork when new mod packs dev will just go for the official fork. Existing packs will have to stay with your mod for sure so maybe change could be to help them players feel like they are not at a disadvantage over the official fork.

Your custom changes might be for the better over official fork for sure. You could ask for permission to go solo on your mod and take it out a fork to your own mod?

**Comment by TheQuadShot** [comment]
I must be missing something here, but in the case of a Possible abandonment of a mod, isn't it customary to notify the mod author/team for access/permission to pick up the project, then if there is no reply, you post it on the mod's page/forum to publicly request said access and wait for 60 days. Then create the fork and post that you have taken over the project due to abandonment. I'm not really aware of many Minecraft mods that this happens to. However on other games that I play and test mods on do have it occur often, and include literally hundreds of ports from previous versions and releases. In most cases of an abandoned mod whoever picks it up continues to support the original api, and IF they feel they need to make changes then they create a "plugin" the requires  the "original" mod. Just my 2 caps worth...

**Comment by thiakil** [comment]
> your fork could include AE2 api as well as your own

technically it does, just an older version. It's not really possible for the api versions to coexist in the same (implementing) codebase.

> Many modders ... will not see much advantage of supporting a fork

They don't even have to, they can just not make the *assumption* that modid x is present, so class y must be. That breaks even with just mainline ae, as they've changed the api on whim.

Modders could also check the mod name from the modloader and bail if it's llamagistics.

But anyway, my point is: if your code is crashing, its on you to fix it.

> Your custom changes might be for the better over official fork for sure. You could ask for permission to go solo on your mod and take it out a fork to your own mod?

Not sure what you mean by that, its already a solo mod and the mod licence lets me do many things with it.

> but if its just backend code changes no feature changes then whats the advantage over the official fork

there were some minor improvements or added features, but nothing groundbreaking

> isn't it customary to 

I've never heard of that happening tbh, but there were length discussions on an issue on the AE tracker.

> In most cases of an abandoned mod whoever picks it up continues to support the original api

That is exactly what has happened. The mainline changed after the fork happened.

**Comment by MJRLegends** [comment]
```
They don't even have to, they can just not make the assumption that modid x is present, so class y must be. That breaks even with just mainline ae, as they've changed the api on whim.

Modders could also check the mod name from the modloader and bail if it's llamagistics.

But anyway, my point is: if your code is crashing, its on you to fix it.
```

totally agree on this one too, im not a official GC dev. im a addon developer for GC, only micdoodle and @radfast are so im sure they will do this for sure

**Comment by radfast** [comment]
To quote one of my heroes "This bickering is pointless".

I have attempted to support @thiakil's fork in parallel with the official version in next GC build 164, not too hard because thiakil's version is unchanged from our 1.11.2 code.  Needs a bit of reflection to detect which API is which, which is a pain but luckily easy enough for us.  @thiakil reallly needs to find a proper solution so that other mods don't have this issue.  Sitting on his tower and crying because AE2 now changed their API in 1.12.2 is not a solution.

**Comment by radfast** [comment]
>  they can just not make the assumption that modid x is present, so class y must be. 

This is the whole point of an API.  We incorporate the API as a dependency and if the mod whose API it is is present on an `isLoaded` check, we assume we are entitled to use the API.  That is the natural way of coding for compatibility and how everybody does it.

The real problem with Applied Llamagistics is it's claiming the modid of AE2, when it is not true to say that it is AE2, now that there is an official AE2 for 1.12.2.  Applied Llamagistics should either switch modid, or bite the bullet and use the same AE2 API.

**Comment by radfast** [comment]
Build 4.0.1.164 now available.
