### ISSUE TITLE
IC2 Drills don't mine blocks on Space Station

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3266]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
IndustrialCraft 2 version 2.7.86

Sometimes blocks on Space Station don't drop if you mine them with IC2 mining drills. After station or world reload "mined" blocks return on their place as if you don't mine them at all

Maybe similar to #2854

**Comment by radfast** [comment]
>    Sometimes  ....

More info please.  What do I do to see this happening?

e.g.
- play the game for 1 hour then it maybe happens?
- always happens after 5 minutes in space?
- depends on a player death or inter-dimension teleport?   (so, log out, log in on the same dimension, then there is no more problem)
- only happens when blocks/tile from X other mod is nearby?
- only happens after mining X block?

The game is logical, there **must** be a reason or trigger for this.

**Comment by QuantumStatement** [comment]
>What do I do to see this happening?

You're need to just arrive on Space Station and start to mine its blocks with any IC2 drill

**Comment by radfast** [comment]
This is fixed in next build 165.

**Comment by QuantumStatement** [comment]
It's fixed :)
