### ISSUE TITLE
BuildCraft Combustion Engine does not accept Galacticraft fuel

### ISSUE THREAD

**Issue by kouwei32** [micdoodle8/Galacticraft#3280]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.163

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP on localhost Forge server.

Galacticraft add-ons and other mods installed?
BuildCraft,Optifine,MrCrayfishFurniture,CodeChickenCore,EnderStorage,ChickenChunks,NEI,JEI

Please provide screenshots / crash report / log as needed.

BuildCraft Combustion Engine does not accept Galacticraft fuel when connected to fluid pipe. Bucket does not work either.

![2018-03-25_11 30 22](https://user-images.githubusercontent.com/29967594/37878588-31585a1e-3020-11e8-8a32-bcbe5f1d8504.png)

**Comment by QuantumStatement** [comment]
Buildcraft developers [changed](http://imgur.com/a/AXUOX) the fuel system

**Comment by TheQuadShot** [comment]
Can Bc fuel work in a Gc rocket?

**Comment by kouwei32** [comment]
@TheQuadShot I havn't got time to test it right now, might do it tomorrow.

**Comment by radfast** [comment]
Fixed in next build 172.

* Fuel Loader will accept only normal Fuel
* Refinery will accept Crude Oil, Heavy Oil and Distilled Oil
* Galacticraft Fuel can be burned in Combustion Engine.  Its burn time is between BC Fuel and BC Mixed Light Fuels (9000 ticks).  Its energy per tick is 83% of the BC Fuel amount.  In combination this makes our Fuel around 75% of the efficiency of BC's own Fuel, in engines.  I think this is fair - it's easier to create GC Fuel, our refining system is simple and produces no residue.  A full Buildcraft refining system produces a lot more 

Our Refinery should certainly accept BC Distilled Oil - that is the BC Fluid that is intended to be refined into Fuel.  (It's the only BC oil which produces no residue in engines - because distilling Crude Oil -> Distilled Oil takes out the residue.)

In BC, 1000mB of Crude Oil produces 500mB Fuel, 250mB Dense Fuel and 2000mB Gaseous Fuel for a total Combustion Engine energy of 90000 MJ if you use all of them.  (This is not counting the MJ cost of transporting or distilling the oil to make these products.)

In Galacticraft, 1000mB of Crude Oil produces 1000mB GC Fuel, for a total Combustion Engine energy of 45000 MJ.  (Again, not counting the energy cost of running the Refinery.)
