### ISSUE TITLE
Rocket despawns right before exiting the atmosphere.

### ISSUE THREAD

**Issue by Maturein** [micdoodle8/Galacticraft#3285]
Minecraft version: 1.6.4
Galacticraft version: 2.0.13

SMP

Galacticraft add-ons and other mods installed? Galacticraft Mars, using the Attack of the B-Team modpack

Please provide screenshots / crash report / log as needed. 
Video recording of the event: https://youtu.be/x14wOfm3gvI

**Comment by MJRLegends** [comment]
Sorry but im pretty sure 1.6.4 mc is unsupported and very very old

**Comment by radfast** [comment]
@Maturein you can try updating the Galacticraft version inside that modpack to version 1.6.4 - 2.0.14.1098.
That's the latest, and more recent than 2.0.13 which you are using.

To update, you would need to [download](https://micdoodle8.com/mods/galacticraft/downloads) the three files from our site - look for the 1.6.4 versions.  Then move them to the correct modpack folder, probably that's a folder inside your `.technic` folder if you are using Technic Launcher.  Also tell the Technic Launcher not to auto-update Attack of The B Team, otherwise it will just overwrite 2.0.14.1098 with the older 2.0.13 version.

I don't guarantee that 2.0.14.1098 will fix your issue but it's worth a try.

This is a shame, because I **like** the Attack of the B Team modpack, but - as is typical - the modpack maker hasn't kept our mod updated in the pack, so basically you are going to get some bugs.  (I don't know what the bugs in 2.0.13 are, but everything that was fixed in 2.0.14 I guess...)
