### ISSUE TITLE
Rocket/Moon Buggy Base Bugs

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#3292]
Minecraft version: 1.12.2
Galacticraft version: 166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
GaacticraftPlanets

Please provide screenshots / crash report / log as needed.
1: So this is basically #3003 but for rocket bases...
![2018-03-27_21 36 54](https://user-images.githubusercontent.com/28928887/38009087-34cc51a8-3207-11e8-9722-80475e9660fb.png)
I will try to make a PR for this :)
EDIT: More ways to do this now:
![2018-03-28_08 07 41](https://user-images.githubusercontent.com/28928887/38038126-2d9733be-325f-11e8-9872-fc337babd465.png)
EDIT2:
![2018-03-28_08 28 16](https://user-images.githubusercontent.com/28928887/38039453-28ccdb38-3262-11e8-8944-b16217831ec5.png)

If you break the connecting piece in the diagonal one, one base will stay with 1 piece missing.

2: You can make floating bases by placing on the side of blocks.
![2018-03-28_08 32 46](https://user-images.githubusercontent.com/28928887/38039710-b212de38-3262-11e8-9812-df52e4a5cbb6.png)

3: You can make a base on top of a *FULL* base
![2018-03-28_08 34 17](https://user-images.githubusercontent.com/28928887/38039792-e1ddcc5e-3262-11e8-8385-2dfda01de3b9.png)

> Edit: After restart the world the platform became 3x3, as it should be.

Ok well then,
4: Dupe glitch with 1, infinite pads when reloading the world.

5:
![2018-03-28_10 40 13](https://user-images.githubusercontent.com/28928887/38046392-7168ca3e-3274-11e8-9ade-bcbe30b149c1.png)
infinite pads (+3 every reload)

**Comment by Romsik788** [comment]
LOL
![2018-03-28_18 34 16](https://user-images.githubusercontent.com/33905242/38039999-d7f5cc36-32ae-11e8-8137-e92378cd6de3.png)

**Comment by marcus8448** [comment]
>Edit: After restart the world the platform became 3x3, as it should be.
LOL you just made issue 4

**Comment by marcus8448** [comment]
LOL EVEN BETTER:
![2018-03-28_10 37 54](https://user-images.githubusercontent.com/28928887/38046305-32dc6ce4-3274-11e8-8f20-76060d54bf92.png)
Don't worry @radfast this was made with commands :) Sorry about the large amount of issues

**Comment by Romsik788** [comment]
I did not expect that galacticraft has many bugs(not only with platforms)😭

**Comment by MJRLegends** [comment]
Tbh all these issues only come down to actual 2 causes

**Comment by radfast** [comment]
Thank you for testing this and reporting.

Issues 1, 4 and 5 are fixed in next build 167.  All have the same underlying cause like MJRLegends said, but yes we definitely want to deal with any duping.

Issue 2 is intended behaviour - nothing wrong with a floating (cantilevered?) Launch Pad, you might need to build like that on a Space Station or similar.  And you will see the smoke and flame effects better if you build like that with a hollow underneath it.  Anyhow, **any** Launch Pad could be built like this, by building the pad on top of solid blocks then breaking the blocks below...

Issue 3 is "not a bug but a feature" - Galacticraft has always been this way, and it does no harm.  Of course the launch pad below cannot sensibly be used, but any obstructed Launch Pad has the same problem.
