### ISSUE TITLE
[1.12.2] Difference between map & display screen [minor]

### ISSUE THREAD

**Issue by marcus8448** [micdoodle8/Galacticraft#3294]
Minecraft version: 1.12.2
Galacticraft version: 166

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP
Galacticraft add-ons and other mods installed?
Planets

Please provide screenshots / crash report / log as needed.
![2018-03-28_08 46 17](https://user-images.githubusercontent.com/28928887/38040742-040a035e-3265-11e8-8d68-a847cb84d9eb.png)

Compare your map to a display screens map :)
Note: Map in the picture has the scale of:
1/4
Level 2/4

**Comment by radfast** [comment]
The maps look the same in terms of accuracy.

Our map is visually different, that's intended.  Our map gives you biome information if you understand the colours.  Our mapping also covers the whole world (up to ~12000 blocks from spawn) although you are not currently seeing this in game.  (In your client `.minecraft/assets` folder there is a .jpg file where you can preview the whole world map.)

**Comment by EzerArch** [comment]
If it helps: the **_only_** thing that bothers me is that the sea level seems to be 1-3 blocks higher. There are some flat areas by the sea or river are rendered as water.

**Comment by radfast** [comment]
It's difficult / impossible for our maps to be more accurate than they are - the whole point of them is that they map **without causing Worldgen to happen**.

The map seen on the Display Screen is really only a placeholder so that I can check things are working.  It's still intended in future for this to be a much more zoomed out map (where single block differences by sea or river will not matter) and also a basis for the view of the Overworld seen from orbit....
