### ISSUE TITLE
Astro Miner doesn't work at the distance more than ~196m

### ISSUE THREAD

**Issue by OverSavior** [micdoodle8/Galacticraft#3307]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.156

Multiplayer (SMP)

No other mods installed

At the distance of more than Xm (not sure, around 196 I belive), miner just stops and does nothing until distance become less than Xm. Then miner continues to dig and move.
That's all I can say.

**Comment by radfast** [comment]
Is it a **Sponge** server?

**Comment by OverSavior** [comment]
Negative

**Comment by radfast** [comment]
Thanks, we'll take a look and try to get this fixed.  Intended behaviour is for it to keep mining while its player is online, distance doesn't matter.

**Comment by kouwei32** [comment]
Hmm, I'm not seeing this behaviour on my worlds, both SSP and SMP. All of my astro miners are working except they do something annoying: #3291

**Comment by OverSavior** [comment]
I found that for some reason render distance is limited on this server, no matter what distance I set personally. So when Astro Miner leaves this field, it stops working.

I'd suggest to make Astro Miner render a couple of chunks aroung it by itself. Like how world anchor works.

**Comment by radfast** [comment]
Thank you for your suggestion @OverSavior.  The Astro Miner is already coded to do something like that, and as @kouwei32 said it seems to be working for some people.

**Comment by KethTheMeifwa** [comment]
I noticed you said 
> Is it a Sponge server?
is there a problem with gc and sponge?

**Comment by TheQuadShot** [comment]
@KethTheMeifwa It's more like Sponge/forge has a problem with the way they handle dimensions and permissions since it's a "new" code base that allows them to run Forge Mods.  (iirc they used to be bitbuket compatible) it also lets the dev team setup repo (re-produce) the error and ensure that "we" handle it correctly and/or provide help to the Sponge/forge team. So the short answer is: If your on a Sponge/forge Server Please provide as much information as you can and logs if at all possible to help nail down this issue. Thanks!! ps some of the known issues are covered here on the [wiki](https://wiki.micdoodle8.com/wiki/Sponge)

**Comment by KethTheMeifwa** [comment]
Thanks TheQuadShot, it may be a bit before I can get you logs, but I know the owner pretty well so it shouldn't be a problem. Also for now, I figured out that using the custom npcs mod, you can create chunk loaders, which seem to allow the astro miner to work in a 3 chunk radius around that npc

**Comment by radfast** [comment]
> is there a problem with gc and sponge?

There are two known problems with Sponge, #3206 - which mainly affects servers running Extra Planets, and it also seems to depend on the Sponge dimension configs in a way which is not currently well understood (so the problem disappears with a fresh set of configs) - and #2864 which is a very minor problem, simply an error seen in logs when servers shut down.

Because both of those issues occur only with Sponge, we - like most other mods - take the view they are Sponge bugs, not our bugs.  **But** we are willing to work with Sponge devs to try to resolve these types of bugs, because it's very difficult for the Sponge devs to fix otherwise.  I personally have contributed a couple of bugfixes to Sponge in the past.  It's just a question of finding time, because these issues are hard to fix, and I prefer to spend my time on Galacticraft.  Both we and Sponge are open source, and so of course any other coder who can find a fix is welcome to post it... 

There is also an issue with Astro Miners and Sponge in 1.12.2 versions only.  The Astro Miner seems to "go slow" but not stop completely, if the player moves even 32 blocks away from the miner.  There's a good chance this is the same issue as is being reported in this thread, or linked.

------

The Astro Miner code has a built-in chunk loader which is intended to keep it working however far from its player it is - as long as its player is online.  (It stops when the player is offline, otherwise it would be too OP!)  AFAIK this is working correctly in the 1.10.2 and 1.11.2 versions, even with Sponge (actually the code has special adaptations to make sure it works with Sponge), any problems are in 1.12.2 only.

Which versions of GC and Sponge is **Emraldia** running?  This version info is even more important than logs...

**Comment by KethTheMeifwa** [comment]
@radfast galacticraft 4.0.1.169 and sponge 2586-7.1.0-BETA-2862 also they run slow like said

**Comment by KethTheMeifwa** [comment]
oooh that's funny we aren't running either of the problematic issues you mentioned. We used to run extra planets, but after a server reset (due to corrupted files) it kept crashing the server. since I see we are running an old sponge version, what do you recommend we upgrade to?

**Comment by TheQuadShot** [comment]
I'd run the 3039 build personally. 
https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2
Recommended(stable): 1.12.2-2611-7.1.0-BETA-3002

ß(stable): 1.12.2-2655-7.1.0-BETA-3039

**Comment by CojoTheApacheHelicopter** [comment]
Hello, im Cojo_Nut, the owner of Emreldia, if you need the server logs, let me know where to send them, and I will gladly send them. I do have an issue with custom NPC's that sort of spams the logs every couple of minutes or so, but besides that, they should be of some use. So tell me where to send them, and I can get them to you.

**Comment by radfast** [comment]
@CojoTheApacheHelicopter   please can you let me know exact Sponge and Galacticraft versions.

I'll try to reproduce the issue myself in the same versions, if I can't then I will ask you for the logs.

**Comment by CojoTheApacheHelicopter** [comment]
We have the .169 version of GC, and the sponge version of 1.12.2-2611-7.1.0-BETA-3002.jar. My guess is that they are both out dated, and I need to update them.

**Comment by CojoTheApacheHelicopter** [comment]
Add "spongeforge-" to the begining of the sponge file name, and thats the full file name

**Comment by radfast** [comment]
Thanks, I'll test with those.  Might be a few days or longer before I find anything close to a solution for this.

Nothing related to this has changed since the .169 version of Galacticraft, you're OK to keep using that one if you want for now.  You should update sometimes though - obviously we don't expect people to update every time we make a new release, but each release does fix and improve things.  This [https://wiki.micdoodle8.com/wiki/Whats_New changelog] may help you.
