### ISSUE TITLE
Crash when switching server on a BungeeCord / Sponge network

### ISSUE THREAD

**Issue by Fungie2134** [micdoodle8/Galacticraft#3317]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.168

Multiplayer (SMP)

1 addon, tested with GC Core only, same crash.
The complete mod list is visible here : 
https://pastebin.com/p3KwPPj2 (crash report)

Sorry for this very quick post, I don't have much time now. I wanted to report it.

This bug totally prevents the use of GC on modded Bungee because it crashes 1/2 times. FoamFix helps.

**Comment by radfast** [comment]
Why are you reporting this to us?  It does not appear to be a Galacticraft crash.  See [notes for contributors](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) (given to you when you created this new issue), heading *Are you sure it's a Galacticraft issue?***.

Please carefully describe all tests done.

**Comment by radfast** [comment]
>  If you want I can give you the GC only crash report.

Yes, of course we need to see that.

As already posted, I do not think the error has anything to do with our `GCEntityClientPlayerMP` class.  Please **read** the links I already posted.

**Comment by phit** [comment]
yes, this is a bungeecord issue

https://github.com/SpigotMC/BungeeCord/issues/2350
https://github.com/MinecraftForge/MinecraftForge/issues/4764
https://github.com/SpongePowered/SpongeForge/issues/1978

**Comment by radfast** [comment]
hey @phit thank you for looking in and thank you for that confirmation :)    There's another unrelated Sponge issue which I've posted on today, as you've probably seen.

-----

me:  The crash appears to be linked with parrot sounds for a parrot mounted on the player's shoulder.
@Fungie1234:  You did not understand the issue.

Lol.

**Comment by radfast** [comment]
@Fungie2134  you can maybe help to get this issue actually resolved if you can figure out the **minimum set of mods to reproduce the issue** and then ask to re-open SpigotMC/BungeeCord#2350 with that info.

You said: "If you want I can give you the GC only crash report."

As I'm 100% certain that it's **not** Galacticraft causing this, this means that you must also be able to reproduce the issue in **vanilla + Forge only** (no mods).

Please try to do that.  If you can show the BungeeCord devs a crash report with no mods, then they will - l'm confident - re-open their issue and try to find a solution.  You might have to try a few times, because as you and other people have said, the crash doesn't happen always, only sometimes.

**Comment by Fungie2134** [comment]
@radfast 
Sorry for the delay.
Sorry for reporting that so fast, GC happens to make the crash appears more often... It is surely a BungeeCord / SpongePls / Sponge / Forge issue that needs to be fixed, as it happens with 0 mods on the forge server / client, sometimes ( 1/100 tries ) without Sponge, and almost never without SpongePls.
Why Forge ? It never happens when using a Spigot server.

Mods that modify the player class or inventory data like Baubles or Galacticraft seems to be on of the major problem with this issue.
I wrote a very simple Bungee plugin that /send my player every 10s, to get a crash without SpongePls if possible.

So now I am going to try to get a 0 mods crash, with and without SpongePls, to be sure about which one causes the issue.

I hope this issue will get fixed, and sorry for accusing GC. Thanks for your support !
Last thing, it seems to be an "pretty old" issue, present since the first Forge version.
The issue generally happen on slow computers like an old Core 2. Also, increasing the timeout in the back-end server config does reduct the percent of crashes.
This surely has something to do with some client latency, for example when the 1st server is normal spigot, and the back-end one is modded, as the client take more times to connect...

And @phit, it is surely not a Sponge issue as it happens without Sponge.
So only BungeeCord / SpongePls can be the cause.

(I hope this message is 100% understandable, as my main language is not English)

**Comment by Fungie2134** [comment]
Reported it to BungeeCord. I will report it to Forge if necessary.
https://github.com/SpigotMC/BungeeCord/issues/2413

**Comment by radfast** [comment]
See https://github.com/SpongePowered/SpongeForge/issues/1978#issuecomment-361280844 for the explanation of @dualspiral for the real cause for this.  Later in the same thread, he explains why  the more mods you have, the more common the issue is.  People need to pay attention to his explanations, he's a smart guy and he understands BungeeCord very well.

**Comment by Fungie2134** [comment]
This confirms what I tough the cause could be... I'm going to report this to forge, since they should be the cause, but what's strange with this bug is that it has never happened on older version, ex : 1.10.2 / 1.11.2, even if it theoretically could... The only way to "fix" the issue is to add mods like FoamFix that help reducing the mappings time.
Thanks for this explanation !
