### ISSUE TITLE
Refinery and fuel loader accept BC fluid what shouldn't

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3328]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.171

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- **Buildcraft**
- and others

Please provide screenshots / crash report / log as needed.

- Refinery
![2018-04-06_20 03 10](https://user-images.githubusercontent.com/36822613/38453233-79419d04-3a52-11e8-9cd7-120be35d09c7.png)
1. Oil
2. Heavy Oil
3. Dense Oil
4. Distilled Oil
5. Residue
- Fuel Loader
![2018-04-06_20 04 42](https://user-images.githubusercontent.com/36822613/38453240-93e33fc8-3a52-11e8-808e-a94bb84d14dd.png)
1. Dense Fuel
2. Mixed Heavy Fuels
3. Fuel
4. Mixed Light Fuels
5. Gaseous Fuel

GC Oil has been replaced by BC Oil but Fuel Not

**Comment by QuantumStatement** [comment]
> GC Oil has been replaced by BC Oil but Fuel Not

BC Fuel (named as ``fuel_light``) an Galacticraft Fuel (named as ``fuel``) are different liquids and shouldn't replace each other.

**Comment by radfast** [comment]
Thanks, included in next build 172.

We now will not accept any BC Fuel except the regular "Fuel" (also known as light fuel).

Our Refinery will now accept only Crude Oil, Heavy Oil and Distilled Oil.  I think it's OK to accept all three, because the Buildcraft refining system produces mostly Fuel when it refines Heavy Oil and Distilled Oil.

**Comment by FrostQ** [comment]
Refinery still accept _Dense Oil_ and _Residue_

**Comment by radfast** [comment]
oops.  fixed in 173
