### ISSUE TITLE
Snow Golem on Venus

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3331]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.171

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
Yes

Please provide screenshots / crash report / log as needed.

I think, snow golem should melt in this dimension because it is too hot. (Like on desert or other hot biomes)
![2018-04-07_16 40 39](https://user-images.githubusercontent.com/36822613/38456221-7940c598-3a82-11e8-94f2-0b55f568cb5e.png)

**Comment by TheQuadShot** [comment]
iirc they (snow golems) and snow "melt" based on light level, not temperature

**Comment by radfast** [comment]
Thanks, nice feature, easy to implement.

Do **not** ask for different water or ice behaviour on Venus.  One of our long term goals is to have all liquids behave differently in space dimensions - for example globular liquids in zero gravity, instant sublimation on Moon, rapid freezing on cold planets.

On Venus water on the surface probably would not boil (not sure, haven't researched) because the pressure is super high.  But I think it should rapidly convert to sulfuric acid ...

All these things are complex to implement and we have other projects ahead of them.
