### ISSUE TITLE
[Optifine] Rain on Venus missing particle effects with Optifine

### ISSUE THREAD

**Issue by FrostQ** [micdoodle8/Galacticraft#3333]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.173

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Both

Galacticraft add-ons and other mods installed?
- **Optifine**
- and others

Please provide screenshots / crash report / log as needed.

If it is Intended Behavior:
- rain sometimes not rendering correctly (not reach ground)
![2018-04-08_22 21 12](https://user-images.githubusercontent.com/36822613/38472120-4ecb6d64-3b7b-11e8-86bc-656585172972.png)
- if optifine is installed, yellow particles from ground do not appear
- Without optifine
![2018-04-08_22 13 36](https://user-images.githubusercontent.com/36822613/38472145-9ecd9ea4-3b7b-11e8-925d-e35eedd47103.png)
![2018-04-08_22 13 47](https://user-images.githubusercontent.com/36822613/38472146-9eeedf88-3b7b-11e8-9d3e-d2812af181f9.png)

- With optifine
![2018-04-08_22 10 28](https://user-images.githubusercontent.com/36822613/38472147-a6c18896-3b7b-11e8-80a3-680ad1cec8f6.png)
![2018-04-08_22 10 38](https://user-images.githubusercontent.com/36822613/38472148-a75478b8-3b7b-11e8-973c-84181012be7d.png)

**Comment by radfast** [comment]
1.  Not reaching the ground is [intended behaviour](https://blogearth.wordpress.com/2008/02/23/venus-the-planet-where-it-rains-acid/).  OK for strict accuracy we should have rain high in the atmosphere, not at ground level.  But we thought it more fun to have it close to the ground, with a "sizzle" sound.

If you observe carefully, you might notice the rain height varies a bit, sometimes it is down to the player's eye level, sometimes it is higher.

2.  Thanks for reporting the Optifine issue.  Optifine is a big pain for us - mainly because they refuse to release source code and it's very hard to figure out their specific changes.

**Comment by kouwei32** [comment]
Perhaps @FrostQ 's Optifine settings are lowering/disabling particles.

**Comment by radfast** [comment]
It's most likely connected with MicdoodleCore, we had to add Java bytecode to vanilla to be able to change the rain particles.  Probably there will be a 6/7 patch warning reported in the startup log, when Optifine is present.

**Comment by FrostQ** [comment]
> Perhaps @FrostQ 's Optifine settings are lowering/disabling particles.

I didn't decrease particles
![2018-04-09_22 35 48](https://user-images.githubusercontent.com/36822613/38521614-7a25d8e8-3c46-11e8-9a0d-f273db43a5b8.png)

**Comment by radfast** [comment]
Thanks, fixed from build 175.
