### ISSUE TITLE
(minor-trivial) Inconsistent behavior with Arc Lamp and Beam Reflector

### ISSUE THREAD

**Issue by TheQuadShot** [micdoodle8/Galacticraft#3335]
Minecraft 1.10.2
Forge 12.18.3.2511
Waila-1.7.0-B3_1.9.4
MicdoodleCore-1.10.2-4.0.1.173.jar
Galacticraft-Planets-1.10.2-4.0.1.173
GalacticraftCore-1.10.2-4.0.1.173

Arch Lamp will place "light" away from player, Energy Beam Reflector will place facing player

**Comment by radfast** [comment]
See also #3256, I think this is already covered there.

**Comment by TheQuadShot** [comment]
Sorry, I thought the other was decided.

**Comment by radfast** [comment]
No, not decided :)  and I take it that you are in the "toward" the player camp ...

I think probably the real answer is it depends on the situation - if the player is placing Arc Lamps to defend against hostile mobs then it's going to be away from the player, but if the player is placing Arc Lamps actually to light his base then he wants them facing toward the player.

I guess we should go for "towards" the player as being the most common use.

**Comment by EzerArch** [comment]
> There's a decision to make whether the light should light "away" from the player

The reason I wanted "away" was because Arc Lamp implies a "flashlight" logic: You don't point a flashlight towards you but away in front of you. And since it is also used as a defense weapon, likewise you don't point, say, a laser or light canon against you but towards the enemy. Plus, what I said in [that post](https://github.com/micdoodle8/Galacticraft/issues/3256#issuecomment-374099608).
