### ISSUE TITLE
Runaway World Gen

### ISSUE THREAD

**Issue by Mattabase** [micdoodle8/Galacticraft#3340]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 
GalacticraftCore-1.12.2-4.0.1.172 
Galacticraft-Planets-1.12.2-4.0.1.172
GalacticraftTweaker-1.12.2-1.0.1

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?

Singleplayer

Galacticraft add-ons and other mods installed?
ExtraPlanets-1.12.2-0.3.2
More-Planets-1.12.2-2.0.14-GC156

Please provide screenshots / crash report / log as needed.

Starting on line 56558 the log beings reporting this issue. 
https://goo.gl/XL5Gws

""[17:23:47] [Server thread/WARN] [FML]: Galacticraft Core loaded a new chunk [-31, -39] in dimension 0 (overworld) while populating chunk [-31, -34], causing cascading worldgen lag.

[17:23:47] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.""

Another log as well
https://goo.gl/AfH4JZ

**Comment by marcus8448** [comment]
I don't think this is Galacticraft... It seems like you are in debug mode or something like that....

**Comment by TheQuadShot** [comment]
@Mattabase Are you sure about the line numbers? both logs end long before line 10000 and I didn't see any errors in what is posted.

**Comment by Mattabase** [comment]
Yeah, I should have explained this in the initial report. The log is truncated by github, need to click the message at the top of the log. 
https://goo.gl/uNdnKX

Then you will see the line number I am referring to.

**Comment by TheQuadShot** [comment]
@Mattabase That's a .png file
Try pastebin I don't remember the file size limit on the free accounts though, it's pretty big iirc, else trim it down to just the head (about 30 lines) then cut from there to about 30 lines before the error starts showing.

**Comment by Mattabase** [comment]
@TheQuadShot Yes, that is a PNG file. That was picture showing the button I was suggesting you push to see the entire log, and where you could find it at the top of this URL (https://goo.gl/XL5Gws) which I linked in the first post. My apologies if that was unclear, here is a video showing you what I intended to show you with the png. https://goo.gl/Xd1BGj

However, to be read the file I would suggest downloading the file and opening in a local file editor such as sublime. Here is a picture of the lines I am refereeing to. https://goo.gl/1Bd5Be

And @marcus8448 The error is instructing me to report the issue to Galacticraft , it may in fact not be an issue with Galaticraft just following instructions. =)

**Comment by SteveKunG** [comment]
> [17:23:47] [Server thread/WARN] [FML]: Galacticraft Core loaded a new chunk [-31, -39] in dimension 0 (overworld) while populating chunk [-31, -34], causing cascading worldgen lag.
> [17:23:47] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

This is Forge cascading world gen debug log I believe.

**Comment by TheQuadShot** [comment]
@Mattabase Sorry didn't catch what you meant.  
I'm not sure it's just forge, if it were wouldn't do it for every mod that has worldgen? It's only reporting 3 mods, and iirc GC had an issue with this though it may have regressed (I know it's hard to believe, cause that never happens!).

**Comment by Mattabase** [comment]
Yeah no worries @TheQuadShot =)

That is why I tried to speak more clearly in my response.

**Comment by radfast** [comment]
This is nothing serious.

If it happens maybe once every 100 chunks (actually, if it happens less than once every **4** chunks) then the worldgen will not actually cascade.

It is an overly cautious warning message from Forge.  Unhelpfully, it also does not tell us **which** part of our worldgen has loaded a new chunk, so it's extremely difficult to troubleshoot.

On the Overworld it would have to be one of our ores or an underground oil reservoir but I don't know which.  In all tests, these worldgens are not **normally** causing this, so it's not a problem.

No action required. Don't worry about it, just enjoy the game.

**Comment by TheQuadShot** [comment]
@radfast Thanks for the explanation!

**Comment by Mattabase** [comment]
https://goo.gl/DF6Tgk

**Comment by radfast** [comment]
In the profiles that is other mod worldgen code being slow (mainly **Dungeons2**?).  It's just "passing through" Galacticraft's `otherModGenerate` code, the same way that it passes through vanilla `ChunkProviderServer`.

That is not necessarily linked with the "cascading" worldgen at all.  I don't think there is any connection between the profiles and the issue here.  You might want to report laggy worldgen to the Dungeons2 developers.

The issue reported here, the cascading flag is simply Forge flagging exactly what it says, where generating ores or blocks in a chunk needs the neighbouring chunk to be loaded for some reason.  That can happen if you generate ore blocks in the edges of a chunk like chunk position x=0 or x=15.

If somebody really wants to debug this, they would need to run the code inside a development environment with a breakpoint set on the Forge cascading worldgen error message then look at the stacktrace at that point.

But like I said already, it's not necessary at this point, it is not a serious issue.  More like a "quality of logs" issue.
