### ISSUE TITLE
Translation Suggestion——Could we use more native expressions?

### ISSUE THREAD

**Issue by ETStarLight** [micdoodle8/Galacticraft#3346]
Hello,everyone!
As all our developers and translators know,GC use many names from the USA:such as 

> commands.gchouston.confirm.1=This is Mission Control, say again please?
commands.gchouston.confirm.2=(To abandon mission, type /gchouston again to confirm.)
commands.gchouston.fail=Command /gchouston is only available from space (or Creative Mode).
commands.gchouston.help.1=Uh, Houston, we've had a problem....
commands.gchouston.help.2=(Type /gchouston to abandon mission and return home.)
commands.gchouston.noop=Using command /gchouston on other players is only available to operators.
commands.gchouston.success=OK, stand by, %s, teleporting to Overworld home position.

>  tile.rocket_workbench.name=NASA Workbench

NASA Workbench

However,NOT all the players are Americans(maybeBottom line of political,I think) .So,I think it will be better if we translate these phrases into native phrases,for example:

> tile.rocket_workbench.name=CNSA工程台           （China）
    tile.rocket_workbench.name=Верстак RKA          （Russia）
     tile.rocket_workbench.name=JAXA 作業台           (Japan）

I think these expressions will make players from different countries feel better when they use this items.But it's very different from en_US.lang,so I want to know all your opinions.

Whom I think is important to this issue:
@micdoodle8  the owner
@radfast   the most active developer now
@ErrorCraftLP   de_DE
@Romsik788     ru_RU
@SteveKunG     th_TH

Waiting for you!

**Comment by Romsik788** [comment]
A good idea. Only I think it's necessary to rename the /gchouston command, for example, to /gcspacecenter. What do think?

**Comment by TheQuadShot** [comment]
It's an homage to Apollo 13, I don't think it would change since it is a major event in NASA history.

**Comment by radfast** [comment]
* Galacticraft is not intended to be political, it is a game for everyone in the world to enjoy.  Actually we are very **pleased** that the Galacticraft community brings together players who enjoy space from many different countries, and all can play in harmony.
* Neither @micdoodle8 nor @radfast are from USA.
* Some features in the game are based on the US Apollo space program from the 1960s because that was the first to land on the Moon.  (At that time the USA and USSR were racing each other to get to the Moon, that is why in the game we have the "Space Race" concept).
* Many countries now have space programs and many countries have sent astronauts to the International Space Station, so in modern times there is no exclusive link between space exploration and any specific country.
* You can localise all the game names and phrases to make it more meaningful for the players in your country or language group - especially please bear in mind the understanding of **younger players** who do not speak other languages.
* For example we expect **astronaut** to become **cosmonaut** in Russian (but I didn't check!)
* You can localise **NASA workbench** how you want - internally in Galacticraft's code it is Rocket Bench.
* The `/gchouston` command and message sequence is intended to reflect a [specific incident](https://en.wikipedia.org/wiki/Houston,_we_have_a_problem) in the [Apollo 13](https://en.wikipedia.org/wiki/Apollo_13) mission which - as @TheQuadShot  says - was a major event in NASA history and in the history of spaceflight generally
* We changed the message sequence to make it more international, for example "This is Houston" has become "This is Mission Control" in the game.
* If that sequence of messages makes no sense in your country - for example because even the kids who like space have not seen [this movie](https://en.wikipedia.org/wiki/Apollo_13_(film)) - then you are welcome to change the messages totally to something which has meaning for your players.
* We cannot easily change the command names in game, I'm not even sure if localisation of command names is possible - and logically if one command name is localised they would all need to be localised
* A further reason for not changing command names is that it could go badly wrong if server and client are using different localisations...

**Comment by SteveKunG** [comment]
I'm not serious about this much, because in our country doesn't have any space organization :D
But yeah, In Thai we called NASA (นาซ่า = na sa).

**Comment by ErrorCraftLP** [comment]
In the german language file, the nasa workbench is already called "rocket workbench".

**Comment by TheQuadShot** [comment]
Although I can appreciate being "world/political" friendly,  I think if "we" were to diminish or change some of the Great accomplishments of cosmonauts like Yuri Gagarin's first communications from orbit would be kind of like a stick in the eye or a diminishing of the Russian Federal Space Agency (Roscosmos State Corporation for Space Activities(Государственная корпорация по космической деятельности)). I'll also admit that most people wouldn't and don't bother learning about history, so I guess I'm saying political correctness be damned, accurate history is much more important. Maybe "we" could incorporate some Russian comments from Vostok 1:

"Предварительный этап....промежуточный... главный....снимите! Желаем вам хорошего полета. Все в порядке."
Korolev: "Preliminary stage..... intermediate..... main..... lift off! We wish you a good flight. Everything is all right."
	 
Gagarin: "Поехали!" (Poyekhali!—Let's go!) This became a "meme" in the eastern block for many years.

**Comment by EzerArch** [comment]
Tip: create a resource pack containing only the phrases you want to customize and be happy. :D

**Comment by radfast** [comment]
I think this can be closed.  Everyone is 99% happy.

@ETStarLight you can change Workbench how you want, certainly it can be CNSA.

**Comment by ETStarLight** [comment]
Why everyone pay nearly all your attention to the word 'political'?!
I only hope that when players from different countries play the mod,they will remind proud of their own country,or even more,make teens being interested in rocket science!
