### ISSUE TITLE
Being kicked to the main menu after world switch

### ISSUE THREAD

**Issue by BreadtheRipper** [micdoodle8/Galacticraft#3354]
Minecraft version: 1.7.10
Galacticraft version: 3.0.12.504
Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?:  Single Player
Galacticraft add-ons and other mods installed?
Extra planets, Galacticraft planets
Please provide screenshots / crash report / log as needed.
https://pastebin.com/DJDFhYg5

Creating a new world or logging into one works fine for the first two times. But from the third time onwards it just gets back to the title screen and you need to relaunch the game. I'm unsure if this is a galacticraft issue, but there is no crash report, so I've provided the log from the console after attempting to log into a world the third time

**Comment by radfast** [comment]
Dim -45 problem.

That's probably Extra Planets, or maybe a dimension ID config with another mod.  You might be able to fix it by looking at all your configs and thinking about which mod(s) want to make dimension -45.

Not a bug in Galacticraft _per se_

**Comment by BreadtheRipper** [comment]
I've already been to the configs
All I've seen of it, is that it's for the dimension "Asteroids" in the galacticraft config
And it used to be dimension -30 and I changed it to -45 in hopes of resolving a conflict, but it still kept happening

**Comment by radfast** [comment]
Your log is filled with messages like this:

     java.lang.IllegalArgumentException: Failed to unregister dimension for id -45; No provider registered

Change Asteroids back to -30 or delete the Galacticraft configs completely and let Galacticraft remake all of them.  (You'll need to create a new world.)

If after you've done that something else also wants dimension -30, give details.

**Comment by BreadtheRipper** [comment]
Okay, so I've tried deleting the configs, but after entering and leaving the world twice, trying to get in to any world kicks me back to the main menu again
This is the log for that period of time: https://pastebin.com/2ZyNsrFD

This is the list of mods installed: https://imgur.com/a/GvtjTfr
The modpack is [Questing Mayhem](https://minecraft.curseforge.com/projects/questing-mayhem?gameCategorySlug=modpacks&projectID=261342#c78)

Galacticraft version: 3.0.12.504
Galacticraft Planets version: 3.0.12.504
Micdoodlecore version: 3.0.12.504
Forge version: 10.13.4.1558-1.7.10
If anything else is needed, please let me know

**Comment by radfast** [comment]
OK, I can see the dimension conflict for dimension `-30` now.

This doesn't tell us what is causing it.

Logically it can only be a conflict with another mod.  You will have to figure out which one is conflicting, by removing mods and restarting, until you see that the problem is fixed.  (To speed up the process you can remove mods in groups using a binary search method.)

The mod developers don't have time to troubleshoot specific modpacks, so either you or the modpack creator will have to spend the time to do this.

The cause could well be a changed config in another mod.

(I think if Galacticraft had a dimension ID conflict with another mod in its standard configuration, we would probably have heard about it before now.  The 1.7.10 version has been played for around 3 years now and millions of people have played it.)

If you can figure out the exact conflict - like Galacticraft + **X mod** causes this, with nothing else installed - then we can look for a solution.  But like I say, I think it's most likely because something else has non-standard configs, in which case using the standard config might fix things.

**Comment by BreadtheRipper** [comment]
It seems the issued lied within the ExtraPlanets config, as resetting the config seemed to have fixed it
Thank you for your time and assistance in helping me with this

**Comment by radfast** [comment]
you're welcome

You really should update to 1.10.2 - 1.12.2, they are much improved.  I think all the mods in that pack you're playing exist in 1.12.2.

**Comment by BreadtheRipper** [comment]
Sadly, one of the reasons I've chosen to play this pack, it's one of the only packs that isn't a skyblock that my potato can run, and is one of the few that features a whole ton of quests and changed recipes that I'm interested in (along with Divine Journey, but my laptop absolutely hates that one)
Most other packs, even 1.10 and 1.12.2, are pretty much unplayable, and the skyblock ones, like nfinit and the like only last so long before I drop to a whopping ~15 FPS

**Comment by radfast** [comment]
did you try **foamfix**?    can help low memory systems a lot (eg any 32-bit Java with 1GB maximum game memory)
