### ISSUE TITLE
mod not working

### ISSUE THREAD

**Issue by marcbekhuis** [micdoodle8/Galacticraft#3362]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: forge-1.12.2-14.23.2.2611-universal
Galacticraft version: GalacticraftCore-1.12.2-4.0.1.174

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? got a modded server for me and my friends wanted to start a new survival and wanted to add galacticraft

Galacticraft add-ons and other mods installed? Extra-Planets-Mod-1.12.2

Please provide screenshots / crash report / log as needed.
[2018-04-25-4.log](https://github.com/micdoodle8/Galacticraft/files/1947385/2018-04-25-4.log)
[crash-2018-04-25_16.06.43-server.txt](https://github.com/micdoodle8/Galacticraft/files/1947387/crash-2018-04-25_16.06.43-server.txt)

**Comment by marcbekhuis** [comment]
after i remove tinkers defence it gave a new error.
[crash-2018-04-25_16.34.04-server.txt](https://github.com/micdoodle8/Galacticraft/files/1947457/crash-2018-04-25_16.34.04-server.txt)
[2018-04-25-5.log](https://github.com/micdoodle8/Galacticraft/files/1947459/2018-04-25-5.log)

**Comment by radfast** [comment]
The first crash does not seem to have any connection with Galacticraft, it's Tinker's Defence and its `IItemColor` crashing which is not something we use.  Not clear why you reported it to us?

The second crash was likely caused by using an **Extra Planets** version which wanted a different version of Galacticraft - each Extra Planets matches a few specific Galacticraft versions only.  Anyhow you have it working now so that's good.

**Comment by MJRLegends** [comment]
The ExtraPlanets version hes using is off a stole site, please download the correct official version

**Comment by MJRLegends** [comment]
Not only has it been stolen its been complied unofficially too
