### ISSUE TITLE
Refined storage silicon not working with circuit fabricator 

### ISSUE THREAD

**Issue by icray1** [micdoodle8/Galacticraft#3372]
Minecraft version:1.12.2
Galacticraft version:4.0.1.174

While ender io and other ore dictonaried silicon work in the circuit fabricator, Refinded Storage silicon doesn't work even though it is ore dictonaried.
Here is a gif demonstrating it.
https://i.imgur.com/6hfclp9.gifv

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Multiplayer Server

Galacticraft add-ons and other mods installed?
Refined storage

**Comment by TheQuadShot** [comment]
I believe this is a Refined Storage Issue since the fabricator will accept any itemSilicon and RS produces ItemSilicon

**Comment by icray1** [comment]
Alright i'll just figure out a work around thanks.

**Comment by TheQuadShot** [comment]
@icray1 I wouldn't use his silicon, it's too expensive, since you can make EIO's out of sand. I just make a sag mill put a large chest or crate(AA), next to it and set that side for push/pull, then fill it up with cobble and leave it for a while, it will be full of silicon and flint when it's done.

cobble -> gravel/flint -> sand/flint -> silicon/flint
