### ISSUE TITLE
stairs not working

### ISSUE THREAD

**Issue by kevinbruinsgamer** [micdoodle8/Galacticraft#3384]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.10.2
Galacticraft version:4.0

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? yes

Please provide screenshots / crash report / log as needed.

![2018-04-30_20 24 07](https://user-images.githubusercontent.com/38865596/39443388-ba15a4d2-4cb4-11e8-98d6-e80b5050bdef.png)

i have placed al the stairs the same way. note how the stair in the mod(s) have a issue. you can even look through other blocks that are directly attached to the stairs. this is realy anoying for my space-base. hope ther will be a patch soon.

**Comment by radfast** [comment]
Unfortunately, fixing this in the obvious way by correcting the block models is going to damage any **existing builds** if players have found a way to position the stairs so that things look the right way around.  It will also damage any Abandoned Base in the asteroids dimension, which makes heavy use of stairs.

I think probably the best we can do is look at the code for players _placing_ stairs, see if that can be adjusted to overcome this bug.

I will comment that stairs have had quite a few bugs and they have been one of the most problematic areas when updating Galacticraft for different Minecraft versions.  With hindsight, we might have been better off not including stairs in the mod...

**Comment by TheQuadShot** [comment]
? I'm not seeing this
https://imgur.com/a/Yb5Bn87

**Comment by radfast** [comment]
@kevinbruinsgamer  which **exact** Galacticraft version did you do your test in?  "4.0" is not enough info.

**Comment by kevinbruinsgamer** [comment]
It is 4.0.00 if this number is not valid, it is just 4 and 0's behind it.

**Comment by EzerArch** [comment]
> It is 4.0.00 if this number is not valid, it is just 4 and 0's behind it.

Can you open `mods` folder, search for Galacticraft jar files? Please copy and paste the file names. It's something like `Galacticraft-Planets-1.10.2-4.0.1.175.jar`.

**Comment by radfast** [comment]
@kevinbruinsgamer did you download Galacticraft from the [official download site](http://micdoodle8.com/mods/galacticraft/downloads)?

**Comment by kevinbruinsgamer** [comment]
No because the servers were down

**Comment by MrEyeballs29** [comment]
>  No because the servers were down
The download site does not look down.

**Comment by dj3520** [comment]
>The download site does not look down.

It _could_ have been before though. Either way, development on a non-official version can't exactly be done. Try again with the newest and official Galacticraft, and if the problem still exists we can start from there.

**Comment by radfast** [comment]
appears to have been fixed a long time ago in 74044ee

If still seen in latest build 4.0.1.175 please give steps to reproduce.

**Comment by kevinbruinsgamer** [comment]
Then my question is awnserd. I use a older version. I will update it. Thanks for the info
