### ISSUE TITLE
Thermal Padding issue with addons

### ISSUE THREAD

**Issue by MJRLegends** [micdoodle8/Galacticraft#3387]
See https://github.com/MJRLegends/ExtraPlanets/issues/296

Im posting this here as i dont touch thermal padding rendering here are my classes related to thermal padding

https://github.com/MJRLegends/ExtraPlanets/tree/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/thermalPadding

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/ExtraPlanets_Items.java#L334

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/ExtraPlanets_Items.java#L547

https://github.com/MJRLegends/ExtraPlanets/blob/dev_1.12.2/src/main/java/com/mjr/extraplanets/items/ExtraPlanets_Items.java#L838

Also personally i wasnt able to see this issue when i tested it

**Comment by radfast** [comment]
> personally i wasnt able to see this issue when i tested it

!

I can't see any reason why the core code would be failing here.  Tier 1 and Tier 2 thermal padding are added by Mars and Venus modules respectively, and the core code treats additions by GalacticraftPlanets just the same way as additions by other add-ons.

The OP said that the issue occurred only after **installing an add-on in an existing game**.  That can maybe cause weird issues because of data structures changing when the add-on is installed.  I do not see that we are under any obligation to support bugs which occur when mods are changed in an existing game world.

**Comment by MJRLegends** [comment]
No problem i will take a look could be another mod causing the issue or another factor ive missed

**Comment by MJRLegends** [comment]
@radfast please see my latest comments over on MJRLegends/ExtraPlanets#296 as i believe it not to be a issue on my side :D please let me know if you see anything im doing wrong.
