### ISSUE TITLE
No keybindings set, "Calculator" key opens Galactic Map

### ISSUE THREAD

**Issue by KikiCur** [micdoodle8/Galacticraft#3389]
Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.1-170

currently in SMP, server but I will test on single player

Galacticraft add-ons and other mods installed? Core, Planets and Tweaker 1.0.1, SevTech:Ages 3.0.6 pack

Suggestion - I would like a button on the star map to exit said star map please.

This is my dilemma, I usually turn off all keybinds of mods I am not currently using so Galacticraft has no active keybinds. I play with an older Microsoft keyboard with an easy access to calculator button. Keyboard layout is French Canadian.

When I press the calculator button with minecraft open, it opens up galacticraft star map on the game as well as my calculator ^\_^ :D. 
Buuuut since I don't have a keybind set to the starmap, I can't press anything to get out of it. Repressing the same calculator button does not close the star map, neither does pressing escape so I'm effectively stuck in the starmap till I relaunch the game >_<.

:D Took me a good while to identify the key I'd inadvertently pressed to open that I tell ya lols. I'm really curious to know what combination of code triggers that calculator button activates to access your star map O_O.

Looking forward to exploring your mod :). Thanks tons for your time.

edit - yup, same happens in single player, pressing that calculator button opens up both the star map in minecraft and the calculator app of my computer ^_^
Thanks again.

update - back on server and I set a keybind (p) to my galacticraft Galaxy Map (using correct term now that I've actually payed attention, sorry o_o) and when I now press my calculator key on my keyboard, only the calculator pops up, thought that information could be useful to figure out what actually happens

**Comment by radfast** [comment]
Seems like you've fixed it by setting a key binding.

>   I usually turn off all keybinds of mods I am not currently using so Galacticraft has no active keybinds.

You're on your own if you do that, sorry.

-----

I think what you're saying here is that **even with no keybind**, the Galaxy Map opens when you press key 'M'.  That's intended behaviour.  If there is no keybind set, then a Galacticraft control will be set to its default key.

You can exit the map either by pressing the 'Esc' key (like any Minecraft GUI) or else by clicking on the red 'Exit' button in the top right corner.

**Comment by KikiCur** [comment]
Yeah, I am glad I found a work around but I'm still really curious as to why hitting a dedicated calculator key on my keyboard, gets me stuck in the Galaxy map if I have no keybind :/.
I understand if you think it's such an outlying case that you don't want to take the effort to code an exit Galacticraft function on any of your UIs. :) 

I don't get stuck if I press M, I press an extra dedicated key on my keyboard that opens up my calculator. O_o and the only reason I reported it is because pressing the ESC key does not close my Galaxy Map when I get stuck. That's the reason I reported it.

What I subsequently noticed is that that key (WITH a keybind) pauses my game and also opens up... the Space Race Manager pop up in the bottom right of my UI, as well as... an Report Bug tab to report issues directly to SevTech: Ages pack and thirdly a What's New from WAILA tab on the right sides of my minecraft game screen. 

Thanks for the quick reply ^_^.

**Comment by tterrag1098** [comment]
Sorry, when a keybind is unbound you just use the default? That is a bug by any means, GC should not be taking up a key if the keybind is specifically unbound...

**Comment by KikiCur** [comment]
okay, so subsequently, after talking with the guys on CoFH, I have a mayyybe supposition of that is happening?

it seems when I press my calculator key withOUT keybinds set on galacticraft it triggers the escape key in such a manner that it first accesses and opens up your galactic map?
then I can use the mouse to browse the planets and other buttons on that ui, but any subsequent presses of the ESC key does not close the map at and I am stuck in the map screen in game with no way out but to close minecraft o_o

**Comment by radfast** [comment]
A screenshot might help here.  There should be a red "EXIT" button on the top right of that screen, which you can click.

**Comment by wamc2017** [comment]
Hmm, Sevtech Ages also got Extra Planets, have you tried setting "Use Custom Galaxy Map/Celestaial Selection Screen" to false in the config?

**Comment by radfast** [comment]
>  Sorry, when a keybind is unbound you just use the default? That is a bug by any means, GC should not be taking up a key if the keybind is specifically unbound...

There is no bug.  I don't think it's wise to assume there are bugs based on a quick comment in this thread, without actually testing it.

Galacticraft's behaviour in more detail is as follows:

*  On first start of a new world, Galacticraft takes its startup keybindings from the Galacticraft config files.  If a config is missing or set to none there or has an invalid value, the Galacticraft default will be used, for example 'M' for Map.

* That startup keybinding becomes the "default" for Minecraft's in-game config system.  If the player clicks 'Reset' in the in-game menu, it will reset to the value specified in the Galacticraft config (or the Galacticraft default if there is none)

* The keybinding can be changed to anything you want in Minecraft's in-game config system, the same as for most other mods.  There is the keybinding "None" if you want to unbind the key, so that works.  Minecraft saves all the keybindings (including mods keybindings) in `options.txt`.

This system allows players to customise their keys, and it also allows modpacks to provide a "recommended" set of keybindings by setting up Galacticraft config correctly (if the modpack compiler troubled to do that).

------

This Calculator key issue is a weird one.  @KikiCur  please can you post up a copy of your `options.txt` file?

**Comment by radfast** [comment]
@KikiCur is it a Microsoft Sidewinder keyboard?  Maybe with Intellitype software?

I don't know how this works, but maybe the Calculator key is a macro key - meaning, it simulates one or more other keypresses.  I'm fairly sure there is no such thing as an actual "Calculator" key in a PC keyboard mapping.

`org.lwjgl.input.Keyboard` has nothing about a Calculator key, so however Microsoft does it, this key must look like something else to Java.

**Comment by TheQuadShot** [comment]
There is no such thing as "dedicated calculator keys". The "10 key" keypad was/is an addition to the Standard keyboard (83 keys, the function keys (F1-F12), and the 10 key were added to make a 101 key "modern" keyboard). The 10 key keypad toggles to 2 different functions via the NumLock key. When the NumLock is on it's a standard 10 key (adding machine functions, yea that old) and the ACSII code/key scan sent is different. You can demonstrate this easily, open note pad or any "vanilla" text editor, turn numlock OFF, with your cursor in the text editor press the LEFT ALT key and on the 10 key type 225 then release the ALT key, a "ß" should appear on/in the text editor, now repeat with NumLock ON, you will get "♣". In windows "we" try/ed to take care of this by "looking" at what app you are in when you use it, so if you open your calculator we do try to read the input from the key pad as a 10 key, so it may appear that it's dedicated but its not, we just went with what we felt was "normal" expectation my most (not trying to be mean or cruel) computer illiterate people (about %99 of users).

**Comment by KikiCur** [comment]
I'm getting you those pictures/screenshots now..., just relaunching the game since I went and did the keybind set to NONE picture first.

**Comment by TheQuadShot** [comment]
@radfast Right, what they are seeing is a function of the keyboard, the keyboard is sending the ascii, which is grabbed by windows and hence java and the keyboard driver is seeing the "launch the calc" function of the keyboard macro. @KikiCur  There should be a configuration for your keyboard and a way to disable that functionality so it behaves more like a "vanilla" keyboard. Some drivers will let you set these based on the program your running others can be a switch on the bottom of the keyboard.

**Comment by tterrag1098** [comment]
I also have a calculator button on my keyboard and have never had issues inside MC. I often use it to quickly calculate crafting requirements etc.

**Comment by TheQuadShot** [comment]
@tterrag1098 I'm not disputing that, I'm sure lots of people do it and that's kind of my point. I would venture to say this is a "thing" with the keyboard driver not dealing with the French-Canadian keyboard properly, ie it's not reading/handling the extended ascii correctly. Otherwise this would be a much larger issue (lots of people with it) and it just isn't the case. I am of course only addressing part of the problem and imo it's the part that can't be dealt with here. The user could try a keylogger to see exactly what windows "sees" when they hit that key/s that may shed some light. They might also check to see and ensure that they are running the latest drivers. Call it a hunch if you want, but with as much i18n and l10n work I've done this isn't that weird a problem, just my 2 caps worth and trying to get this issue solved via elimination of variables.

**Comment by 7eggert** [comment]
According to xmodmap, keycode 148 is the X11 symbol for the calculator key, the XF86 symbol is XF86Calculator. I don't have it on my keyboard.

**Comment by radfast** [comment]
There's no mapping for that calculator key in LWJGL like I said above.

I think what's actually happening here is:
* the calculator key has no mapping in Java, but a key has been pressed, so LWJGL treats it like key "NONE" has been pressed (Java LWJGL Keyboard code 0)
* Galacticraft and probably other mods as well are still checking for their keypresses every tick.  If a key is unbound (Keyboard code 0) then pressing the calculator key actually matches that (Keyboard code 0) so a mod's code "thinks" its key has been pressed
* In Galacticraft's code, the Galaxy Map keybinding is the first one to be checked, so that's why that opens
* Probably other mods also think their (unbound) keys have been pressed, so can have multiple weirdness all at the same time

Still unexplained why you don't have the red EXIT button on the solar system map.  That should literally be impossible.  **Could be another mod is drawing something in that corner of the screen (covering the EXIT button) but the button is still there, if you click in the place where it should be.**

I have fixed the "matching calculator key with an unbound Galacticraft keybind" issue in our next version 176, should be available ~ Friday.  Until then, please take care not to press the calculator key...

**Comment by KikiCur** [comment]
Thanks you guys, I very much appreciate that you took the time to look into this

(Just for completion sakes, I went and checked if the exit key is actually clickable in the problem galaxy map and nope, it does not respond to a mouse press when I click in the top right corner screen.)

Thanks again.

**Comment by radfast** [comment]
You're welcome.  When 176 is released, try that, I think keys will work properly (or any remaining issues are outside our mod).  If the "EXIT" button is still missing in the map, that maybe a totally separate issue.  In that case, please open it as a new issue.  Please test whether the same issue takes place without Extra Planets installed.
