### ISSUE TITLE
Telemetry Unit show wrong heart beat values

### ISSUE THREAD

**Issue by QuantumStatement** [micdoodle8/Galacticraft#3391]
Minecraft version: 1.11.2
Galacticraft version: 4.0.1.176

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP

Galacticraft add-ons and other mods installed?
None

In some situations Display Screen (with Telemetry Unit) show wrong heart beat values:
1. If player is in any Galacticraft dimension, heart beat constantly rises until it reaches 200 bpm
2. When player uses Hydraulic Platform, heart beat rapidly rises up to 200 bpm

**Comment by TheQuadShot** [comment]
I believe this to be by design. Based on what I know about real life experiences by astronauts. Believe it or not, but working in zero G or low G you have to actually work just to stand erect, your body "wants" to curl up into a fetal position. Think about it, you aren't using "pure muscle" when you stand, you rely on bones and gravity, to "hold" the structure erect. You also don't have gravity to help with leverage. During early spacewalks (Mercury Missions), several tests where canceled due to excessive heart rate and blood pressure just from tightening and loosening bolts. Elevated bp can be shown here when you take a high speed elevator up, blood is "pushed" down into your legs, so your heart has to pump harder to get the blood going "up hill". It is also true that during "rest" or slack time blood pressures were recorded to be pretty low.

**Comment by radfast** [comment]
It's a bug.

But we should also add in the "by design" features that @TheQuadShot mentioned so that it increases in low gravity dimensions and goes very high during spacewalks - and goes pretty low in the **Cryogenic Chamber**   All should be easy enough in coding terms, Galacticraft knows when the player is spacewalking  :)

**Comment by TheQuadShot** [comment]
_man, that Quad is such a **NERD**_ btw there are tons of papers/studies/reports on hr/bp studies on the NASA website if anyone's interested.

**Comment by 7eggert** [comment]
If there is a claim, I'm compelled to verify it:
http://theconversation.com/five-things-that-happen-to-your-body-in-space-52940
"A human heart rate (number of beats per minute) is lower in space than on Earth, too. In fact, it has been found that the **heart rate of individuals standing upright on the ISS is similar to their rate while lying down pre-flight on Earth**. Blood pressure is also lower in space than on Earth."

More results, all without raw data:
https://www.nasa.gov/mission_pages/station/research/experiments/975.html
https://medium.com/@room_n/john-young-the-astronaut-fe2c1076a986
https://www.sciencedirect.com/science/article/pii/S2214552415000024
