### ISSUE TITLE
Can't render items when opening my inventory (conflit with Real Train Mod) 

### ISSUE THREAD

**Issue by BastienGames** [micdoodle8/Galacticraft#3393]
Minecraft version: 1.12.2
Galacticraft version: 176
Real Train Mod version : 2.4.4-23 ([https://minecraft.curseforge.com/projects/realtrainmod/files](https://minecraft.curseforge.com/projects/realtrainmod/files))

When I open my creative inventory (in SSP or in SMP), and want to charge the mods pages, Minecraft crashed.

I think it's a Galacticraft problem, because I tried to open my inventory with GC older versions, and without change RTM mods (I don't get this problem with the 123 version, and older).

I add one of my crash-report : https://gist.github.com/BastienGames/d8e7d1ecc4e31627cd0dc03f611710ce

Hope you will fix the problem :wink:

**Comment by TheQuadShot** [comment]
Yup, you can't even use `@gal` on the search or you crash. I can't find link to source, or bug db, just a pointer to twitter https://twitter.com/Murakami1564

**Comment by radfast** [comment]
Although the crash is in our code, it's not us **causing** the crash.

It looks like a JavaX library version has been loaded which is different from the standard one which we are expecting.  I don't know whether Real Train Mod caused this, or something else.  (It's also possible that the issue is unique to your setup, maybe you are using an unusual JVM and runtime?)

I'm not going to debug an issue in a mod which doesn't release it's source code.

Please report to the RTM dev and ask him to resolve it, or if you can't do that, you will need to not play Galacticraft and RTM together.

**Comment by radfast** [comment]
[Here is the same crash](https://pastebin.com/66P5mXV8) (I found by Google) with RTM and **no Galacticraft installed**

The crash is also reported somewhere in [this thread](http://forum.minecraftuser.jp/viewtopic.php?f=13&t=13633&start=3640) but I don't understand Japanese...

This issue is **definitely** not caused by Galacticraft.
