### ISSUE TITLE
Crash when right-click the Compressor

### ISSUE THREAD

**Issue by Jacky10X** [micdoodle8/Galacticraft#3402]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version: 1.12.2-4.0.1.176.jar

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Only Client Crash, The Server is fined

Galacticraft add-ons and other mods installed?
Yes, Some mods like BC IC2 TE EU 
Please provide screenshots / crash report / log as needed.
https://pastebin.com/wc0MgmXe

**Comment by TheQuadShot** [comment]
What happens if you remove Thaumcraft? I can't repro this with very short list of mods, I don't have BC/IC2/TE/EU or Thaumcraft either. but there is this line in the log:
 at thaumcraft.api.crafting.ShapelessArcaneRecipe.func_77569_a(ShapelessArcaneRecipe.java:59)

**Comment by Jacky10X** [comment]
Just confirm it is conflict with Thaumcraft mod 
when i remove Thaumcraft, it is work as normal
So i think Thaumcraft somehow conflict with Galacticraft mod

**Comment by radfast** [comment]
I think we can fix this easily.  Looks like Thaumcraft have some recipes which are not a 3x3 shape, our code wasn't taking account that another mod might have differently shaped recipes.

**Comment by radfast** [comment]
OK I've looked at this.

It seems to be a bug in **NoMoreRecipeConflict**.  Not a bug in Galacticraft.

I don't know what that mod is doing, but it shouldn't be adding its button to our Compressor GUI.  It's because that mod is doing that, that the crash happened.  Basically it was (a) trying to draw a button which shouldn't be there; (b) accessing Thaumcraft recipes which are **larger** than 3 x 3 inside our Compressor which has a 3 x 3 crafting grid.

Seems bugged on several levels.

I think uninstall **NoMoreRecipeConflict** and your problem will be gone.

**Comment by MachinegunMarty** [comment]
Can confirm i have the same crash.

I also commented in the NoMoreRecipeConflict GitHub post.

Just wanted all 3 of the mod makers to be aware of the problem and post a link to the NoMoreRecipe GitHub.

Maybe you can shine some light on a possible solution in that post ?

Any help is appreciated.

Thanx in advance !

grtz,

MachinegunMarty

Link to NoMoreRecipeConflict Github "Crash when using Galacticraft's Compressor":

https://github.com/GotoLink/RecipeHandler/issues/18

**Comment by NicosaurusRex99** [comment]
I am unsure if this is a good idea or if it is already a thing but how would temporarily adding the plates to oreDict do so we can use the thermal variants

**Comment by radfast** [comment]
@NicosaurusRex99 not sure why we need to change anything here.  The issue is caused by NoMoreRecipeConflict.  That's not an essential mod, so just remove it or wait until they fix the issue.
