### ISSUE TITLE
Compatibility with Tomb Many Graves 2

### ISSUE THREAD

**Issue by M4thG33k** [micdoodle8/Galacticraft#3406]
Hello!

I have recently made an update to Tomb Many Graves 2 which allows mod authors other than myself to add compatibility between their mod and mine. This update uses a new API I created; I have also (temporarily) created a plug-in to allow your mod to work with TMG using this API. I was hoping/wondering if you would consider using the API in order to take compatibility handling out of my hands in case future updates change the way things work for your mod? You can use the plug-in I created as an example, and I can answer any questions you may have.

Link to API project: https://minecraft.curseforge.com/projects/tombmanygraves-2-api
(A link to the specific plugin's project can be found on that page as well)

Thanks!
-M4thG33k

**Comment by M4thG33k** [comment]
Thanks for the quick response! I did use your API in creation of the [plugin](https://github.com/M4thG33k/TombManyPlugins/blob/master/Galacticraft/src/main/java/com/m4thg33k/tombmanyplugins_galacticraft/TombManyPluginsGalacticraft.java) to add compatibility. I wanted to give you the option to incorporate the compatibility side into your project if you wanted to go that route. If you would prefer to leave the compatibility in the stand-alone plugin, I can definitely do that too. 

If you prefer the stand-alone plugin option, I just wanted to double-check that the inventory returned from AccessInventoryGC.getGCInventoryForPlayer(...) is, in fact, the only additional inventory added by Galacticraft for items stored on the player. (I, personally, haven't played with GC too much, but compatibility was requested so I did my best.) Thanks again! -M4thG33k

**Comment by radfast** [comment]
* We do not have any other additional inventory slots, that API class covers it fully.  (And I think it will automatically adjust, if we add more slots in future, as it is returning a subclass of `IInventory`)

* I prefer to leave compatibiity in the stand-alone plugin for now, but we can see how it goes.  Right now we are busy working on other upcoming features for Galacticraft.

* I guess the modpack needs to specifically download the correct TMG2 plugin for each other mod installed?

* You do not need to set the minimum GC version at 4.0.1.176, there will be some players who prefer to use older out-dated versions for whatever reason.  That API has been unchanged for 1 year now.  Any GC version later than 4.0.0.100 should be good.

* If your mod exists in earlier MC versions than 1.12, you'll find Galacticraft API is identical (and up to date) in GC versions for Minecraft 1.8.9, 1.10.2 and 1.11.2.   All carry the same internal version and build number, for example 4.0.0.100 or 4.0.1.176, because they are basically exactly the same apart from adaptations needed for the Minecraft/Forge versions - meaning Galacticraft's own internal operation and Galacticraft's API is the same.

* We also change the player entity from `EntityPlayerMP` to [GCEntityPlayerMP](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/entities/player/GCEntityPlayerMP.java) - this doesn't have anything to do with the inventory, it's only to allow us to hook into or change some vanilla methods in the player class which Forge doesn't have hooks for.  This does not normally affect other mods, except that in any server crash report you will always see the nearby player entity named as a `GCEntityPlayerMP` not an `EntityPlayeRMP`.

I think this issue can be closed.  Did you try out your API in game and it seems to be OK?  (In the GUI, the extra inventory slots are accessed in the player inventory, second tab.)  If you have any problems please re-open.

BTW I know what it's like when you're busy coding, but you really should try playing Galacticraft some time, it's fun :)
