### ISSUE TITLE
Chunkloader does not load Galacticraft/Extra Planets on Server Restart

### ISSUE THREAD

**Issue by justinrusso** [micdoodle8/Galacticraft#3416]
### Issue
When a chunkloader is placed in a GC/EP dimension, the dimension does not get loaded again after a server restart. A player must visit the planet to get it to work.

Reference: https://github.com/DarkPacks/SevTech-Ages/issues/2004

#### Versions
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.177

#### Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Single Player, but can be replicated on any.

#### Galacticraft add-ons and other mods installed?
Extra Planets

**Comment by radfast** [comment]
Which chunkloader?

Seems to work OK with our own chunkloaders, otherwise launch-controlled rockets could not fly to another dimension.  (A Launch Controller works as a chunk loader.)  So it may be an issue in the other mod.

**Comment by artdude543** [comment]
I'm going to assume we are talking about the Weirding Gadget @justinrusso  _(From the same mod name)_

**Comment by justinrusso** [comment]
Correct. The Weirding Gadget

**Comment by radfast** [comment]
@justinrusso does it work if a Galacticraft **Launch Controller** is in the same spot.

(An easy way to tell is if you can launch a rocket with that Launch Controller as the destination, before any player went to that dimension.)

If that works then the problem is likely in The Weirding Gadget not in our mod.

**Comment by AtomicBlom** [comment]
I think it is an issue on my side. Someone reported to me that The Weirding Gadget wasn't properly reloading chunks for the nether on restart. I'll be looking into it soon.

**Comment by justinrusso** [comment]
@radfast I apologize for missing your reply. I guess it got lost in my email.

@AtomicBlom Thanks for digging up this issue and commenting on it. I appreciate the update!

**Comment by radfast** [comment]
@AtomicBlom  I haven't looked at the issue in detail, but you might want to look at the sequence of dimension registration and `WorldProvider` creation at server startup.  Maybe your chunk loader is trying to load chunks before the dimensions are registered?

Our Galacticraft dimensions are registered only during `postInit` phase of server startup.  That's because we wait to see what Galacticraft add-ons are present, it can also help to reduce dimension ID conflicts if another mod already took one of the dimensions.

And some space station dimensions are not even registered then, unless the `/gckeeploaded` command is used.
