### ISSUE TITLE
Crash when new 1.12.2 EnderIO versions Conduit connected to Aluminum Wire

### ISSUE THREAD

**Issue by Moobien** [micdoodle8/Galacticraft#3422]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.1.175.jar Galacticraft-Planets-1.12.2-4.0.1.175.jar MicdoodleCore-1.12.2-4.0.1.175.jar

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP

Galacticraft add-ons and other mods installed?

please refer to attached log file.

Please provide screenshots / crash report / log as needed.

Was in an asteroid base, connected a EnderIO Ender Energy Conduit to an Extra Planets Basic Decontamination Unit and then crashed. Both Server AND client have had Extra Planets removed and crash persists at the "loading terrain" stage of logging in.

[crash-2018-05-28_23.15.36-client.txt](https://github.com/micdoodle8/Galacticraft/files/2048327/crash-2018-05-28_23.15.36-client.txt)

**Comment by TheQuadShot** [comment]
That map is screwed, you may be able to "fix" the crash and get it back but there is no guarantee.
Edit your forge.cfg file, and look for this line, and change it to true. Then start your server. If you recover the map, don't forget to go back and restore the forge.cfg to its original. 
`# Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    
B:removeErroringEntities=false
` 
so it should be 
B:removeErroringEntities=true

**Comment by Moobien** [comment]
Thanks for the response. I will let my server admin know and let him decide.

**Comment by EpicSquid** [comment]
Ender IO dev here, we have no issues with any other mods implementation of the forge energy capability. Are you asking for a direction? Because we return null only if no direction is given. Can you link your capability call please?

**Comment by radfast** [comment]
@EpicSquid  [our code](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#L265) was definitely specifying a direction.

That line is inside a loop like this, so `direction.getOpposite()` cannot be null.

    for (EnumFacing direction : EnumFacing.VALUES)
    {
    }

**Comment by radfast** [comment]
This is fixed in latest Galacticraft build 180.

(One issue remaining is that EIO conduits seems not to be able to draw power from Galacticraft generators and energy storage, we'll take a look at that.)

**Comment by EpicSquid** [comment]
Thanks for the fix, I'll check it out at some point.
