### ISSUE TITLE
Crash with MFR beta 1.3

### ISSUE THREAD

**Issue by gonnnsteee** [micdoodle8/Galacticraft#3441]
Minecraft version: 1.12.2
Galacticraft version: 4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? Extra Planets/many mods

Please provide screenshots / crash report / log as needed. 

 https://pastebin.com/yqVXuzjm

I was told by MFR devs GC simply needs to disable integration.

**Comment by radfast** [comment]
Instead of **disabling** integration, I think we should now have correct integration with MFR 1.12.2 beta.

To test:  make an Slimeling with an Inventory bag filled with valuable items.  Capture it, take it to a MFR mob spawner.  Set the spawner to 'Exact copy' mode.  The copy Slimeling should spawn with no inventory.  This prevents item duping (cheating) on servers.
