### ISSUE TITLE
Crash when flying around

### ISSUE THREAD

**Issue by Monknot** [micdoodle8/Galacticraft#3445]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?SSP

Galacticraft add-ons and other mods installed? Yes

Please provide screenshots / crash report / log as needed.
FLying through my world and crashed with this error. I have seen you said not to report "micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP" if it's in middle of the crash log but this one is at the top.

https://pastebin.com/YNLaq6C6

**Comment by radfast** [comment]
It's not connected with Galacticraft, this crash.

The code which is crashing is shown here:

    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:457)
    at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)

That is standard Minecraft / Forge code, not Galacticraft code.  I don't know the exact reason for the crash, and that's going to be virtually impossible to figure out because you have so many mods installed, including mods which might change this.

Best guess: it's something connected with a mod which changes the way your in-game statistics work, like food eaten, distance flown, distance walked, that type of statistics.

"micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP" is always going to be the internal code name of your player entity when you have Galacticraft installed.  Seeing this does not mean it is our code crashing.

Hope you find a solution.  If nobody else can help you, try reducing your mod list until the problem stops happening, then you'll know it was caused by a mod you removed...

**Comment by Monknot** [comment]
Thank you for your reply.
