### ISSUE TITLE
Crash when breaking non-GC block

### ISSUE THREAD

**Issue by BrisingrAerowing** [micdoodle8/Galacticraft#3446]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? See Gist below.

Please provide screenshots / crash report / log as needed. [Crash Log / Modlist](https://gist.github.com/BrisingrAerowing/c37fe04b45c7216a4681486ac1b4b7d7)

I was breaking a Cataplant from the Plants mod when this happened.

**Comment by radfast** [comment]
I don't think it's fishtaco's fault!

This is not a Galacticraft issue.  Your saved world has a block claiming to be an Aluminum Wire with metadata 16.  That's an impossible value and cannot be created by our code.

Two possible causes for this:
1.  A messed up Forge worldstate where many block IDs are mismatched to the wrong blocks - this sometimes happens, I don't know why, but occasionally Forge messes up if you change mods in an existing saved world

2.  A specific error in this saved chunk, maybe something went wrong when writing to disk last time it was saved - this might be fixable by WorldEdit, or just delete the chunk totally and let Minecraft regenerate it.

Although we could update our code so that it won't crash in this situation, there's not really any point as this is a one-off problem - or if it happens again, it could just as easily be a different block.

If possible you might want to restore an earlier backup of your world (maybe Forge created a zip file when you changed mods?)

**Comment by BrisingrAerowing** [comment]
I think that this is a bug in either the Plants mod or Just Enough IDs. Not sure which yet.
