### ISSUE TITLE
License request for GTNH Pack

### ISSUE THREAD

**Issue by Dream-Master** [micdoodle8/Galacticraft#3452]
Since Galacticraft no longer developed for mc 1.7.10 (but my pack will stay at 1.7.10)  it would be nice to can fork the project to make a few minor changes or additions for my Modpack GT New Horizons.
We are a major pack with 200 mods a huge playerbase all mods have hard nerfed recipes (Gregtech) and my Team and me developing the pack since 2014 and we not done yet.

If this isn't possible would you accept pull requests @micdoodle8 @radfast ?
Maybe in a separate branch GTNH so we are able to build it?

One thing I lie to change is that rockets only use rocket fuels not simple fuel.

Hope for a answer soon. Thanks

Modpack:
https://github.com/GTNewHorizons/NewHorizons
https://www.gtnewhorizons.com/

Pack is public on Twitch, FTB and Technic.
https://forum.feed-the-beast.com/threads/1-7-10-gt-new-horizons-ultra-hard-gregified-modpack-via-minetweaker-and-modtweaker-1-5k-quests.181742/

https://minecraft.curseforge.com/projects/gt-new-horizons

https://www.technicpack.net/modpack/mcnewhorizons.677387

DreamMasterXXL

**Comment by radfast** [comment]
Yes, permission granted to fork the source and build a modified version of Galacticraft 1.7.10 for this purpose.  **But** you must make sure all support requests and issue reports for the modified version come to you, not here ...

We'll keep an eye on this and we can revoke permission if we think someone is starting to abuse it (for example, "pay to play").  Not likely in your case @Dream-Master because we know you :)

**Comment by Dream-Master** [comment]
ok thanks @radfast will do my best no one complains and we report bugs to my repo in case we find some of get new ones.
