### ISSUE TITLE
Compatibility with Warp Drive mod

### ISSUE THREAD

**Issue by darthbieler** [micdoodle8/Galacticraft#3478]
Minecraft version: 1.7.10
Galacticraft version: 1.7-3.0.12.504

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP

Galacticraft add-ons and other mods installed? Warp drive

This question might have been answered already, but i cant seem to have these 2 mods to work together, if you can help please let mo know, if not, just close this issue. Thx for your time

**Comment by TheQuadShot** [comment]
The 1.7.10 version (1.7-3.0.12.504) is no longer being updated (barring any game breaking bugs). You should post your question over at the Forums page since there may be people there that can help. Also post log files or give much more info that you have. 
The forums can be found here:
https://forum.micdoodle8.com/index.php
And the Wiki here:
https://wiki.micdoodle8.com/wiki/Galacticraft

**Comment by darthbieler** [comment]
thanks for all your help

**Comment by radfast** [comment]
I'm not sure what the issue is/are, but I don't really have time to investigate a 1.7.10 issue unless it's game-breaking, sorry.

You could maybe ask the Warp Drive mod author to fix the compatibility?  50/50 it's on his side not ours anyhow.

**Comment by radfast** [comment]
See also #586 and - if that's the problem - #3116 which looks like the same issue with power networks in moving chunks.
