### ISSUE TITLE
TPS drop when launching rocket

### ISSUE THREAD

**Issue by aikainnet** [micdoodle8/Galacticraft#3512]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.1.177

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SMP

Galacticraft add-ons and other mods installed? Main pack is Sevtech Ages 3.08

Please provide screenshots / crash report / log as needed. https://gyazo.com/e570e524501af02692310090e5f75720

TPS drops quickly after starting launch countdown and until you choose a planet to land on

**Comment by MJRLegends** [comment]
Theres no evidence this is the issue, You need need profile logs to support this for it to even be looked at

**Comment by radfast** [comment]
TPS can drop for two reasons:
1.  a lot of launch smoke, if you have a slow computer - mainly an issue for Tier 3 rockets
2.  Galacticraft is intentionally "pre-generating" some of the terrain around the rocket landing site on destination planets (Moon, Mars etc)

On any normal server you should not notice any effect from 2, the server load is not much different to a player walking around unexplored territory.  But if you have a server which is already severely TPS challenged, or a large number of players launching rockets simultaneously, then I guess you might notice something.  It should only happen the first time a rocket is launched from that launch pad.  The game has to generate these map chunks _some time_, and Galacticraft is designed to spread the load across the 20 seconds of launch countdown when not much else is happening, so that in normal conditions it should be unnoticeable.

If the issue you experienced is not within 1 and 2 described above, please re-open and please provide details, such as a tick profiler profile.
