### ISSUE TITLE
Water electrolyzer is too slow

### ISSUE THREAD

**Issue by EnderiumSmith** [micdoodle8/Galacticraft#3524]
Minecraft version: 1.11.2
Galacticraft version: 4.0.0.109

The water electrolyzer is way too slow as a source of oxygen. 2 of them with tier 2 power are just shy of supplying a sealer. For such an expensive machine i would expect it to be more effective. I suggest speeding it up by 2.5x or even 5x, increasing power consumption as well of course. 2.5x would allow one to power a sealer and leave a bit spare for a compressor. 5x would put it in line with a collector.

**Comment by TheQuadShot** [comment]
I don't think this is a bug. What happens if you pipe the O2 into a Gas Liquifier? Also have you read the Wiki? https://wiki.micdoodle8.com/wiki/Water_Electrolyzer It's primary function is to provide Hydrogen. It's also the highest energy consuming machine in the mod, so using it for O2 production would be rather silly, since crops and leaf's are so much more efficient.

**Comment by EnderiumSmith** [comment]
The wiki does not say how much O2 it makes per tick.

It should still be a valid way to get oxygen even if it takes more power. I want to grow crops in the TE phytogenic insolator and use the electrolyzer for oxygen. That should be an option.

**Comment by dj3520** [comment]
The machine's primary output is hydrogen, not oxygen. If you need more oxygen I'd suggest an oxygen collector instead.

**Comment by PhysicalNova** [comment]
Logically, it should provide 2x less oxygen than hydrogen (H2O). You sould use an oxygen collector surrounded in leaves and cropes, it's really efficient. If you put one oxygen collectory (or more) in a big block full of leaves, it can provide oxygen for a full base. The O2 provided by the electrolyzer is almost useless (maybe you can store it for refilling oxygen tanks idk)
