### ISSUE TITLE
Astro Miner Suggestion

### ISSUE THREAD

**Issue by baxandrei** [micdoodle8/Galacticraft#3547]
I hate this.

![80cf0fc2-0312-11e5-884d-99208898a53a](https://user-images.githubusercontent.com/12484505/48024659-ebd0ec00-e149-11e8-8bf8-5d9fd6af7738.png)

Add a chunk loader for astro miner ... I have this problem since 1.7.10 ... It is really so hard? I've worked so hard to make an Astro Miner.. to lose it ...

**Comment by marcus8448** [comment]
Isn't this #1671?

**Comment by marcus8448** [comment]
So, you have an Astro Miner. You send it, & have it travel away.
Do you:
1. Disconnect from the server/world and then come back in and it's gone?
2. Stay on the server/world and it unloads itself

If you chose 1 then _I think_ it might be that the astro miner chunckloads until you disconnect then the chunck is unloaded, so when you come back the Miner doesn't load to chunckload? 🙃
If you chose 2 I have no idea what the problem is 😕.

**Comment by baxandrei** [comment]
`Stay on the server/world and it unloads itself`

**Comment by radfast** [comment]
>   It is really so hard?

This kind of comment is rude to the developers, and unlikely to help get your issue resolved.
You can update to a more recent version of Galacticraft, where the Astro Miner has updated chunk loading logic.

The Astro Miner is intended to "mine everything" similar to an IC2 miner.  A planned future upgrade will be to give it some AI to ignore certain blocks, but don't expect that anytime soon.

**Comment by baxandrei** [comment]
I'm already using the latest version ... do what you want, I've worked to make this item lose it;)
