### ISSUE TITLE
[Suggestion] Option to merge space station worlds

### ISSUE THREAD

**Issue by kmecpp** [micdoodle8/Galacticraft#3556]
There are a number of issues with using multiple worlds for space stations, especially for large servers

1) The number of worlds on the server can grow arbitrarily large which is not sustainable
2) Loading space stations with a large number of tile entities and other stuff causes extreme lag and it doesn't really help to simply keep those chunks loaded all the time.
3) It makes multi world management with most plugins extremely difficult if not impossible to do correctly
4) It's not even realistic to have players in the same "location in space" to be separated by dimensions

To address these issues, I think it is quite necessary to have an option in the config that will merge space stations together into one world. Then when players create a space station, it should just be generated at a random spot in the orbit world, with coordinates less than some configurable amount in the config. This is much more resource efficient, easier to manage, more realistic and necessary for many large servers.

Thanks,
kmecpp

**Comment by marcus8448** [comment]
There is a config option to turn **off** space station creation if you have a large server and it's getting too laggy.
I don't see why bundles of TileEntities in space are more laggy than in the overworld/earth.
Because of the way the spin thrusters work everyone's station would be spinning if you had one placed down. If they were not in separate dims anyone could access anyone's space station, allowing for mass greifing/trolling because you can break all the blocks in a station causing everything to fall back to earth.

**Comment by kmecpp** [comment]
1) Space stations and galacticraft in general is a big part of the server so it would upset a lot of players to have them disabled
2) It's laggy because the entire dimension has to be loaded/unloaded and players can simply join and quit to trigger this as often as they please which can render the server almost unusable if there is enough stuff on the space station.
3) I'm aware of that, but I think it's a rather minor issue. Spin thrusters can always be rewritten to be more flexible or they can be disabled entirely if single world space stations are enabled
4) That is intentional and its still very difficult to find anyone's base if not nearly impossible and that's entirely dependent on the coordinate range set in the config. Also its not any different from people having different bases on the overworld, and it would be easier to create a permission system for that world if that is desired because there's just one world.

**Comment by radfast** [comment]
Hi @kmecpp

[quote]1.   The number of worlds on the server can grow arbitrarily large which is not sustainable[/quote]
This statement is incorrect.  There is nothing unsustainable about a large number of space stations.  The dimensions are not loaded unless the owning player is online.  Moreover, there is nothing inherently problematic about a Minecraft server having a large number of dimensions.

[quote]2.  Loading space stations with a large number of tile entities and other stuff causes extreme lag and it doesn't really help to simply keep those chunks loaded all the time.[/quote]
I don't think you understand how a Minecraft server works.  The server loads the chunks around the player's current location.  This will cause chunk loading + tile entity loading depending on what is there.  It does not matter about the dimension.  If the player had the exact same base on the Overworld or the Moon, the server load would be about the same.  On a large server (more than 30 players online together) it actually reduces server load to spread the players between several different dimensions.

If you are seeing actual server lag from a specific tile entity - and if it's a Galacticraft tile entity - please let us know and we can do something about it.

[quote]3.    It makes multi world management with most plugins extremely difficult if not impossible to do correctly[/quote]
Please that issue with the multi world plugin authors.  They need to be able to support dimension creating by Forge mods.

In practice, I doubt that there is an issue as you describe, this sounds like "theorycrafting".  I used to admin a server with 30,000 players, typically 100+ players online simultaneously, with Galacticraft space stations and without any problems (at least, without any problems caused by Galacticraft).

[quote]4.   It's not even realistic to have players in the same "location in space" to be separated by dimensions[/quote]
You are entitled to your opinion, but I do not see that this needs me to re-code the fundamental structure of our mod.  If players want to use the same dimension in space, they only need to invite each other to their stations using the `/ssinvite` command.

[quote]It's laggy because the entire dimension has to be loaded/unloaded and players can simply join and quit to trigger this as often as they please which can render the server almost unusable if there is enough stuff on the space station.[/quote]
Again your understanding of lag here is incorrect.  The Minecraft server would have to load/unload the chunks the exact same way no matter where they are located.

If you are seeing a specific lag issue connected with chunk loading / unloading, please report it separately - preferably with detailed logging and performance monitoring data.

**Comment by radfast** [comment]
Hi @kmecpp

> 1. The number of worlds on the server can grow arbitrarily large which is not sustainable

This statement is incorrect. There is nothing unsustainable about a large number of space stations. The dimensions are not loaded unless the owning player is online. Moreover, there is nothing inherently problematic about a Minecraft server having a large number of dimensions.

> 2. Loading space stations with a large number of tile entities and other stuff causes extreme lag and it doesn't really help to simply keep those chunks loaded all the time.

I don't think you understand how a Minecraft server works. The server loads the chunks around the player's current location. This will cause chunk loading + tile entity loading depending on what is at that location. It does not matter about the dimension. If the player had the exact same base on the Overworld or the Moon, the server load would be approximately the same. On a large server (more than 30 players online together) it actually reduces server load to spread the players between several different dimensions.

If you are seeing actual server lag from a specific tile entity - and if it's a Galacticraft tile entity - please let us know and we can do something about it.

> 3. It makes multi world management with most plugins extremely difficult if not impossible to do correctly

Please raise that issue with the multi world plugin authors. A plugin needs to be able to support dimension creation by Forge mods.

In practice, I doubt that there is an issue as you describe, this sounds like "theorycrafting". I used to admin a server with 30,000 players, typically 100+ players online simultaneously, with Galacticraft space stations and without any problems (at least, without any problems caused by Galacticraft...).

> 4. It's not even realistic to have players in the same "location in space" to be separated by dimensions

You are entitled to your opinion, but I do not see that this needs me to re-code the fundamental structure of our mod. If players want to use the same dimension as their friends in space, they only need to invite each other to their stations using the /ssinvite command. If you want to allow all players to visit all space stations (with griefing possibilities?) that can also be configured.

> It's laggy because the entire dimension has to be loaded/unloaded and players can simply join and quit to trigger this as often as they please which can render the server almost unusable if there is enough stuff on the space station.

Again your understanding of lag here is incorrect. The Minecraft server would have to load/unload the chunks the exact same way no matter where they are located.

If you are seeing a specific lag issue connected with chunk loading / unloading, please report it separately - preferably with detailed logging and performance monitoring data, so we can try to figure out the TileEntity causing the lag.  Usually lag turns out to be caused by badly coded other mods, not by Galacticraft.  Galacticraft TileEntities are coded, so far as possible, to be high performance and not laggy.
