### ISSUE TITLE
Client crash when crafting Tier 3 Rocket

### ISSUE THREAD

**Issue by BowtiesAreCool** [micdoodle8/Galacticraft#3614]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.189
Survival multiplayer (SMP).

The client crashes repeatedly when attempting to craft a Tier 3 Rocket using the NASA Workbench. The server and other connected players are unaffected.

This issue occurs on all tested platforms: Windows 10, Windows 7 & MacOS 10.13 High Sierra.

[Sample crash report here](https://gist.github.com/BowtiesAreCool/1fcd04ba6313c7f6ac70b7429969184c).

Other (non-Galacticraft) mods in use:
- Batty's Coordinates PLUS! Mod for Forge v 1.12.0_004
- GraveStone Mod v 1.10.2
- JourneyMap v 1.12.2-5.5.3

Workarounds attempted:
- Disabling non-GC mods: Failed - crash still occurs.
- Use /give command to create Tier 3 Rocket: Failed - results in an item with no texture that causes a client crash when the user hovers their cursor over it.
- Use creative mode inventory: Successful - user able to obtain and use the Tier 3 Rocket.

**Comment by micdoodle8** [comment]
This is very strange, I'm getting a different crash, which I fixed in my workspace. Your crash is completely different though, it looks like you're being given tier 3 rocket items with damage value (meta) 56. 

/give also works for me, using `/give micdoodle8 galacticraftplanets:rocket_t3`, I get a rocket with damage value 0. The only time when I get the item with no texture and client crash is when I give it a new damage value > 4 (E.g. `/give micdoodle8 galacticraftplanets:rocket_t3 1 5`)

**Comment by BowtiesAreCool** [comment]
Ahh, I may have uploaded the crash report from an incorrectly-entered /give command rather than the workbench crash. I've you've been able to replicate and fix the issue with the NASA workbench then I think you can close this issue.

Here's a [fresh crash report](https://gist.github.com/BowtiesAreCool/e8dcdce4ff1f9d4b78aa98a398482834) with non-GC mods disabled and definitely using the workbench.

Thanks!

**Comment by micdoodle8** [comment]
Yep, that crash is fixed as of build 190. Thank you!
