### ISSUE TITLE
Galacticraft crash with rotarycraft

### ISSUE THREAD

**Issue by 321nick** [micdoodle8/Galacticraft#3635]
i know there was similar issues too this in the github, but reporting this on reikas github says that these issues were fixed in a old version of galacticraft, so im asking here for some suport

im trying to run GC on a server, with reikas mods like chromaticraft, rotarycraft, etc, and a bunch of others.

i think the issue is narrowed down to something wrong with the GC API according to reika. 

it crashes just after finishing generating spawn. a crash-report log isnt generated manually, so i have to copy paste from the console CMD. some of the uper half of the log is cut off, but most of it should be deductable from the FML.log and this.

https://gist.github.com/321nick/f9306c7eb0a2ac2237d6ca69414cee0a 

console CMD output^^

https://gist.github.com/321nick/caaaeeecc1a4dd4507e19db6b162a48d

FML server log output^^

Galacticraft-Planets-1.7-3.0.12.504
GalacticraftCore-1.7-3.0.12.504
MicdoodleCore-1.7-3.0.12.504

these are the versions i am running

no addons to galacticraft were installed at the time.

i know similar issues have cropped up, but only a long time ago, and it was supposedly fixed from then, according to reika. 

the modpack works in singleplayer just fine.

**Comment by radfast** [comment]
This is the error reported:

> [16:30:32] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
        at net.minecraft.profiler.Profiler.func_76320_a(Profiler.java:64) ~[qi.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:546) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 4 more

There is nothing there that points to this being a Galacticraft issue.  Using Google I can see this same error reported by other people [1](https://www.minecraftforum.net/forums/support/server-support-and/2334936-server-launcher-insta-close) [2](https://www.minecraftforge.net/forum/topic/33319-new-forge-1710-server-automatically-exiting-with-mods-please-assist/) with lists of mods not including Galacticraft.

Galacticraft 1.7-3.0.12.504 has been a stable release unchanged for over 1 year now.  This version has been played by 100,000s or millions of players (I'm not sure how many are still on 1.7.10).  If there was a serious issue like this in Galacticraft preventing servers from starting, it's likely it would have been reported long before now.

Therefore, I think it's _likely_ this has a non-Galacticraft cause.

If careful testing shows that the same issue happens with **only** Galacticraft installed, or **only** Galacticraft + one other mod (e.g. one of reika's mods), then we can look at this some more and re-open the issue.

>  i think the issue is narrowed down to something wrong with the GC API according to reika.

Please explain this or give me a link to reika's original comment - as said already I currently do not see anything in the posted logs pointing to Galacticraft.  If there is something to suggest that Galacticraft is a potential cause then we can happily re-open this.
