### ISSUE TITLE
w BuildCraft, we get Registry Item: Found a missing id from the world galacticraftcore

### ISSUE THREAD

**Issue by PatriceBoivin** [micdoodle8/Galacticraft#3638]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Forge version: forge-1.12.2-14.23.5.2808-universal
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.190.jar

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SMP

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets-1.12.2-4.0.2.190.jar
MicdoodleCore-1.12.2-4.0.2.190.jar
That's all... I am not aware of more add-ons (?).

Please provide screenshots / crash report / log / full modlist as needed

Steps to reproduce: add the BuildCraft mod, server halts during startup with the error
The BuildCraft developer on GitHub responded that this looks like a Galacticraft problem, that some items are not registered (?).

forge server startup log ends with...
[...]
[12:04:23] [Server thread/INFO] [FML]: Registry Item: Found a missing id from the world galacticraftcore:bucket_oil
[12:04:23] [Server thread/INFO] [FML]: Registry Item: Found a missing id from the world galacticraftcore:crude_oil_still
[12:04:23] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:blocks
[12:04:23] [Server thread/ERROR] [FML]: galacticraftcore:crude_oil_still: 725
[12:04:23] [Server thread/ERROR] [FML]: Unidentified mapping from registry minecraft:items
[12:04:23] [Server thread/ERROR] [FML]: galacticraftcore:crude_oil_still: 4679
[12:04:23] [Server thread/ERROR] [FML]: galacticraftcore:bucket_oil: 4680
[12:04:23] [Server thread/WARN] [FML]: Forge Mod Loader detected missing registry entries.

There are 3 missing entries in this save.
If you continue the missing entries will get removed.
A world backup will be automatically created in your saves directory.

Missing minecraft:blocks:
galacticraftcore:crude_oil_still
Missing minecraft:items:
galacticraftcore:bucket_oil
galacticraftcore:crude_oil_still

Run the command /fml confirm or or /fml cancel to proceed.
Alternatively start the server with -Dfml.queryResult=confirm or -Dfml.queryResult=cancel to preselect the answer.

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by MJRLegends** [comment]
Yes this is intended as compatibility in gc with buildcraft, changes which oil is used

**Comment by PatriceBoivin** [comment]
do I tell the launcher to proceed?  What will that do to my existing world, will the oil already in the ground disappear, leaving empty spaces in the rock?

**Comment by TheQuadShot** [comment]
https://wiki.micdoodle8.com/wiki/BuildCraft

`If you install the Buildcraft mod in an EXISTING GALACTICRAFT SAVED WORLD then you will find that suddenly all the Galacticraft oil and fuel has disappeared. (That's because it gets de-registered - it literally does not exist in the game - if Buildcraft is installed) And the Buildcraft oil can only be found in newly generated Overworld chunks.`


`To solve this problem, Galacticraft gives a config option to use legacy Galacticraft oil and fuel - this will preserve the old Galacticraft oil and fuel in the world (underground reservoirs, liquid tanks and buckets in inventories) alongside the new Buildcraft oil and fuel. Both can be used in the Refinery and the Fuel Loader. To be effective you must enable this config option before starting the game with Buildcraft mod installed. Except in this specific situation, you generally should not use this config option because otherwise there can be too much oil in the game (Buildcraft oil and Galacticraft oil) - also Buildcraft quarries can be laggy if they encounter liquids underground.`

**Comment by marcus8448** [comment]
This can be closed, @micdoodle8

**Comment by radfast** [comment]
Many unexpected things can happen if mods are installed or uninstalled _in an existing world_

In this case I feel this is well-documented on the Wiki.
