### ISSUE TITLE
Galacticraft crashing java.lang.ClassCastException

### ISSUE THREAD

**Issue by FusRoman** [micdoodle8/Galacticraft#3661]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.210

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP opened to LAN

Any Galacticraft add-ons installed? please list all

ExtraPlanets

Please provide screenshots / crash report / log / full modlist as needed

The game crashed whilst ticking entity
Error: java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by MJRLegends** [comment]
We'll need the full crash log please

**Comment by FusRoman** [comment]
[crash-2019-03-31_20.13.49-client.txt](https://github.com/micdoodle8/Galacticraft/files/3026985/crash-2019-03-31_20.13.49-client.txt)

**Comment by FusRoman** [comment]
here is the full log

**Comment by micdoodle8** [comment]
I know it doesn't look like it, because you see GCEntityClientPlayerMP, but this is actually a damage indicators issue. GCEntityClientPlayerMP is just the client-side GC player, and DI is trying to cast it to a server-side player. The crash would happen without GC. 

Try updating DamageIndicators, as there have been several releases since this was reported (my apologies on the late reply).
