### ISSUE TITLE
Switchable Aluminum Wires not working properly with multiple wires

### ISSUE THREAD

**Issue by jsrobson10** [micdoodle8/Galacticraft#3693]
Minecraft version: 1.12.2
Mode: Single player (SSP)

<b>Galacticraft versions:</b>
<ul>
<li>Galacticraft Core: 4.0.2.210</li>
<li>Galacticraft Planets: 4.0.2.210</li>
<li>Micdoodle8 Core: 4.0.2.210</li>
</ul>

<b>Extra mods involved: </b>
<ul>
<li>ic2 power (batbox), but it works the same with Galacticraft power sources.</li>
<li>Applied Energistics 2 (me chest), but it works the same on Galacticraft machines.</li>
</ul>

<b>Description:</b>
When the switchable wires are toggled off, another existing wire lets power through. The power also gets let through if the power is cut and re-enabled. When all the wires get enabled at once, only one cuts the power, all the animations appear that the power is cut. The animation dosn't update on the other wire, but it still is transmitting power. The same issue happens when powering devices in different mods, as well as Galacticraft machines. The power source dosn't change the issue (Galacticraft one or non Galacticraft one).

<b>As a programmer myself, I have some ideas to fix this:</b>
I noticed that the switchable wire activated and deactivated is the same block, but with different values for north/south (the directions that the wire is going in). For some blocks in Minecraft, the activated block is a different block to the deactivated one. For example, there is an activated furnace block and a deactivated furnace block, the activated furnace emits light. My idea would be to have a switchable aluminium wire and a disabled variant, maybe the disabled variant could have a red light on it, and still connect to wires, but be non-conductive? (for aesthetic reasons, to look nicer).

<b>Screenshots:</b> (note in my screenshots me chests are used, they're easier to visualise, but they work exactly the same with Galacticraft machines), with the levers: up is on, down is off.

![2019-05-19_07 30 37](https://user-images.githubusercontent.com/45777442/57975310-984d2e00-7a09-11e9-9a1b-e9ae795a36ec.png)
<sup>Just turning on one wire, it works as expected.</sup>

![2019-05-19_07 30 49](https://user-images.githubusercontent.com/45777442/57975322-f11cc680-7a09-11e9-8397-a12c81e79124.png)
<sup>Turning on another wire, the other wire lets power in.</sup>

![2019-05-19_07 36 45](https://user-images.githubusercontent.com/45777442/57975335-21646500-7a0a-11e9-9eaf-84d6bfc28b69.png)
<sup>After resetting the power (breaking and placing the solar panels wire).</sup>

![2019-05-19_07 39 43](https://user-images.githubusercontent.com/45777442/57975343-38a35280-7a0a-11e9-80b5-778167d0ee72.png)
<sup>After enabling all the wires at once.</sup>

**Comment by radfast** [comment]
Thank you for reporting, and sorry it has taken so long to get to this.

The cause of the issue was that whenever the wires network was broken (and therefore two sub-networks created on the server), it was assuming that all Switchable aluminum wires were in the connected state.  Therefore, when you switched off one wire (which causes a network break), it treated any other Switchable wires in the network as if they were switched back on at that point.  Just an oversight in the network building code, now fixed - thank you.  :)

>  As a programmer myself, I have some ideas to fix this:
I noticed that the switchable wire activated and deactivated is the same block, but with different values for north/south (the directions that the wire is going in). For some blocks in Minecraft, the activated block is a different block to the deactivated one. For example, there is an activated furnace block and a deactivated furnace block, the activated furnace emits light. My idea would be to have a switchable aluminium wire and a disabled variant, maybe the disabled variant could have a red light on it, and still connect to wires, but be non-conductive? (for aesthetic reasons, to look nicer).

We very much welcome comments and help from other programmers.  If you wanted to have a go at coding your idea and make a Pull Request for it, you could have it incorporated into the mod....  This is how I joined the Galacticraft team - I spotted a bug in the dungeon generation, and then I had an idea for a higher performance algorithm for the Oxygen Sealers seal checks.

For the Switchable Aluminum Wire, the current model - where there is a clearly visible disconnection when the switch is used - is intended to be similar to the switch offered by the **Electric Expansion** mod.  Electric Expansion was a beautiful mod in Minecraft 1.5.2 with various electrical components, and IMHO it had the right balance between difficulty, fun and technical accuracy - better than IC2, Resonant Induction or any of the subsequent attempts.  It was part of a suite and energy system called Universal Electricity.  Galacticraft was originally built using that energy system too, until there were disagreements between various authors on the direction (long before my time).  All of these mods were included in the excellent **Voltz** modpack for Minecraft 1.5.2, which was big back in 2013-2014.  For me, that was the high point of my Minecraft playing experience, and I liked Electric Expansion a lot, therefore I intend the Switchable Aluminum wire to be a kind of homage to that.
