### ISSUE TITLE
Minecraft 1.12.2 forge server too high CPU usage

### ISSUE THREAD

**Issue by Shellyoung** [micdoodle8/Galacticraft#3720]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.211

Multiplayer (SMP)

No Galacticraft add-ons installed

**Java Visual VM recorging**: https://www.youtube.com/watch?v=oTfz2GSwKmw
**debug.log**: https://pastebin.com/tc9MpgXA
**latest.log**: https://pastebin.com/Fj20A5XX

**Mods installed**:
Galacticraft Core 4.0.2.211
Galacticraft Planets 4.0.2.211
Micdoodle8 Core 4.0.2.211

I downloaded mods here: https://micdoodle8.com/mods/galacticraft

**Forge version**: 1.12.2 14.23.5.2838
**Java version**: Version 8 Update 211 (build 1.8.0_211-b12)
**CPU**: Intel Core i7 7700K with stock frequency 4400 Mhz

**The Issue**:
Clean server. No world created. I launch server, world generation completes, nobody connected and _java.exe process shows 13% CPU load_ with no change in later time.

**Comment by TheQuadShot** [comment]
I'm not sure what your issue is, this all looks normal to me. I would guess that even if you removed GC you would get the same results(Also we have no control over Forge), as the process you point out is how Minecraft does its world gen(as I understand it). As I understand it, the only reason you see GC there, is that you(the player) are a GC entity and has nothing to do with world generation.

**Comment by Shellyoung** [comment]
With GC removed the server uses almost 0% of CPU at idle state (no players connected).

**Comment by TheQuadShot** [comment]
stay with me, legit question not trying to be a jerk.
On your first test you say:
     Clean server. No world created
Is this true for your second test with no GC?

**Comment by Shellyoung** [comment]
Yes. I confirm. Clean server with no world created (world has just created to be more accurate) and without GC uses 0% of CPU at idle state (no players connected). Here's **latest.log** if needed: https://pastebin.com/FZzvuWb0

**Comment by micdoodle8** [comment]
Hmmm, yeah it does seem to be a GC issue. Thank you for the detailed report.

As this is a really obscure and hard-to-test problem I'm going to have to take a few guesses. It seems to be caused by the thread that generates a texture for the overworld.

What do you see in your `%save_folder%/galacticraft/overworldMap` folder?

**Comment by Shellyoung** [comment]
This file only: **Overworld192.bin** (http://www.mediafire.com/file/kkwqob4d42uik5b/Overworld192.bin/file)

**Comment by micdoodle8** [comment]
Okay, thanks. Would it be possible to leave your server on for about an hour and check CPU usage again?

**Comment by Shellyoung** [comment]
Yes.

**Comment by Shellyoung** [comment]
After 32 minutes passed CPU usage lowered to 0% and 2-nd file named **Overworld1536.bin** (2.81 MB) created in %save_folder%/galacticraft/overworldMap. Server now starts without the issue. Removal of the file causes the issue to appear.

**Comment by MJRLegends** [comment]
This is intended its one thread thats at 100% though rather than the whole cpu. Task manager on windows gives false details for this.

**Comment by micdoodle8** [comment]
It's still too high even if it's one thread. On my side it doubles the CPU usage of idle minecraft for over half an hour.

Are you using the output "large.jpg" in your addons @MJRLegends ?

**Comment by MJRLegends** [comment]
@MJRLegends nope first time ive heard of the large.jpg

**Comment by radfast** [comment]
This is **intended behaviour**.  It literally is maxing out one CPU core at 100% until the large map is generated, and 32 minutes is an average time for that.  This is [documented on the wiki](https://wiki.micdoodle8.com/wiki/Sponge#For_info:_Galacticraft_background_mapping:_CPU_usage).

It should have no effect on game performance on a modern multi-core PC.  The map generation is a totally separate process, independent from gameplay, networking or tick speed.

People "think" it's a bug because a sign of a locked process is a CPU core sitting at 100% for a long time.

I intended for this process to run during the first hour when a server first starts a new world, because a server is not normally heavily loaded at this time - there's a bit of world generation as players move around, but players won't yet have large bases, many machines, and it's unlikely there will be many players online yet.

However, it's fair to say that there is not yet anything in the game which displays or uses the large map....

**Comment by Shellyoung** [comment]
Understood
