### ISSUE TITLE
Too many small asteroids in the asteroid dimension

### ISSUE THREAD

**Issue by MuteTiefling** [micdoodle8/Galacticraft#3722]
This appears related to #1151 that was fixed several years ago.

REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2
Galacticraft version:

- GalacticraftCore-1.12.2-4.0.2.210
- Galacticraft-Planets-1.12.2-4.0.2.210
- GalacticraftTweaker-1.12.2-1.0.3

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)? SSP, closed LAN, cheats enabled

Any Galacticraft add-ons installed? please list all

- ExtraPlanets-1.12.2-0.5.2
- More-Planets-1.12.2-2.1.5-GC190
- MorePlanetsExtras-1.12.2-1.0

Maybe more. I'm not aware of everything considered a GalactiCraft addon. This is the AstroBlock mod pack. 

Please provide screenshots / crash report / log / full modlist as needed

![2019-07-11_20 41 28](https://user-images.githubusercontent.com/9543430/61094518-85f5dc00-a41d-11e9-8bff-f748dd560809.png)

I can upload logs if requested, but the issue but the issue is pretty plain. There are thousands of small asteroids accumulating at the edge unloaded chunks. If I remain around my base, I'm fine, but as soon as I venture off into any direction, my entity count shoots way up (11k in the screenshot, though I've seen upwards of 20k...) and my frame rate goes waaay down. 

I'm reporting the issue in hopes of an eventual fix (love Galacticraft) but more than anything, I'm hoping I can set up a /kill command block or something to deal with these guys... I just don't know what entity to target. How would I go about that?

**Comment by MuteTiefling** [comment]
Got some help on Discord. This ended up fixing it for me in a command block on a slow clock

/kill @e[type=galacticraftplanets:small_asteroid]

**Comment by marcus8448** [comment]
Ok, i see the problem here, [Line 32 of `EntitySmallAsteroid.java`](https://github.com/micdoodle8/Galacticraft/blob/c16d4546a490edb457633236a3639cc3142b8192/src/main/java/micdoodle8/mods/galacticraft/planets/asteroids/entities/EntitySmallAsteroid.java#L32) kills all asteroids that have lived for longer than 150 seconds. But... since the asteroids are ***spawning*** in unloaded chunks, they do not 'age' causing a huge buildup in unloaded chunks.

**Comment by MuteTiefling** [comment]
Oh cool!

If I may make a suggestion, consider aligning them with vanilla hostile spawn mechanics such that they'll only spawn in a given radius around a player. That way they're not potentially causing trouble if a chunk is simply loaded with no player around.

**Comment by micdoodle8** [comment]
I came up with an alternative solution, where small asteroids aren't saved. So if they enter an unloaded chunk they're just gone forever. This has the minor side effect of small asteroids around a player will be removed if the game is saved and loaded. Since small asteroids are more of an _atmospheric_ feature, this shouldn't be a problem. It also has the benefit of slightly smaller world save files.
