### ISSUE TITLE
Rare crash - corrupted NBT data on saved machine tile

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#3767]
**Minecraft version:** 1.12.2
**Galacticraft version:** 4.0.2.229

**Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?**
SMP

**Any Galacticraft add-ons installed? please list all**
ExtraPlanets

**Please provide screenshots / crash report / log / full modlist as needed**
https://paste.dimdev.org/amupufetal.mccrash

I suspect the crash might have something to do with VanillaFix, but I'm not really sure.
This doesn't happen every time, but sometimes the game crashes when logging in, and Galacticraft appears in the crash log.

**Comment by radfast** [comment]
Thanks for reporting.

This is a chunk loading problem, it looks like there is one corrupted block (a Fuel Loader) in one of your saved chunks.

I have not seen this specific issue before.  A quick Google search shows that **nobody** has reported a crash like this, ever, until now.  And this particular part of the Galacticraft code has been unchanged for nearly 2 years.

The most likely explanation is that you had a crash or other issue a few days ago while the game was saving, so that this particular chunk did not get saved correctly.

I'll see what we can do to fix this, but it might be a few days.  If you have a way to edit your saved game world offline (like MCEdit or similar) then a quick fix might be just to delete that block, if you can find it.  Unfortunately the crash report does not give the block's location.

**Comment by xJon** [comment]
Thank you for your reply.
I've been getting similar crashes before with the same world that look like this:
1. https://paste.dimdev.org/upiwugizay.mccrash
2. https://paste.dimdev.org/izusedovom.mccrash

All of them happened when logging in or out of the server by the client.
All of them didn't seem to have any affect, and because of VanillaFix I can just go back to main menu and continue playing, but I still can't seem to track down the issue.
I did notice the complete lack of Google results. I don't understand why.
None of the crashes point out to any chunk or location.
Thanks in advance for any help!

**Comment by radfast** [comment]
One of those crashes also seems to imply a corrupted chunk.  You can maybe figure out which one by looking for the Galacticraft Fuel Loader?

**Comment by xJon** [comment]
@radfast And do you think I should just get rid of the whole chunk?
The issue is that this only crashes the client, when logging in our out, does that actually make sense to be a corrupted chunk?

**Comment by radfast** [comment]
I've looked at this some more, and I cannot see any obvious cause in GC code.
As it's only the client when logging in, I now think it's **not** a corrupted chunk.
The most likely cause is some type of concurrency issue - meaning too many things happening at the same time on the same object in Minecraft, combined with a bit of bad luck.
This could explain why it only happens sometimes, and also why you're getting other seemingly random and hard-to-explain crashes.

I don't know why this doesn't happen to everyone, but maybe it's a weird combination of mods and VanillaFix causing extra concurrency / race conditions.

**Comment by radfast** [comment]
@xJon in the next Galacticraft build I've made a change which **may** help with this.  Obviously we can't help with any of the other mods crashing at login for similar reasons, but at least it won't be Galacticraft.

Once the next build is available (maybe tomorrow?) please try it out for a few days, see if you get Galacticraft-related issues still, and let us know.

**Comment by xJon** [comment]
That's perfect - thank you also for further explaining the issue and maintaining such a great mod.
I will post further information if I encounter any more Galacticraft-related crashes.

**Comment by xJon** [comment]
The crash persists with build version `1.12.2-4.0.2.237`.
Crash: https://paste.dimdev.org/kuzavudaya.mccrash
At this point I do think it's very likely it's VanillaFix's fault.

**Comment by radfast** [comment]
Thanks for testing in .237.

My theory is this is a "race condition" caused by the code somehow trying to simultaneously load the tile in two different threads, could be that's something VanillaFix adds for a performance improvement reason (I don't know, I have not studied their code).

**_If_** that theory is correct, then this should be fixed in .238.

**Comment by xJon** [comment]
Thank you for the further attempt to fix this issue when Galacticraft is involved.
I will report if the issue is reproduced with `.238`.

**Comment by xJon** [comment]
A few years later, I can confirm this is indeed resolved.

**Comment by MJRLegends** [comment]
@xJon lol woo
