### ISSUE TITLE
Crash when placing wires - Missing EnergyUtil class

### ISSUE THREAD

**Issue by BloxcastJason** [micdoodle8/Galacticraft#3790]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version: 1.12.2-forge1.12.2-14.23.5.2846
Galacticraft version: 1.12.2-4.0.2.236

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
SSP opened to LAN

Any Galacticraft add-ons installed? please list all

MorePlanetExtras, and PlanetExtras

Please provide screenshots / crash report / log / full modlist as needed

Crash Report link: https://paste.dimdev.org/arewibirop.rb and
[crashreport2.txt](https://github.com/micdoodle8/Galacticraft/files/3597975/crashreport2.txt)

All I did was just place wires from galacticcraft itself, placing wires from mekanism and extra utilities also crashes too. 
Placing galacticcraft wires crashes the game instantly and gives the error in shown in the crash report.
Trying to connect wires from other mods also breaks the game.

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
The crash report says it cannot find `EnergyUtil`, that's a standard part of Galacticraft's code.

That's very strange.  Obviously Galacticraft ships with that code and it's present for everybody else, otherwise all our players would be reporting an issue.

We need to figure out what it is about your setup causing the `EnergyUtil` to disappear.  The most likely reason is incompatibility with a specific other mod.  Again, that's unlikely to be any of the major mods (unless they made very recent changes) or else thousands / millions of players would be reporting an issue.

Please can you make a few tests to let us know which other mod is causing the problem, then we can look at their code in detail and find a solution.

1)   Please try first without any of the Galacticraft add-ons like More Planets and Extra Planets.

2)   Please try temporarily uninstalling (move to a different folder) any minor / unusual / rare / beta mods you are using

3)    Please try removing any mod tweakers or inter-mod compatibility mods, those can maybe be messing with our code somehow.

4)    If that still doesn't fix the issue, you can use a "binary search" method to find the problem mod fairly quickly, so you remove half of your mods, if the issue still persists then remove half again (1/4), then 1/8 etc - or else if the last removal ended the issue, then put back half of the ones you just removed.

**IMPORTANT: Back up your world before adding or removing mods, or start a new test world - removing mods and then playing an existing world will cause block/item loss or other corruption**

**Comment by radfast** [comment]
Start by removing all the GC addons including MorePlanets Extras.   It looks like you are using versions of those add-ons which are a few versions behind the current Galacticraft version 236, so that might be a reason for the problem.

**Comment by BloxcastJason** [comment]
Alright I'll give it a shot.

**Comment by radfast** [comment]
It looks like we are not compatible with the latest Buildcraft, I have re-opened this so that it can be investigated some more.

**Comment by radfast** [comment]
OK this is not a Galacticraft issue, and we don't have any problem with the latest Buildcraft.

Plus the modlist seems to show you do not have Buildcraft installed?

It looks like something mighty strange is going on here...
1.  Our code is searching for the Buildcraft code class `buildcraft.transport.pipes.PipePowerWood` but something has auto-replaced that with `buildcraft.transport.TileGenericPipe`
2.  It is somehow finding `buildcraft.transport.TileGenericPipe` which makes a reference to legacy Forge code `net.minecraftforge.fluids.IFluidHandler` - that's actually from a different Minecraft version like 1.10.2, and so referring to that in 1.12.2 is going to cause crashes
3.  The failure to find `IFluidHandler` is causing a crash - even though Galacticraft has trapped errors to "silently fail" here - so looks like you may have a mod which interferes with the crash report process?
