### ISSUE TITLE
game crashes when trying to land on the moon

### ISSUE THREAD

**Issue by ipwnedu107** [micdoodle8/Galacticraft#3796]
REVIEW THE GUIDELINES (LINK AT TOP OF THIS PAGE)

Minecraft version:1.12.2
Galacticraft version:4.0.1.181

, Multiplayer (SMP)

Any Galacticraft add-ons installed? please list all
Galacticraft, Galacticraft Planets, More Planets

Please provide screenshots / crash report / log / full modlist as needed
https://paste.dimdev.org/ajujibusus.mccrash
modlist is provided in the crash report

Game does start , when I tried to join the server it crashes and blames galacticraft core

**Comment by MJRLegends** [comment]
Updating to latest Galacticraft will probs fix this

**Comment by ipwnedu107** [comment]
I can't do that because this is part of a modpack, I just added galacticraft. The latest version of galacticraft requires a version of forge that the modpack doesn't have

**Comment by radfast** [comment]
This is **not a Galacticraft issue** - see guidelines given to you when you created this issue report.
The issue here is a crash in vanilla Minecraft, see this top line in your crash report:

    at net.minecraft.client.entity.EntityPlayerSP.onLivingUpdate(EntityPlayerSP.java:859)

As explained in the guidelines, the only reason you are seeing Galacticraft named in the crash report is because errors like that 'pass through' Galacticraft.

It's one of your other mods causing this.  I don't know which mod, the only way to figure that out would be to selectively remove mods from your /mods folder and keep restarting the game until the error stops - a 'binary search method' can usually get to the right answer in 4, 5, or 6 restarts.

---------

Having said that, it would be a good idea to update Galacticraft to a recent version, that will fix quite a few **other** potential issues - the version you have is around 2 years old.  You should contact the modpack creator and ask them to update Galacticraft.  Tell them Galacticraft is 'backwards compatible' with older versions of other mods and older versions of Forge, so updating Galacticraft should never break anything.

> I can't do that because this is part of a modpack, I just added galacticraft. The latest version of galacticraft requires a version of forge that the modpack doesn't have

Who told you this?  You can go back to them and tell them they are an idiot.  You have Forge 14.23.5.2838.  The latest Galacticraft requires Forge 14.23.1.2555 or later.  So you can **definitely** run the latest Galacticraft on your setup.

If you want to update yourself without the modpack updating, just [download](https://micdoodle8.com/mods/galacticraft/downloads) the latest Galacticraft files (three files) and use them to replace the ones in your .minecraft /mods folder, and everything should be good.
