### ISSUE TITLE
CargoUnloader item dupe exploit

### ISSUE THREAD

**Issue by clienthax** [micdoodle8/Galacticraft#3804]
Minecraft version: 1.12.2
Galacticraft version: GalacticraftCore-1.12.2-4.0.2.224

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Sponge - SMP

Any Galacticraft add-ons installed? please list all
Galacticraft-Planets

Please provide screenshots / crash report / log / full modlist as needed

The cargo unloader ignores NBT stacks.
-Have a cargo loader on one side, rocket in the middle and the cargo unloader on the other side. 
-Place the stackable container (such as Enderio machines) in the cargo loader
![image](https://user-images.githubusercontent.com/1056270/66040834-61873880-e510-11e9-8121-36377c356b40.png)
It'll go into the cargo unloader stacking them, duping the items.
![image](https://user-images.githubusercontent.com/1056270/66040845-677d1980-e510-11e9-8e55-680b59d2ac55.png)

Came across this when testing 1710 bugs and it seems to work on 1.12.2 too :)

**Comment by radfast** [comment]
Thanks, should be fixed in 1.12.2 next version 238.

It's unlikely to be fixed for 1.7.10 unfortunately, though we can look at that in future - essentially it's a simple fix.  One reason for not fixing things in 1.7.10 any more is that most players playing Galacticraft in 1.7.10 still are using that version because of some favourite 1.7.10 modpack ... and if it's in a modpack, doesn't seem like there's much chance the modpack compiler will still be releasing updates.
