### ISSUE TITLE
Stuck in Planet Selection Screen

### ISSUE THREAD

**Issue by Barragek0** [micdoodle8/Galacticraft#3821]
Minecraft version: 1.12.2
Galacticraft version: 2.0

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
Multiplayer

Any Galacticraft add-ons installed? please list all
Everything that's normally in 2.0 apart from GalaxySpace (read that removing galaxyspace fixed this issue for someone else, did not fix it for us)

These are all of the mods we have:
![image](https://user-images.githubusercontent.com/24503018/68485477-4a3a1a00-0237-11ea-8b6e-be3b32057cb7.png)
![image](https://user-images.githubusercontent.com/24503018/68485504-56be7280-0237-11ea-8632-1dae8ef3d56c.png)

Here's a gif of what happens in the planet selection screen (the animation plays a lot faster, it's a lot slower on the gif):
![2019-11-08_14-35-28](https://user-images.githubusercontent.com/24503018/68484570-6ccb3380-0235-11ea-9148-2a63310a2044.gif)

Me and a friend are both stuck in that screen now everytime we login and can't get out.

**Comment by MJRLegends** [comment]
Update all your mods half of them are very out of date

**Comment by radfast** [comment]
PlanetProgression is a Galacticraft add-on, try removing that.

Also you need to update Galacticraft to [version 4.0.2.238](https://micdoodle8.com/mods/galacticraft/downloads) - there's really no reason not to.  Even if you want to keep old versions of other mods, Galacticraft can be updated.  We take care to code Galacticraft so it works with both other and newer versions of other mods.

**Comment by MJRLegends** [comment]
To be fair the Planet Progressions version they are using is a year old so they should try updating first before removing the mod..

**Comment by radfast** [comment]
Yes that's fair.  Best steps:
1.  Remove Galacticraft add-ons
2.  Update Galacticraft to newest build .238, hopefully that should be working for you
3.  Now go get the latest versions of the Galacticraft add-ons too.

You could consider changing the PP version naming convention to be an exact match to Galacticraft's versions, or to state which version it is compatible with?  I know there's no perfect solution here, but it might help people to see "at a glance" if there's an add-on version mismatch.  For example I don't know myself which PP versions match which GC versions.  While we generally try not to include breaking changes in GC versions as you know, we do occasionally have to, to fix a bug or for a substantial improvement.

**Comment by MJRLegends** [comment]
@radfast My addons have a minimum requirement (provided to forge) of the galacticraft version i need for the addon to work. This system will ensure my addons work unless Galacticraft makes a breaking change for my addons and then i release a new update with the galacticraft build as the minimum requirement (provided to forge).

Putting Galacticraft build numbers in my version will just make it be wrong the moment Galacticraft updates.. and looks messy..

Theres nothing i can do to make people actually update their mods and stop reporting issues with very old version, since that seems to be the biggest issue.

**Comment by TheQuadShot** [comment]
@MJRLegends @radfast May be a reach here... Is there a way for you to check your version number, and check if an update is needed outside of the mod? ie, your mod launches checks version of GC, looks up a table, stored on a server somewhere, and notify the end user they need to update? I hope that made sense.

**Comment by MJRLegends** [comment]
Im not willing to make a system to help people update they should be doing it anyways even more so before bug reporting

**Comment by radfast** [comment]
@MJRLegends - dependencies with minimum GC versions should be totally fine.

@TheQuadShot - Galacticraft does a version check, but it only checks the "major/minor" version like if 4.0.0 changed to 4.0.1 - it doesn't check the build.   That's because we don't want to spam people with update messages every time there's a small change.  It's also very possible for the update check not to work ... that "server somewhere" can go down, the user might be disconnected from the internet when they launch, another mod might disable update checks, etc etc.   So not a perfect system!

Formerly I did also try to keep the wiki [What's New](https://wiki.micdoodle8.com/wiki/Whats_New) page updated with significant changes, in case that helps people.   I haven't done it recently (this year) because I had the impression nobody was really using that page - a few hundred page hits each month, out of a playerbase of millions.   The kids these days, they want a YouTube video not an online manual ...

**Comment by TheQuadShot** [comment]
While I can completely agree with you both, it's a trend I'm seeing with some indie game developers in/out of eastern Europe, that when they make a change that they know will "break" their game when loading a save from previouse version, they trigger an update option/event to download and install the newest version. I also understand that it's not the same for modders, since you don't have the same issues or control. However I would gauge this by how many bugs you receive due to an update, hope that makes sense.

**Comment by EzerArch** [comment]
> The kids these days, they want a YouTube video not an online manual ...

Interesting, I prefer written rather than video tutorials because I don't have patience to watch all the yadah-yadah, "Hit the Like button and Subscribe" and stuff until it gets the point where the info I'm looking for. The written tutorial is better because all I need to do is scan the text and voilà, it's there.
