### ISSUE TITLE
Advancement errors in log

### ISSUE THREAD

**Issue by xJon** [micdoodle8/Galacticraft#3837]
Minecraft version: `1.12.2`
Galacticraft version: `.238`

Any Galacticraft add-ons installed? please list all **ExtraPlanets**

Please provide screenshots / crash report / log / full modlist as needed **https://pastebin.com/e8GaCjew**

I'm not sure if this was fully reported in https://github.com/micdoodle8/Galacticraft/issues/3828, but I'm getting these errors in the log I've included.

**Comment by marcus8448** [comment]
From the looks of things it is the same issue as #3828 because the 3 custom triggers -  moon dungeon, rocket launch and space station advancements all fail to load, causing all the child advancements to fail too. But then, the oil advancement failed (due to a missing item), I assume this is because BuildCraft or some other mod that overrides GC's oil fluid has been loaded. I'll change the bucket to the forge bucket or a dummy item.

**Comment by xJon** [comment]
That is true, BuildCraft's oil is enabled.
Thank you!

**Comment by radfast** [comment]
@marcus8448  will you be making more changes to #3832 or do you want me to pull that now?

**Comment by marcus8448** [comment]
I have a few more changes coming.

**Comment by xJon** [comment]
Is there any ETA for `.289`?

**Comment by xJon** [comment]
Still getting an error with `.289`, see there: https://github.com/micdoodle8/Galacticraft/issues/3828#issuecomment-568250780

**Comment by xJon** [comment]
@radfast Is this fix implemented into `.241`?

**Comment by xJon** [comment]
@radfast @marcus8448 I am still getting this advancement error with `.243`: https://pastebin.com/92XHM5TY

**Comment by MJRLegends** [comment]
@xJon  yea it would be caused by that correct

**Comment by xJon** [comment]
👍
