### ISSUE TITLE
SSP/LAN Server stall between ProjectE tool and Galacticraft ores

### ISSUE THREAD

**Issue by HimitsuYami** [micdoodle8/Galacticraft#3852]
Minecraft version: 1.7.10
Galacticraft version: 3.0.12.504

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
LAN but happens in SSP as well
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? please list all
ExtraPlanets 2.1.2

Please provide screenshots / crash report / log / full modlist as needed
[latest.log](https://gist.github.com/HimitsuYami/1f0f2f81d54991cf085e7be5d733b652) as there is no crash log from it. Also another mod involved in the issue is ProjectE 1.10.1

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

I'm not 100% sure this is a GC issue as it could be ProjectE but given I've never had this issue with that mod without GC I figured I'd ask here first. The issue is that when I right click with the red morningstar on any ore from GC (so far tested with desh ore) it stalls the server. I can move around but the server stops processing anything. If I try to drop an item form my hotbar, it doesn't drop, dropping from my inventory decrements the item by one but doesn't drop it, breaking blocks doesn't drop anything, and right clicking anything else with the morningstar doesn't work either. I looked through the log myself and didn't see anything related but I'm not that experienced with looking through logs.

**Comment by radfast** [comment]
Your log is filled with errors where various mods are trying to access the internet to download components, or check updates, while they are loading.  I can see a ProjectE error of this kind.

There is one logged Galacticraft error of this kind, where Galacticraft is trying to download the capes list.  That should not be a problem, Galacticraft "silently fails" on the capes if it can't download the capes list.  This error is only being logged at all because you have set the Galacticraft config to include debug logging.

There is one other logged Galacticraft error, this one is actually connected with ExtraPlanets, maybe you have a dimension conflict or a dimension ID configured wrong?

    java.lang.IllegalArgumentException: Failed to unregister dimension for id -71; No provider registered

Again, that error will not cause a server freeze, you might have issues with that particular dimension -71 of course, but the rest of the game should be fine.

Any other problems you are having are not Galacticraft issues.
