### ISSUE TITLE
Mod combitability

### ISSUE THREAD

**Issue by ZEROX7** [micdoodle8/Galacticraft#3866]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.244

Any Galacticraft add-ons installed? Galaxyspace

hey there would it be possible to add a funktion so all galacticcraft recipes accept thermal foundation (or other mods) plates? i got instant unify installed and i only have thermal foundation plates avaible for me.

**Comment by radfast** [comment]
The Galacticraft recipe required items are OreDicted to `compressedIron` or whatever the metal is.  Any other mod which creates `compressedIron` can be used in the GC recipes.  This is mainly intended for Galacticraft add-ons and other mods specifically designed to interact with Galacticraft.  

It's intended that compressed metals are not the same as other mods plates, because the Galacticraft compressed metals are fairly high value, used to make good tools, weapons and rockets.  (Heavy Duty armor is better than Diamond armor, for example.)

If you don't like our intended design and you are using mod tweakers or unifiers, I'm sure they have a way to add Thermal Foundation plates, or any other item, to the OreDictionary with the name `compressedIron` or whatever plates you want.
