### ISSUE TITLE
1.12.2 Server Crash with Galacticraft core

### ISSUE THREAD

**Issue by BedrockLegends** [micdoodle8/Galacticraft#3869]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.244

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.
SMP
Any Galacticraft add-ons installed? please list all
Galacticraft Add- On - More Planets
Galacticraft Tweaker
Planet Progressions
Zollern Galaxy
Extra Planets

Please provide screenshots / crash report / log / full modlist as needed

https://gist.github.com/BedrockLegends/e8e1b0b95a3e990b642d766a1f2cb8a9

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

**Comment by radfast** [comment]
Looks like a bug in one of the Galacticraft add-ons you are playing.  One of the add-on rockets has implemented `ICargoEntity.removeCargo()` in a way that returned a null result.  Galacticraft's own Tier 1, Tier 2 and Tier 3 rockets and cargo rockets can't do that. 

Do you know which type of rocket you had landed on the landing pad with the Cargo Unloader?   If you know which type of rocket, then you can maybe figure out which add-on and report it to the add-on author.

If you can't figure it out, try uninstalling one or other of the Galacticraft add-ons - I mean MorePlanets, ExtraPlanets, Planet Progression etc.

Looking at your modlist, generally I would comment you have way too many mods, you must be encountering other issues, and the game will run slowly unless you have a **monster** of a PC.  Out of interest, how many minutes does it take to start up the game?

I recommend that instead of adding every mod to the game, you should be much more selective with your mods,.  Choose 30 or 40 maximum to play together, and create different modpacks for totally different game experiences.
