### ISSUE TITLE
Incompatibility with Biome Tweaker

### ISSUE THREAD

**Issue by Dr-Ergmern** [micdoodle8/Galacticraft#3878]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.224

There seems to be a difference between how Galacticraft Registers biomes and how other mods register them. As a result, Galacticraft's biomes are essentially unreadable by all other mods. Currently Biome Tweaker reads biomes from other mods correctly, however when it tries to read galacticraft biomes it sees "Outer_Space (galacticraftcore_outer_space)" rather than "moon" or the various other biomes.

**Comment by radfast** [comment]
Galacticraft re-uses a small number of biome IDs, which all have "galacticraft" in the name.
These biomes will look different on different planets.
The reason is that, with add-ons, people can have 20 or 30 planets in the game.  If each planet has, let's say, 5 biomes, that could be 150 biomes added to the game.  We think that is too many!  Therefore, we use the same 5 over and over (or if an add-on planet needs 6 biomes it will be 6 etc).

>  Galacticraft's biomes are essentially unreadable by all other mods

You can read our biomes the same way as any other.  The "meaning" of these biomes might be different, of course, on different planets. 

It's not clear what you are actually trying to do, but anyhow, there is no issue here.

**Comment by Dr-Ergmern** [comment]
The issue is, your mod essentially becomes completely incompatible with Advanced Rocketry because of the conflicting Thermal Systems, Oxygen Systems etc. Currently Advanced Rocketry has attempted to tackle the oxygen problem however there has been no effort on your side to bridge compatibility (like say using your oxygen system in Advanced Rocketry dimensions...). This results in a poorly implemented compromise between the two systems and I was attempting to use Biome Tweaker to allow for Galacticrafts Biomes to correctly spawn on custom Advanced Rocketry Planets in order to deal with the inconvenience of having to use the two systems. Perhaps it would be easier to implement a system where your systems override Advanced Rocketry's than the other way around.
