### ISSUE TITLE
A random crash. (Compatibility issue?)

### ISSUE THREAD

**Issue by VictorGamerLOL** [micdoodle8/Galacticraft#3880]
Minecraft version:1.12.2
Galacticraft version:4.0.2.244

Single player (SSP)

Addons:
Galaxy Space
ExtraPlanets

Screenshots and crash report:
http://prntscr.com/r0w882
https://paste.dimdev.org/amegezolig.mccrash

Yes I downloaded Galacticraft from the official website.

**Comment by MJRLegends** [comment]
follow https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#galaxyspace-all-versions

**Comment by radfast** [comment]
The issue here is caused by you installing two different Galacticraft add-ons, Extra Planets and Galaxy Space.  That's not a good idea.  If you are expert with configs maybe you can configure them to work together.  @MJRLegends is the author of Extra Planets and he has given you a suggestion.

---

This type of issue should not be reported here in the Galacticraft issues list, as it's not caused by Galacticraft itself and it's not anything the Galacticraft developers can fix.   I think it's great that several different people make add-ons for Galacticraft, but they do sometimes overlap - if you have any further problems, it's best to pick just one add-on and stick with it.
