### ISSUE TITLE
Crash loop when entering launch pad chunk(s)

### ISSUE THREAD

**Issue by IceFireFlame** [micdoodle8/Galacticraft#3884]
Minecraft version: 1.12.2
Galacticraft version: 4.0.2.266

SMP

Extra Planets

https://pastebin.com/mNJdC3Wk <<Mod List

https://pastebin.com/pV4jbqcp <<Crash Log

I have a feeling that the launch pad tileentity in question needs to be removed via setblock.
I can enter the server, but only for a second before crashing. The server isn't going down.
This appears to happen when someone enters the chunk that the launch pad is in and get in an infinite crashing loop.

**Comment by radfast** [comment]
Looks like the cause is CubicChunks.   I'm not too sure what their mod is doing here - I didn't check the code yet.  But looking at [our code](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/blocks/BlockMulti.java#L218) we are not doing anything very strange - simply setting some blocks in the 3x3 square around the landing pad, when the landing pad is loaded.

Please report to the CubicChunks issues tracker.   For now I am flagging this "Not a Galacticraft issue", but if the CubicChunks want to come back and comment, I can look some more.

By the way, your Galacticraft version is out of date, you should update to the latest.
