### ISSUE TITLE
Solar Menu crash

### ISSUE THREAD

**Issue by MrMonster61** [micdoodle8/Galacticraft#3897]
I Need help
Minecraft version:1.12.2
Galacticraft version:latest

Single player (SSP)

Any Galacticraft add-ons installed? please list all=Planets and Micdoodle8

Game crashes when start the count down but when i go back in to the game the count down continues. Nothing wrong there but whene i shoud go to the planet menu it crashes insted :(

**Comment by MJRLegends** [comment]
You need to include crash log please for any chance of anyone helping

**Comment by MrMonster61** [comment]
k
[crash-2020-02-28_18.59.55-server.txt](https://github.com/micdoodle8/Galacticraft/files/4268538/crash-2020-02-28_18.59.55-server.txt)

O ist the correct one

**Comment by MrMonster61** [comment]
i hope it is the*

**Comment by MJRLegends** [comment]
Looks like a open terrain generation mod issue rather than a Galacticraft

**Comment by MrMonster61** [comment]
Hmmmmmmm could it be becouse im on superflat world ?
Or shoud i disable Open Terrain generation?

**Comment by MrMonster61** [comment]
Or could it be all the mods installed i have a 50 mod mod pack but i have seen other YTubers playing Galacticraft with other mods =/

**Comment by radfast** [comment]
>  Or shoud i disable Open Terrain generation?

The crash here is caused by Open Terrain Generation.   See the first line of the crash report stacktrace:

    at com.pg85.otg.forge.dimensions.OTGDimensionManager.IsOTGDimension(OTGDimensionManager.java:136)

You should report this issue to them.  Disable OTG until it is fixed.  (Note: disabling mods will cause block + item loss, and can maybe damage your world - proceed carefully.)

It looks like their mod crashed when you flew in a Tier 3 Rocket - so I guess you flew to a new dimension like Mars, Venus, Asteroids?

If OTG devs want to get in touch with me they are welcome to comment on this thread and I will see it.   I cannot do any more troubleshooting, because I cannot find their source code.

**Comment by radfast** [comment]
i have a 50 mod mod pack but i have seen other YTubers playing Galacticraft with other mods 

Galacticraft can be played with other mods, of course.

**Comment by EzerArch** [comment]
> i have a 50 mod mod pack but i have seen other YTubers playing Galacticraft with other mods

I have Galacticraft and around 35 mods and have been recording videos with them for about 6 years. :<

**Comment by radfast** [comment]
>  I have Galacticraft and around 35 mods and have been recording videos with them for about 6 years.

Awesome videos they are too.  I enjoy the Brazilian vibe, the colours are much better than in rainy /cold northern Europe...   By the way @EzerArch if you want the experience in reverse, try playing [Frostpunk](https://www.rockpapershotgun.com/2018/04/23/frostpunk-review/) - then you can understand conditions where I live :)

**Comment by MrMonster61** [comment]
Ok i will try
