### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by SomeoneOk** [micdoodle8/Galacticraft#3911]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version:
Galacticraft version:

Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)?
- If SMP server, please mention if it has **Sponge**, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? please list all

Please provide screenshots / crash report / log / full modlist as needed

If the game is not starting at all, please confirm that you downloaded from the official Galacticraft download site (https://micdoodle8.com/mods/galacticraft)

Crash Report: https://pastebin.com/NXJBKQ7A

Tried a new version of Galacticraft Core, and Planets. I also had gotten them from micdoodle website. I tried the most recent ones. then the 237 versions and no dice.

**Comment by marcus8448** [comment]
Your problem is caused by an outdated add-on. Update ExtraPlanets from the mod author's official download site [here](https://www.curseforge.com/minecraft/mc-mods/extraplanets). Also, based off of the filenames of your mods, you have downloaded Micdoodle core from a _illegal_ website, for example: "9minecraft". All files downloaded from non-official sources are unsupported, so please visit [the official site](https://micdoodle8.com/mods/galacticraft/downloads) and re-download Micdoodle core. Please checkout the organization [Stop Mod Reposts](https://stopmodreposts.org) for more info about these sites.

**Comment by SomeoneOk** [comment]
https://pastebin.com/3B3CRPV3

No dice but I did get a new crash report and problem according to the launcher.

**Comment by MJRLegends** [comment]
Follow the 3 steps here https://docs.mjrlegends.com/ExtraPlanets/1.12.2compact/#galaxyspace-all-versions

**Comment by SomeoneOk** [comment]
Alright that got it running than you!
