### ISSUE TITLE
Cannot Place Tier 1 Rocket

### ISSUE THREAD

**Issue by SuicideApple** [micdoodle8/Galacticraft#3925]
Currently have constructed a 3x3 rocket launchpad and a Tier 1 rocket, I cannot seem to get the rocket to place onto the launchpad while holding it in my hand and rightclicking the launchpad. Tested and working in a singleplayer worlds, so its clearly something serverside. No server logs can be seen on the issue and no errors are arising in the server log. Any Ideas

Minecraft version: 1.12.2
Galacticraft version: 1.12.2-4.0.2.244

Multiplayer SMP

Installed Mods:

Sponge
LuckPerms
CatClearLag
Galaticraft Planets
Galaticraft Core
Buildcraft
IndustrialCraft2
AE2
Ender Storage

![image](https://user-images.githubusercontent.com/35659606/78961938-0dfa3680-7ac1-11ea-9af7-3e8302536c0a.png)

**Comment by SuicideApple** [comment]
Managed to solve the issue. Not sure if it was related, but if anyone else has the issue, I updated my forge server and spongeforge to build 2847 and regenerated all configs.

**Comment by radfast** [comment]
Thanks for posting your solution.   Normally some other people will find these closed issue reports if they are relevant to them, because these will show up in Google searches.  So that should be able to help others.

It was possibly a temporary issue in whichever SpongeForge build you were using previously.
