### ISSUE TITLE
Magnetic Crafting Table causes significant TPS drop

### ISSUE THREAD

**Issue by vincent-163** [micdoodle8/Galacticraft#3927]
REVIEW THE GUIDELINES - see [Contributing](https://github.com/micdoodle8/Galacticraft/blob/master/CONTRIBUTING.md) link on right side.

Minecraft version: 1.12.2
Galacticraft version: 4.0.2.211

DESCRIPTION:
While identifying the cause for our server lag, we found that the Magnetic Crafting Table in Galacticraft consumes above 30ms per tick on our server for every single table connected to a pipe from another mod (in our case Thermal Dynamics), which causes a huge amount of lag and drags down our TPS tremendously. We ran a benchmark and found that the bottleneck is here:

https://github.com/micdoodle8/Galacticraft/blob/f6a6d2b165d6f7c3d06c4a5ce806eb1581a80d0e/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityCrafting.java#L460

This function calls the `findMatchingResult` function for every call to `canInsertItem`. The `canInsertItem` is called many times per tick from Thermal Dynamics pipes to check if the container is ready to accept an item. Normally a container like a chest or a machine simply checks every slot to find out if it has available space, which is very fast.

However, `findMatchingResult` is a very slow function because it needs to check many recipes in the registry.  When the time cost of this function is multiplied with the frequency of  calls to`canInsertItem`, the time cost per tick is increased dramatically, up to 35ms per tick for every single table as we observed (the expected time is only 50ms).

We suggest that calls to `findMatchingResult` be avoided except when a player is changing the recipe, such as by saving the result of `CraftingManager.findMatchingResult(this.craftMatrix, this.getWorld())`. Check out implementations from other mods, such as [Thermal Expansion](https://github.com/CoFH/ThermalExpansion/blob/1.12/src/main/java/cofh/thermalexpansion/block/machine/TileCrafter.java).

**Comment by Apache553** [comment]
I am the one who is hosting the server we are playing on. I will show you more details about that.

Mod list:
```
[apache553@seniorious mods]$ ls
AppleCore-mc1.12.2-3.1.4.jar                   Galacticraft-Planets-1.12.2-4.0.2.211.jar  railcraft
AppleSkin-mc1.12-1.0.9.jar                     gravestone-1.10.2.jar                      railcraft-12.0.0.jar
appliedenergistics2-rv6-stable-7.jar           Hwyla-1.8.26-B41_1.12.2.jar                RedstoneFlux-1.12-2.1.0.6-universal.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar  industrialcraft-2-2.8.170-ex112.jar        TConstruct-1.12.2-2.11.0.106.jar
CoFHCore-1.12.2-4.6.3.27-universal.jar         jei_1.12.2-4.15.0.268.jar                  ThermalDynamics-1.12.2-2.5.5.21-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar         jeiintegration_1.12.2-1.5.1.36.jar         ThermalExpansion-1.12.2-5.5.4.43-universal.jar
Commons0815-1.12.2-1.3.4.jar                   JustEnoughEnergistics-1.12.2-1.0.8.jar     ThermalFoundation-1.12.2-2.6.3.27-universal.jar
conarm-1.12.2-1.2.0.2.jar                      JustEnoughResources-1.12.2-0.8.7.41.jar    ThermalInnovation-1.12.2-0.3.3.12-universal.jar
CraftTweaker2-1.12-4.1.19.jar                  Mantle-1.12-1.3.3.39.jar                   tinker_io-1.12.2-rw2.7.1.jar
Dynmap-3.0-beta-4-forge-1.12.2.jar             MicdoodleCore-1.12.2-4.0.2.211.jar         UniDict-1.12.2-2.7b.jar
DynmapBlockScan-3.0-alpha-2-forge-1.12.2.jar   ocdevices-MC1.12.2-1.0.0-44.jar            WailaHarvestability-mc1.12-1.1.12.jar
energyconverters_1.12.2-1.3.6.24.jar           ocsensors-1.0.4-b23.jar                    WanionLib-1.12.2-1.5.jar
foamfix-0.10.10-1.12.2.jar                     OpenComputers-MC1.12.2-1.7.5.192.jar       Wawla-1.12.2-2.5.273.jar
GalacticraftCore-1.12.2-4.0.2.211.jar          plustic-7.0.0.0.jar
```

System Info:
```
Minecraft Version: 1.12.2
Operating System: Linux (amd64) version 5.5.13-arch1-1
Java Version: 1.8.0_242, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM
Memory: Total 32GiB, Allocated for JVM 10GiB
```

Profile Flame Graph:
[async-profiler.zip](https://github.com/micdoodle8/Galacticraft/files/4465111/async-profiler.zip)

Single Player Reproduce:
1. place some container and let the ducts transfer items from those to somewhere, check tps with `/forge tps`
![gc1](https://user-images.githubusercontent.com/12186841/79051427-c6131500-7c62-11ea-9a90-df3d4eefde12.png)
2. connect the duct to the chest, nothing happened
![gc2](https://user-images.githubusercontent.com/12186841/79051512-37eb5e80-7c63-11ea-9699-386fa72b9feb.png)
3. connect the duct to four magnetic craft tables, use hopper to get its output, the game becomes laggy
![gc3](https://user-images.githubusercontent.com/12186841/79051561-741ebf00-7c63-11ea-9bba-1dbb4bdcb5f0.png)

**Comment by radfast** [comment]
Thank you, this is very clearly written - good job!  I'll see what we can do.

It is certainly **not** my intention for any element in Galacticraft to cause lag.  I have invested a huge amount of time making various parts of our code as efficient as possible, sorry this one was missed.

**Comment by radfast** [comment]
I've made changes, will be interested to see the improvement if you can run the same TPS check :)

> The `canInsertItem()` is called many times per tick from Thermal Dynamics pipes to check if the container is ready to accept an item.

If there are still problems even after my changes to the Magnetic Crafting Table then that might be something that needs to be fixed on ThermalDynamics side.  It seems unreasonable for their item pipe network to be hitting every tileEntity, in every tick - on what could be a huge network, so many machines - with multiple `canInsertItem()` calls.  I'm not sure exactly how their network functions - does it only run an insertion check for a single item which is "in" the network, or does it check whether **every** container with an output is able to send an item to **any** connected recipient container?  (eek!)

More generally I have not looked at ThermalDynamics code for a long time, but last time I did look at the power conduits (some years ago) I was not impressed.  Their tick time in a large power network scaled with _N_^2 (more precisely, it scales with _N_ x _M_ where _N_ is the number of potential emitters - batteries, generators etc - and _M_ is the number of potential destinations).  In comparison, a grid of Galacticraft Aluminum Wire scales with _N_ + _M_.  Therefore, if your players are making large builds - especially large grids of low-powered generators - and if you care about server TPS then you should direct your players to use GC wiring.

**Comment by radfast** [comment]
Galacticraft code is updated but we have a problem today with the link between the automatic build system (Jenkins) and the download server, so it is not possible to update our download site with this yet.

I made a private manual build 244A which you are welcome to use until the public build becomes available.
[GalacticraftCore-4.0.2.244A.jar](https://drive.google.com/open?id=1mNRm-wdzbh6CuhWRBWupSqWN5cRrg3_1)
[Galacticraft-Planets-4.0.2.244A.jar](https://drive.google.com/open?id=15bMGgmeUZF1xvGeVAMqsBOPJ_-FONx7e)

No need for you to update MicdoodleCore to 244A, MicdoodleCore has not changed so please continue using build 244 of that.

You can run this in single player for testing.

If you are operating a public Minecraft server, you can also update your **server only** to 244A,  I mean it is not necessary also for all your players to update their Galacticraft builds client-side to 244A immediately.  It shouldn't matter so much if a client has slower TPS.  And I don't really want thousands of players hitting my Google Drive for a download, we'd prefer players to download from the official download site only.

There is no problem with build version 244A on a server connecting to clients running Galacticraft build 244.   These two builds are very close, and therefore behave similarly in terms of server-client communications for the mod - the network packets are unchanged between builds.

**Comment by vincent-163** [comment]
Thanks for the prompt fix! We tested it on our servers and the TPS was back to normal.

Ragarding Thermal Dynamics, I'm quite confident that what you said is the case. Thermal Dynamics has very great flexibility and I'm able to get every machine or inventory output to every other machine. This gives me a lot of flexibility and ease of use, since I just need a single pipe to connect everything together and it just works, and the machines know to automatically stop working when no other machine is accepting its output. However, the only way that I can think of to design such a flexible pipe network is for every producer to check the entire pipe network to find an acceptor, which takes O(NM) time where N is the number of producers and M is the number of acceptors.

Fortunately, we are a small private Minecraft server with just ~10 players, and the biggest TE based network consists of about 30 machines. In case the complexity of the network becomes a problem we'll just split that network into two and put chests at their boundaries.

BTW I have not been able to extract items from a Magnetic Crafting Table with a TE itemduct (only with a hopper or an item allocator). Is that a bug or a feature?

**Comment by radfast** [comment]
I don't know why a TE Itemduct is not working.  I don't have time to test Galacticraft with every other different mod's pipes.  If the Magnetic Crafting Table works with a vanilla Hopper then that should normally mean the code on our side is working.

I can look at this specifically - it would help me to see a screenshot of the exact setup you are testing, like which side is the extracting duct connected, if there are multiple pull modes then what mode is the extracting duct set to?

We certainly would not intentionally disable compatibility with another mod's machine - we understand that most players play multiple mods and like everything to work smoothly together.  It is, however, a challenging task ... I'm not sure if it's O(N) where N is the number of other mods, could be more than that (because there can be three-way interactions between mods) or less (because a lot of other mods use overlapping techniques or are "inspired by" each other, bearing in mind most are open source...`).

---

There have been issues in the past with other mods feeding items into Galacticraft machines which don't understand about recipe placement - so other mods (for example, AE2) usually just try to force items into any old slot in the recipient, because they treat the recipient like a vanilla chest.  There are some honourable exceptions which allow for slot-specific placement but they are rare.      The Magnetic Crafting Table code you have examined in this thread is therefore designed to fix the input problem - so the Magnetic Crafting Table in a smart way will only accept items into slots matching a recipe, and it distributes input items evenly between slots if a recipe has multiple inputs which are the same item.

----

> an item allocator

I don't know what this is - which mod is this from?

----

> Fortunately, we are a small private Minecraft server with just ~10 players, and the biggest TE based network consists of about 30 machines.

To me your server is small!  Before I joined the Galacticraft team I was admin on server with 30,000 registered players, usually around 100-200 online together depending on time of day.  This was a modded server, back in MC 1.4.7 days running the excellent Voltz modpack.  But a lot of the Universal Electricity mods were quite buggy, and not coded efficiently on the server side.  Especially Calclavia's mods, his concepts were great and designs pretty but he never seemed to think about low latency coding when I examined the actual code.  I wrote some Java patches for the hotspots.  It's how I came to Galacticraft, there was also lag in the Moon worldgen in those days, at least on large multiplayer servers.  I found the problem and [posted a solution here](https://github.com/micdoodle8/Galacticraft/issues/295) and the rest is history!  lol, I didn't even know about Pull Requests in those days, wasn't previously a Github user - but micdoodle8 was gracious and a beautiful friendship was formed.
