### ISSUE TITLE
Overlapping ore drops [Lucraft]

### ISSUE THREAD

**Issue by Xman102003** [micdoodle8/Galacticraft#3933]
There is an issue with the galacticraft ores conflicting with the lucraftcore so when I mine a lucraftcore ore it will drop the galacticraft one instead. Could you please fix this.

**Comment by radfast** [comment]
Have you reported this to Lucraft?

**Comment by Xman102003** [comment]
Not yet

**Comment by radfast** [comment]
When you've done that, please provide a link to the Lucraft issue report and I'll see what the Lucraft developer(s) say about this.

**Comment by Xman102003** [comment]
I looked for it and it looks like the mod Lucraft: Core that the ores overlaps with isn't on github. Also sorry if I seem like I don't know a lot I'm new to github.

**Comment by radfast** [comment]
OK I've tested this myself.

Seems like the actual issue here is as follows:

1.  Both Galacticraft and Lucraft have similar ores - for example, Copper Ore, Tin Ore.

2.  If you place 1 block of Lucraft Copper Ore into a Furnace and smelt it, this gives you 1 Copper Ingot.  Only, now it's a **Galacticraft** copper ingot.

3.  Lucraft has some recipes which need it to be a **Lucraft** copper ingot.  For example, the Lucraft recipe _Hammer + Copper Ingot -> Copper Dust_ does not accept a Galacticraft copper ingot.

-----

This problem is on Lucraft's side, not ours.

Lucraft's developer has made a decision - which looks strange to me - to register a smelting recipe for [every type of ore to every type of ingot](https://gitlab.com/threetag/legacy/LucraftCore/-/blob/master/src/main/java/lucraft/mods/lucraftcore/materials/MaterialsRecipes.java#L136).   So he's told the game that a Lucraft Copper Ore, for example, smelts into 2 types of ingot.  I guess the game then picked which ever of those 2 types of ingot came last, which was Galacticraft here.

Many mods in the game each have their own Copper Ore, Tin Ore etc (for example, Tinker's Construct, Mekanism, Thermal Dynamics).  All these mods work OK with Galacticraft.

I think the normal approach is for each mod to smelt its own ore into its own ingot.  That's certainly what we do.  We did not add any smelting recipe for Lucraft Ores.

I am hoping the Lucraft developer will read this and know how to fix it.

**Comment by TheQuadShot** [comment]
Related (sounds like same issue I reported to TC a while back) could be tl;dr though https://github.com/SlimeKnights/TinkersConstruct/issues/2884

**Comment by radfast** [comment]
@TheQuadShot it's a similar type of issue, but in this case the cause is clear.  Lucraft's code (the line I highlighted) has actually added a smelting recipe Lucraft Copper Ore -> Galacticraft Copper Ingot.  They shouldn't do that, this is on them.  The approach which works (and which we are careful to adhere to) is for each mod to provide smelting recipes only for its own ores to its own ingots.

It's a case of **too much** OreDicting, if you like!  (But also inconsistent OreDicting, the crafting recipes should be OreDicted.)

**Comment by radfast** [comment]
I've reported this on [Lucraft's Issue Tracker](https://gitlab.com/threetag/legacy/LucraftCore/-/issues/14).  It's up to them now.

**Comment by radfast** [comment]
Lucraft developer got in touch today to say this is now fixed in latest (May 1st) version of Lucraft.

**Comment by Xman102003** [comment]
Thank you for all the hard work you put into this mod and working things
out!
