### ISSUE TITLE
[Website] Changelog page is outdated

### ISSUE THREAD

**Issue by EzerArch** [micdoodle8/Galacticraft#3941]
About: https://www.micdoodle8.com/mods/galacticraft/changes

I don't know if the changelog page is manually updated or automatically generated. The last build shown there is 190.

As a workaround we could point the link to https://github.com/micdoodle8/Galacticraft/commits/master.

**Comment by radfast** [comment]
Changelog has been broken since the Jenkins was restructured a few months back.  I'm not sure how easy this is to fix - one for @micdoodle8 I feel :p

I also try to maintain the [Whats New](https://wiki.micdoodle8.com/wiki/Whats_New) page on the Wiki with the bigger changes - that's probably more interesting for most players.

**Comment by micdoodle8** [comment]
All future builds will have their changes logged. The changelog is linked from the main download site.
