### ISSUE TITLE
EnderIO power compatibility

### ISSUE THREAD

**Issue by ronyala** [micdoodle8/Galacticraft#3942]
Minecraft version: 1.12.2
Forge version: 14.23.5.2847
Galacticraft version: 4.0.2.252
Endercore version: 0.5.73
EnderIO version: 5.1.55

Single player (SP), Multiplayer (MP), or SP opened to LAN (LAN)? SP

Please state the site that you downloaded Galacticraft from: https://micdoodle8.com/mods/galacticraft/downloads

Galacticraft can accept energy from EnderIO, but energy almost can't transfer the other way round, I added a screenshot with some examples.

![2020-04-19_14 17 17](https://user-images.githubusercontent.com/63063653/79686375-8e026800-8248-11ea-93e8-5c19fff88be5.png)

* bottom-left - Power *is* transferring from the EnderIO generator to the Energy storage module, despite it looking like they are not connected.
* top-left - The EnderIO capacitor is not able to recive energy from the Galacticraft generator.
* bottom-right - Even when placed directly next to each other, EnderIO capacitors don't work flawlessly with a Galacticraft generator, for them to work you need to set that side explicitly to be input (the oppasite with an EnderIO generator and a Galacticraft machine works with no problems).
* top-right - The capacitor bank *can* somewhat accept power from galacticraft via wires, but it is pretty finicky (you pretty much need to break and re-place the blocks until it works)

Note: issue #3809 is about EnderIO conduits, but it seems it's not related as conduits *can* connect to galacticraft things, but they can't get a power input from galacticraft blocks, only output to them.

**Comment by radfast** [comment]
Thanks for reporting.  We should be able to fix some of this.

I don't know if we can fix **all** of it though.  Specifically, the way that it _looks_ like EnderIO conduits are not connecting (they render a connection plate 'in mid air') is down to their mod, not us.

**Comment by radfast** [comment]
OK thank you for reporting, all is now tested and working as intended in next build .253.

**top-left and bottom-left**   Intended behaviour here is that these are _not_ connected.   Galacticraft is now fixed so that EnderIO cables will not try to connect to Galacticraft wires, and EnderIO cables will not show the connection plate.  Three reasons:

1. joins between the cables of two different mods look wrong - in this case, if we allowed joins there would be EnderIO connection plates which look ugly on our wires
2. if a player build has - let's say - a 5 block cable run of EnderIO cable, laid next to a 5 block cable run of Galacticraft wire, if we allowed them to connect that would give you 5 connections all the way along, which would probably give a server a lot of problems (at its mildest, each mod would try to transfer energy 5 times each tick to the other mod causing lag, and at worst maybe you'd get a loop or energy duplication)
3. it might sometimes be very handy to be able to run two power lines next to each other in the game without connections.  Especially in space stations?  I like the idea of the wiring being a bit crowded.

It's intended that Galacticraft machines can be connected to other mods' power using either Galacticraft wires, or the other mod's wires.   You can also use Galacticraft wires to connect two machines from another mod (e.g. two EnderIO capacitors) so they can meet all your power needs.  They are intended to be universal connectors.  (Originally our heritage was as one of the Universal Electricity mods, though I think I'm the only person now maintaining any of that!)   On big servers or for very large builds we recommend using Galacticraft wires everywhere, they are still (so far as I am aware) the least laggy types of wiring in the game, for large setups.

**bottom-right**  (direct GC Machine -> EnderIO connection)  This works flawlessly now.  I've fixed one issue where the EnderIO capacitor was able to push energy into the Galacticraft machine's output side, so it could both push and pull energy in the same tick (unless the EnderIO machine is set to only allow input).  On Galacticraft's side the energy flow should now be only one way as intended.  This means you can now set the EnderIO capacitor side to **None** or **Input**, both should work.

**top-right**  (GC Wire -> EnderIO connection)  This works correctly in my testing, I didn't see any finicky or intermittent issue, tried breaking and replacing the wires any number of times and it always worked.  Could be something else I've changed today fixed the finicky behaviour?  Or could be caused by a third mod - if you're still seeing any problem here, please try removing other power mods like IC2, Mekanism and Thermal Dynamics and see if that makes any difference?

**Comment by ronyala** [comment]
**top-right** - I checked again with the latest version, and it is fixed now.

There is still one problem, where when galacticraft wires are placed next to enderio outputs, they are connected to them, despite not showing it. Also, if it is intended that galacticraft wires cannot be connected to other mod's wires, you might want to stop connections to thermal expantion fluxducts too

![2020-04-20_11 31 35](https://user-images.githubusercontent.com/63063653/79731166-90bd9580-82fa-11ea-803d-3d46b30226ac.png)

**Comment by radfast** [comment]
Thank you, I'll take a look at those visible connection issues.
