### ISSUE TITLE
Titanium Issue

### ISSUE THREAD

**Issue by Binxx2222** [micdoodle8/Galacticraft#3949]
FIXED. Theres a config option in Core config which makes other mod metals unusable in GC recipes. Setting that to false has fixed the 'issue'.

Hi, me and a friend are playing All The Mods 3 with Galacticraft 4 and Extra Planets installed seperately. We've run into a few issues but the main one is Titanium. We went to the Asteroids and mined many stacks of Titanium shards, however upon smelting or doing anything with them, the outcome is Tech Reborn Titanium. Not compatible with Galacticraft. The only way we thought would work is crushing the Ilmenite or with an Ore Crusher from Tinker I/O, however that produces Rutile Ore. So in this current mod pack there is no way of making Titanium ingots and the only way to get Compressed Titanium is finding it or spawning it, but we need ingots for higher tiered space suits and JEI doesn't show the ingots. Even the Ore Dictionary has been overwritten by Tech Reborn. Help!

Other issues we've found are really high radiation on Asteroids and on Mercury. We couldn't survive on Mercury but assumed it was our Tier 1 Space Suits letting us down. The Asteroids were survivable but not for long. 

FIXED. Theres a config option in Core config which makes other mod metals unusable in GC recipes. Setting that to false has fixed the 'issue'.

**Comment by Binxx2222** [comment]
We've decided to remove Tech Reborn entirely.

**Comment by Binxx2222** [comment]
It seems to happen with any mod that has it's own Titanium. Vulpes has replaced it now.

**Comment by Binxx2222** [comment]
> 
FIXED. Theres a config option in Core config which makes other mod metals unusable in GC recipes. Setting that to false has fixed the 'issue'.
> 
> Hi, me and a friend are playing All The Mods 3 with Galacticraft 4 and Extra Planets installed seperately. We've run into a few issues but the main one is Titanium. We went to the Asteroids and mined many stacks of Titanium shards, however upon smelting or doing anything with them, the outcome is Tech Reborn Titanium. Not compatible with Galacticraft. The only way we thought would work is crushing the Ilmenite or with an Ore Crusher from Tinker I/O, however that produces Rutile Ore. So in this current mod pack there is no way of making Titanium ingots and the only way to get Compressed Titanium is finding it or spawning it, but we need ingots for higher tiered space suits and JEI doesn't show the ingots. Even the Ore Dictionary has been overwritten by Tech Reborn. Help!
> 
> Other issues we've found are really high radiation on Asteroids and on Mercury. We couldn't survive on Mercury but assumed it was our Tier 1 Space Suits letting us down. The Asteroids were survivable but not for long.

FIXED. Theres a config option in Core config which makes other mod metals unusable in GC recipes. Setting that to false has fixed the 'issue'.

**Comment by radfast** [comment]
Thanks for reporting, and thanks for reporting the fix!

I think the root cause of the issue could actually  be Tech Reborn.   They should make sure that they add smelting recipes to the game only for their own mod's ore - they should not add oredicted smelting recipes that smelt GC shards into TR ingots.  (Oredicted crafting recipes are fine, but not oredicted smelting recipes otherwise you get the problem mentioned here, and there's not much we can do about it from our side.)   I _**think**_ that's what is happening here, but I can't find the part of Tech Reborn's code which registers smelting recipes so I can't be sure.

It could also being caused by some other mod or tweaker, which thinks it's a good idea to re-register everybody's smelting recipes.  I guess you could try testing just Tech Reborn and Galacticraft together, nothing else?

But at the moment I am not seeing anything we can fix from our side.
