### ISSUE TITLE
Ticking Memory Exception Crash when Starting any World

### ISSUE THREAD

**Issue by Dknir** [micdoodle8/Galacticraft#3953]
Minecraft version:
1.12 , playing with the project ozone 3 modpack version 3.2.55
Singleplayer

Installed are Extra Planets and Galacticraft Tweaker

https://pastebin.com/Y5mKyttf   | There is unfortunatly no Clientside crash Report

Automatic Download of the modpack from the twitch launcher

So, I got this after i wantet to go back to the main menu one day just playing normally 
But it was frozen at "shutting down internal server" for over 10 min , so i had to terminate it 
And well , after starting up the pack again when trying to enter any world, not just the one i played in, I Crash to the aformentioned Issue when loading in the world.

**Comment by dj3520** [comment]
Version used: v244. I'd suggest an update.

**Comment by Dknir** [comment]
> Version used: v244. I'd suggest an update.

Tried already to no avail , apparently the world is corruped and 'somehow' all other worlds with it since it's telling me before loading any world that forge detected that it's using a backup level.dat

**Comment by Dknir** [comment]
Alright , after reinstalling the modpack , and just outright removing the level.dat in the savefile evrything works again normally 
So , while that workaround worked for me , the problem was cerantly caused by galactricraft so ill keep the thread open incase any more debugging info is needed to fix whatever bug causes this

**Comment by radfast** [comment]
Thanks for reporting.

Do you still have the full server log to match that crash report?  I think it's likely that the server had some kind of earlier issue when originally starting up and initialising the mods.  The root cause of this issue is it looks like the Galacticraft part of the server did not ever finish registering the planets -  - [`WorldUtil.registeredPlanets`](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/util/WorldUtil.java#L1202) because of an earlier error, like I say.

Because it never finished registering the planets, when a player tried to log on to actually use the planets, you had this crash.   I don't think that's something we can really fix - without registered planets, the game could never have worked properly, even if we stopped this specific crash from happening something else would be wrong.

The root cause of this was probably your corrupted level.dat.

You have literally 306 mods installed, as listed in your crash report.  With so many mods ... I guess corruption and other issues are going to happen, and it will be ultra-hard to figure out which mod caused it.  Do you really need so many?   I play with about 20 mods maximum myself (and the game loads faster this way too).  If I want to try other mods, I make a different modpack and try that for a totally different game experience.

If you still have the server log we can try to look at what caused the planet registering problem earlier on - most likely a Galacticraft add-on (or compatibility between two add-ons) not Galacticraft itself.   If you don't have the server log now, there's probably nothing more we can do here.

**Comment by Dknir** [comment]
> Do you really need so many?
Well, I did not make the modpack , as I said its one called Project Ozone 3 

As for the log , sorry after basicly deleting and reinstalling the pack , it's gone , the only thing i saved beforehand were the world saves 

I wantet to crash the game on purpose  by loading one of the old saves were I did not delete the apparently corrupt level.dat , but as it turns out , it ... just loaded normally 

So that would rule out the level.dat as a cause , must've been something else that got reset to default when reinstalling the pack

**Comment by micdoodle8** [comment]
If you or anyone else is experiencing this same crash, please turn on "Enable Debug Messages" in the Galacticraft config and link the full server log in a new issue please.
