### ISSUE TITLE
The game crashed whilst unexpected error

### ISSUE THREAD

**Issue by rravnmc** [micdoodle8/Galacticraft#3955]
### The game crashes as soon as i right-click with the Fyrite Pickaxe from the mod [Netherrocks](https://www.curseforge.com/minecraft/mc-mods/netherrocks) but apparently the problem comes from Galacticraft. Any help?

Minecraft version: **1.12.2**
Galacticraft version ("latest" is not a valid option): **Galacticraft Core 1.12.2-4.0.272**

Single player (SP), **Multiplayer (MP)**, or SP opened to LAN (LAN)?
- If MP server, please mention if it has **Forge**, Sponge, AtomMC, BukkitForge, BungeeCord etc.

Any Galacticraft add-ons installed? Please list all of them: **Galaxy Space 1.12.2-2.0.12**, **More Planets 1.12.2-2.0.23-GC251**

Please upload crash report / full log to [Github Gist](https://gist.github.com/) or any other paste site: **https://gist.github.com/rravnmc/5ab129a215a3b3d14c0591aec7dbc2c4**

Please provide screenshots / videos / full modlist as needed: **[Video](https://streamable.com/ftjoq2) / [Screenshot](https://prnt.sc/s899f9) / [Modlist](https://prnt.sc/s89bs0)**

Please state the site that you downloaded Galacticraft from: **https://micdoodle8.com/mods/galacticraft**

**Comment by radfast** [comment]
>  apparently the problem comes from Galacticraft

The problem is from the Fyrite pickaxe code, not from Galacticraft.

This line:

    java.lang.ClassCastException: micdoodle8.mods.galacticraft.core.entities.player.GCEntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at alexndr.plugins.netherrocks.helpers.FyriteHandler.onItemUse(FyriteHandler.java:195)

tells you that the problem is in FyriteHandler at code line 195.

The problem is they are sending a client-side handler into server-side code, something like that.  The crash report might as well say:

    java.lang.ClassCastException: net.minecraft.entity.player.EntityClientPlayerMP cannot be cast to net.minecraft.entity.player.EntityPlayerMP

As we have explained elsewhere, the GCEntityClientPlayerMP is pretty much the exact equivalent of Mojang's EntityClientPlayerMP and for all non-Galacticraft purposes should be inter-changeable.

Please report this to the Netherrocks devs, not us.
