### ISSUE TITLE
Dependencies with the micdoodle core

### ISSUE THREAD

**Issue by guiwar09** [micdoodle8/Galacticraft#4081]
I placed the micdoodle core in the mods folder along wIth the other mods and the game says there isn't any micdoodle core installed on the folder

**Comment by ROMVoid95** [comment]
would need a log file from the logs folder or something. As long as all 3 mod jars (MicdoodleCore, GalacticraftCore, Galacticraft-Planets) are in the mods folder and launching using the correct game directory. This sounds like a user-error and not an actual issue/bug with Galacticraft.

Closing this since nothing else was posted, if for any reason a bug/issue with the mod is found please open a new issue report at the new repository here [TeamGalacticraft/Galacticraft-Legacy](https://github.com/TeamGalacticraft/Galacticraft-Legacy)
